### ISSUE TITLE
Keyboard shortcuts? (ENTER, SHIFT+ENTER)

### ISSUE THREAD

**Issue by basickarl** [fraywing/textAngular#1004]
Is there any documentation regarding keyboard shortcuts?

Currently whenever I press "ENTER" it creates a new row, where as the standard is "SHIFT"+"ENTER" for a new row and "ENTER" to submit (call a function).

I would like to append `data-ng-keypress` for example on the textarea!

**Comment by basickarl** [comment]
Searching more deeply saw this: taOptions.keyMappings = [];

:)

**Comment by SergeyMell** [comment]
@basickarl Could you, please, tell how you managed to solve the issue with the use of keyMappings?

**Comment by detilium** [comment]
It's now 2017, and we still need to know this. I can't seem to wrap my head around it from reading the Setting defaults section in the wiki.
