### ISSUE TITLE
Focus Lost When Clicking The Tools

### ISSUE THREAD

**Issue by varun-raj** [fraywing/textAngular#1006]
Textarea losses the focus when clicking on the tool bar elements.

`<div text-angular text-angular-name="board_text" ng-model="board.text"  ta-toolbar="[['h1','h2','h3','p'],['bold','quote','ul']]" rows="15"></div>
</div>`

**Comment by dsine-de** [comment]
I get the same behaviour in Chrome, Chrome Canary and Internet Explorer Edge, but not in Internet Explorer 11.

To reproduce:

1. Open http://textangular.com/ (e.g. in Chrome Version 48.0.2564.103 m)
2. Click somewhere in the editor. (The toolbar is now enabled.)
3. Click somewhere outside of the editor. (The toolbar is disabled again.)
4. Click again somewhere inside the the editor, mark some text and try to press the "B" for bold text. The editor looses focus and the toolbar is disabled.

**Comment by pbassut** [comment]
Confirmed. Thanks for letting us know about this.

**Comment by pirquessa** [comment]
Same problem here ;)

**Comment by RajathaKrishnamurthy** [comment]
@pbassut  could you please let us know when this issue gets fixed.

**Comment by pirquessa** [comment]
I found the origin of my problem... I was trying to bing an item of a String Array to the editor. I changed from:

```
$scope.value = {
  texts: ['a','b']
}
```

to

```
$scope.value = {
  texts: [{value: 'a'}, {value: 'b'}]
}
```

It solves my problem.

**Comment by RajathaKrishnamurthy** [comment]
@pirquessa Could you please paste the code snippet for this

**Comment by pirquessa** [comment]
What do you need ? I just give a solution (for my problem, with a code sample)...

**Comment by RajathaKrishnamurthy** [comment]
I wanted to know whether in the customization of textAngular (with the model name specified without the array of objects)
<div text-angular="text-angular" name="htmlcontent" ta-disabled='disabled' 
        ta-toolbar="[['bold','italics','underline','undo','redo', 'quote','p','pre','ul','ol', 'insertImage','insertLink','wordcount', 'charcount']]"></div>

I am facing the same issue. So wanted to check if it is a similar issue and whether I can solve it.

**Comment by pirquessa** [comment]
I was trying to do something like:

```
.form-group(ng-repeat='step in action.steps')
  label Step {{$index + 1}}
  text-angular(ng-model='action.steps[$index]', ta-toolbar="[['bold','italics','underline','strikeThrough','insertLink']]", ta-text-editor-class='form-control text-step', ta-html-editor-class='form-control text-step')
```

but **action.steps[$index]** was an item of a String Array. Changing **action.steps[$index].value** solves the problem (I also update the scope object as said before).

**Comment by RajathaKrishnamurthy** [comment]
@pirquessa Thanks a ton.. :)

**Comment by TheWizz** [comment]
I had the same (or possibly similar) problem, where clicking a toolbar button sometimes (but not always) caused the edited text to lose focus (and hence the toolbar getting disabled). I managed to fix it by adding the following event handler on a div enclosing the toolbar

```
	enclEl.on('mousedown', function(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	});
```

It seams the mousedown event sometimes escape, despite the similar handler inside textAngular's taButton directive. Catching it upstairs, like shown above, seems to trap this and kill it before it causes any damage. Before I added this, the editor (sometimes) lost focus when I clicked a button, with the activeElement becoming the <body> tag.

**Comment by JoelParke** [comment]
Please re-test with v1.5.5 release and let me know.   There were many changes.

**Comment by TheWizz** [comment]
I've made some tests with 1.5.5 now. Sadly, it seems there's a regression related to

   https://github.com/fraywing/textAngular/issues/1241#issuecomment-234459479

as I again have to manually call updateSelectedStyles() in order to make the tools show the proper initial state without having to click or arrow-key in the edited text once.

-JM

**Comment by JoelParke** [comment]
I just tested this with v1.5.7 and I cannot reproduce.  Could you reopen if it is still and issue, and if so, could you setup a Plunker that may demonstrate the issue.  I don't see it with Chrome of Firefox using the current demo: http://textangular.com/

**Comment by TheWizz** [comment]
Yes, the problem remains in 1.5.7. As soon as I cause *any*e event to be fired on the textangular editor, the tool status is set correctly. It is sufficient to press the shift key once (ehich doesn't change the text or the selection, but apparently sends enough key event data to the editor to make tools update). I work around this issue by adding the following code:

`			/*	Ugly hack to set initial state of editing tools
				No longer needed after this  commit
				https://github.com/fraywing/textAngular/issues/1241#issuecomment-234459479
				YES - Problem back again in ta 1.5.5, so put this code back
			 */
			const taScope: any = angular.element(toEdit).scope();
			taScope.updateSelectedStyles();`
