### ISSUE TITLE
this.action is not a function on button click

### ISSUE THREAD

**Issue by Raystorm7** [fraywing/textAngular#1013]
Hi,
this is the that I used:
main.js:
paths: 
```
        'rangy-core': '../bower_components/rangy/rangy-core.min',
        'rangy-selectionsave': '../bower_components/rangy/rangy-selectionsaverestore.min',
        'textAngular-sanitize': '../bower_components/textAngular/dist/textAngular-sanitize.min',
        'textAngularSetup': '../bower_components/textAngular/dist/textAngularSetup',
        'textAngular': '../bower_components/textAngular/dist/textAngular'
```
shims:
```
       'rangy-selectionsave': ['rangy-core'],
        'textAngular-sanitize': ['angular'],
        'textAngularSetup': ['angular'],
        'textAngular': ['angular', 'textAngular-sanitize', 'textAngularSetup']
```
and then:
```
require(['rangy-core', 'rangy-selectionsave'], function(rangyCore){
    window.rangy = rangyCore;
});
```

In my index.jade:
```
   i.fa.fa-bluetooth <--only to check if font-awsome is loaded
   div(text-angular ng-model="htmlContent" name="demo-editor")
```
indexController.js
```
     $scope.htmlContent = '<h2>Try me!</h2>';
```

I'm using:
angular 1.4.8
font-awsome 4.5.0
rangy: 1.3.0
bootstrap: 3.3.6
requireJS: 2.1.18

And this is the result:
http://imgur.com/QYnJ1rO

With this error when I try to click one button:
http://imgur.com/muHlIPr

Anyone can help me, please?

**Comment by maxiaolin0615** [comment]
Hi, did your problem above solved?  I encounter the same one today. Many thanks if you could show me the solution.

**Comment by Raystorm7** [comment]
No, sorry. I switch to another Text-Editor.

**Comment by maxiaolin0615** [comment]
Thanks. Which one you use?

**Comment by Raystorm7** [comment]
https://github.com/froala/angular-froala

**Comment by maxiaolin0615** [comment]
Any special notes for using froala? I have also tried it, but ended with not showing the editor at all.

**Comment by MiguelSMendoza** [comment]
I had the same issue. In my case I wasn't requiring textAngular in my module. I've solved simply with:
angular.module('myModule', ['textAngular']);

**Comment by TakahashiEi** [comment]
See this comment -> https://github.com/fraywing/textAngular/issues/1092#issuecomment-207695137
