### ISSUE TITLE
Paste text from MS Word/Google Docs

### ISSUE THREAD

**Issue by sergey-morenets** [fraywing/textAngular#1014]
I've read few issues on that and it seems that it should work properly however ...

1) When I paste text from MSWord or Google Docs in Firefox the formatting is completely lost
2) When I use Chrome things get better. However when I paste text fragment from MSWord some of the lines are lost. When I paste as plain text all the text lines are pasted correctly without formatting. 
When I paste text from Google Docs some formatting is preserved and some is lost(for example, bold text).

Could you please help?

**Comment by pbassut** [comment]
Maybe it's a version related issue?
Provide informations like: MSWord version, TA version, Angular Version.

If possible, provide a plunkr/jsfiddle with those versions. 
We need to reproduce the issue to fix it. 

Thanks.

**Comment by sergey-morenets** [comment]
Hi, unfortunately I migrated to CkEditor so can't reproduce it.

**Comment by hiretheheir** [comment]
I just did a check on **textangular.com** and tried pasting a formatted sentence from MS WORD. Firefox pastes it without any formatting.
Firefox 44.0.1
Windows 7

This specifically happens with Firefox.
