### ISSUE TITLE
Unable to copy from OneNote

### ISSUE THREAD

**Issue by jordancrawfordnz** [fraywing/textAngular#1022]
**Overview of the issue**
If you copy text out of Microsoft's OneNote application and into textAngular, no text is pasted. If I do the same into a normal text field, the content works.

**Motivation for or Use Case**
Initial content entry into our system is very likely to come from existing OneNote content, so the ability copy from OneNote is needed.

**Angular Version(s)**
Running Angular 1.3.20.
Running textAngular 1.4.6 via bower and using the master branch in bower instead of defining a specific version does not fix the issue.

**Browsers and Operating System**
I have confirmed this on my Mac using Chrome and OneNote 15, and on a colleague's Windows 7 machine on Chrome with OneNote.

**Reproduce the error**
The demo at http://textangular.com/ doesn't let me paste from OneNote.

**Related issues**
Issues currently exist with formatting from other Microsoft applications in https://github.com/fraywing/textAngular/issues/1014 and https://github.com/fraywing/textAngular/issues/786. I can still paste content in from these applications though, so the problem with OneNote is likely caused by something different.

**Suggest a Fix**
The issue does not happen on other text fields, such as the GitHub issue creation one.
One thought was that it might be trying to paste as an image for compatibility.

**Comment by pbassut** [comment]
What do you mean by "don't let me paste"?
I had to download OneNote for Mac to see the issue.
And it pastes nothing even though I copied a considerably big block of text.
I'll mark as a bug.

Do you really need this feature?

**Comment by jordancrawfordnz** [comment]
@pbassut, yes. Thats exactly the issue I'm seeing.

You paste but nothing goes into textAngular at all. Pasting into a plain text editor then pasting into textAngular works (but obviously loose all the original OneNote styles).

The web app I'm working on often requires users to input their existing content, and OneNote is a fairly common source of this information so this would be very helpful.

**Comment by pbassut** [comment]
Right.
There should be a spec for pasting content. Every now and then there's a bug with pasting content from elsewhere.
I'll look into this.
Thanks for reporting.

**Comment by jordancrawfordnz** [comment]
@pbassut, thanks for that.

I notice if I copy just a list or just text it works fine, but if you try copy a region that includes both text and a list you tend to just get text without the list.

See below examples (textAngular is on the left). Also formatting is a bit funny.

When copying a text and list region:
![screen shot 2016-01-18 at 3 52 03 pm](https://cloud.githubusercontent.com/assets/7520773/12382139/9cdf3954-bdfb-11e5-87a8-6f05dbc9a37c.png)

When copying a list only region:
![screen shot 2016-01-18 at 3 52 13 pm](https://cloud.githubusercontent.com/assets/7520773/12382140/9ce957a4-bdfb-11e5-8990-f38483507e66.png)

**Comment by pbassut** [comment]
Hmm, tricky. What version of OneNote you're using?

Enviado do meu iPhone

**Comment by jordancrawfordnz** [comment]
I'm on version 15.18 for Mac. Can check if this issue appears on a Windows machine a bit later today.

**Comment by pbassut** [comment]
Fine. I'm on Mac too. I can reproduce it now.

**Comment by pbassut** [comment]
I'm moving forward on this. Stay tuned. :)

**Comment by lucasgranberg** [comment]
Pasting from other products will always give problems. It would be cool to be able to override this easily. For example special characters i inDesign gave me some unexpected results and if I want to do my own mappings it would be nice to override a service or inject more formatters.

**Comment by pbassut** [comment]
I think ta-bind supports a function that will get called whenever a paste occurs. Give me a few minutes to get to a computer and check this.

Enviado do meu iPhone

**Comment by JoelParke** [comment]
test

**Comment by JoelParke** [comment]
I believe that this is now fixed.  Could you re-test and comment and re-open if still an issue????  I did work a bit ago to allow pasting from OneNote to function.
