### ISSUE TITLE
How to set default row count?

### ISSUE THREAD

**Issue by ChrisMaher** [fraywing/textAngular#1028]
How do i make the clickable area fill the whole div its in rather than just one line at the top of the div?

Also is there any way to make it auto focused rather than having to click at all?

Thanks

**Comment by pbassut** [comment]
Look at #687 to know how to focus a contenteditable element.
About making the whole div clickable: you tested it on the website or you used in your application and saw this behaviour?

**Comment by ChrisMaher** [comment]
On localhost with no Placeholder text. On the textAngular website the whole box is clickable. Maybe its CSS?

**Comment by ChrisMaher** [comment]
Yes it was. CSS file not added.
