### ISSUE TITLE
Adding an ng-class directive to textAngular editor

### ISSUE THREAD

**Issue by rpelleti22** [fraywing/textAngular#1063]
Hi,

I am developping a web console for authors of children's books so that they can add their text, images, etc. from a web page. I am using textAngular to add the text and simple formatting like bold, italics, etc. However, I also need to add other css classes such as animation, fonts, background (page) color, which are not available through textAngular. I have tried to add an ng-class to the ```<div>``` holding the editor but  this poses a problem because the css classes will then be applied to the whole editor (including the toolbar!) instead of only the ta-html-editor. 
Is there a way to add an ng-class to the ta-html-editor element before textAngular compiles?
This is the html page where I use textAngular:
```html
<div class="displayText" ng-model="listText">
	<div class="titlePage">{{listText.InsidePage}}</div>
	<div class="textConteneur">
		<div class="languesOptionsConteneur">
			<div ng-repeat="l in listText.langues"
				ng-click="choisirLangue($index);"
				ng-class="{ langueColorSelected : listText.currentLanguage == $index }"
				style="box-shadow: 0 0 1px inset;"
				class="languesOptionsPosition languesColor">{{l.name}}</div>
		</div>
		<div class="textEditorConteneur">
	     	<div id="inputTextEntier" 
	     		 name = "inputTextEntier" 
				 class="textColorBlue"
				 text-angular = "textAngular"
				 ta-toolbar="[['bold','italics', 'underline', 'strikeThrough', 'html', 'clear', 'redo', 'undo']]"
				 ng-model = 'htmlContent[listText.currentLanguage]'
				 ng-focus="resetTextonFocus('textFormatting')"
				 ng-blur="resetTextonBlur('textFormatting')">
			</div>
		</div>
	</div>
</div>
```
Thanks so much for the help!

**Comment by pbassut** [comment]
I tried that and it only adds the class to the textAngular's div.
I used ```ng-class="{myClass: true}"```

Maybe you did something different?
