### ISSUE TITLE
Dismiss Keyboard

### ISSUE THREAD

**Issue by amsheehan** [fraywing/textAngular#1067]
Would love a way to dismiss the virtual keyboard on mobile after a selection has been made and a toolbar button has been applied to the selection.

**Comment by pbassut** [comment]
You can do that in your button's function by taking the focus out of the textarea. 
As for when a selection is made, you could do something like this:
```javascript
if(rangy.getSelection() != oldSelection) {
    oldSelection = rangy.getSelection();
    fireEvent("selectionUpdated");
}
```
It's a bit hacky. But we don't provide an API through taSelection yet.
