### ISSUE TITLE
Cannot bundle 1.5.0, Uncaught TypeError: rangy.saveSelection is not a function(…) when bundled 1.4.6

### ISSUE THREAD

**Issue by hinok** [fraywing/textAngular#1070]
Hey,

```
angular 1.4.7
angular-sanitize 1.4.7
rangy 1.3.0
browserify 13.0.0
```

**Summary**

- I cannot bundle `1.5.0` and other people tooo have problems with it...
- I can bundle `1.4.6` and then I'm getting error: `rangy.saveSelection is not a function`
- I use browserify
- PR **refactor(umd): Better support of UMD** https://github.com/fraywing/textAngular/pull/1023 fixes all problems, kudos @LoicMahieu

**Related to bundling 1.5.0**

- v1.5.x breaks browserify https://github.com/fraywing/textAngular/issues/1068
- Module breaks if rangy is not defined in requirejs https://github.com/fraywing/textAngular/issues/892

I found that `1.5.0` is broken and I have to revert to `1.4.6`, by:

- Error in dist/textAngular.min.js https://github.com/fraywing/textAngular/issues/1058

Reverted.
Now I have `1.4.6` and I'm able to bundle textAngular (I have small problems with taTools undefined, but after some investigation I found that it can be temporary solved by using minified version: `dist/textAngular.min.js` instead of `textAngularSetup` and `textAngular`).

So finally I'm getting to the point where I get this error:

```
TypeError: g.rangy.saveSelection is not a function
    at Scope.m.startAction (http://localhost:8000/index.js:114644:9518)
    at Scope.executeAction (http://localhost:8000/index.js:114643:6266)
    at fn (eval at <anonymous> (http://localhost:8000/index.js:38523:15), <anonymous>:4:230)
    at callback (http://localhost:8000/index.js:48750:17)
    at Scope.$eval (http://localhost:8000/index.js:41190:28)
    at Scope.$apply (http://localhost:8000/index.js:41290:25)
    at HTMLButtonElement.<anonymous> (http://localhost:8000/index.js:48755:23)
    at HTMLButtonElement.eventHandler (http://localhost:8000/index.js:28499:21)
```

Of course, I'm started exploring Issues and found that I'm not the first person who has that problem.

**Related to g.rangy.saveSelection is not a function**
- g.rangy.saveSelection is not a function https://github.com/fraywing/textAngular/issues/853

I was also trying to apply some hacks from

- Problem to work with browserify https://github.com/fraywing/textAngular/issues/713

but they just don't work.

I checked in the console and found that rangy.saveSelection is a reference to itself  - to the rangy object.

Is there any way to bundle textAngular by using browserify now?
Do you have any plans for making textAngular CommonJS compatible?
@LoicMahieu added one month ago PR which fixes all problems described above. It would be great if someone could check that PR https://github.com/fraywing/textAngular/pull/1023 and merge it if everything is OK.

**Comment by LoicMahieu** [comment]
Waiting for review.... =)

**Comment by ralphvanetten** [comment]
I can confirm that #1023 fixes the "TypeError: rangy.saveSelection is not a function" error.
The problem is in https://github.com/fraywing/textAngular/blob/master/src/main.js#L22 (and surrounding code)

It is caused by `require('rangy/lib/rangy-selectionsaverestore');` which returns the whole `rangy` object and not just a `saveSelection` function.

**Comment by pbassut** [comment]
I'm checking this now. Let me reproduce the browserify error first. And if that PR fixes it I'll check if it doesn't break anything else and merge it.

**Comment by pbassut** [comment]
Guys, I don't use browserify and I need your help to reproduce this issue.
Could someone setup a simple project or tell me how to do it?

**Comment by hinok** [comment]
@pbassut I created sample repo for you https://github.com/hinok/textAngular-browserify

**Comment by pbassut** [comment]
@hinok Looks like the minified version is not getting through because of syntax errors. This is weird, because it works on browser with a script tag.

**Comment by hinok** [comment]
@pbassut Yep, browserify cannot bundle minified version of textAngular.
This is the first problem. It can be easily avoided by using directly non-minified version of textAngular.
Instead of doing this:
```
require('textAngular');
```
We have ability to `require` specific files (based on https://github.com/fraywing/textAngular#usage)

```
require('textAngular/dist/textAngularSetup');
require('textAngular/dist/textAngular');
```

but then we all get unmighty error `taTools`.
```
bundle.js:819 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module textAngular due to:
ReferenceError: taTools is not defined
```

I created new branch if you would like to play with it https://github.com/hinok/textAngular-browserify/tree/non-minified

**Comment by hinok** [comment]
@pbassut I see that you've already merged #1123 to the `master` branch.

I created today new repo and textAngular on master branch works without any problems with browserify.
https://github.com/hinok/textAngular-browserify/tree/merged-1123

![zrzut ekranu 2016-04-12 o 22 10 44](https://cloud.githubusercontent.com/assets/1313605/14474163/e41d63b6-00fb-11e6-9412-badbaa7c3676.png)

Could you create a new tag, like `1.5.1`?
I close this issue :)

**Comment by pbassut** [comment]
@hinok Sure. I'll do that as soon as I get home. 
Thanks!

**Comment by nabblschnur** [comment]
@pbassut Don't want to push you ;). But can you please tag the current master version? I really need v1.5.0 to run with browserify.

**Comment by pbassut** [comment]
@nabblschnur Sorry!
It's there already.
Forgive me for taking too long.

**Comment by nabblschnur** [comment]
@pbassut 
Wow that was fast! Thank you!
