### ISSUE TITLE
Is it possible to ad a onLoad attribute/directive to textangular?

### ISSUE THREAD

**Issue by erex1** [fraywing/textAngular#1078]
It would be really helpful with a onLoad attribute/directive that calls a scope function when the editor has been loaded. This would be a great place to retrieve the editor with textAngularManager, set focus to the editor, and do other useful things like disabling execCommand ObjectResizing with document.execCommand('enableObjectResizing', false, 'false');

Or is there allready a better place where I could put this kind of code?

**Comment by pbassut** [comment]
There's a thread on that already. We're discussing the possibility of events on TA. #730 .
A workaround already exists. I guess DOMContentLoaded is being used in that regard.
