### ISSUE TITLE
Is there a maxlength like option available?

### ISSUE THREAD

**Issue by alexander-elgin** [fraywing/textAngular#1079]
I had checked https://github.com/fraywing/textAngular/issues/308, https://github.com/fraywing/textAngular/issues/117 and https://github.com/fraywing/textAngular/issues/619 already. I know that in textAngular there is an option `ta-max-text` which validates the HTML text length but I would like to strict the length of the HTML preventing typing of more than e.g. 255 characters (I mean what is seen after HTML rendering but not the actual HTML content including tags). I also need that on a content pasting into the editor the content is truncated down to 255 character not breaking the HTML structure.

**Comment by opadillaintegrify** [comment]
+1

**Comment by alexander-elgin** [comment]
I've created a directive for that. See https://github.com/alexander-elgin/ta-maxlength

**Comment by BukicMicko** [comment]
@alexander-elgin I tried with your directive and I am getting undefined for editor variable...

Here is how I am using it in my view:

<a class="clickable" editable-text-angular="reviewvm.findingOrObservationTitle" ta-maxlength="1000" name="title" ng-click="editableTitleForm.$show(); edit = true" ng-show="!editableTitleForm.$visible">
