### ISSUE TITLE
Is it possible to add keyDown event handler programmaticaly?

### ISSUE THREAD

**Issue by alexander-elgin** [fraywing/textAngular#1081]
I want to assign a keyDown event handler to an instance of `textAngular` got using `textAngularManager.retrieveEditor`. Is there a way to do that?

**Comment by pbassut** [comment]
Check the wiki. There are ways to handle key presses there.

Enviado do meu iPhone

**Comment by alexander-elgin** [comment]
There is nothing in the wiki (see https://github.com/fraywing/textAngular/wiki). According to https://github.com/fraywing/textAngular/issues/493 the following should work
`textAngularManager.retrieveEditor('YOUR-TEXTANGULAR-EDITOR-NAME').scope.events.keydown = eventHandler`
but it does not.

**Comment by alexander-elgin** [comment]
However the following works properly
```
textAngularManager.retrieveEditor('YOUR-TEXTANGULAR-EDITOR-NAME').scope.displayElements.text[0].addEventListener('keydown', eventHandler)
```
