### ISSUE TITLE
soft break instead of paragraph

### ISSUE THREAD

**Issue by diego-vieira** [fraywing/textAngular#1086]
Is there a setting that will do a soft break ```<br>``` instead of a paragraph ```<p>``` when you press enter?

**Comment by pbassut** [comment]
Yes. Press ```shift-enter```.

**Comment by diego-vieira** [comment]
Maybe I explained myself poorly.
Does textAngular have an option to make a <br> instead of <p> by default without holding shift?

**Comment by pbassut** [comment]
I don't think this is currently supported. 
I'll update this if I find an easy way to do so.

**Comment by diego-vieira** [comment]
thanks @pbassut just found something.
https://github.com/fraywing/textAngular/blob/master/src/taBind.js#L809

Perhaps I can send a PR including the option.

**Comment by pbassut** [comment]
Did it work? Cause this is for wrapping AFAIK.


Enviado do meu iPhone

**Comment by varmint09** [comment]
FWIW I think Shift-Return for a line-break is the expected and standard behavior in this sort of plugin – I don't personally see the benefit from this change. 

Besides <br /> tags are messy, if its paragraphs of text, use the p tag and use CSS to correct the spacing.

**Comment by pbassut** [comment]
I agree with @varmint09. Every editor out there uses the shift-return for line-break.
As he also noted, you can correct the paragraph issue with css.

I don't see why you would want to change this. Because if it's not a problem of everyone else I suggest you fork it and do your changes then possible make a PR that will be up to discussion.

**Comment by jemunk** [comment]
Add this attribute to the text-angular element:
`ta-default-wrap="div"`
which replaces the default `<p>` for new lines to `<div>`

**Comment by atheimer** [comment]
In case anyone else wanders upon this. ta-default-wrap="div" does work.  Nothing else does.
div = works as expected
none = p appended
null = p appended
span = p appended
empty = p appended
