### ISSUE TITLE
Switch editor into "source" view programatically.?

### ISSUE THREAD

**Issue by laughlinez** [fraywing/textAngular#1088]
Is it possible to switch the editor into source view pragmatically?. (i.e NOT from the editor toolbar). 
I tool a look at the editor manager api but nothing stood out.

**Comment by caiyo** [comment]
you can target the button with and call click. something like $('.fa.fa-code').parent().click(). You have to make sure the text editor is focused so that the button is not disabled

**Comment by laughlinez** [comment]
@ciayo,

Yes - I have looked at this - it is very sub-optimal. 
It also means that the UI textAngular must be visible (and by definition attached to a UI)

I may look at a PR to abstract the toolbar buttons into their own API within the editor so that you may interact with them, perhaps via a simple evented infractructure that mimics UI interaction.

I'll get back to this in a week or 10 days, when it again hits me in the face!.
