### ISSUE TITLE
Respect the "tabindex" property

### ISSUE THREAD

**Issue by s3thi** [fraywing/textAngular#109]
Assume I have the following markup:

```
<form>
    <label for="name">Name:</label> <input type="text" tabindex="1" id="name" ng-model="name">
    <label for="website">Website:</label> <input type="url" tabindex="2" id="website" ng-model="website">
    Bio: <div text-angular ta-toolbar="{{toolbarOptions}}" ng-model="bio" tabindex="3"></div>
</form>
```

I should be able to hit `<tab>` to cycle through all the inputs in the form above. If my cursor is in the `name` input, pressing `<tab>` twice should result in the cursor moving into the `bio` editor. But, the current behavior is to select the `ta-root` element instead of the `ta-editor` element when I tab through the form.

Ideally, the tabindex property should be removed from the root element and moved to the editor element.

**Comment by nalex-macaroni** [comment]
I need to be able to tab OUT of a textangular div. I have a large form with 5 textangular divs. I don't care about indenting using the TAB key, I need to be able to tab-through each in-turn. I've tried several things - if I disable the TAB response, the cursor just sits there - any ideas?
