### ISSUE TITLE
Using 1.4.6 with npm and browserify...

### ISSUE THREAD

**Issue by varmint09** [fraywing/textAngular#1093]
Hello,

As the latest release does not work with gulp/browserify, I read that version 1.6 does; and it almost does!

I have included textAngular 1.4.6 and use the following code to configure it.

```
function taOptionsConfig($provide) {

    $provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions) {

        taOptions.toolbar = [
          ['h1', 'h2', 'h3', 'p', 'quote'],
          ['bold', 'italics', 'ul', 'ol', 'redo', 'undo', 'clear'],
          ['html', 'insertImage','insertLink', 'wordcount', 'charcount']
        ];

        taOptions.forceTextAngularSanitize = false;

        return taOptions;
    }]);
}

module.exports = taOptionsConfig;
```

Now the editor does display in my browser (its odd that I don't think it can be applied to a textarea?! but I get the following error when I try to use it...

```
Cannot read property 'getSelection' of undefined

Cannot read property 'style' of null
```

What am I missing?

**Comment by pbassut** [comment]
Let's refer to the already opened issue about browserify.
Since we're having other issues with it somewhere else, the other issues will very likely solve yours.
