### ISSUE TITLE
Can I change font color ?

### ISSUE THREAD

**Issue by jinwyp** [fraywing/textAngular#11]
Hi, I didn't found the button for changing the font color，  So is there a way to do that ?

**Comment by sant123** [comment]
I just prefer to use Spectrum as color picker.

Look an example: 

http://plnkr.co/edit/0047t2ZuwDgAdGpasmi3?p=preview

*angular-spectrum restricted to 'EA'
*4 new tools at the end of TextAngularSetup.js

![example](https://cloud.githubusercontent.com/assets/7959437/8016864/0802395c-0baf-11e5-90ee-49f007389363.PNG)

**Comment by sahanrox** [comment]
@sant123 -
i added  4 tools to TextAngularSetup.js and angular-spectrum restricted to 'EA'.
but it not shows in the toolbar

**Comment by tjones0808** [comment]
@sahanrox

i had the same proble, replace your textAngular.js with his version of it and it shows up.

EDIT: Instead of using an old version of textAngular.js which had other problems, is simply added this to the latest version of line 2871 : 'ui.bootstrap.dropdownToggle', 'angularSpectrumColorpicker'

**Comment by mfrye** [comment]
Hey everyone. Sorry for any issues you have with my code. I built this years ago when I was working for a company that needed all the enhancements I added. 

I've both moved on to new technology (mainly React lately) and I'm super busy with work. I don't think I'll ever have the time to come back to this.

**Comment by tjones0808** [comment]
Heyy @mfrye  No worries here. Thanks for the repo, in the end, for the work you dude this works great for me. And with the community here very easy to make work how I needed.

**Comment by W-prog** [comment]
Hey guys, 
Has someone already tried to reproduce a plunk with the color picker for text angular ?
I am reallly interressed cause i don't reproduce the example here : https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar 
Have a nice day

**Comment by sahanelvitigala** [comment]
@W-prog - i did text color change , font change and font size change.here is the link.
[https://github.com/sahanrox/textAngular-toolbar-customized-with-font-color-font-size](https://github.com/sahanrox/textAngular-toolbar-customized-with-font-color-font-size)
[http://embed.plnkr.co/V6ZJS7GdsvRIrpznGbh9/preview](http://embed.plnkr.co/V6ZJS7GdsvRIrpznGbh9/preview)

**Comment by W-prog** [comment]
Great thank you !
