### ISSUE TITLE
Retain placeholder text after focus

### ISSUE THREAD

**Issue by tomalex0** [fraywing/textAngular#1100]
How can we still show placeholder text  even if its focused?

This is how it works http://plnkr.co/edit/blg82xFuZVHfyxucp9pb?p=preview

**Comment by pbassut** [comment]
This is not an issue with TA cause this also happens with an ordinary input.

**Comment by arzynik** [comment]
@pbassut that is not the expected behavior of an input. see https://plnkr.co/edit/blP0baWM4mt8yqzAxyq9?p=preview

would be nice to get this fixed

**Comment by persiasama** [comment]
I confirm that is an issue it's not the expected behavior of an input
