### ISSUE TITLE
Problem with copy paste extra br and break paragraph

### ISSUE THREAD

**Issue by coder1412** [fraywing/textAngular#1101]
It's not about Word copy-paste or something hard like this.
It's about a very simple task. I try to copy and paste some paragraphs without any styling and the editor always add extra br ! Please help, i really need this for my project!!!

> For Sample: Paste these very simple paragraphs into the demo at http://textangular.com/

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

**Any hot fix advices are appreciated!**

**Comment by DavidVentura** [comment]
Same here on #1155

**Comment by RDMEC** [comment]
+1

**Comment by JoelParke** [comment]
<p>I can not longer reproduce this under Firefox and Chrome with v1.5.9 so closing this....</p>
