### ISSUE TITLE
How to change while click on Image Insert than prompt 'http//:' ?

### ISSUE THREAD

**Issue by higunjan** [fraywing/textAngular#1109]
Hi, I'm developing Image upload from local and use textAngular. Now insert Image should always be take  as link not any option to upload image. so just make functionality to upload Image and return uploaded path. For now I have to copy that path and paste into Image prompt. 
Is their any way to auto push path comes on prompt at place of 'http//:'  ?

![image](https://cloud.githubusercontent.com/assets/6925531/13770092/a3ec99b8-eaaa-11e5-8e3c-d058faf64367.png)

**Comment by pbassut** [comment]
I don't understand. Where would that path come from? What you mean "auto push"? 
Are you asking if there's a way to get what's selected(or what the mouse is currently hovering) and paste that into the prompt?
