### ISSUE TITLE
how can i make pasting text from word print as plain text?

### ISSUE THREAD

**Issue by aryeharmon** [fraywing/textAngular#1113]
I know there were a lot of issues with the opposite. For them the pasting did not work with the style. and that is the behavior i want.
Looks like that issue was fixed. but is there any way to still do it?

**Comment by aryeharmon** [comment]
```
    builderApp.filter('htmlToPlaintext', function() {
        return function(text) {
            return text ? String(text).replace(/<[^>]+>/gm, '') : '';
        };
    });
```

**Comment by aryeharmon** [comment]
this removes enters

**Comment by pbassut** [comment]
Basically you should wait for regular textangular to parse what's coming from word and them use angular's ```$sce``` to remove the tags.
Something like:
```
myApp.filter("nl2br", function($filter) {
 return function(data) {
   if (!data) return data;
   return data.replace(/\n\r?/g, '<br />');
 };
});
```
