### ISSUE TITLE
Strange behavior with buttons disabling/enabling at wrong times

### ISSUE THREAD

**Issue by idungotnosn** [fraywing/textAngular#1126]
I really like this rich text editor library and would like to use it for one of my work projects.  I especially like the customizability of the buttons, and the fact that I can easily integrate bootstrap modal UI into one of the buttons. There’s a couple of bugs that have been making me reconsider using this library, though.  In the newest release of textAngular, the toolbar buttons enabling/disabling seems like a cool feature, but it happens to be the source of all my frustrations with this library due to a couple of bugs:

**Browser information:**

I observed these bugs on the latest update of chrome (49.0.2623.87) while using a MacBook Pro. 

**Bug 1 - Button goes from enabled to disabled when clicked, when it should apply style to text selection**

Reproduce this bug by doing the following on the textAngular demo at http://textangular.com/:

1. Click in the text area.  The buttons will enable.
2. Select some text in the text area and press the italics toolbar button.  The selected text will be italicized as expected.
3. Click out of the text area.  The buttons should disable again.
4. Select some text and try pressing “italics” again.  
5. Observe that buttons disable again instead of changing the selected text.

**Bug 2 - Buttons don’t enable when text in the text area is selected**

This may be intentional behavior but would still be annoying to an end user.  Reproduce this bug in the textAngular demo by following these steps:

1. Select some text in the textAngular demo but don’t release the mouse button yet.  Keep the mouse button down and move the pointer outside of the text area.
2. Observe that the buttons don’t enable

Many of the bugs seem to revolve around the buttons not enabling/disabling at the correct times.  Is there a way to stop the buttons from enabling/disabling like it did in previous versions of textAngular (like 1.1.2?)  See this codepen to look at an older version of textAngular where these issues were non-existent:

http://codepen.io/anon/pen/zqzGLr

**Comment by pbassut** [comment]
Bug 2 is not the intended behaviour. While bug 2 we [have](https://github.com/fraywing/textAngular/issues/1105) [several](https://github.com/fraywing/textAngular/issues/1044) [others](https://github.com/fraywing/textAngular/issues/1006) that's related to it and might fix this when those gets fixed.

I think this issue should be closed and bug 2 reported in another issue alone.
Please do.
