### ISSUE TITLE
Dropdown with dynamic key value array

### ISSUE THREAD

**Issue by iagocaldeira** [fraywing/textAngular#1131]
How can I  access a $scope variable inside $provide.decorator to generate a dynamic dropdown like this ( https://jsbin.com/yoqoqe/edit?html,js,output )?

**Comment by pbassut** [comment]
You don't have the scope variable in a ```$provider```, that's basic angular.
You do have have ```$rootScope``` though.

But why would you want the $scope there?

**Comment by iagocaldeira** [comment]
Sorry, I wasn't very clear.
When I set `options: $rootScope.variableOptions` on taRegisterTool and at controller `$rootScope.variableOptions = [ {name: "{{ cat1 }}"}, {name: "{{ cat2 }}"}, {name: "{{ cat3 }}"}, {name: "{{ cat4 }}"}, {name: "{{ cat5 }}"}];`
 
Dropdown list is empty and my rootscope is undefined.

Can you help me with the best way to bind the ng-repeat from dropdown toolbar and my controller variables?

**Comment by pbassut** [comment]
That's because ```config()``` runs, then ```run()``` runs, and then your controller.
That is, your ```$rootScope.variableOptions``` won't be yet.
What you want is [this two functions here](https://github.com/fraywing/textAngular/blob/742e8116f51ae76d649969bd66d43a1ba316b318/src/main.js#L848-L859)
