### ISSUE TITLE
Webpack TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by circy** [fraywing/textAngular#1133]
I use Webpack:

Stepp 1:
npm install npm install textangular --save

Step 2:
I add 2 alias in the Webpack.config.js 
` resolve: {
        alias: {
            textAngularCSS:  path.join(__dirname, 'node_modules/textAngular/dist/textAngular.css'),
            textAngularEx: path.join(__dirname, 'node_modules/textAngular/dist/textAngular-sanitize.min.js')
        }
    },`

Step 3:
I add the textangular in my app:
`
require('textAngular');
require('textAngularEx');
require('textAngularCSS');
`

And i becom this Error: TypeError: Cannot read property 'call' of undefined

What am I doing wrong?
Thanks for the help.

**Comment by pbassut** [comment]
Sorry, but this a duplicate issue. 
We already have things related to webpack. So, follow these issues to know a bit of what's going on.
