### ISSUE TITLE
Error on Using with Webpack

### ISSUE THREAD

**Issue by KarthickSelvam** [fraywing/textAngular#1147]
bundle.js:18125 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object

**Comment by KarthickSelvam** [comment]
my entry,

var angular = require('angular');
angular.module('app', [
  require('angular-ui-bootstrap'),
  require('angular-sanitize'),
  require('routes.js').name,
  require('ngstorage').name,
  require('textAngular'),

**Comment by pbassut** [comment]
Take a look at the issues opened. There's already thousands for webpack.
