### ISSUE TITLE
Model is not refreshing after custom action

### ISSUE THREAD

**Issue by pchodak** [fraywing/textAngular#1153]
I added button with custom action that adding character ('%') to trigger mentio menu. 
Right now it change the model only if i blur. I tried to blur with jquery and angular element but it does't affect to model. I tried also to refresh **textAngularManager.refreshEditor() ** but it says digest already in use. Any help with this?
http://plnkr.co/edit/qMPqKssjj76NIclbPDF8?p=preview

**Comment by roybekhuis** [comment]
@pchodak I'm having the same issue. Did you ever solve it? and if so how? Thanks!

**Comment by pchodak** [comment]
@roybekhuis Yes i solved it. http://plnkr.co/edit/8j0rMyW0Mof3k1i7LXVF?p=preview
i'm glad to help you

**Comment by roybekhuis** [comment]
@pchodak thanks for getting back to me so quickly! Sadly this isn't solving my problem though. I'm trying to implement Mentio with TextAngular. I got everything working except that the replace action by Mentio is not binding to the textAngular NgModel until I type something in the textEditor. I See you also included Mentio so you might have a solution? Thanks again!

**Comment by pchodak** [comment]
@roybekhuis This is because your model is not refreshed. Check NgModelCtrl (viewValue and modelValue) it will be different than element.value. I solved it using ngModelCtrl you should use it and then 1. focus element (textAngular) 2. ctrl.$setViewValue() 3.ctrl.$render(). Also I used event.stopPropagationon on click event on textAngular.

**Comment by roybekhuis** [comment]
@pchodak Thanks ones more for getting back to me! Any change you could share your code so I can solve my issue? I'm probably overseeing something here and fail to fix it... Cheers!

**Comment by pchodak** [comment]
[mail](mailto:przemek186@gmail.com)

**Comment by roybekhuis** [comment]
@pchodak Thanks ones more for all your help.
Finally solved the issue! I made the change in ment.io though. Seems the replace text function was not giving a change statement to the parent (textangular).

                $scope.replaceText = function (text, hasTrailingSpace) {
                    $scope.hideAll();

                    mentioUtil.replaceTriggerText($scope.context(), $scope.targetElement, $scope.targetElementPath,
                        $scope.targetElementSelectedOffset, $scope.triggerCharSet, text, $scope.requireLeadingSpace,
                        hasTrailingSpace);

                    if (!hasTrailingSpace) {
                        $scope.setTriggerText('');
                        angular.element($scope.targetElement).triggerHandler('change');
                        if ($scope.isContentEditable()) {
                            $scope.contentEditableMenuPasted = true;
                            var timer = $timeout(function() {
                                $scope.contentEditableMenuPasted = false;
                            }, 200);
                            $scope.$on('$destroy', function() {
                                $timeout.cancel(timer);
                            });
                        }
                    }

> added this line...

                    if ($scope.targetElement) {
                         angular.element($scope.targetElement).blur().focus();
                    }

                };
