### ISSUE TITLE
Remove image with 'delete' key

### ISSUE THREAD

**Issue by theo-bittencourt** [fraywing/textAngular#1157]
When click on image and press 'delete' key the default browser behavior is triggered (navigate to back) instead remove the image.

There is a workaround to solve that?

Thanks!

**Comment by pbassut** [comment]
The behaviour to delete an image is just like to delete a text. Put the cursor in front of it and hit backspace.

**Comment by theo-bittencourt** [comment]
But if user tries to delete image selecting it first, all form content will be lost.

**Comment by pbassut** [comment]
You probably want to override [this](https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L273-L377) and listen for when the delete key is hit, prevent the default behaviour and do a ```$element.remove()```.
That will do the trick.

**Comment by theo-bittencourt** [comment]
@pbassut Thanks!
