### ISSUE TITLE
Set focus to textAngular editor by default so that user can directly type on it.

### ISSUE THREAD

**Issue by induri** [fraywing/textAngular#1163]
Hi,

I'm trying to set focus to textAngular editor by default so that user can directly type on it.
I tried to get the scope of editor as below ( as suggested in another thread), but textAngularManager is not getting initialized.

```javascript
.controller('demoController', ['textAngularManager', function(textAngularManager){
  var editorScope = textAngularManager.retrieveEditor('demo-editor').scope;
  $timeout(function(){
    editorScope.displayElements.text.trigger('focus');
  });
}]);
```

or is it possible to directly set the focus programmatically in  .config(function($provide){   $provide.decorator()?

-Prakash.

**Comment by pbassut** [comment]
Take a look here #811
