### ISSUE TITLE
Hello, I have tried to insert video using textAngular in Wordpress.. But it can't upload or link any video

### ISSUE THREAD

**Issue by Ishtiaque-Shaad** [fraywing/textAngular#1171]
Please help me!

**Comment by pbassut** [comment]
You don't upload videos, you send the youtube link. Note that this only works with youtube for now.
So if you try to upload a vimeo link it just won't work

**Comment by Ishtiaque-Shaad** [comment]
I also have tried youtube link. But It only brings the preview image from the video. Not the exact video. 
Will you please give me a hint why this is happening? or how can I solve this problem?

Any help is cordially & really appreciated from my end. :) :)

**Comment by pbassut** [comment]
Take a look at the [FAQ](https://github.com/fraywing/textAngular#faq).
