### ISSUE TITLE
Count total number of characters including HTML tags

### ISSUE THREAD

**Issue by pp611** [fraywing/textAngular#1178]
Hi, I need to count the total number of characters of the edited text including HTML markup tags (the HTML content is stored with length restriction). I wrote a new tool to do the counting:

``` js
taRegisterTool('charcountall', {
	display: '<div id="toolbarCC" style="display:block; min-width:120px;">total with markup (max 4000): <span ng-bind="charcountall"></span></div>',
	disabled: true,
	charcountall: 0,
	activeState: function () { // this fires on keyup
		var editor = this.$editor();
		var html = editor.html;
		// var html1 = editor.displayElements.text[0].innerHTML;
		var noOfChars = html.length;
		this.charcountall = noOfChars;
		editor.charcountall = noOfChars;
		return false;
	}
});
```

The problem is that `this.$editor().html` seems always behind the `ng-model`. It seems that `this.$editor().html` is obtained before (or in the middle of) the digest loop while `ng-model` is displayed after the digest loop. I added a `$timeout()` to obtain the html and its length but could not  see any difference.

`this.$editor().displayElements.text[0].innerHTML` is insync with the content  but it differs from ng-model as it always has `<br>` instead of the `<br/>` in `ng-model` (there might be other differences as well). So the length is always a little short than the one of `ng-model`.

Any suggestion to get around this issue?

**Comment by pbassut** [comment]
Take a look of how [```wordcount``` is implemented](https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L790-L815) and you might get an idea of how things work.
My best guess is that you're taking the ng-model version of TA. Which as you pointed out, hasn't been filled yet. Thus, wordcount gets the innerHTML instead.

**Comment by pp611** [comment]
`wordcount` does use innerHTML, which, as I mentioned, somehow differs the ng-model in how it stores `<br>`. In the end I added a `$timeout()` call to simulate  a mouse-up event for every caret movement, which makes it a little slower, but get the exact count.

``` js
           activeState: function () { // this fires on keyup
                var editor = this.$editor();
                var html = editor.html;
                var noOfChars = html.length;
                this.charcountall = noOfChars;
                editor.charcountall = noOfChars;
                $timeout(function () {
                    editor.updateSelectedStyles();
                })
                return false;
            }
```
