### ISSUE TITLE
InsertLink is not working

### ISSUE THREAD

**Issue by mkeerthivasan** [fraywing/textAngular#1186]
Steps: 
1. Select editable area 
2. Move to next tab/browser and Copy the url 
3. Return back to the page 
4. Click on the insertLink button and paste the copied url in popup and then click Ok
5. The link is not added in editor. (If we click on the editable area before click in insert link button, it's working fine)

Is there any work around to fix this issue?

**Comment by pbassut** [comment]
It's confirmed to happen on Chrome. Haven't tested on others websites though.
As of now there's isn't a workaround for this issue unless you modify the library. Make sure to provide a PR if you do so.
Thanks for reporting the issue.

**Comment by mkeerthivasan** [comment]
Any future plan to fix this issue from your end!

**Comment by HeyJoel** [comment]
I've found a similar issue with the insert video command (testing in chrome), whereby on occasion the video image is added to the dom outside the editor (on your homepage example it is appended after the div element with the class "container"). So I think it is adding it, just in the wrong place/position.

**Comment by iggyZiggy** [comment]
+1

**Comment by JoelParke** [comment]
I believe that this is the same issue as reported #1272 and will investigate...

**Comment by JoelParke** [comment]
Corrected with PR #1279  Closing and it will be fixed in the next release.

**Comment by JoelParke** [comment]
The PR #1279 caused other issues... so I am re-opening this issue.

**Comment by JoelParke** [comment]
I can no longer reproduce this with v1.5.8.  Please detail the steps if you can reproduce now with textAngular.com.  Thanks!!!  Closing for now.
