### ISSUE TITLE
Can't resize image 

### ISSUE THREAD

**Issue by salvatoreleone** [fraywing/textAngular#1191]
Hi,

I'm implementing a custom image uploader iin Textangular that upload/retrieve ilages from Dropbox using the Dropbox Chooser. It works, and the image is inserted into the text but I cannot resize it.

Normally if you hover on images than you'll see a pop-up like menu ith options to resize the image. This is not happening.

The code should be pretty simple, but I cannot find where the issues is.

```
// custom button in textAngular
$provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions){                
    var that;
    // options for the dropbox choser
    var options = {
        // Required. Called when a user selects an item in the Chooser.
        success: function(files) {
            that.$editor().wrapSelection('insertImage', files[0].link);
        },
        linkType: "direct", // or "direct"      
        extensions: ['images'],
    };
    taRegisterTool('DropboxChooser', {
        iconclass: "fa fa-picture-o",
        action: function(){
            // makes the editor available outside
            that = this;
            // launches the dropbox chooser
            Dropbox.choose(options);                
        }
    });
    // add the button to the default toolbar definition
    taOptions.toolbar[1].push('DropboxChooser');
    return taOptions;
}]);
```
any idea? 

Edit: just find out that this is in Chrome (IE can resize)

Edit2:
I found out that if I put back the defaut 'insertImage' in the ta-toolbar than it works even with Chrome. So I guess the default one has something different in the options object?

Thanks

**Comment by salvatoreleone** [comment]
Hi again,

basing on this: https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js

I think I have to find a way to add

```
onElementSelect: {
			element: 'img',
			action: taToolFunctions.imgOnSelectAction
		}
```

but I can't inject taToolFunctions and always get` Uncaught TypeError: Cannot read property 'imgOnSelectAction' of undefined`

How do I import taToolFunctions ?

**Comment by JoelParke** [comment]
What you did by adding 'taToolFunctions' is exactly what you must do.   This fix is correct!

When I get a chance, I will add a note to the [https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar](url) so that it is clearer that one must inject things like 'taToolFunctions, 'taSelection', etc. in order to use those within tool functions.

**Comment by JoelParke** [comment]
Added the injection information to the 'Customizing The Toolbar'.
