### ISSUE TITLE
text angular not working ..

### ISSUE THREAD

**Issue by skyees** [fraywing/textAngular#1194]
Error: [$injector:modulerr] Failed to instantiate module textAngular due to:
Error: [$injector:nomod] Module 'textAngular' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.10/$injector/nomod?p0=textAngular

**Comment by skyees** [comment]
js: [
        'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js',
        'http://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js',
        '//code.jquery.com/jquery-migrate-1.2.1.min.js',
        'public/lib/supersized/slideshow/js/jquery.easing.min.js',
        'public/lib/angular/angular.js',
        'public/lib/angular-resource/angular-resource.js',
        'public/lib/angular-animate/angular-animate.js',
        'public/lib/angular-messages/angular-messages.js',
        'http://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.12.0/ui-bootstrap-tpls.min.js',
        'public/lib/javascript-detect-element-resize/jquery.resize.js',
        "public/lib/angular-gridster/dist/angular-gridster.min.js",
        'public/lib/angular-spectrum-colorpicker/dist/angular-spectrum-colorpicker.js',
        'public/lib/spectrum/spectrum.js',
        'public/lib/ng-file-upload-shim/ng-file-upload.js',
        'public/lib/textAngular/dist/textAngular-rangy.min.js',
        'public/lib/angular-sanitize/angular-sanitize.min.js',
        'public/lib/angular-ui-router/release/angular-ui-router.js',
        'public/lib/angular-ui-utils/ui-utils.js',
        'public/lib/angular-bootstrap/ui-bootstrap-tpls.js',
        'public/lib/angular-scroll/angular-scroll.min.js',
        'public/lib/ngDraggable/ngDraggable.js',
        'public/lib/jquery-box-slider/js/lib/modernizr.min.js',
        'public/lib/jquery-box-slider/js/box-slider-all.jquery.min.js',
        'public/lib/supersized/slideshow/js/supersized.3.2.7.min.js',
        'public/lib/supersized/slideshow/theme/supersized.shutter.min.js',
        'public/lib/angular-file-upload/angular-file-upload.js',
        'https://api-cdn.amazon.com/sdk/login1.js',
        'public/lib/owasp-password-strength-test/owasp-password-strength-test.js',
        'public/lib/ng-facebook/ngFacebook.js',
        'https://cdn.rawgit.com/olton/Metro-UI-CSS/develop/build/js/metro.min.js',
        'public/lib/object-fit/dist/polyfill.object-fit.js',
        'https://www.paypalobjects.com/js/external/api.js',
        'public/lib/textAngular/dist/textAngularSetup.js',
        'public/lib/textAngular/dist/textAngular.js',
        ],

**Comment by pbassut** [comment]
I can't help you without a more descriptive scope of your setup.
This is working everywhere else.
Have you tried using textAngular.min.js alone instead?

**Comment by skyees** [comment]
Before that it works fine but now it showing errors i think because of compatibility version with node.js or mean.js ..it is meam.js application  i am going to intigrate  it showing errors

**Comment by pbassut** [comment]
So, I'll close this issue if you start seeing errors in a very unusual way, let me know. And I'll try to help you.
