### ISSUE TITLE
Add Superscript and Subscript button

### ISSUE THREAD

**Issue by ezuniga** [fraywing/textAngular#1197]
Hi! I want to add a button like Bold or italic but for superscript(`<sup></sup>`) like 5^2 and subscript(`<sub></sub>`) expressions, Can you please guide me in how to do this?

**Comment by gbittmann** [comment]
This should be enough to get you started.

https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

```
                taRegisterTool('sup', {
                    buttontext: 'sup',
                    action: function() {
                        this.$editor().wrapSelection('superscript', '');
                    }
                });
```
