### ISSUE TITLE
Using Backspace in WYSIWYG before links causing additional styles?

### ISSUE THREAD

**Issue by pwilms** [fraywing/textAngular#1207]
Using Backspace in WYSIWYG before links causing additional styles in Chrome?
Plunkr: [http://plnkr.co/edit/7M3oK4?p=preview](http://plnkr.co/edit/7M3oK4?p=preview)

For example:

`<p><span>Lorem ipsum&nbsp;</span><a href="mailto:lorem@ipsum.de" target="">lorem@ipsum.de</a></p>`

In WYSIWYG mode i put a linebreak before the href and directly undo it with backspace. The link looks like:

`<p><span>Lorem ipsum&nbsp;</span><a href="mailto:lorem@ipsum.de" target="" style="background-color: rgb(255, 255, 255);">lorem@ipsum.de</a></p>`

**Comment by JoelParke** [comment]
Very interesting: 
On the plnkr.com given above, the <html> before doing anything is:
`<p><span>Lorem ipsum&nbsp;</span><a href="mailto:lorem@ipsum.de"      target="">lorem@ipsum.de</a></p>`
Then as soon as I click into the editor and add a space character before the ipsum, I see (after ~0.5 sec, one digest cyle I think):
`<p><span>Lorem  ipsum </span><a href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=lorem@ipsum.de" target="_blank">lorem@ipsum.de</a></p>`
This looks like the digest cycle... which does some magic...

I will look into this tomorrow.

**Comment by JoelParke** [comment]
The issue if from Chrome.  We already have a taFixChrome factory that does a LOT of cleanup of the junk from Chrome.   The question is, can I also remove the added style stuff without removing additions from the user and not Chrome.... 

Looking into this some more, but this may become:  wontfix because of Chrome... we will see.

**Comment by JoelParke** [comment]
I did the work to remove this additional styling and that removal only happens when the removal of the other odd styling from Chrome has taken place.  So I need to investigate if this breaks any user added styling...  I think it may be okay, but I will check.

**Comment by JoelParke** [comment]
Fixed with release v1.5.2
