### ISSUE TITLE
prepopulate text area

### ISSUE THREAD

**Issue by KRav007** [fraywing/textAngular#1212]
Hi there, 
how could it be possible to prepopulate the text area with a custom html.

Cheers K.

**Comment by stevokk** [comment]
Having a string value already set before binding to textAngular should do this automatically?

Here is an example plunker that may help with using textAngular:
http://plnkr.co/edit/t1YIpwLjPo7yNfVTWPAt?p=preview

**Comment by pbassut** [comment]
Exactly! Just do what @stevokk said and you're good to go.
