### ISSUE TITLE
Support for multi-line placeholder text

### ISSUE THREAD

**Issue by madmarcel** [fraywing/textAngular#1215]
Would it be possible to add support for multi-line placeholder text?

As in, add the newline characters in the placeholder text, and have the element
render the multi-line text correctly?
<text-angular id='foo' ng-model="example" placeholder="this\nis\n\an\example"></text-angular>

**Comment by stevokk** [comment]
textAngular uses the innerHTML attribute of the element to keep the original content, you could pre process your content and replace `/n` with `<br>` via a regex?

**Comment by madmarcel** [comment]
Tried that, it doesn't interpret the html text in placeholder attribute as html.
``
<text-angular id="content" ta-toolbar="toolbarbuttons" ng-model="myContent" required="true" placeholder="This Is An Example<br>Line Number Two<br>Line Three<br>"></text-angular>
``

**Comment by stevokk** [comment]
Sorry I misread your initial issue and assumed you were talking about the HTML within the directive on page load. Your issue is not with textAngular as the directive will directly copy any placeholder attribute on to the textarea element. 

```
if (attrs.placeholder) {
  scope.displayElements.text.attr('placeholder', attrs.placeholder);
  scope.displayElements.html.attr('placeholder', attrs.placeholder);
}
```

Are you seeing multiline placeholder text working on regular HTML elements?

**Comment by pbassut** [comment]
As @stevokk said, we respect the html5 placeholder attribute.
However, we don't extend it's support for multi-line or html rendering(html inside an html attribute would be weird and messy).
I'm not sure this is something we could implement for a general use.

Therefore, you can easily mimic the behaviour you want by listening to onblur and onfocus events to remove/add the placeholder if the textarea is empty.
