### ISSUE TITLE
Firefox: Only able to insert line breaks (<br>), and not paragraphs (<p>) when deleting all content

### ISSUE THREAD

**Issue by JohnBernardsson** [fraywing/textAngular#1217]
**Reproducible:** always
**Browsers:** Firefox (tested on Firefox 47)
**Operating system:** Windows 10

**Steps to reproduce:**
- Open http://textangular.com
- Select **all text with the mouse**, and press Delete or Backspace
- Type some text and press Enter. A ```<br>``` will be inserted instead of a new ```<p></p>```

From now on, you are "trapped" in ```<br>```s, and you won't be able to insert paragraphs with the enter key.

This can be a big problem, not only because of the fact that you can't insert paragraphs, but because inserting other stuff as lists will be completely messed up.

**Comment by alyrik** [comment]
The same for me. Firefox. Mac OS. The same is for selecting all the content with Cmd+A and then deleting it.

**Comment by JoelParke** [comment]
I have reproduced this and see some other weird behavior with Firefox -- I will be look into this.
And fix soon.

**Comment by JoelParke** [comment]
The fix is simple and reasonable.  I will commit it to master as soon as my last PullRequest is merged.

**Comment by JoelParke** [comment]
Fixed with release v1.5.2
