### ISSUE TITLE
Firefox: new lines are not wrapped with <p> after image is inserted.

### ISSUE THREAD

**Issue by alyrik** [fraywing/textAngular#1223]
Firefox.

Try to insert image on official demo page and then make new lines right after that. These lines will not be wrapped with `<p>`:

![screen shot 2016-07-07 at 13 24 19](https://cloud.githubusercontent.com/assets/10388022/16650347/5aaf5fe2-4446-11e6-94a6-a2e6449ab2b6.png)

**Comment by JoelParke** [comment]
Looking into this, I find that when you insert an image in the demo on FIREFOX, the insert of the image generates the following html:
`<p><b>Code at GitHub:</b> <a href="https://github.com/fraywing/textAngular">Here<img src="http://dy999ib17dqym.cloudfront.net/skin/frontend/peets/main/images/promo-image-coffee-page.jpg"></a></p>`
AND on chrome it generates:
`<p><b>Code at GitHub:</b> <a href="https://github.com/fraywing/textAngular">Here</a><img src="http://dy999ib17dqym.cloudfront.net/skin/frontend/peets/main/images/promo-image-coffee-page.jpg"></p>`
which is correct. 

Notice that on Firefox, the image is inserted inside the <a></a>.  So to reproduce this bug, you need to have a link at the end of the line as in the demo.

I will look into this a bit more, but I would suggest as a work around, enter a space before inserting an image for now.

**Comment by JoelParke** [comment]
I have a fix for this and will put a pullRequest out there later today....

**Comment by JoelParke** [comment]
Please test with the fix: https://github.com/fraywing/textAngular/pull/1225 which should correct this issue.

**Comment by JoelParke** [comment]
Fixed with v1.5.2
