### ISSUE TITLE
Impossible to add Iframe

### ISSUE THREAD

**Issue by Fristing** [fraywing/textAngular#1229]
Hi,
I create a tool to post an iframe. I see in editor mode the result but in html mode no iframe. Why ?
This is my code : 
`taRegisterTool('insertVideoYT', {
      		iconclass: 'fa fa-youtube-play',
      		action: function(){
            var urlPrompt;
            var $window = $windowProvider.$get();
      			urlPrompt = $window.prompt("Lien de la vidéo:", 'https://');
      			if (urlPrompt && urlPrompt !== '' && urlPrompt !== 'https://') {
              urlPrompt = urlPrompt.replace("https://www.youtube.com/watch?v=", "https://www.youtube.com/embed/")
      				return this.$editor().wrapSelection('insertHtml', '<iframe src="'+urlPrompt+'" frameborder="0" allowfullscreen></iframe>', false);
      			}
      		}
      	});`

Thanks !
Best Regards
Fristing

**Comment by stevokk** [comment]
iframes would be stripped out by the sanitize function, textAngular has an inbuilt YouTube placeholder, is there a reason you are unable to use that? You'll need to understand the use of renderers and reverseRenderers if you wanted to implement your own solution.
