### ISSUE TITLE
Model becomes empty after edit for some templates and with 'disableSanitizer = true'

### ISSUE THREAD

**Issue by driver-by** [fraywing/textAngular#1230]
For some html, if you edit the text, model becomes empty. But only with 'disableSanitizer = true'.
Here is an example of html: 
`'\n\n<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-spacing: 0px; border-collapse: collapse; padding: 0px; font-size: 12px; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; "><tr><td>xxx</td></tr></table>'`
and [plunker](http://plnkr.co/edit/MuQNXYr3vBz07gp4bjaS?p=preview) (try to edit the field in the first textarea, the second one works fine)

What helps to fix that in the sample template:
1. Remove one of the first '\n\n' charachters.
2. Remove entire 'style=".."' attribute in the table

Looks really strange.
I have to disable sanitizer because I work with complex email-templates in text field. And these templates doesn't always work properly with sanitizer.

**Comment by JoelParke** [comment]
This is very interesting.   I am looking at this with a number of fixes already in the code for the next release and will see if I can figure out why this is happening.

**Comment by JoelParke** [comment]
This happens in Chrome and Firefox.  Also if the html has one blank line at the start, all you need to do is toggle back and forth between the html and wysiwyg view. and MAGIC all the html is gone!  
YUCK!

**Comment by JoelParke** [comment]
This looks difficult to fix. I will punt for today....

**Comment by JoelParke** [comment]
<p>I took a long look at this again yesterday.  The code in this whole area is relatively difficult to modify.  It will take some time and perhaps this section of code needs a full redesign which will be difficult. </p><p>One way in which you can see some of the issues, is to simply take your </p><pre>&lt;table&gt;....&lt;/table&gt; </pre><p>example and add a 'a' character before the 'html' in the html view.  When you switch to the WYSIWYG  view your see the expected view, and it you view the underlying html using Chrome's Developer Tools and selected Elements and viewing the &lt;input&gt; element you will see this have become </p><pre>&lt;p&gt;a&lt;/p&gt;...&lt;table&gt;...&lt;/table&gt; </pre><p>as expected.  BUT the 'html' view is still</p><pre>a&lt;table&gt;...&lt;/table&gt;</pre><p>as before.  YUCK</p><p>If I can see a good way synchronize this with the &lt;input&gt; element it will get better.  But the fact that it doesn't do that yet is why I believe a redesign of this area of the code is needed.</p><p>How big of an issue is this for you at this point.  Have you discovered any good work arounds?</p>

**Comment by driver-by** [comment]
Thanks for your try!
For me that's not a big issue now. I've just removed the '\n\n' from the templates. They generate from the other source with comments at the start, that's the reason of break lines.

But it was really a bad day when I was trying to figure out what the heck is going on :)
So it's really critical fro other users, as they could encounter with the same problem.

**Comment by JoelParke** [comment]
I have just about fixed this.  I need to spend some time tomorrow making sure that my changes will not break the functionality that folks depend on related to trimming white space.

**Comment by JoelParke** [comment]
I will finish this tomorrow.  The issue is how best to keep the html and the ngModel in sync.  And another day of thought makes sense.  It now works, but one can get the html out of sync from the model and I would like to stop that.

**Comment by JoelParke** [comment]
v1.5.3 fixes this... please check...

**Comment by driver-by** [comment]
Really good news, thanks!
I'll definetly check

**Comment by driver-by** [comment]
Fix works fine with provided plunkr but still doesn't work for my templates :(
I've modified plunkr and added one bad template with small modifications that fix bad behaviour
[click here](http://plnkr.co/edit/MuQNXYr3vBz07gp4bjaS?p=preview). There is really strange pattern.

**Comment by driver-by** [comment]
Looks like comments make the problem here. Maybe textAngular should clear comments from the model at the start?

**Comment by driver-by** [comment]
@JoelParke should I create new issue?

**Comment by JoelParke** [comment]
Please test with v1.5.5 which should resolve this. I will close, and please re-open if this is still an issue!

**Comment by driver-by** [comment]
It works!
