### ISSUE TITLE
textAngularManager leaking toolbar scopes

### ISSUE THREAD

**Issue by TheWizz** [fraywing/textAngular#1231]
I'm having trouble with textAngularManager leaking toolbar scopes. When a toolbar scope is destroyed, this is handled by 

```
	scope.$on('$destroy', function(){
		textAngularManager.unregisterToolbar(scope.name);
	});
```

in the textAngularToolbar directive, which calls unregisterToolbar on textAngularManager, thus removing it from textAngularManager's "toolbars". So far so good. However, textAngularManager also keeps references to toolbar scopes here:

```
	// _toolbars is an ARRAY of toolbar scopes
	var _toolbars = [];
```

Scopes are added to this array in two places, but are never removed. Hence, in my application (which creates toolbars dynamically, as needed, destroying them as they're no longer needed), _toolbars holds on to destroyed toolbar scopes, which it also keeps calling functions on when focus/blur and other events occur.

It seems to me that some mechanism is called for. This could either be done through unregisterToolbar (somewhat more complicated since _toolbars isn't available from that scope). Alternatively by anoher '$destroy'handler on scopes added to _toolbars, removing those from _toolbars.

I don't feel sufficiently familiar with the textAngular source code to veture a fix myself, but hopefully the above provides enough context and details for someone involved with the project to quite easily implement the best solution.

**Comment by snugbeard** [comment]
+1
We're struggeling with memory leaks in our SPA - which makes use of textAngular - as well, therefore we strongly support a fix for that.

**Comment by domyos** [comment]
+1 We're having memory issues, too. A fix would help us alot.

**Comment by JoelParke** [comment]
I just created a PR #1231 that fixes this issue.  It will be in the next release.
Thanks for reporting this and so clearly narrowing down the issue.
