### ISSUE TITLE
Pasting from word

### ISSUE THREAD

**Issue by worldspawn** [fraywing/textAngular#124]
So... inevitably, our clients have started trying to paste msword content in to textAngular. So I am just wondering if this is something that has any support?

**Comment by kotmatpockuh** [comment]
`<h3 xmlns="http://www.w3.org/1999/xhtml" id="sites-page-title-header" style="color: rgb(0, 0, 0);text-align: left;"><b><span id="sites-page-title" dir="ltr">Corporate party at 20 12.00</span></b></h3>
<span class="announcementsPostTimestamp" id="afterPageTitleHideDuringEdit" style="color: rgb(102, 102, 102);">posted<span class="Apple-converted-space">&nbsp;</span><span xmlns="http://www.w3.org/1999/xhtml" dir="ltr">Dec 1, 2011, 4:34 AM</span><span class="Apple-converted-space">&nbsp;</span>by me &nbsp;<span class="Apple-converted-space">&nbsp;</span><span id="sites-announcement-updated-time" class="updatedTime"><b>[ updated<span class="Apple-converted-space">&nbsp;</span><span xmlns="http://www.w3.org/1999/xhtml" dir="ltr">Dec 6, 2011, 4:36 AM</span><span class="Apple-converted-space">&nbsp;</span>]</b></span></span>
<div id="sites-canvas-main" class="sites-canvas-main">
   <div id="sites-canvas-main-content">
      <table xmlns="http://www.w3.org/1999/xhtml" cellspacing="0" class="sites-layout-name-one-column sites-layout-hbox" style="width: 936px;">
         <tbody>
            <tr>
               <td class="sites-layout-tile sites-tile-name-content-1">
                  <div dir="ltr">
                     <span style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);">blablabla&nbsp;blablalba</span><br style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);"><br style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);"><span style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);">blablalba&nbsp;</span><span style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);">Заяц попрыгает с ребятами по “льдинкам”, построит blablalba&nbsp;</span><span style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);">blablalba&nbsp;</span><span style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);">blablalba&nbsp;&nbsp;</span><br style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);"><br style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);"><span style="color: rgb(0, 0, 0);float: none;background-color: rgb(255, 255, 255);">blablalba:&nbsp;</span><a href="http://" style="color: rgb(85, 26, 139);background-color: rgb(255, 255, 255);">http://</a><span style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);">&nbsp;</span><br style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);"><span style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);">Длительность:&nbsp;</span><span style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);">1.5-2 часа&nbsp;</span>
                     <div style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);"><span style="text-align: left;"><br></span></div>
                     <div style="color: rgb(0, 0, 0);text-align: left;background-color: rgb(255, 255, 255);"><font face="tahoma, arial, verdana, sans-serif, 'Lucida Sans'"><span>blablalba</span></font></div>
                  </div>
               </td>
            </tr>
         </tbody>
      </table>
   </div>
</div>
`

hello


how could i drop formatting like style's etc when copy-paste from other sources? just leave html tags?

when i send it to server i use regex, but how to be with copy-paste?

**Comment by SimeonC** [comment]
To intercept the pasted content you want to use ta-paste. e.g. `ta-paste="modifyHtml($html)"`. In this case $html is a generated variable that contains the pasted html/text, the result of the expression, modifyHtml in this case, is what is pasted in.

**Comment by jeserkin** [comment]
Is it described in wiki or somewhere as well?

**Comment by markleusink** [comment]
@jeserkin I'm having a similar issue. Did you figure out exactly what formatting is causing it? It might be fixable with a `ta-paste` function.

**Comment by jeserkin** [comment]
@markleusink tried it, but as far as I can see it is sanitizer issue or normal work. There was some workaround posted here in some similar issue, but workaround author isn't sure how will it change the behavior.

**Comment by noldotar** [comment]
I had troubles on pasting text in Windows (on Mac works perfectly), the escape wasn't added, and the bold isn't displayed.
I solved using ta-paste="modifyHtml($html)" in text-angular tag, then I created the function:
scope.modifyHtml = function(html) {
	html = html.replace(/\r|\n/gi, '<br>');
	return html;
}
This added the line break, but the bold is lost while pasting

**Comment by episodeyang** [comment]
It's likely that some of the built in preprocessor is doing this. I might try to make it more customizable by using angular.value and expose these functions.
