### ISSUE TITLE
JavaScript error when pasting an image

### ISSUE THREAD

**Issue by hughanderson4** [fraywing/textAngular#1247]
I receive a Js error in console when I paste an image into text-angular.

I have created a Plunkr to demonstrate the issue

https://embed.plnkr.co/7Iy8dUOkLtdM8wVoh3Vy/

open MsPaint or similar editor, create a small image, "copy" it.

go to the Plunk, type the text "asdf asdf asdf asdf" into the text editor, then "ctrl-v" to paste the image from the clipboard.

in the Js console you can see the error message

```Uncaught TypeError: Cannot read property 'match' of undefined```

It happens whether or not I use ta-paste. The Plunk has a pass-through implementation of ta-paste in the script.js which does nothing. If the ta-paste attribute is removed altogether, the behavior is the same.

Browser: latest Chrome Version 51.0.2704.103 m
Today (7/25/2016) I copy and pasted the required text-angular js and css files from the dist folder into my Plunk.

**Comment by JoelParke** [comment]
I will take a look at this later today. This error was introduced after 1.5.0.  QUESTION: What does this do in version 1.5.0 and earlier under windows? THANKS.

**Comment by JoelParke** [comment]
This is corrected with PR #1249, and it does what it did before which is nothing... (Limitations of clipboard paste and html).
