### ISSUE TITLE
Backspace key does not work

### ISSUE THREAD

**Issue by rbatllet** [fraywing/textAngular#1252]
What happens with the keyboard ? The `Backspace key` does not work.

I can't remove the content created with the `Enter key` and using the `Backspace key`:

```
<p><br></p>
<p><br></p>
<p><br></p>
```

Could you fix it ?

**Comment by JoelParke** [comment]
This is very much related to the bug (issue #1230) and is being looked at.  But seems difficult to fix easily.

**Comment by rbatllet** [comment]
In other editors, the `Enter key` generates:

```
<p>&nbsp;</p>
```

Instead of:

```
<p><br></p>
```

But, It cannot be removed either.

**Comment by JoelParke** [comment]
I believe that this corrected with release 1.5.3 --
Could you verify and close?  
Or comment if you still have an issue!

**Comment by rbatllet** [comment]
The `Backspace key` does not work yet in the new version.

I happens something strange: 
If you only press the `Enter key` and see the `html source mode`, the content is  empty and the cursor can be moved to the last pressed `Enter key` in the `WYSIWYG mode`.

I've tested it with the last version of Firefox and Chrome in MacOS El Capitan.

**Comment by JoelParke** [comment]
I believe this is resolved with PR #1259
Could you please check and close???
Also PR #1260 corrects the formatting.. which #1259 messed with.

**Comment by rbatllet** [comment]
I've tested it with the master branch and it does not work yet.

In what OS are you using to test it?

**Comment by JoelParke** [comment]
The issue here is tied to how TA works.  I am thinking about it some more.  
This is not really related to the keyboard.  Lets see if I can move it along.  
I test on Windows 10 & Ubuntu.  Chrome and Firefox.  primarily.

**Comment by rbatllet** [comment]
I'm going to test it on Ubuntu as well. I'll tell you if this works ...

**Comment by JoelParke** [comment]
I have a new version to check-in sometime tomorrow.  It improves things a bit more.  It is difficult to fix because Chrome and Firefox function differently.  Chrome is more consistent, but to have them both work, more consistently it is necessary to sometimes have the html view be out-of sync with the wysiwig view. I will test some more tomorrow.

**Comment by JoelParke** [comment]
The final changes at in PR #1262 which I will merge into the master branch as soon as they clear.
This will probably be the best we can do, but I am hopeful the behavior will be a tiny bit better and more consistent.  We can't make this perfect because Firefox and Chrome are different!

**Comment by rbatllet** [comment]
Are you sure it's solved ? Neither Firefox nor Chrome works on MacOS El Capitan

Note: The TextAngular 1.4.6 does work. You can try it here -> http://textangular.com/
