### ISSUE TITLE
taBind directive requiring ng-model

### ISSUE THREAD

**Issue by 1111x** [fraywing/textAngular#1261]
I'm trying to view YouTube links, but they are appearing as images. I've followed the FAQ and have used the HTML below
`<div ta-bind ng-bind-html="story.bindHTML"></div>`

but my browser complains that "Error: [$compile:ctreq] Controller 'ngModel', required by directive 'taBind', can't be found!" This error goes away when I add the ng-model attribute, but the links still show as img tags.
`<div ta-bind ng-bind-html="story.bindHTML" ng-model="story.bindHTML"></div>`

Here is the HTML generated by the editor
<img width="873" alt="screen shot 2016-07-31 at 10 04 26" src="https://cloud.githubusercontent.com/assets/7280094/17276995/34d755e0-5706-11e6-93f2-8a2b700760a3.png">

I am using version 1.5.3 with Angular 1.5.7 and have confirmed I'm only using textAngular-sanitize.js. 

<img width="1026" alt="screen shot 2016-07-31 at 09 45 04" src="https://cloud.githubusercontent.com/assets/11162377/17276962/52978c0e-5705-11e6-9cd7-7e4a4d2aa063.png">

**Comment by rsaintcyr-creditshop** [comment]
My bad... FAQ clearly shows use of ng-model instead of ng-bind-html.

**Comment by 1111x** [comment]
My bad.... FAQ clearly shows ng-model instead of ng-bind-html. Video worked just by removing the latter.
