### ISSUE TITLE
Model becomes empty after edit for some templates and with 'disableSanitizer = true'

### ISSUE THREAD

**Issue by driver-by** [fraywing/textAngular#1265]
This issue continues the problem in issue #1230.
While edit the text in textAngular model becomes empty. [Plunker is here](http://plnkr.co/edit/MuQNXYr3vBz07gp4bjaS?p=preview)
Try to edit text in each input and you'll see the model underneath.
There is no pattern to find the reason. Removing various elements in template solves the problem.

Maybe html comments shouldn't be kept in the model. Looks like comments one of the main problems there.

**Comment by JoelParke** [comment]
I am continuing to work on this.  I am hopeful that we can get a release that resolves all these issues.   Thanks, Joel

**Comment by JoelParke** [comment]
Please test with v1.5.5 which should resolve this. I will close, and please re-open if this is still an issue!

**Comment by driver-by** [comment]
It works!
