### ISSUE TITLE
No paragraphs anymore after empty content

### ISSUE THREAD

**Issue by bouks** [fraywing/textAngular#1268]
Can be reproduce on live demo. So i will describe the steps in the live demo

1. Remove the content of the area
2. Write some content
3. Push <enter> to have a new paragraph and write some new content in this paragraph.

Bug: there is no new paragraph, only BRs (inside the initial paragraph). You have to use the "P" button if you want more paragraphs.

**Comment by JoelParke** [comment]
Please test with v1.5.5 which should resolve this.  I will close, and please re-open if this is still an issue!
