### ISSUE TITLE
Sanitation example

### ISSUE THREAD

**Issue by joscarras** [fraywing/textAngular#1271]
Hello guys! Thanks for the great plugin!

I am currently creating some actions that add custom directives, and I have been looking for an simple example on how to add them to the sanitizer but I cant find one.

Could you please show me a link or provide an example how we would accomplish this?

Best regards!

**Comment by stevokk** [comment]
It depends on how you define your custom directives, are they via class, element or attribute? I do it using attributes and I can make an exception for our custom video player placeholder image by editing the following existing function :

```
// this function is used to manually allow specific attributes on specific tags with certain prerequisites
function validCustomTag(tag, attrs, lkey, value){
  // catch the div placeholder for the iframe replacement
  if (tag === 'img' && attrs['ta-insert-video']){
    if(lkey === 'ta-insert-video' || lkey === 'allowfullscreen' || lkey === 'frameborder' || (lkey === 'contenteditable' && value === 'false')) return true;
  }
  
  // New BC player tag format support (using img placeholder and custom renderer, see setup file)
  if (tag === 'img' && attrs['ta-insert-bc-video']){
    return true;
  }
  
  return false;
}
```

**Comment by joscarras** [comment]
Hey! Thanks for the quick reply!

I can do it anyway I prefer so if it easy to use attributes I can change the directives to work with attributes.

Here is the test example I currently have

```
textAngularManager.addTool( 'def', {
    iconclass: 'fa fa-square',
    buttontext: 'def',
    action: function() {
        alert('Def Pressed');
        var txt = window.getSelection();
        var sel = angular.element( taSelection.getSelectionElement() );
        this.$editor().wrapSelection('insertHTML', '<test>' + txt + '</test>' , true );
    }
}, 1 );
```

In order for the model to get the custom directive, I need to pass

`<text-angular ng-model="model"  ta-unsafe-sanitizer="true"></text-angular>`

and reading #335 its suggested to not use the unsafe but instead to register them.

I understand the function validCustomTag and its simple, however it is still not clear to me where to add this function. Should I add it in the object definition I pass to addTool?

Best regards!

**Comment by stevokk** [comment]
The function is within the sanitize file:

https://github.com/fraywing/textAngular/blob/master/src/textAngular-sanitize.js#L573

I unfortunately don't know of another way to handle adding exceptions other than editing the file directly as this is originally provided by the angular team and then modified by textAngular developers to loosen the restrictions on allowed elements and properties.

I guess it would be possible to DI a new Angular.value of allowed custom elements in to the sanitize module, but this would be more of a large feature request.

Hope this cleared things up for you!

**Comment by joscarras** [comment]
Thank you Steven!

This has really cleared things up! I though there was way to customize the sanitize process without having to change core files!

Best regards!

**Comment by stevokk** [comment]
Glad I could help, best of luck!
