### ISSUE TITLE
Drag and drop text in textarea makes editor jump to the top

### ISSUE THREAD

**Issue by Schaemelhout** [fraywing/textAngular#1276]
When you make the text area big enough so it doesn't fit the screen vertically and you drop some text in it, the editor jumps to the top automatically. This behavior is even present in the demo on http://textangular.com/. Is there any way to fix this? Or any workarounds for disabling this behavior?

**Comment by JoelParke** [comment]
I saw this happen, but then checked it again and could not get it to reproduce.  Can you check it again?  And Let me know how to reproduce this under Ubuntu?  Or do I only need to try it under windows?  Thanks.  I tried with 1.5.6-0 with the demo as posted: http://textangular.com/

**Comment by Schaemelhout** [comment]
I could only test it out on Windows, but here's the issue illustrated in a GIF:

![](https://media.giphy.com/media/3o6ZsYjDpbB5tVOCSQ/giphy.gif)

**Comment by Schaemelhout** [comment]
Hi Joel,

The issue seems to be resolved when removing [this line of code](https://github.com/fraywing/textAngular/blob/master/src/main.js#L570).

I don't know what effects this change has on other parts of the functionality of the editor...
