### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by pixael** [fraywing/textAngular#1280]
Hi
a customer has noticed a very strange issue. He can't see icons from various devices. I can't reproduce the error so I don't really know what is happening. Does anybody have similar issues?

![schermata 2016-08-19 alle 09 32 40](https://cloud.githubusercontent.com/assets/14755958/17803465/7b057e42-65ee-11e6-8c50-1f30650f8203.png)

**Comment by stevokk** [comment]
Looks like font-awesome is failing to load, does he have the log from the developer tools?

**Comment by pixael** [comment]
Yes it was the case! Looks like he had issues with the browser's cache. I've suggested him to delete the cache, everything is working now.
