### ISSUE TITLE
Multiple text angular directives on page are sharing the same toolbar button state

### ISSUE THREAD

**Issue by NathanGRomano** [fraywing/textAngular#1282]
I have multiple text angular directives.  When I go to edit content, the button UI states are synchronized for all instances.

**Comment by JoelParke** [comment]
Thanks for reporting this.... I will hopefully get to this soon!

**Comment by JoelParke** [comment]
I have fixed this and will commit in a few...!!

**Comment by JoelParke** [comment]
Fixed in v1.5.7

**Comment by NathanGRomano** [comment]
You are awesome thanks!
