### ISSUE TITLE
Using tab key to put focus into a textangular control doesn't add .focussed to the text-angular-toolbar element

### ISSUE THREAD

**Issue by rdeutsch** [fraywing/textAngular#1285]
I have a <text-angular-toolbar> element alongside my <text-angular> element. I'm using the .focussed class in my custom CSS to hide the toolbar until the user puts focus in the textangular control. 

Here is my CSS: 
    .ta-toolbar .btn-group{
        opacity: 0;
        transition: opacity 0.3s ease;
    }
    .ta-toolbar.focussed .btn-group{
        opacity: 1;
    }

MOUSE - works as expected:
This works perfectly well when using the mouse - the sequence of events is:
1. User clicks into the text-angular box
2. Both the <text-angular> and the <text-angular-toolbar> elements get the .focussed class applied correctly
3. My css makes the toolbar appear with an animation - success!

KEYBOARD - does not work as expected:
This does NOT work when using the keyboard to tab into the text-angular box - repro steps:
1. From somewhere else in the form, tab until you enter the text-angular box
2. Only the <text-angular> element gets the .focussed class. The <text-angular-toolbar> does NOT get the .focussed class applied
3. Without the .focussed class, my css doesn't make the toolbar visible. 

I'd expect the .focussed class to get applied to the toolbar in the keyboard case as well. 

(Note: I found issue #379, and this might have a similar root cause? But this issue still repros with the fix for #379)

**Comment by JoelParke** [comment]
Can you edit the Plunker for v1.5.7 so I can check this? and put a link here.  Thanks!

**Comment by rdeutsch** [comment]
OK here is a plunker that shows the issue: http://plnkr.co/edit/ovlGDrd6xvSb173LU1kj?p=preview

In playing with it some more, I just found that the toolbar does end up showing up (with the .focussed class) as soon as you type anything into the box. So, the toolbar doesn't get the .focussed class immediately on tabbing into the textangular box, but then the toolbar does get the class applied as soon as you type any key. 

Given that, this is a pretty minor issue, and I'm ok if you triage this as won't fix & close it.

**Comment by JoelParke** [comment]
I have corrected this with a PR #1300 and will close this issue.  Thanks very much for the plunker.  This helped me fix this easily. Although it took a day to get our tests to all run without error.  That was due to using and $apply() instead of a $timeout() in this one piece of code and interaction with karama, YUCK.
