### ISSUE TITLE
rangySelectionBoundary

### ISSUE THREAD

**Issue by crazyingen** [fraywing/textAngular#1290]
When i look at the html mode, everywhere are 
`<span id="selectionBoundary_1472324064801_5997167485505315" class="rangySelectionBoundary">﻿</span><span id="selectionBoundary_1472324096806_6687540850780826" class="rangySelectionBoundary">`

What is this and how can I avoid to get this?

**Comment by JoelParke** [comment]
This is corrected with release v1.5.8.  Sorry about that.  Please reopen if you still see an issue.  This came about with release v1.5.6 due to an attempted enhancement which failed.

**Comment by realview** [comment]
Looks like this has crept back into 1.5.13?  1.5.12 was fine. In my case, it doesn't appear in htmlMode, but the rangySelectionBoundary classes and ids appear in the ng-model object in 1.5.13.

This [plnkr](https://plnkr.co/edit/HY8R0O0jhppVVf0rNYa0?p=preview) demonstrates - just add a space to the textangular editable (above the hr) and see the result.  

If you rollback to 1.5.12 it's fine

**Comment by pbedat** [comment]
I'm also having the issue in 1.5.16. Thanks to @MarkOdey who commented in #1458 I was able to fix it by placing another Regex around line 425
`new RegExp(/<span id="selectionBoundary_\d+_\d+" (style="[^"]+?")? class="rangySelectionBoundary">[^<>]+?<\/span>/ig)`

**Comment by volmerf** [comment]
This is still happening in 1.5.16 like @pbedat is saying.
