### ISSUE TITLE
Option to disable default <p> wrapping

### ISSUE THREAD

**Issue by mshick** [fraywing/textAngular#131]
I commented on this over here https://github.com/fraywing/textAngular/issues/114, but was worried it would never get seen / considered since that issue is already closed.

I've been encountering the auto `<p>` wrapping / default as a bug. I'd like to be able to rich-text format text without any surrounding block-level elements (think, headline text allowing `<b>` which will be placed inside an `<h1>` in a template).

Could this be made optional on an instance-by-instance basis? Even better, could a default wrapper option be created, like, `ta-default-wrap="h2"` or `ta-default-wrap="div"`?  `<p>` would remain the default, but `ta-default-wrap=""` would disable the wrapping entirely?

**Comment by squadwuschel** [comment]
I am using TextAngular 1.4.1 and AngularJs 1.3.4 and the empty Tag is not working for me:

     <div text-angular ng-model="editTranslationsCtrl.locals.langBoxOne.Translation" ta-target-toolbars='toolbar' ta-default-wrap=""></div>

its Wrapping the content into an <p> Tag.

**Comment by hariskhan10** [comment]
<p> tags is being wrapped with on page <style> tags
<meta>tags
like this
<p><meta></p>
<p><style></style></p>

is there any way to disable this ?

**Comment by hariskhan10** [comment]
Dear @SimeonC i have placed   <text-angular ta-unsafe-sanitizer="true" ng-model="htmlVariable" ng-hide="html" ta-default-wrap=""></text-angular>

but its still wrapping in <p> tags.... what should i do

**Comment by dimaslanidis** [comment]
Can you try using ta-default-wrap="span" ?
It worked for me ...

**Comment by pbassut** [comment]
@hariskhan10 Please, if you're still having problems, open a new issue. Thanks.
