### ISSUE TITLE
how can i use textAngular with angular bootstrap carousel

### ISSUE THREAD

**Issue by denis-andrikevich** [fraywing/textAngular#1311]
For example:
`<uib-carousel active="active" interval="myInterval" no-wrap="noWrapSlides">
    <uib-slide index="0">
         text
    </uib-slide>
     <uib-slide index="1">
         text1
    </uib-slide>
     <uib-slide index="3">
         text2
    </uib-slide>
</uib-carousel>`

The result is an empty div in editor. Any advice?

**Comment by stevokk** [comment]
Are you placing this HTML inside textAngular? If so it won't work as we don't run the angular $compile functionality on that content. You need to look at the customRenderer feature, you can find many examples in the setup file and also in various issues.

**Comment by denis-andrikevich** [comment]
thx a lot
