### ISSUE TITLE
Bold and Italics buttons can't be (de)pressed one straight after the other

### ISSUE THREAD

**Issue by nikolawannabe** [fraywing/textAngular#1333]
This bug is a continuation of https://github.com/fraywing/textAngular/issues/693.  I applied your fix for #693 locally and noticed that this also happens when you want to end style options.  I saw you filed with rangy on this https://github.com/timdown/rangy/issues/403 and noticed this problem as well.

Is there a similar workaround that can be applied for discontinuing styles?  Thanks.

**Comment by JoelParke** [comment]
I'm not sure ... just back from vacation and slowly beginning to work on other bugs...  Let me know what you learn.  Thanks!

**Comment by nikolawannabe** [comment]
@JoelParke This is fixed in PR 1334.  Looks like the build is broken in general, unrelated to that commit.

**Comment by JoelParke** [comment]
thanks for your fix... closing this issue.
