### ISSUE TITLE
Allow custom Tag

### ISSUE THREAD

**Issue by JToto** [fraywing/textAngular#1337]
Hello,

I'm trying to use the textAngular-sanitize.js to allow a custom tag. Let's say the name of the tag is `"<custom-tag>"`. I added custom-tag to the list of block-elements (I also tried inline and void).

ng-model is set to "htmlText" and defined in the controller:
`$scope.htmlText = '<custom-tag name="test"></custom-tag>'`

Whenever I load the text-angular editor and switch to html-mode, I can see the html-text for a millisecond, but then it changes to an empty editor.

If I change the htmlText to 
`'<custom-tag name="test">abc</custom-tag>'`, it works and gets wrapped into a paragraph `<p></p>`...

It seems like the editor does not like tags that create no visible content whatsoever... can I prevent the editor from deleting my html-text?

Greetings and sorry for my bad english,
Thorben

**Comment by stevokk** [comment]
Your best bet of resolving this would be to trace through the sanitize call as the logic in there is pretty complex and I don't think anyone knows it off hand, textAngular as far as I am aware would not be doing anything to remove this element. 

To test I'd suggest using a string that includes a div at the same level as your custom tag so you know what path the logic should make.

Sorry I cannot be of more help.

**Comment by JToto** [comment]
I resolved the problem by making the service "_taBlankTest" in textAngular.js always returning false.
