### ISSUE TITLE
FireFox Bug: Copying and pasting from WPS Office - Content spans past contenteditable div

### ISSUE THREAD

**Issue by AlvSovereign** [fraywing/textAngular#1338]
textAngular Version: 1.5.10
WPS Writer Version: 10.1.0.5674
Tested On: Local development and on textAngular.com
Tested With: Windows 10

Hi all.

Please see the image below:
![textangular __ lightweight angular js javascript wysiwyg_text-editor - mozilla firefox 28_09_2016 11_31_45](https://cloud.githubusercontent.com/assets/10330161/18910239/0239c0b8-856f-11e6-8a7a-43371e836a42.png)

I cannot reproduce this bug in the latest versions of Chrome or Microsoft Edge. I have also tested using Google Docs and Notepad, which all seem too work correctly in different browsers including Firefox.

Has anyone else encountered this?

Thanks

Alvin Sovereign

**Comment by stevokk** [comment]
Very strange, it may be the space encoding from your particular source application. If you're wanting to investigate, paste processing is done on this line: https://github.com/fraywing/textAngular/blob/master/dist/textAngular.js#L2004

**Comment by AlvSovereign** [comment]
This seems to be fixed in textAngular version 1.5.11 so I'll close this now.
