### ISSUE TITLE
exception on resize event

### ISSUE THREAD

**Issue by annechinn** [fraywing/textAngular#1368]
I just downloaded v1.5.12 and am experiencing an exception at line # 3015 when the window is resized in our app. _el[0] fails because _el is null.  The exception occurs in IE, but not in Chrome.

I tried to reproduce it on your demo page, but couldn't. It may be because in our app we have a button that allows the user to collapse our left navigation menu to save space and we also handle the resize event. We also added the fullscreen button to our editor and it happens when I toggle fullscreen on the editor.

```
    scope.reflowPopover = function(_el){
                var scrollTop = scope.getScrollTop(scope.displayElements.scrollWindow[0], false);
                var spaceAboveImage = _el[0].offsetTop-scrollTop.top;
```

My temporary solution was to add a check for a null _resizeElement in handlePopoverEvents

```
scope.handlePopoverEvents = function() {
                if (!_resizeElement)
                    return;
```

**Comment by JoelParke** [comment]
That's a bit strange.
scope.reflowPopover(...) is only called in two places:
1. scope.showPopover()
2. scope.handlePopoverEvents() 
   -called when the window is scrolled, or resized

Could you try instead, modifying scope.handlePopoverEvents.. to be:
```
/* istanbul ignore next: popover resize and scroll events handled */
				scope.handlePopoverEvents = function() {
					if (scope.displayElements.popover.css('display')==='block') {
						if(_resizeTimeout) $timeout.cancel(_resizeTimeout);
						_resizeTimeout = $timeout(function() {
							//console.log('resize', scope.displayElements.popover.css('display'));
							if (scope.resizeElement) {
								scope.reflowPopover(scope.resizeElement);
								scope.reflowResizeOverlay(scope.resizeElement);
							}
						}, 100);
					}
				};
``` 
Where  I added an:
```
 if (scope.resizeElement) 
```
around the call to 
```
								scope.reflowPopover(scope.resizeElement);
								scope.reflowResizeOverlay(scope.resizeElement);
```
and see if that takes care of the problem??? 
Thanks!

**Comment by seyuf** [comment]
Thanks @JoelParke, that did the trick for me under IE.
I had this exception popping up at the scroll event.
But only after ui-router 'state change'  (after leaving the state where text-angular was loaded for the first time). I hope this will be in the next release...

**Comment by JoelParke** [comment]
As soon as I get a chance, I will update.... caught in another project at the moment!!!

**Comment by JoelParke** [comment]
Fixed in the last two releases.  Please reopen if still an issue.

**Comment by azachar** [comment]
Hi There, 
I have updated to 1.5.16 and I am still getting it 

```js
angular.js:14110 TypeError: Cannot read property '0' of undefined
    at Scope.scope.reflowPopover (textAngular.js:3089)
    at textAngular.js:2994
    at <anonymous>:285:29
    at angular.js:19861
    at completeOutstandingRequest (angular.js:6035)
    at angular.js:6314
```

I am using ionic 1.3.2.

Thanks for the help!

Cheers,
Andrej

**Comment by MarkOdey** [comment]
Same here. Has this fix been promoted to the latest release?
