### ISSUE TITLE
How to remove all format

### ISSUE THREAD

**Issue by piotrpabian** [fraywing/textAngular#1377]
as the topic. How to remove the tag html. Needs to plain text when you click the button

**Comment by JoelParke** [comment]
<p>What happens when you click on the removeTag button when the text is high lighed? <br/>If you could post html, etc... this would be helpful since I made a lot of changes in this area of the code a while back.</p>

**Comment by piotrpabian** [comment]
now I write in detail.
I need to enter text, format it.
Save it to the base of the HTML tags, and send the same text as the message as SMS (plain text)

**Comment by piotrpabian** [comment]
removeTag button ????
I have not found in the documentation "removeTag"
