### ISSUE TITLE
Can not paste list from MS Word

### ISSUE THREAD

**Issue by katherinautlik** [fraywing/textAngular#1379]
Hello,

I am using textAngular for one of my angular application (AngularJS v1.3.15). Recently I have faced a tricky issue. When text was pasted there is an error in console:
`textAngular-rangy.min.js:221 Uncaught TypeError: Failed to execute 'setStartBefore' on 'Range': parameter 1 is not of type 'Node'.`

Reproducable: always, using attached file or creating it by the steps below
Browsers: all
Operating system: all

Also I want to notice, that $html param is empty <p></p> in the ta paste function, but there is a text in clipboard. All my attempts to find any information about a similar issue have failed.

Steps to reproduce:
- open the textAngular demo site
- copy all text from this file (ctrl+a, ctrl+c)
  [angular-text-issue.docx](https://github.com/fraywing/textAngular/files/552815/angular-text-issue.docx)
- paste text in the textAngular

By the way, the document was created by copying and pasting list from the textAngular.

Could you please have a look at the issue? 

Thank you in advance,
Kate

**Comment by JoelParke** [comment]
<p>Thanks for reporting this.  I will attempt to duplicate this problem as soon as I have some time.</p>

**Comment by JoelParke** [comment]
<p>I have reproduced this and will attempt to fix and check-in a fix by late Sunday.  </p><p>I will cut a new release (I hope by the end of the coming week).  </p>
