### ISSUE TITLE
Can't add any text to the editor

### ISSUE THREAD

**Issue by kavka3** [fraywing/textAngular#1395]
Hi,
I'm trying to use textAngular directive with ionic 1.3.1 and angular 1.5.8.
The directive perfectly working on Android,
but unfortunately it's not working on iOS. iOS version 9.3.2.

The input is does not get focused and I can't add any text to the editor.

`<text-angular  ta-text-editor-class="text-editor" ta-html-editor-class="text-editor" ta-focussed-class="focussed" ng-model="createActivityCtrl.model.description"></text-angular>`

Can someone please help me with this issue?
Thank you

**Comment by JoelParke** [comment]
<p>I have not used iconic at this point.  I am hopeful that someone who has, can help answer this question and on iOS!!  If I understand, it works fine with iconic on Android, but the issue is under iOS??</p>

**Comment by kavka3** [comment]
Yes, it works only on Android

**Comment by kavka3** [comment]
I figured the problem. I had the css property '-webkit-user-select' set to none on an element. This is was preventing the cursor from ever being positioned within my editable content div.

Just add next to your css file

`html,body{
  -webkit-user-select: none;
  -webkit-touch-callout: none;
}

*[contenteditable] {
  -webkit-user-select: auto !important;
}`
