### ISSUE TITLE
Image insert does not always work

### ISSUE THREAD

**Issue by amanteaux** [fraywing/textAngular#1400]
Sometimes, the image insertion functionality does not work.

For example:
1. go to http://textangular.com/
2. below the "Try me" title, place the cursor after "AngularJS"
3. press enter to add a new line
4. click on the image button
5. add the URL https://www.google.fr/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
6. validate

**Comment by JoelParke** [comment]
I will try to take a look at this, this weekend.  ? is this the only case where you have seen this? or is it more common?  Thanks!

**Comment by amanteaux** [comment]
It is rather common the first time I want to upload a picture.
However, after the failed first attempt, the second attempt always work fine.

Moreover, the bug seems to be always present when a new line is added before the image is inserted.

**Comment by JoelParke** [comment]
I have fixed this with release 1.5.14

**Comment by amanteaux** [comment]
Thank you! It works fine :)
