### ISSUE TITLE
Rangy Warning: Marker element has been removed

### ISSUE THREAD

**Issue by robertTechJocks** [fraywing/textAngular#1406]
It appears that the Rangy wrapper is being deleted and cannot be found. Upon deletion of the wrapper, any action will throw an error and then focus is lost on the textbox.

How to reproduce (on Chrome):
Go to http://textangular.com/
Open console
Delete everything in the textbox
Keep hitting delete until you see "Rangy warning: Module SaveRestore: Marker element has been removed. Cannot restore selection."
Hit any key and an error will be thrown

**Comment by JoelParke** [comment]
I corrected this and another issue with PR #1408 - so closing this issue. I will include this soon in the next release.

**Comment by kaelhem** [comment]
@JoelParke have you plane a date for this release? thanks
