### ISSUE TITLE
Unwanted <br> tags when pasting HTML content

### ISSUE THREAD

**Issue by vojtechjelinek** [fraywing/textAngular#1440]
When you paste HTML content to textAngular on Linux Firefox 50.0.1 (same with nightly 53.0a1), that was also copied on Firefox, you get unwanted line breaks (`<br>`).

[Plunker](http://plnkr.co/edit/ekJ4dp?p=preview) 
When you copy the first  Lorem Ipsum paragraph to the textAngular field, new lines will be inserted.
### From this:
![image](https://cloud.githubusercontent.com/assets/10142938/22215768/e036ae60-e19c-11e6-99b0-527d4c55c4a7.png)
### To this:
![image](https://cloud.githubusercontent.com/assets/10142938/22215775/e63d415c-e19c-11e6-8d6e-1e5dff73ce81.png)
Second paragraph is even more interesting, because it seems like Firefox is copying internal HTML structure

The `<br>` tags are inserted [here](https://github.com/fraywing/textAngular/blob/master/dist/textAngular.js#L2378).
This whole thing is probably bug or different implementation in Firefox, so think it isn't fixable now.

**Comment by ajayreddy56** [comment]
Please resolve the issue soon @vojtechjelinek

**Comment by vojtechjelinek** [comment]
This is not completely resolvable because implementations of [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) object differ across browsers. But it's partially fixed in #1450

**Comment by ajayreddy56** [comment]
Hi,

@vojtechjelinek please copy text from libreoffice(ubuntu) and paste it in above plunker.and observe the styling.
