### ISSUE TITLE
textAngular loses focus after a few seconds

### ISSUE THREAD

**Issue by wgilpin** [fraywing/textAngular#1514]
If I keep typing it works, but if I stop the editor loses focus

editor is setup:
`<div id="editor" text-angular ng-model="editNote.Body" ta-toolbar-button-class="md-button md-small-button" ta-toolbar="[['h1','h2','h3','bold','italics','saveContent','','close']]"></div>`

**Comment by gbittmann** [comment]
Sounds like the same behavior from [#1458](https://github.com/textAngular/textAngular/issues/1458).

**Comment by wgilpin** [comment]
Yes, I was about to reply "but I'm not updating the model" when I realise I am, by typing into the bound control

**Comment by wgilpin** [comment]
Closed as a duplicate as above
