### ISSUE TITLE
Webpack : Uncaught Error: [textAngular:textAngularSetup] The textAngular-sanitize provider has been replaced by another -- have you included angular-sanitize by mistake?

### ISSUE THREAD

**Issue by kalpitpandit** [fraywing/textAngular#1523]
I am not sure, Why its forcing me to use **textAngular-sanitize** instead **angular-sanitize**. 

I can not remove angular-sanitize as my other packages are using angular-sanitize, Is there any workaround or solution for this issue?

```
export default require('angular')
    .module('demo', [
          ---- my other packges ---
           require('angular-sanitize'),
          require('textangular'),
    ]);
``` 
**Output**

![textangular](https://cloud.githubusercontent.com/assets/4717515/26103844/f1305ec2-3a58-11e7-8344-31c38afda1b3.png)

**Comment by pbassut** [comment]
Have you looked at: https://github.com/textAngular/textAngular/wiki/Setting-Defaults ?
Specially the forceTextAngularSanitize?
