### ISSUE TITLE
textangular 1.5.16 and old versions => XSS

### ISSUE THREAD

**Issue by kac89** [fraywing/textAngular#1534]
Hi there!
I find small security issue in textAngular, XSS, its works in new version.

Reproduction steps:
https://www.youtube.com/watch?v=WZSWsoF26nc

**Comment by attritionorg** [comment]
Duplicate to https://github.com/textAngular/textAngular/issues/1478?

**Comment by pbassut** [comment]
@attritionorg Thanks. 

@kac89 This is indeed a duplicate.
