### ISSUE TITLE
<iframe> tags are removed after html preview

### ISSUE THREAD

**Issue by epysmennyi** [fraywing/textAngular#1562]
First i added iframe tag to textAngular-sanitize.min.js
`x=/([^\#-~| |!])/g,y=/^(\s+)/,z=f("area,br,col,hr,img,wbr,input,iframe"),A=f("colgroup,dd,dt,iframe,li,p,tbody,td,tfoot,th,thead,tr")`

Then i inserted content like this `<iframe width="560" height="315" src="https://www.youtube.com/embed/zIwLWfaAg-8" frameborder="0" allowfullscreen align="center"></iframe>` in html editor. 

Then clicked to toogle button preview - video is displayed , and then click to edit on toogle button - and textarea are empty.  I need `<iframe>` tags only, not `<img>` tags! 

But if i insert before `<p>Hello</p>` to this content like this `<p>Hello</p> <iframe width="560" height="315" src="https://www.youtube.com/embed/zIwLWfaAg-8" frameborder="0" allowfullscreen align="center"></iframe>` - works good. 

So, clear iframe doesn't work , but with additional tags - works. In database saves good. 
Thanks.

**Comment by rfcabal** [comment]
If you insert a video, for example from youtube you get this HTML code:

`<img class="ta-insert-video" src="https://img.youtube.com/vi/330cLU15FqM/hqdefault.jpg" ta-insert-video="https://www.youtube.com/embed/330cLU15FqM" contenteditable="false" allowfullscreen="true" frameborder="0">`

It's change the tag from iframe to img. Al so tried in http://textangular.com/ happens the same thing.

**Comment by epysmennyi** [comment]
@rfcabal But i need not only video . Also need to allow to set site, for example, in iframe .

**Comment by stevenkissack** [comment]
Definitely sounds like a sanitize issue, I'd suggest using the uncompiled version of the angular-sanitize function to better trace why it is stripping the iframe out even after your changes.

@rfcabal - What you're seeing there is the youtube plugin for textAngular making the content safe for the editor without requiring an iframe. If you want this to be converted back to an iframe on save look into the textAngular reverse renderers.

Hope some of this helps, I'd investigate but lack a development setup for the library nowadays.

**Comment by rfcabal** [comment]
@stevokk I have tried the tag, ta-bind, works fine but it is not really useful for my project because i'm doing a bind with other componente and ta-bind makes things worse because doesn't accept any angular tag like ng-click, ng-show, etc in a biding, is there other way to use iframe?

**Comment by rfcabal** [comment]
@epismenniy , I found a post where they remove iframe tag, I did the opposite I add iframe to 

textAngular-sanitize.js

here: blockElements

textAngular-sanitize.min.js

here: D=b.extend({},A,f(

And now iframe works, I now it is risky but I really need the tag. Same i did with button.

[how do I make angular-sanitize not remove iframe tags from html](https://stackoverflow.com/questions/22449454/how-do-i-make-angular-sanitize-not-remove-iframe-tags-from-html)

**Comment by epysmennyi** [comment]
@rfcabal , unfortunately, it did'nt solve my problem. I have choosen previous version 1.2  - and iframe works.
