### ISSUE TITLE
<ol>, <ul> break <blockquote> toggle

### ISSUE THREAD

**Issue by sathran** [fraywing/textAngular#157]
If you press the blockquote option on the toolbar while on a ordered or unordered list, the blockquote option stops working as a toogle and keeps adding blockquote levels, like so:

![textangular____lightweight_angular_js__javascript_wysiwyg_text-editor](https://cloud.githubusercontent.com/assets/1090355/2828716/f26e06b4-cf98-11e3-9c46-012a06af8fb0.png)

To reproduce, go to the demo page (http://textangular.com/), click on one of the bulleted lines, and click blockquote a bunch of times.

**Comment by connect-technologies** [comment]
Hi,

is the second option really possible to do right now?
I want a list in a blockquote block. But I only get blockquotes in a list.

thanks
