### ISSUE TITLE
Manipulate html before rendering

### ISSUE THREAD

**Issue by paglias** [fraywing/textAngular#165]
Hi,

great project!

I would like to know if it's possible to manipulate the content before it is rendered, for example: if the user types a url (http://sss...) I would like to catch it (using a regex) and replace the plain text with a <a> tag. Is this possible?

**Comment by nikhilvm1993** [comment]
when applying taCustomRenderers to convert video, image insert also affected

when i am using this ,my images gets an additional span with unwanted special characters

**Comment by pbassut** [comment]
@nikhilvm1993 open an issue for that. It will be better to tackle this from there.
