### ISSUE TITLE
Capture Ng-click event from button inside the texteditor in text-angular

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [fraywing/textAngular#1652]
**Use-case** : User clicks on a button inside text angular textarea and applications angular function to be invoked
**Changes made** :  We had added ng-click, onclick events in `textAngular-sanitize.js` refer below screenshot
![image](https://user-images.githubusercontent.com/11851015/148558411-3b5e9a53-30e2-494c-8dd9-af3dc316080f.png)
and added button in svgIcons variable 
![image](https://user-images.githubusercontent.com/11851015/148558679-25414394-bc24-4b69-b42b-767dd2f2c007.png)

So that a button should get displayed and ng-click , onclick not to be stripped out.  Button with the ng-click is rendered successfully but onclick of the button we need to call a angular function in our application. 

**Issues faced** : The ng-click is not calling any function and we don't know under the hood how to make it work. Attaching the , 
[https://plnkr.co/edit/ZYtuTD8pZn93FxsC?open=lib%2Fscript.js&deferRun=1&preview](Pluker demo) please suggest . 

Unfortunately I am not able to make the plunker work but the code change is there what we are trying to achieve

**Comment by Anand-J-Kadhi** [comment]
TextAngular Community - Any update for the same issue ?

**Comment by fraywing** [comment]
You've been added as a maintainer.
