### ISSUE TITLE
Issues implementing a spell check toolbar item

### ISSUE THREAD

**Issue by noahjcz** [fraywing/textAngular#200]
I have a working spell check feature, and when it is a standalone button, it updates ta-bind just fine.  I can even hack in clickable spelling error features with a hidden toolbar button.

The problem comes when I try to add a real spell check button to the toolbar.

The toolbar seems to be built to only support "wrapSelection()" type commands.  A spell check is more of a global command, but toolbar actions mess with the default ngModel rendering process.

Is there a way I can add toolbar items that make global document changes?

I tried the refreshEditor() method, which didn't work.  I also hacked the ngModel.$render function, which sort of worked, but is really ugly and buggy.

**Comment by mattdsteele** [comment]
@noahjcz @enkodellc Were you able to get spell checking implemented?

**Comment by enkodellc** [comment]
Sorry no. I am building a few other controls at the moment. I haven't touch the textAngular code since September.

**Comment by Fatal-Errol** [comment]
Hey @nkingsley, have you successfully integrated the spell checker? Can I see your code? I'm quite lost on how to do it. Thanks!

**Comment by nkingsley** [comment]
I ended up building my own contenteditable wrapper for Angular.

**Comment by Fatal-Errol** [comment]
I see. With the limited functionality textAngular gives, I think I might go that path also. Thanks!
