### ISSUE TITLE
Multiple instances of directive in same view with different setups

### ISSUE THREAD

**Issue by andrezero** [fraywing/textAngular#203]
Congrats for the great work.

We are trying to use different instances of the directive in the same app, sometimes even in the same view. Some of these text fields need only B, I, U buttons, others need some more controls. 

I'm genuinely puzzled how to achieve this since there seems to be one single(ton) setup.

Can you please advise?

Thanks!

**Comment by SimeonC** [comment]
I've added in the docs for all the attributes as seen here: https://github.com/fraywing/textAngular/wiki/Directives

**Comment by andrezero** [comment]
thanks! we are about to upgrade it across our apps ;-)
