### ISSUE TITLE
justifyCenter, justifyRight and justifyLeft don't generate any markup

### ISSUE THREAD

**Issue by gushonorato** [fraywing/textAngular#210]
Take a look on the image below. The text area on image is bound to textAngular. Note that no markup is generated for justifyCenter, justifyRight and justifyLeft tools. Is it a bug or I'm just using it wrong?

Thanks in advance.

![captura de tela 2014-06-11 as 14 44 11](https://cloud.githubusercontent.com/assets/369689/3248602/35dbecb8-f190-11e3-82cf-95a8c26a5d9e.png)

**Comment by Taylor-Allred** [comment]
Thanks for being diligent on answering peoples questions Simeon, Every issue I have run into so far has already been answered by you in some form or another.
