### ISSUE TITLE
Toggle HTML in Firefox cause ‘Unexpected exception’

### ISSUE THREAD

**Issue by peterhe2000** [fraywing/textAngular#223]
Hi. There. I only noticed this error after developed a javascript error logging in our application. Here are the steps to replicate this issue in firefox.
1.  Open http://textangular.com/ in firefox.
2.  Click Toggle HTML from toolbar.
3.  Then just mouse click anywhere in textangular. When you view console from firefox, you will see there is “unexpected error” exception. 

Here is stack trace of error log. [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: http://cdn.jsdelivr.net/g/angular.textangular@1.2.0(textAngular-sanitize.min.js+textAngular.min.js) :: .link/d.queryFormatBlockState :: line 4"  data: no]
http://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js
Line 85

BTW: I am using firefox 30, I believe firefox 29 also has this issue. Chrome has no problem at all.

**Comment by rdheepan** [comment]
Hi, I am currently using 1.4.6 version and still getting this error. 
Steps to reproduce, In firefox, type the text in textangular field and click outsite and inside of textAngular field using mouse repeatedly. 
Error  Message,
    
    [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS     frame :: https://bmhe1059612.kor.apac.bosch.com/FRONT_END/vendor/textAngular/dist/textAngular.js     :: .link/scope.queryCommandState :: line 2420"  data: no]
    src/scripts/ui-scroll.js
    Line 21538

**Comment by pbassut** [comment]
@rdheepan Could you create an issue for this? I couldn't reproduce it. Please, detail the error a little more so I can see what's wrong and fix it.
