### ISSUE TITLE
How can I add every link with default attribute "target=_blank"

### ISSUE THREAD

**Issue by dddd1919** [fraywing/textAngular#224]
My pleasure to use testAngular for my site,now I have a special need that when I embed link to some words, I just want to add `target='_blank'`to that `a` tag with default. I am a ruby developer and embed some angularjs with my program,already tried to modify source codes but fail, can I catch this goal with any solution? Thanks a lot!

**Comment by ericq** [comment]
Hi, 
I have to slightly tweak the code mentioned above to make this example work. I have pasted below. 

 $provide.decorator('taOptions', ['taCustomRenderers','$delegate', function(taCustomRenderers, taOptions){
            taCustomRenderers.push({
                selector: 'a',
                renderLogic: function(element){
                    element.attr('target', '_blank');
                }
            });
            return taOptions;
        }]);
