### ISSUE TITLE
Using textAngular inside ng-repeat with same name attribute value?

### ISSUE THREAD

**Issue by yulric** [fraywing/textAngular#240]
Hi there,
Thanks a lot for the directive. I am trying to use angularjs validation with textAngular but unfortunately I have run into a problem. I have an ng-repeat which repeats an ng-form inside of which I have a textAngular element. However the ng-repeat array can't have more than one element because I get the error "textAngular Error: An editor with the name <editorName> already exists".I was wondering if there was a way to fix this problem. Thanks a lot for your help.

Edit: Made a plunker so you can see the problem http://plnkr.co/edit/xdbP7ouKOf4ySRRyaAo0
        Once you run the plunker go to the console to see the issue

**Comment by checat** [comment]
Can't this limitation be removed?
