### ISSUE TITLE
Youtube Embed inserts <img> tag

### ISSUE THREAD

**Issue by bradparker** [fraywing/textAngular#242]
This directive is awesome and snappy; you've saved us from the mess of hulking RTEs. Thanks a bunch.

I'd like to submit failing specs etc. I thought I'd post this though, just in case the fix is easily grock-ed by someone here.

Inserts img
https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L491

Perhaps because iframes will get santized?
https://github.com/fraywing/textAngular/blob/master/test/textAngularSanitize/sanitize.spec.js#L251

If you need more info before I can get to the spec, please ask.

**Comment by nullart** [comment]
Hi, 

Is there a way to revert back to the image placeholder when the user would want to edit the content containing the youtube iframe?

Currently, I am storing html data to the server with taApplyCustomRenderers.
