### ISSUE TITLE
Custom button to popup button menu

### ISSUE THREAD

**Issue by yzhiJun** [fraywing/textAngular#243]
So here is my question:

![image](https://cloud.githubusercontent.com/assets/2598813/3597673/f7c1fcd6-0cd5-11e4-915a-4a77170f87d2.png)

I add a custom button in toolbar,this is the functionality i want to achieve:
OnClick this button,I want to popup a button menu like the picture, click on one of them, it will popup a modal and then do anything i want to insert element to the editor.

any tip to do that?

**Comment by bxcodec** [comment]
Where I can see the specific project please ? I'm doing the same things here. Thankyou
