### ISSUE TITLE
Webkit Issue

### ISSUE THREAD

**Issue by peteringram0** [fraywing/textAngular#245]
There is an issue on webkit browsers when clicking in the area then anywhere outside.

Uncaught TypeError: Cannot read property 'setSelectionRange' of null angular.textangular@1.2.1(textAngular-sanitize.min.js+textAngular.min.js):4
(anonymous function) angular.textangular@1.2.1(textAngular-sanitize.min.js+textAngular.min.js):4

<div text-angular ng-model="htmlVariable"></div>

**Comment by veob** [comment]
Hello.
We use 1.3.0 version of your plugin (thanks by the way) and got this error.
Chrome version: 41
Any suggestions?

**Comment by veob** [comment]
Hello,
We use v1.3.0 (tested in v1.3.11 as well) of your plugin (thanks by the way) and keep getting this error.
Chrome version: 41.
Any suggestion?

**Comment by veob** [comment]
Sorry. False alarm. Problem was on our side :)

**Comment by weixiangzhe** [comment]
so ,I has the some Problem ,I use v1.37..chrome is 51
