### ISSUE TITLE
Textarea focus

### ISSUE THREAD

**Issue by jakobholmelund** [fraywing/textAngular#246]
Im seeing some weird behavior when i click on the textarea. the textarea goes into focus and the toolbar activates on mousedown, but unfocusses and disables the tool bare on mouseup. This makes the whole thing quite unusable, first i thought it was foundation, but it has the same behavior when i remove that library.

Has anybody else experienced this ? i really hope i can figure this out, since this seems like an AWESOME module !

**Comment by SimeonC** [comment]
This should be fixed, I think we fixed something similar in 1.3.0.
