### ISSUE TITLE
How to get selected text?

### ISSUE THREAD

**Issue by joforiam** [fraywing/textAngular#248]
Is it possible to get the selected text from the editor?  document.getSelection().toString() doesn't appear to be supported:

	  config(function ($provide){
	    $provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions){
	      // $delegate is the taOptions we are decorating
	      // register the tool with textAngular
	      taRegisterTool('createSomething', {
		iconclass: 'glyphicon glyphicon-user',
		action: function(){
		  var selectedText = '';
		  selectedText = this.$editor().getSelection.toString();
		  console.log('Do something with selected text: ' + selectedText);
		}
	      });
	      taOptions.toolbar[1].push('createSomething');
	      return taOptions;
	    }]);
	  }).

I'd like to return the selected string to use in another controller/service.

**Comment by joforiam** [comment]
This seems to have reverted.  For example, using 1.3.7, this no longer works:
````
 $provide.decorator('taOptions', function(<dependencies>) {
      function doSomethingWithSelectedText() {
        var fullText, selected, selectedText;
        selected = taSelection.getSelection();
        fullText = selected.end.element.textContent;
        selectedText = fullText.substring(selected.start.offset, selected.end.offset);

        if (selectedText === undefined || selectedText === null || selectedText === '') {
          alert('Nothing selected');
        } else {
          console.log(selectedText);
        }
      }
}
```
The selected text offsets no longer seem valid, and i'm only getting the first character of the selected text.  Does this make sense?  Am I missing something?

Thanks in advance.

**Comment by SimeonC** [comment]
Hmmm, can you run up a plunkr demonstrating it please? I'm a little short on time ATM to go testing to find it.

**Comment by joforiam** [comment]
@SimeonC  sorry for the delay.  Here you go:

http://plnkr.co/edit/WcFYiIJIs1RfFDDjaycJ?p=preview

Click the 'leaf' icon to test.  Pre 1.3.7, all highlighted text would be selected, now I only get the first letter.  Any guidance would be helpful.

**Comment by SimeonC** [comment]
After having a look, the issues seems to be in the rangy library or in the browser API itself.

You could try using the beta of the 1.3 of rangy (rangy-core and rangy-saveselection) instead of our minified version and see if they've fixed the bug there.

**Comment by joforiam** [comment]
Thanks much, I'll see if i can chase that down.

**Comment by windmaomao** [comment]
i'm sorry, but what is the current way to find the current selected string ?

I tried the above suggestions, but none of them works, including taSelection.getSelection().end.element.textContent; which selects the entire paragraph around the selected text.

**Comment by windmaomao** [comment]
ok, i used this, it worked,                     var selectedText = window.getSelection();

yeah window is a global object.
