### ISSUE TITLE
Resolving deferred object needs double call

### ISSUE THREAD

**Issue by stinoga** [fraywing/textAngular#261]
Hey guys. I'm setting up a modal instance when adding a link, rather than the prompt dialog. I'm using the deferred object in the insertLink action, and for some reason the link will only insert if I add the wrapSelection function call twice. Any idea what may be wrong here?

``` javascript
action: function(deferred){
  var self = this;

  hvDialog.showPromptModal({
    title: 'Insert Link',
    titleIcon: 'fa-link'
  }).
  confirmed(function(promptInput) {
    self.$editor().wrapSelection('createLink', promptInput, true);
    self.$editor().wrapSelection('createLink', promptInput, true);

    deferred.resolve();
  });

  return false;
}
```

Also, I noticed when using a modal rather than the prompt, the selected text loses focus, so the link never adds to the selected text, but next to it. Any good way around that?

Thanks, loving textAngular so far!

**Comment by logusgraphics** [comment]
Thanks a lot for this @stinoga it was very helpful.
