### ISSUE TITLE
Sanitize is removing iframe

### ISSUE THREAD

**Issue by visb** [fraywing/textAngular#277]
I can't display an iframe(youtube embed) in text-angular.

html:

```
<div text-angular ng-model="item.data.text"></div>
```

---

$scope.data.text:

```
<img src="assets/theme/img/banner1.jpg" class="img-responsive"><hr><div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="http://www.youtube.com/embed/..." allowfullscreen=""></iframe></div></td>
```

Editor is showing this(iframe was removed):

```
<img src="assets/theme/img/banner1.jpg" class="img-responsive"><hr><div class="embed-responsive embed-responsive-16by9"></div></td>
```

I have tried $sce.trustAsHtml on $scope.data.text, but dont solve.

How fix it?

Plunker: http://plnkr.co/edit/ZtCM4dPxOcqfyuOky49B?p=preview

**Comment by nikhilvm1993** [comment]
when applying taApplyCustomRenderers,a question mark is come up with img tag,like
<span id="selectionBoundary_1444709938237_9921742759179324" class="rangySelectionBoundary">?</span>
