### ISSUE TITLE
Youtube video blocked by browser when server is running https.

### ISSUE THREAD

**Issue by TheEngineGuy** [fraywing/textAngular#282]
I try to insert a youtube link ( https). But the link was converted into a http link. When the hosting site is running https, the posted video will be blocked by browser.  Tested in both Firefox and Chrome.  
Got the following error in Chrome's developer tool console:

[blocked] The page at 'https://localhost/issue/3' was loaded over HTTPS, but ran insecure content from 'http://www.youtube.com/embed/xxxxxxxx': this content should also be loaded over HTTPS.

I have to switch to raw html and change the video link to https. Then the video link works.

**Comment by levydev** [comment]
Has this change been put into a version of TextAngular yet?   I'm using v1.2.2   in httpS and the youtube links are still being converted to http.

**Comment by SimeonC** [comment]
Yes, this is in the v1.3.0+ releases
