### ISSUE TITLE
Prevent the textangular-editableFix-ID to be visible

### ISSUE THREAD

**Issue by tplaindoux** [fraywing/textAngular#287]
On pages using textAngular I have a 1px square created by textAngular:

```
<input id="textAngular-editableFix-010203040506070809" style="width:1px;height:1px;border:none;margin:0;padding:0;position:absolute; top: -10000; left: -10000;opacity: 0;" unselectable="on" tabindex="-1">
```

Can you add an
    opacity: 0

to its style and prevent a white pixel to be visible ? (Background of the page is not white)

**Comment by kotmatpockuh** [comment]
chrome 39 same problem

**Comment by DumboJet** [comment]
I still see this appearing on my page:

    <input id="textAngular-editableFix-010203040506070809" class="ta-hidden-input" unselectable="on" tabindex="-1">

textAngular Version 1.3.6
Using Rangy 1.3alpha.804

**Comment by SimeonC** [comment]
That means you aren't including src/textAngular.css which has the styling for it. As I had to use the same css for two inputs I opted to use a class instead of a style attribute.

**Comment by DumboJet** [comment]
Oh, my bad... I hadn't updated my CSS file to the new one after upgrade...
Silly me...

Another question:
I see in that dist/textAngular.min.js says Version 1.3.0
while src/textAngular.js says Version 1.3.6
I guess that the dist folder is not updated frequently and I should use the src one, right?

**Comment by SimeonC** [comment]
No the dist should be current, I'll check tomorrow but I think all that's happened is that the release build process isn't updating the version number.

**Comment by DumboJet** [comment]
Ahh, seems the "textAngularSetup" JS file version number stays behind and that's what I saw.

**Comment by nicooga** [comment]
I've downloaded the package via bower and the css's doesnt have the `ta-hidden...` selector.
It is on master though. Should I resort to link the package from github?

**Comment by courtyenn** [comment]
Is there a way we can get rid of the textangular-editable-id all together? It clutters up the html. I don't even use the text angular box until it is on a specific page, but there is that element, on every single page of my SPA. Just because I loaded the text angular javascript in the main index of my application.
