### ISSUE TITLE
ordered list  and number list broken in Firefox 

### ISSUE THREAD

**Issue by anitin** [fraywing/textAngular#290]
Hi fraywing,

This is a great library and I am trying to use it on my project.

I experimented with 1.2.0 version and every thing worked great.

But when I upgraded to 1.2.2 the ordered list / numbered list is not working (intermittently) on Firefox. I even used the editor on textangular.com and there too the ol and ul does't work (intermittently)

I tried Firefox on Mac    -- the issue is present.
Firefox on Windows 7   -- the issue is _not_ present.
Firefox on Windows 8.1 -- the issue is present.
IE 11 on windows 8.1  -- the issue is present. 

But when I rollback to 1.2.0 version, everything works !! But I really need the tooltip feature in 1.2.2.
Any help is much appreciated 

Thanks
Ankit

**Comment by bulucseku** [comment]
Hi,
I have tried your plugin, it was working fine but after updating the angular.js to version 1.3 it is not working.
Would you please let me know what may be the issues
