### ISSUE TITLE
Border Color on Focus

### ISSUE THREAD

**Issue by dmarg** [fraywing/textAngular#296]
I am trying to style my web app and I have a border color that I am using around input boxes and text areas on focus. However, I can not change the textAngular text area on focus. Is this a bug? or Does someone know how to do this?

I have written rules for that element in the css and I have used the chrome debugger and tried to select that element and add the rules there but immediately the rule gets overwritten and disappears.

**Comment by ant-fx** [comment]
@jovpet thanks, very helpful!

**Comment by ToddWebDev** [comment]
@jovpet Exactly what I needed as well. Thank you.

**Comment by kylekrzeski** [comment]
I was having issues as well and fixed it by adding:
```
div[contenteditable="true"]:focus {
    //styling
}
```
