### ISSUE TITLE
&#10;&#10;&#9;&#9;

### ISSUE THREAD

**Issue by djskinner** [fraywing/textAngular#307]
Seems that when I edit the HTML I end up with really messy code including lots of these: `&#10;&#10;&#9;&#9;`

You can reproduce this on the home page by editing the HTML and pressing the return key a few times. Is there a way to stop it HTML encoding preformatting such as line breaks, spaces and tabs in this way?

**Comment by SimeonC** [comment]
I suddenly realised there is a good use for doing this properly, so it is done correctly now.
