### ISSUE TITLE
How to apply max-length validation on text-angular

### ISSUE THREAD

**Issue by cbunhok** [fraywing/textAngular#308]
Dear All,

I have problem to apply max-length validation on text-angular. When I added this validation on it, it always raise error though the text length is smaller than number determined in validation.

Anyone has any solution?
Thanks you in advance.

**Comment by VaibhavP17** [comment]
How can I stop the user to enter any more characters if the 'ta-max-text' has exceeded exactly the way HTML-5 'maxlength' attribute works ? @SimeonC

**Comment by SimeonC** [comment]
I guess you'd have to catch the keyup event and detect it there. It's not a normal input so it's a bit difficult.

**Comment by alexander-elgin** [comment]
@cbunhok  and @VaibhavP17 I have created a directive (see https://github.com/alexander-elgin/ta-maxlength) with the functionality you required

**Comment by cbunhok** [comment]
@alexander-elgin : It's pretty good. Thanks for your effort.

**Comment by VaibhavP17** [comment]
:+1: @alexander-elgin

**Comment by BukicMicko** [comment]
@alexander-elgin I tried with  your directive and I am getting undefined for editor variable... 

Here is how I am using it in my view:

`<a class="clickable" editable-text-angular="reviewvm.findingOrObservationTitle" ta-maxlength="1000" name="title"
                               ng-click="editableTitleForm.$show(); edit = true" ng-show="!editableTitleForm.$visible">`

**Comment by akshay-bbytes** [comment]
Can we use this  https://github.com/alexander-elgin/ta-maxlength directive like i set max length as 200 character so after 200 character text angular will stop trying more than that?
