### ISSUE TITLE
Custome Parser using document.createElement does not allow html5 (div inside p)

### ISSUE THREAD

**Issue by episodeyang** [fraywing/textAngular#314]
Hi @SimeonC and @tarjei,

I am implementing a custom parser to clean up the textvalue when I ran into this rather interesting bug.

## TLDR;

basically, when I use `createDocumentFragment` to create a shadow element to parse the `textvalue`, it incorrectly parses textNodes in a paragraph that are *after* child spans into a new paragraph. 

## example

content: 

```
<p>lalala<div>haha</div>haha</p>
```
gets converted into

```
<p>lalala</p><div>haha</div><p>haha</p>
```

## code

```
            mathJaxParser: function (textValue) {
                /** regex is NOT a good way to parse the text!!
                 * one can not make sure that string in the text field are properly
                 * escapped.
                 */
                try {
                    var i;
                    var fragment = document.createDocumentFragment();
                    var base = document.createElement("span");
                    fragment.appendChild(base);
                    base.innerHTML = textValue;
                    console.log(base);
                    console.log(textValue);

```

## My thoughts
`<div>` inside `<p>` is not supported in html4 standard, however it *is* support in html5. Any thoughts?

ps: the code is copied from @tarjei's awesome math-jax textAngular project [here](https://github.com/tarjei/textangular-mathjax/blob/master/editor/editor-directive.js):

**Comment by SimeonC** [comment]
Closed due to inactivity.
