### ISSUE TITLE
Custom Elements inside TextAngular Editor

### ISSUE THREAD

**Issue by crabhilash** [fraywing/textAngular#323]
I am trying to set up an editor using Text Angular. I need my custom elements to be rendered with in the editor. For example : `<Content><Title>Here is Title</Title><Text>Here is my Content</Text></Content>`
When I put this inside the `<text-angular></textangular>` I don't see the above tags in the DOM explorer and get only "Here is Title Here is my Content". Is there a way to keep those elements or can I create directives in the name of those custom Elements I want to put in?

**Comment by phpschool** [comment]
I want to add <span th:text="${entityName}">name</span> in the editor bi9nd HTML. How can i do that?
