### ISSUE TITLE
Remote Html

### ISSUE THREAD

**Issue by louislewis2** [fraywing/textAngular#324]
Hi, first off, this is a great editor that you have written.

However I cannot get it to bind with data coming from a remote server.
The rest of my application loads its data from a remote server that provides a rest api.
I am trying to use your editor to show emails. The object returned has a bodyHtml property on it.

I can display this value in a normal div or input tag, using a sanatize filter to ask the sce to trustAsHtml.
This works great, then I needed to reply to emails, and I found your editor. Regardless of what I have tried, it simply does not work.

I have tried using both versions of the sanatize files, the one from angular and the one from textAngular.

All your examples, show binding to local html data, which works great.
Am I maybe missing something?

**Comment by SimeonC** [comment]
Closed due to inactivity.
