### ISSUE TITLE
Error: error:multidir Multiple Directive Resource Contention

### ISSUE THREAD

**Issue by sylouuu** [fraywing/textAngular#345]
Hi,

Can't use it: https://docs.angularjs.org/error/$compile/multidir?p0=textAngular&p1=textAngular&p2=new%2Fisolated%3Cdiv%20ng-view&p3=%3Ctext-angular%20ng-model%3D%22htmlVariable%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E

Bests

**Comment by irenagroup** [comment]
Does anyone has working example of textAngular with requireJS yet. I am not able to make it work even though after following steps.

Getting window.rangy.saveSelection is not a function error when I try to apply h1 tag on this line
_savedSelection = $window.rangy.saveSelection(); in textAngular.js
