### ISSUE TITLE
Mail Merge - inserting text at cursor position

### ISSUE THREAD

**Issue by jeremiahblanch-PropertyMe** [fraywing/textAngular#350]
I'm using textAngular to make an editor for mail merge templates. I have buttons for different fields and when they are clicked I want to insert text like [[firstName]] into the text at the cursor position.  When using a textarea, I just used ng-blur and event.target.selectionStart to get the cursor position, and then just inserted the field into the model string at that spot.  But textAngular's contenteditable div doesn't have these properties, and the getSelection from rangy is a fair bit more complicated when all I need is to know is 'put it at position 46'.
1. Is there a way of easily exposing the cursor's position?
2. Or, is there a way to expose the methods that the tools use, eg $editor().wrapSelection();

I could probably create a new textAngular 'tool' for each merge field, but ideally I don't want to do this, as it would be inconsistent with the rest of our app. I would rather treat textAngular as a black box.
Thanks.

**Comment by rekhasfahrizi** [comment]
hi,
can you give me a complete example how to insert text at cursor?
thank
