### ISSUE TITLE
Dynamically disabling text angular inputs.

### ISSUE THREAD

**Issue by kyranjamie** [fraywing/textAngular#36]
Have you guys thought about being able to use `ng-disabled` or `ng-readonly` on text angular elements?

I think the functionality could be quite useful, but since it's using divs, both of those attributes do diddily-squat. The ways I can think of to do this would be pretty nasty (transparent div overlay).

Any thoughts?

**Comment by abisheksharma** [comment]
Hey guys. First of all great texteditor. Really liked it but having a slight problem. I was trying to use ta-disabled in my project but it seems like its not evaluating the expression. It works with true or false but problem arises when i put some expression. I have the expression on scope in my controller. Any help will be appreciated. thanks

**Comment by SimeonC** [comment]
Ahhh, I think I know what that may be... It may be due to something like an ng-if or ng-repeat that's forcing an isolated scope. Can you write that up as a separate issue please as that's a bug! (Just so I can find it better when I get some time).
