### ISSUE TITLE
Clicking on content when unfocused gives error

### ISSUE THREAD

**Issue by hollyxu** [fraywing/textAngular#360]
Begin with an unfocused editor. Clicking on content in the editor will give an INDEX_SIZE_ERR error.

**Appears in:** 1.3.0-pre5
**Error message:**

> y {code: 1, codeName: "INDEX_SIZE_ERR", message: "DOMException: INDEX_SIZE_ERR", INDEX_SIZE_ERR: 1, HIERARCHY_REQUEST_ERR: 3…}
> code: 1
> codeName: "INDEX_SIZE_ERR"
> message: "DOMException: INDEX_SIZE_ERR"
> **proto**: Object
> (anonymous function) -  _angular.js:9778_
> (anonymous function) -  _angular.js:7216_
> Scope.$apply -  _angular.js:12512_
> _keydown  - _textAngular.js:719_
> jQuery.event.dispatch  - _jquery.js:4409_
> elemData.handle -  _jquery.js:4095_

**To reproduce:**
![image](https://cloud.githubusercontent.com/assets/4806583/4723824/1971f2e8-594b-11e4-901c-869107a64539.png)
1) Start with unfocused editor
![image](https://cloud.githubusercontent.com/assets/4806583/4723850/5996d352-594b-11e4-98b5-23fed63be11c.png)

2) Click anywhere on "Some text here". Notice cursor (flashing vertical line) does not appear. Error message will appear.

![image](https://cloud.githubusercontent.com/assets/4806583/4723855/65d16d94-594b-11e4-98f1-d7417d204ead.png)
Note: If you click anywhere else in the box, the editor behaviours normally. The cursor appears at the end of the text.

**Comment by mwayi** [comment]
It maybe that there is a slight disconnect between rangy and textAngular. Rangy doesn't appear to be tracking text-angular elements that can be newly inserted into the dom.

`var container = range.commonAncestorContainer;` will eventually throw an error because it is undefined.
