### ISSUE TITLE
Foundation support (instead of bootstrap)

### ISSUE THREAD

**Issue by Martinspire** [fraywing/textAngular#361]
It would be nice to use textAngular with Zurb Foundation instead of Bootstrap. Or have a separate CSS file for when you use custom frameworks.

I like the functionality of this module, but currently cannot use it in most of my projects.

Edit:
I've installed it with Bower and didn't get the .css file, nor did i get the rangy javascript file. Perhaps they were forgotten?

**Comment by KovganIV** [comment]
Need to fix this
