### ISSUE TITLE
How to insert text at current position from ouside editor

### ISSUE THREAD

**Issue by NeevShah** [fraywing/textAngular#378]
Hello,
 I'm sorry for my bad Engilsh. I'm using textangular for printing letter. I have some question and i don't know where to ask so i'm creating as issue. Now my use case is on select from drop down i need to insert selected value at current position of  editor. I don't know how to do it. And I don't want to put drop down in toolbar. Please help me..
here is my plunker http://plnkr.co/edit/l5aPtqu3Ic00l4sB2kwa?p=preview

**Comment by SimeonC** [comment]
Sorry I never got back to you, I seemed to have missed your last reply at some point.

Probably the issue here was that the select was removing the focus from the editor. That's what that error usually means. If you're using a `<select>` tag try adding `unselectable="true"`.

I'm on a issue cleanup spree, re-open the issue if you're still having troubles.

**Comment by NeevShah** [comment]
unselectable="true"  didn't solved my problem. Errors still remains. However the solution doesn't seems to work at all in firefox. So I need a proper solution.  Can you update your plunker?

**Comment by SimeonC** [comment]
Ah, my bad - I realised for some reason this is `unselectable="on"` not some truthy value, Sorry!
You may also have to grab the mousedown event and kill it like here: https://github.com/fraywing/textAngular/blob/master/lib/main.js#L936-L942.

That code is also how we setup our buttons for the toolbar so it should work, check the surrounding code as well.

**Comment by scottmeng** [comment]
@SimeonC could you please check the plunker? it does not seem to work

**Comment by NeevShah** [comment]
@SimeonC  sorry never got a chance to work on it.. I'll try it when I'll get a chance to work on it..

**Comment by mohsinrs** [comment]
Hi i am using textAngular 1.4.1 but solution provided <a href="http://plnkr.co/edit/CyQ3B7RJpmnmE1hf542U?p=preview">here</a> is not working for me.
My code is as following:

angular.module('minovateApp')
.controller('MergeCodeCtrl', ['$scope', 'taSelection', '$modalInstance', '$rootScope', '$http', '$window', function($scope, taSelection, $modalInstance, $rootScope, $http, $window) {
          
            $scope.insertMergeCode = function (key) {
                console.log(key);
                taSelection.insertHTML('<b>Test Some Content</b>');
            };           
        }]);
'use strict';

Will be great help if you can tell what I am doing wrong....

**Comment by nickknissen** [comment]
@mohsinrs This is a closed issue. 
But you can do something like this: http://plnkr.co/edit/yLBZ8Zqt2UYgkKOQ3UDS?p=preview

**Comment by sgentile** [comment]
I'm getting same error message, and it has nothing to do with a select ?

**Comment by sgentile** [comment]
(and I'm getting a 404 on the proposed fix above)

**Comment by pbassut** [comment]
@sgentile You're saying the plunkr is unavailable to you?

**Comment by sgentile** [comment]
This above comment is:

---
Ah, my bad - I realised for some reason this is unselectable="on" not some truthy value, Sorry!
You may also have to grab the mousedown event and kill it like here: https://github.com/fraywing/textAngular/blob/master/lib/main.js#L936-L942.

That code is also how we setup our buttons for the toolbar so it should work, check the surrounding code as well.
---

**Comment by rnugraha** [comment]
The page https://github.com/fraywing/textAngular/blob/master/lib/main.js#L936-L942 does not exist anymore, can anyone post the work around? I'm having this problem as well.
