### ISSUE TITLE
two-way binding not working properly

### ISSUE THREAD

**Issue by pykiss** [fraywing/textAngular#38]
If you edit the text, and them change the model, the text-angular does not change.

```
<div ng-init='test="hello world"'>
  <input type="text" ng-model="test"></input>
  <text-angular ng-model="test"/>
  <button ng-click="test='hello world'">reset</button>
</div>
```

If you write something in the textbox and then click the reset button, it works fine.

If you write something in the textangular and then click the reset button, it does not work.

**Comment by SimeonC** [comment]
Landed in v1.3.6

**Comment by thegreatmichael** [comment]
Is this still fixed (like in in 1.3.11)? #660 may be related

**Comment by SimeonC** [comment]
Yup. Looks like it got back in somehow.

**Comment by adityapatadia** [comment]
I am getting similar issue. When the mode changes, the editor does not show changes. When I either focus or remove focus from textarea, it gets reflected. Can't we have the changes displayed immediately as the model is changing?
