### ISSUE TITLE
Changing underlying data will not change if the editor box is highlighted

### ISSUE THREAD

**Issue by jchatel** [fraywing/textAngular#387]
I use a text-angular to edit different items listed on a my side bar in a nice "ng-repeat".

(This is my haml for text-angular)
%div{"text-angular" => true, "ng-model" => "getScript().body", "name" => "body"}

As you can see, I'm using getScript to get the underlying item and I'm editing the body element. 

Nothing ground breaking here.

I can switch items by having an ng-click on my buttons (inside my ng-repeat):
"ng-click" => "setScript(item)"

It works well and nicely if I don't edit anything (e.g. not clicking in the edit box). As I click through my button, the underlying is replaced in Text-Angular. Just what I want.

When I edit and then change however, the first ng-click will only takes the focus away from the editor, the new underlying item body won't be displayed. I need to click on another item again to have my text-angular finally refreshing the underlying data.

Any idea how I could work around this?

**Comment by SimeonC** [comment]
v1.3.5 is the current stable version. Re-open this if it's still an issue.
