### ISSUE TITLE
Keyboard shortcut for custom tools?

### ISSUE THREAD

**Issue by somelinguist** [fraywing/textAngular#389]
Is there anyway to add a keyboard shortcut for a custom tool registered via `taRegisterTool()` ?

The shortcuts for normal html in contenteditable work fine, but I would like to be able to assign a key that executes the registered custom action as if the button were clicked.

Thanks!

**Comment by vineshhpatel** [comment]
How can I specify key combinations?
like : 'ctrl+k'
