### ISSUE TITLE
Losing focus causes silent error when writing in contenteditable

### ISSUE THREAD

**Issue by assisrafael** [fraywing/textAngular#39]
I'm using ui-bootstrap to generate a modal dialog to capture some input before writing in the contenteditable element. However the call of this.$parent.wrapSelection does not work once the contenteditable loses the focus.

This is the custom toolbar button that I'm using: 

```
$rootScope.textAngularTools.definition = {
    display: '<button ng-click="action()" ng-class="displayActiveToolClass(active)" ><i class="fa fa-bullseye"></i></button>',
    action: function(){
        var selectedText = document.getSelection();
        var container = this.$parent;
        var modalInstance = $modal.open({
             templateUrl: 'template.html',
             controller: 'CustomCtrl'
        });
        modalInstance.result.then(function (selectedItem) {
            if(selectedItem){
                container.wrapSelection('insertHTML', '<definition term="someId">'+selectedText+'</definition>');
            }
        }, function () {
            console.log('Modal dismissed at: ' + new Date());
        });
     }
 };
```

The text is supposed to be only added to the contenteditable element after the modal dialog is closed.

I tried a lot of alternatives to finally discover the problem. In the wrapSelection function, it seems to be necessary to set the focus again in the element before executing the following line:

```
document.execCommand(command, false, opt);
```

I made a small experiment changing the wrapSelection function like this:

```
wrapSelection: function(command, opt, updateDisplay) {
    if (scope.showHtml)
        scope.displayElements.text[0].focus();
    else
        scope.displayElements.html[0].focus();
    // the default value for updateDisplay is true
    if (updateDisplay == null) updateDisplay = true;
    document.execCommand(command, false, opt);
    // refocus on the shown display element, this fixes a display bug when using :focus styles to outline the box. You still have focus on the text/html input it just doesn't show up
    if (scope.showHtml)
        scope.displayElements.text[0].focus();
    else
        scope.displayElements.html[0].focus();
    // note that wrapSelection is called via ng-click in the tool plugins so we are already within a $apply
    if (updateDisplay) scope.updateDisplay();
},
```

This modification solves the problem partially, but once the focus is set to the beginning of the file, the html is added in the wrong position.

It seems that we need to save the current cursor position before losing the focus  and recover it before adding the document.execCommand call.

**Comment by jwweb** [comment]
thanks both, solved my problem!

**Comment by Anand-J-Kadhi** [comment]
How this can be used in angularjs application controller . I mean what is "document" here  in document.getSelection() ?? And how to get the document from textAngularManager
