### ISSUE TITLE
Is it possible to handle paste event?

### ISSUE THREAD

**Issue by kaiqigong** [fraywing/textAngular#393]
I want to upload the images in pasted content. For example.
`<img src="//others/1.png">`
after pasting
`<img src="//myplace/1.png">`

**Comment by episodeyang** [comment]
Hi @SimeonC 

What's our update on handling the paste events? 

Thanks!!
Ge

**Comment by SimeonC** [comment]
Eh, it's there. I missed closing and updating this issue.

Event is `ta-paste="expression"`, result of the expression in the attribute will be the pasted string. Stupid example: `ta-paste="'[No Paste]'"` Inserts [No Paste] every time you try to paste. Better example is this: `ta-paste="pasteHandler($html)"` `$scope.pasteHandler = function(html){return html.replace(/<(\/|)b>/,'<$1i>');};` which I do believe will replace all b tags with i tags.

**Comment by episodeyang** [comment]
AWESOME!! 

SO I guess there is no unified handler for both file drag and drop and pasting? 

This works for me for now!

Ge

**Comment by SimeonC** [comment]
No there isn't, the process of handling each event is too different.

**Comment by episodeyang** [comment]
Got it!

**Comment by kaiqigong** [comment]
Wow, nice, thank you! @SimeonC

**Comment by aydcery** [comment]
@SimeonC it's really works , i don't want to paste div codes and style="..." , is it possible?
