### ISSUE TITLE
[BUG] textAngular + Angular 1.3.1

### ISSUE THREAD

**Issue by amcdnl** [fraywing/textAngular#403]
A fresh install of 1.2.1 with Angular 1.3.1 results in an unknown provider error on taOptions.  See:  http://www.screencast.com/t/jXFn2QQfoLn

Oddly enough, 1.1.2 seems to work though.

Anyone else getting this?  Am I doing something wrong?

**Comment by SimeonC** [comment]
Closed due to inactivity. (v1.3 is out)
