### ISSUE TITLE
h1 and h6 buttons are larger

### ISSUE THREAD

**Issue by madhur** [fraywing/textAngular#404]
![screenshot-www akoshalocal com 2014-11-10 20-44-18](https://cloud.githubusercontent.com/assets/509431/4978183/ade9d286-68ed-11e4-940f-c1858c9256dc.png)

I am getting big buttons for h1 and h6. On closer inspection, it seems that all others are vector buttons (font awesome) instead of h1 and h6.

**Comment by wmogk** [comment]
This detail had been bugging me for a while - it wasn't serious, but the toolbar didn't look quite right - so I spent some time tracking this down.

In my case, it turned out was simply, a missing <!DOCTYPE html> tag.
