### ISSUE TITLE
Sometimes getSelection returns a wrong offset

### ISSUE THREAD

**Issue by askmike** [fraywing/textAngular#405]
I am extending TA with a function to tag a specific list of people. I am displaying a div with people whenever someone types the `@` symbol (after a space):

![screen shot 2014-11-10 at 16 16 54](https://cloud.githubusercontent.com/assets/969743/4978083/ddbee9d4-68ec-11e4-9969-5b4c0957dcf1.png)

To position this box correctly I am using the `taSelection.getSelection` method. The selection contains a container and an offset which I can use to position the box. This works except when the content is inside a `p` tag and there is some HTML before the `p` tag. This causes the offset to be wrong.

When the editor has the content `dskjanajks dn @` the selection will return (pseudo): offset 15 and the element `<p>dskjanajks dn @</p>`, this is correct.

However when the editor has the content `dskjanajks *dn* @` the selection will return: the element `<p>dskjanajks <b>dn</b> @</p>` and the offset will be 2. This offset is wrong.

I am pretty sure the error lies [here](https://github.com/fraywing/textAngular/blob/master/src/textAngular.js#L2234), where traversing the tree to the parent is good to get the `p` element, but the offset is not recalculated to account for siblings of the original node. However my DOM/rangy skills are preventing me from proposing a fix.

**Comment by SimeonC** [comment]
Version 1.3 has an improved version of the getSelection method, i.e. it's a rangy wrapper now.
Much more reliable.
