### ISSUE TITLE
Ignore image in editor

### ISSUE THREAD

**Issue by cbunhok** [fraywing/textAngular#408]
Hello Mr. @SimeonC ,

How can I ignore image in the this editor?

**Comment by SimeonC** [comment]
Closed due to inactivity.

@juanpujol You might be interested in our new 'ta-paste' attribute that allows you to modify the HTML as it's parsed in. There's also a discussion going on #534.

**Comment by ajayreddy56** [comment]
How to disable the image when i copy(clip board contains text and image) and paste in editor.
@SimeonC
