### ISSUE TITLE
How to manipulate a TextAngular editor from outside the editor?

### ISSUE THREAD

**Issue by tomsoderlund** [fraywing/textAngular#416]
I want to have my UI completely elsewhere, in my own toolbar, and hide the TextAngular toolbar completely. Is there a way of triggering the formatting options (i.e. trigger `executeAction()` on the buttons) from the outside?

**Comment by crunkyedwards** [comment]
I've been trying this approach, and can't seem to get it to work reliably. Here's a Plunkr that has two added buttons outside of the directive: "My Insert" and "My Bold". The "My Bold" button should bold a selection but doesn't, and the "My Insert" button will only insert once, right after the script is initialized. I would like to be able to place my cursor anywhere in the textAngular text and have "My Insert" insert new HTML right at the cursor. 

I'm guessing I'm missing something trivial. Thanks in advance for your help!

Here's the Plunkr: 
http://plnkr.co/edit/o0DoCuNdSJn51i4wPMHF?p=preview
