### ISSUE TITLE
Using Rangy 1.2.* causes console info log

### ISSUE THREAD

**Issue by ibexcore** [fraywing/textAngular#417]
Rangy 1.2.\* causes this log: `'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).`

Use Rangy 1.3.\* to fix.

**Comment by Urigo** [comment]
Hi, great library and thank you so much.
Why is this issue closed? it doesn't seem to be fixed for me..

**Comment by paustria** [comment]
+1

**Comment by pdonorio** [comment]
+1!!
