### ISSUE TITLE
Cant set the activeState toggle with STRONG

### ISSUE THREAD

**Issue by Davekeel** [fraywing/textAngular#422]
Hi,
i'm struggling to activate the toggle with strong custom button,
my code is this 
```javascript
.config(function($provide){
    $provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions){
        // $delegate is the taOptions we are decorating
        // register the tool with textAngular
        taRegisterTool('strong', {
            iconclass: "fa fa-bold red",
            action: function(){
                return this.$editor().wrapSelection("formatBlock", "<STRONG>");                
            },
           activeState: function{
             return this.$editor().queryFormatBlockState('strong'); }  
        });
        // add the button to the default toolbar definition
        taOptions.toolbar[1].push('strong');
        return taOptions;
    }]);
})
```

**Comment by nikhilvm1993** [comment]
how to make it for a tag like <sup> for superscript??
taRegisterTool('superscript', {
                display: '<button type="button" class="btn btn-default" title="Superscript"></button>',
                action: function() {
                    return this.$editor().wrapSelection("superscript", null)
                },
                activeState: function() {
                     return document.queryCommandState("superscript")
                }
            });
