### ISSUE TITLE
Text formatting works incorrectly

### ISSUE THREAD

**Issue by marbug** [fraywing/textAngular#423]
Hello.

I tried textAngular 1.2.2 and 1.3.0-pre14 with rangy 1.2.3 and with rangy 1.3alpha.804 and got the following issue.

Open page with textAngular (my code is shown below).
Click on input field ("P" is selected in the textAngular's menu)
Press Q - common Q is added
Click 'B' in TA menu
Press W - bold W is added
Click 'I' in TA menu
Press E - bold and italic E is added
Click 'U' in TA menu
Press R - bold, italic and underlined R is added
Click 'U' in TA menu - 'U' becomes unchecked
Click 'I' in TA menu - 'I' becomes unchecked but 'U' becomes checked again !!!
Click 'B' in TA menu - 'B' becomes unchecked but 'I' and 'U' become checked again !!!
Press 'T' - italic and underlined T is added

Please fix or tell what I am doing wrong.

Thank you

P.S. My page code:

    <head>
        <link rel="stylesheet" type="text/css" href="../../bootstrap-3.3.1-dist/css/bootstrap-theme.min.css" >
        <link rel="stylesheet" type="text/css" href="../../bootstrap-3.3.1-dist/css/bootstrap.min.css" >
        <link rel="stylesheet" type="text/css" href="../../font-awesome-4.2.0/css/font-awesome.min.css" >
        <script src="../../angularjs/1.2.27/angular.min.js" ></script>
        <script src="../../rangy/1.2.3/rangy-core.js" ></script>
        <script src="../../rangy/1.2.3/rangy-selectionsaverestore.js" ></script>
        
        
        <script src="textAngular-master/src/textAngular-sanitize.js" ></script>
        <script src="textAngular-master/src/textAngularSetup.js" ></script>
        <script src="textAngular-master/src/textAngular.js" ></script>
        <script src="app.js" ></script>
    </head>
    <body>
        <div text-angular ng-model="htmlVariable"></div>
    </body>

**Comment by SimeonC** [comment]
Thanks for letting me know that fixed it, removing it is not the right solution (it's needed for popups/modals/anything that steals focus) but if that fixed it I should be able to find the right bit for fixing it.

**Comment by JoelParke** [comment]
This is mostly fixed with PR #1289 and actually a rangy bug.
