### ISSUE TITLE
Creating a list from initial input results in broken component

### ISSUE THREAD

**Issue by JohanSmolders** [fraywing/textAngular#426]
Scenario:

* Click in the editor
* Type one or more words, DON'T hit enter
* Select what you just typed
* Hit one of the list buttons (ordered or unordered) 
* You see a list but the input in broken

Debugging the issue it seems that above scenario results in the taTextElement taBind being replaced by the list.

**Comment by SimeonC** [comment]
Definitely fixed in the v1.3
