### ISSUE TITLE
Toolbar button active class variable inconsistency

### ISSUE THREAD

**Issue by czottmann** [fraywing/textAngular#433]
_v1.2.2, problem still in effect in 1.3.x_

The variable for setting the active toolbar button class and the related HTML attribute are inconsistent.  In `src/textAngular.js`, there's this:

```
if(attrs.taToolbarActiveButtonClass)    scope.classes.toolbarButtonActive = attrs.taToolbarActiveButtonClass;
```

So, the variable is named `toolbarButtonActive` ("button active") while the attribute is named `taToolbarActiveButtonClass` ("active button").  Yet, the documentation in the wiki speaks about using setting the CSS class like this:

```
<div … ta-toolbar-button-active-class="active">…</div>
```

So either the documentation is wrong or there's a mistake in the code.  As I just stumbled over this I thought I mention it here.  :)

**Comment by herrethan** [comment]
The documentation still suggests using `ta-toolbar-button-active-class`, but that needs to be corrected to be `ta-toolbar-active-button-class`. Correcting now.
