### ISSUE TITLE
loop calling of scope.updateSelectedStyles() after switching window

### ISSUE THREAD

**Issue by marbug** [fraywing/textAngular#443]
Hello.

During #423, #424, #425 issues investigation the following small issue was found (for 1.3.0-pre15).

Chrome, FireFox
1) add console logging like the following:
scope.updateSelectedStyles = function(){ console.log( 'scope.updateSelectedStyles' );

2) click the TA's input field

3) switch to another window (Alt+Tab)

4) switch back
See in console the loop calling of scope.updateSelectedStyles()
I.e. scope._bUpdateSelectedStyles is not set to false

5) click the TA's input field - looping is stopped.

**Comment by SimeonC** [comment]
OK, I've added that fix into the new pre-release can you check please?

**Comment by marbug** [comment]
Hello. The issue has been fixed.

**Comment by SimeonC** [comment]
Awesome, thanks for getting back to us.
