### ISSUE TITLE
No resize overlay toolbar when adding image

### ISSUE THREAD

**Issue by ZissisT** [fraywing/textAngular#446]
Hello,

I was trying to use textangular in my app but overlay does not work when adding an image and clicking on toolbar button before clicking on the image
I can reproduce this also in www.textangular.com.
# Firefox

1) In www.textangular.com click to add an image url .e.g http://i.telegraph.co.uk/multimedia/archive/01448/Sax_1448658i.jpg 
2) DO NOT click on image yet, but click on P button for paragraph.
3) click anywhere outside the image, on the white space, so P gets active.
4) Now click on image. Resize overlay appears but the toolbar to align image left and right is not and there is no way to make it appear.

In some cases no resize borders appear at all also, depends on which button is active when we click on the image. --- I do not mean when we add the image, I mean when we click on image, button must be active when we click on image for this to be reproduced ---

In my app, I don't know why, P is always enabled for some reason, even with no content, which makes it impossible for me to add any picture/resize it/move it inside the document.

This can be reproduce in latest stable Firefox and Chrome.
# Chrome

In Chrome is even worse, add the image (do not click on it), then click on any of the h1/h2/h3 etc or P toolbar buttons and THEN click on image. No resize overlay at all (or toolbar)

Thank you
Zissis

**Comment by ZissisT** [comment]
Hello,

Found the issue..there was a contenteditable directive that was overwriting ngModel.$render() function with its own (so textangular's activeElement set was never executed on textangular's ngMoel.$render() function, so it didn't know where to add the image). I removed it and everything works fine :) But ngModel.$render function gets overriden often in several cases, any way to 'shield' textAngular from that ?

Zissis

**Comment by SimeonC** [comment]
Awesome, thanks for sharing your solution. We might be able to do something with terminal and compilation priorities to do that which would probably cover most cases, thanks for the suggestion.

**Comment by episodeyang** [comment]
@ZissisT

Just to clarify, did you have that directive bound to the same element as
the taBind directive and executed after taBind was applied?

ps: In my project I am actually intentionally overwriting the default
textAngular render with a differential html render I wrote myself. This is
done intentionally by running a `my-bind` directive after the taBind
directive.

**Comment by ZissisT** [comment]
Hi,

Well, not exactly. It was the contenteditable directive descibed inside angular.js file as an example over custom control using NgModelController.

```
      angular.module('customControl', ['ngSanitize']).
        directive('contenteditable', ['$sce', function($sce) {
          return {
            restrict: 'A', // only activate on element attribute
            require: '?ngModel', // get a hold of NgModelController
            link: function(scope, element, attrs, ngModel) {
              if(!ngModel) return; // do nothing if no ng-model

              // Specify how UI should be updated
              ngModel.$render = function() {
                element.html($sce.getTrustedHtml(ngModel.$viewValue || ''));
              };

              // Listen for change events to enable binding
              element.on('blur keyup change', function() {
                scope.$evalAsync(read);
              });
              read(); // initialize

              // Write data to the model
              function read() {
                var html = element.html();
                // When we clear the content editable the browser leaves a <br> behind
                // If strip-br attribute is provided then we strip this out
                if( attrs.stripBr && html == '<br>' ) {
                  html = '';
                }
                ngModel.$setViewValue(html);
              }
            }
          };
        }]);
```

so, I didn't use it directly but it was added in my app sometime ago as an actual directive and any div that used the html contenteditable attribute (like textangular I suppose) used this directive

Zissis
