### ISSUE TITLE
Chrome crashes on pressing "enter" key

### ISSUE THREAD

**Issue by stivni** [fraywing/textAngular#449]
In version 1.3.0-pre15, when pressing the "enter" key with the cursor inside a textAngular editor, the latest chrome version stalls and eventually crashes.

It does not happen with faster machines, but even with an MacBook Air, it happens. With the same machines, it does not happen anymore when hardware-acceleration is switched off. I does also not happen in Firefox.

It does not happen al the time, but it happens a lot. It also happens more easily when there is a lot of content in the editor (even with 500 words of unstyled text).

I was not able to reproduce the crashes with textAngular 1.2.x.

If you want specific detail to be able to address this issue, please let me know.

**Comment by stivni** [comment]
I wanted you to know that this issues seems fixed with the 1.3.0-19 version.
But it seems that there still is some kind of slowdown, but this may be related to the amount of binding on my page.

**Comment by kilisinovic** [comment]
this started happening to me in version 83.0.4103.116 (Official Build) (64-bit).
Usually happens when I open some page and then try to type something in search bar.  After pressing enter chrome occasionally crashes.
