### ISSUE TITLE
Paste event

### ISSUE THREAD

**Issue by veteran1** [fraywing/textAngular#462]
Hello,
how can i listen for paste event?
for example when I paste a text I want to remove images and styles from it.
 Note: ng-paste directive seems to work only with input, select, textarea and a.
Thank you

**Comment by SimeonC** [comment]
Hi there. Currently there is no option for this, as pointed out in #393.

I wasn't aware of the ng-paste directive so when I add the enhancement I'll use that if I can.

**Comment by kotmatpockuh** [comment]
how is it there with this? 
i really need ng-paste(

**Comment by SimeonC** [comment]
So ng-paste will trigger as an event. To intercept the pasted content you want to use `ta-paste`.

`ta-paste="modifyHtml($html)"` In this case $html is a variable that contains the pasted html/text, the result of the expression, `modifyHtml` in this case, is what is pasted in.
