### ISSUE TITLE
Text is replaced with the string 'undefined' if typed in the HTML editing, prepended with a newline, and then converted to a paragraph

### ISSUE THREAD

**Issue by errendir** [fraywing/textAngular#463]
In order to reproduce this bug:
- switch the mode to "HTML"
- type in some text
- switch the mode back to the standard
- add a newline before the inputed text
- select the entire input
- press the paragraph button to convert the selection to a paragraph

This will result in a text being replaced with "undefined"

This GIF shows the process:
![output](https://cloud.githubusercontent.com/assets/2817891/5516144/e19c1c56-888c-11e4-8210-859783ce2c89.gif)

Tested on the 1.3.0-pre9 version as well as the 1.2.2 (the demo on the http://textangular.com/)

**Comment by SimeonC** [comment]
Thanks for letting us know, I'll look into this and see what I can do.

**Comment by SimeonC** [comment]
Ok, I've checked this and it should be fixed in v1.3.0, coming ASAP.
