### ISSUE TITLE
AngularJS Version in bower.json

### ISSUE THREAD

**Issue by Bavragor** [fraywing/textAngular#465]
Please change AngularJS Version in bower.json to 1.3.x or a version range from 1.2.x to 1.3.x.
Else bower will ask for the right version and textAngular works fine with AngularJS 1.3.x

Greetings

**Comment by SimeonC** [comment]
In the 1.3.0 pre-releases it's set to `"angular": "^1.2.x",` I think this is just a legacy issue and will be fixed in future releases.

**Comment by SimeonC** [comment]
Should be fixed in latest releases.
