### ISSUE TITLE
image and video resize doesn't seem to be working

### ISSUE THREAD

**Issue by episodeyang** [fraywing/textAngular#470]
Hi @SimeonC,

I just want to check, is the image resizing working? on my pre19, both the image resizing of video and image are not working.

Thanks,
Ge

**Comment by SimeonC** [comment]
Yea, it's not working for me either, I'll fix this now I'm back from holiday!

**Comment by episodeyang** [comment]
Happy holidays! Have fun:)

**Comment by SimeonC** [comment]
Ok, should be fixed in new pre-release, can you confirm please?

**Comment by mgruesbeck** [comment]
I found the same issue. Also, when `bower install https://github.com/fraywing/textAngular` (the pre-release git) the local bower install still stays it's release 1.2.2. 

Is that incorrect or am installing the pre-release wrong?

**Comment by episodeyang** [comment]
@mgruesbeck You need `bower install https://github.com/fraywing/textAngular#master` inorder to install the pre-release git.

@SimeonC , I have not tested this one yet since I need to merge my fork with it first. I will get to this tonight!!

**Comment by mgruesbeck** [comment]
Thanks @episodeyang.

Alright, I updated to pre-release. All textAngular files are loading with no errors but I'm still having resizing issues.

If I click the image and drag the corner it will pass: 
`<img height:"xxx" width:"xxx" src="image.jpg">`

However, if you click the image and use the percentages to resize no percent width are passed. For example if you select 100% on an image the output will be:
`<img src="image.jpg">`

I'll wait for @episodeyang's results.

**Comment by SimeonC** [comment]
@mgruesbeck The percentages are aimed at a percentage of the original size of the uploaded image. So 100% is a 1:1 ratio of the image, I copied the logic off of summernote.org.

**Comment by episodeyang** [comment]
@SimeonC @mgruesbeck 

The resize handle works well in firefox. However, the image popup does not show.

In Chrome, the handle changes *all* of the images in the editor proportionally simultaneously. The popup shows properly though. 

I haven't tested it on other machines.

**Comment by mgruesbeck** [comment]
Thanks guys. From what @episodeyang is saying it sounds like my issue is different.

For example, when clicking 50% I would expect textAngular to pass: 
`<img style="width:50%" src="image.jpg">`. 

However, in my case, no percentage is passed and the result is this: 
`<img src="image.jpg">`

I'll update you if I can figure it out.

**Comment by SimeonC** [comment]
@mgruesbeck Ugh, that was my bad actually - I just checked and what you said is what should be happening and is what happens on my end when I actually try it. Possibly you have angular-sanitize instead of textAngular-sanitize loaded? That would strip out the width regardless.

@episodeyang I see that now, looks like something weird is going on there...

**Comment by SimeonC** [comment]
OK, try pre-release 21, that should have it fixed.

**Comment by episodeyang** [comment]
@SimeonC , it works! 

There is just one problem though, it seems rangy crashes a lot. When it crashes, the whole app turn into a text view.

What I have are two svg images that are 900kb each.

**Comment by SimeonC** [comment]
What's the error? I haven't had that problem yet - also which rangy version?

**Comment by SimeonC** [comment]
Weird, I'll try look into this and see if I can find what's causing it, if I can replicate it that is!

**Comment by SimeonC** [comment]
When you say it only occurs when a user uploads an `svg` file do you mean like this? `<img src="http://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg"/>`

**Comment by episodeyang** [comment]
yes! so in chrome, if I click on this svg a lot, it crashes the page.

this however does not occur with the current demo on the website.
