### ISSUE TITLE
Prevent colors in paste

### ISSUE THREAD

**Issue by dbounds** [fraywing/textAngular#471]
Hello,

Recently I've upgraded to the latest build of TextAngular from 1.2.2 for Word doc paste support.

While that works reasonably well, it appears colors are also being imported and applied a style properties. Is there an option I can use to disable this? While I want hierarchy imported from a paste I do not want any colors.

**Comment by SimeonC** [comment]
Hey, currently there isn't any such functionality, though we are adding in a ng-paste hook in 1.3.1 as stated in #462, that will allow you to modify the pasted content.

**Comment by dbounds** [comment]
Thanks.

**Comment by SimeonC** [comment]
See #534 For the discussion on this.
