### ISSUE TITLE
Pressing the return key, sometimes makes a <br />, sometimes makes a <p>...</p>

### ISSUE THREAD

**Issue by stivni** [fraywing/textAngular#473]
The result of pressing return is not consistent.
Sometimes it makes a `<br />` (acting as a soft return)
Sometimes it makes a new paragraph (`<p>...</p>`, acting as a hard return)

**Comment by SimeonC** [comment]
Hey, Which version of textAngular are you using?

**Comment by stivni** [comment]
I'm using 1.3.0-19.

You think it should work in 1.3.0-21?
I didn't test it, because I couldn't find any open or closed related issue...

**Comment by SimeonC** [comment]
Nope, it shouldn't make a difference. I'll look into it.

**Comment by SimeonC** [comment]
I can't seem to replicate this, are you perhaps accidentally pressing `shift+enter` which inserts a soft return `<br/>`?

**Comment by stivni** [comment]
I'm sure I'm not using shift.

The problem is that it happens randomly, I can't write down a scenario in which it happens for sure.
It is just sometimes like this sometimes, like that...
I'll give it another try though!

Btw, thanks for the fast feedback every time I log an issue! You guys are really responsive! Keep up the good work!

**Comment by SimeonC** [comment]
Looking through the code I have a theory - does the `<br/>` inserts occur when you hold down the enter button?

Code Reference: https://github.com/fraywing/textAngular/blob/master/lib/taBind.js#L409-L424

**Comment by indraneelr** [comment]
I am using version 1.4.6 and I am seeing the same issue. When I press enter, in chrome it adds <p> tags whereas in firefox it adds <br>.

**Comment by JoelParke** [comment]
This is now essentially identical in Chrome and Firefox.  We remove the extraneous <br> tags when in can.   So as you type, more, you will see the <br> go away.  So I am closing this issue, as it is foundational to differences between firefox and Chrome.
