### ISSUE TITLE
Possible to replace/insert text while typing

### ISSUE THREAD

**Issue by CedricDumont** [fraywing/textAngular#474]
Hi, I would like to know if it is possible to replace the content of textangular while typing. 
Examples:
- the user types '...' and it's replaced with a `<hr/>  `
- the user types 'hello', and it automatically append ' World!' . So hello World is printed. 

I've tried with a plunk : http://plnkr.co/edit/pSOnfBtfTb57uBOAzKXw?p=preview
but it does not change the content. And I would like to know if there is a better solution than using $watch.

kind regards

**Comment by SimeonC** [comment]
So changing the model while typing actually won't work - we prevent model -> DOM updates when the input is focussed as otherwise we get some nasty infinite loops.

To do this you want to attach a keyup listener and do it there, a similar issues is #235.
