### ISSUE TITLE
Older internet explorer autolinks text

### ISSUE THREAD

**Issue by iainbeeston** [fraywing/textAngular#475]
I've noticed that the content editable tag created by the text-angular directive does slightly strange things on internet explorer. Notably, if you type in a url, IE9 automatically converts it to an `<a href="...">` tag. That may or may not be a problem (depending on your app), but the user hasn't explicitly made that text into a link (as they would have to do for other browsers - so it's inconsistent).

Apparently this can be fixed (in IE>=5.5) by calling `el.execCommand("AutoUrlDetect", false, false)` (see [here](http://msdn.microsoft.com/en-us/library/aa769893%28v=vs.85%29.aspx)).

I'm fine with doing that myself on my own project, but I figured it should probably be the default on text-angular? Or at least something that has a known fix.

**Comment by iainbeeston** [comment]
I'm not 100% sure if you can call `execCommand()` on a particular content editable tag, or if it has to be on the document (in which case it might be a bad idea to include this in text-angular, but perhaps it'd be worth recording the fix somewhere?)

**Comment by SimeonC** [comment]
Thanks for posting up the issue and fix, `execCommand` unfortunately cannot be called on a specific instance AFAIK, for now I'll just document it in the readme.
