### ISSUE TITLE
Difficulty focusing textarea (1.3.0-21)

### ISSUE THREAD

**Issue by dbounds** [fraywing/textAngular#477]
I've been using 1.3.0 for a while now, including the latest build. I've been noticing there are issues with focusing the textarea with a click. For example, in the screenshot here (http://cl.ly/image/2f1F0o2I3J28) I can only focus that input by clicking on the existing text, the empty space in textarea doesn't focus it.

**Comment by dbounds** [comment]
I resolved the issue by specifying a fixed min-height on .ta-scroll-window > .ta-bind.

I had previously in place the CSS mentioned here: https://github.com/fraywing/textAngular/issues/459

**Comment by SimeonC** [comment]
That particular issue is not really relevant to v1.3.0+ as the css was moved to the external file and fixed up a bit.

Look at lines 20 and 34 of https://github.com/fraywing/textAngular/blob/master/src/textAngular.css which is how it's set by default now, removing/changing/overriding those two lines will help with the #459 issue in the new versions.
