### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by dbounds** [fraywing/textAngular#478]
We've been running into many issues with 1.3-21 and are going to revert to 1.2. 

Many issues with formatting, copy/paste, pasted content arriving out of order and the fact you can't prevent styling on paste...

**Comment by SimeonC** [comment]
Well it is a pre-release, it's under active development (when I can). We've covered prevent styling on paste in another issue. Have the other issues been recorded somewhere so I can fix them or at least look into them?

**Comment by dbounds** [comment]
Understood. I'm cataloging the issues and will submit them when I have some time. 

I did have to revert though.

**Comment by SimeonC** [comment]
Thanks a lot for helping me make textAngular better!! :+1:

**Comment by SimeonC** [comment]
I'm going to close this as I think we've got all the issues you posted up fixed now with the full release.
