### ISSUE TITLE
Is there a way to wrap selection with custom tags?

### ISSUE THREAD

**Issue by Bavragor** [fraywing/textAngular#481]
See my question above...
For example you have selected "Price" and want to look it like 
```
<span class='example'>Price</span>
```

**Comment by SimeonC** [comment]
Best way to do this is to use the rangy library, we want to add this sometime in the future but haven't yet as nothing natively supports this as far as I can remember, there is something close in the CSSClassApplier library of Rangy here: https://code.google.com/p/rangy/wiki/CSSClassApplierModule

Covered in issues: #180 #448 #156

**Comment by Bavragor** [comment]
Well ok.. I wrote something and will introduce this as a pull request :)
