### ISSUE TITLE
Using ng-focus with textAngular

### ISSUE THREAD

**Issue by costinn** [fraywing/textAngular#482]
I have the following code written in Jade:

> div(text-angular, ta-toolbar="[[""]]", ta-toolbar-class="btn-toolbar", ta-toolbar-group-class="btn-group", 
> ta-toolbar-button-class="btn btn-sm btn-primary",
> ta-toolbar-button-active-class="active", ng-model="model", ng-focus="someFunction()",
> ng-blur="someFunction()")

If someFunction was to contain a console.log("Hello!"), "Hello!" would be logged to the console only on blur, but not on focus. I really need that ng-focus function to work and it does not.

**Comment by SimeonC** [comment]
Thanks for pointing this out, turns out I forgot to add the focus handler trigger as well as the blur.
Will be fixed in next pre-release out shortly!

**Comment by SimeonC** [comment]
Should be fixed in newest pre-release of 1.3.0.
