### ISSUE TITLE
Retaining text selection upon applying different formatting

### ISSUE THREAD

**Issue by shubhendusaurabh** [fraywing/textAngular#485]
Text selection is lost when applying different styles.
For e.g I have multiple lines in the editor and want to check out different styles like order list or unordered list. But text lose selection upon clicking ul/ol/h1 buttons.
They work fine for bold/italic/underline/text-alignments etc.

**Comment by SimeonC** [comment]
OK, I can see that issue!! Thanks for reporting it, but as it's a minor and not a breaking change I'm going to have to push it out to 1.3.1 release.

**Comment by SimeonC** [comment]
Is fixed in master now.
