### ISSUE TITLE
Auto blur issue with 'textAngular-editableFix' element

### ISSUE THREAD

**Issue by guyius** [fraywing/textAngular#487]
The use case is as follows:
1. Select text angular text area (you can enter text but you don't have to).
2. Select the input on the same page/form.
3. Type 1 letter in the input field and you will get un focused automatically.

What happens is that the 'textAngular-editableFix-010203040506070809' element gets focused, this only happens on chrome.

Versions: angular 1.3.4, text-angular 1.2.2,

Plunker: http://plnkr.co/edit/HmCl6RgHM6drtmYSkeQc?p=preview

**Comment by SimeonC** [comment]
I can't find when this was fixed but I did fix it in the 1.3.0 pre-releases. See https://gist.github.com/shimondoodkin/1081133 for why this is there.
