### ISSUE TITLE
Multiple tags being inserted

### ISSUE THREAD

**Issue by Gillardo** [fraywing/textAngular#492]
I have created a custom image insert button.  You click the button, a model window appears, and you can pick from a list of images.  That string is then inserted into the content.  If you do this and then look at the HTML view, you will see lots of rangy tags like so

```sd
<p><span id="selectionBoundary_1421406872546_3313087276183069" class="rangySelectionBoundary">&#65279;</span><img src="http://www.google.com"/><br/></p>
```

I have created a plunkr to replicate it and you can view it here.

http://plnkr.co/edit/1qfKx0eBEq7tL30l3iqA?p=preview

It all works, apart from all the tags that get inserted.  I have tried both the normal ngSanitize and textAngular sanitize and neither make a difference.  I have also tried upgrading to the latest version of textAngular, but that completely breaks the look as buttons are missing (not sure if this is a bug?)

Can someone have a look and see whats up?

**Comment by SimeonC** [comment]
Alright, I've had a look, it looks to me like you missed the arguments passed to the `action` function: `function(deferred, restoreSelection)`. When returning false you need to use both of these, I've edited your function as below.

In short the `restoreSelection` function does what your `savedSelection` logic was doing and the `deferred.resolve()` tells text angular it can keep processing now.

```js
action: function (deferred, restoreSelection) {

                          var textAngular = this;

                          var $modalInstance = $modal.open({
                              // Put a link to your template here or whatever
                              templateUrl: 'image-picker-modal.tpl.html',
                              size: 'lg',
                              controller: ['$modalInstance', '$scope', 'TaImagePicker',
                                function ($modalInstance, $scope, TaImagePicker) {

                                    var removeWatch = $scope.$watch(function () {
                                        return TaImagePicker.selected;
                                    }, function () {
                                        if (TaImagePicker.selected.length > 0) {
                                            $modalInstance.close(TaImagePicker.selected);
                                        }
                                    });

                                    // when the scope is destroyed, remove watch
                                    $scope.$on('destroy', function () {
                                        removeWatch();
                                    });

                                    $scope.cancel = function () {
                                        $modalInstance.dismiss('cancel');
                                        deferred.resolve();
                                    };

                                }
                              ]
                          });

                          $modalInstance.result.then(function (e) {
                              restoreSelection();
                              textAngular.$editor().wrapSelection('insertImage', e);
                              deferred.resolve();
                          });

                          return false;
                      }
```

**Comment by Gillardo** [comment]
Thank you very much!! Sorry for the trouble

**Comment by SimeonC** [comment]
No trouble at all, I know that textAngular does some things a bit strange so it doesn't bother me.
