### ISSUE TITLE
How to wrap the default taBind event handler?

### ISSUE THREAD

**Issue by episodeyang** [fraywing/textAngular#493]
Hi @SimeonC ,

I have a few custom directives inside the editor, so some of the `keydown` events in the editor needs to be handled differently.

I am trying to wrap the taBind event handler but failing. Here is how I did it:

in my directive:
```javascript
taBindHandler = iElement.off('keydown');
... my code..
... more code...
taBindHandler(event);
```

but I realized that the taBindHandler returned from the iElement.off() is the element itself, not an event handler. How to get the event handler instead?

Thanks!

**Comment by SimeonC** [comment]
I think I should implement some ng-keyup kind of interaction for the taBind directive as I don't think the event handler is accessible outside of the directive itself.

**Comment by episodeyang** [comment]
Hey, 

So if we can save the keydown handler in the scope, it would be fairly easy to wrap.

Do you think something along the line of 
```javascript
scope.onKeydown = function onKeydown () {
blah blah
}

iElement.on('keydown', onKeydown);

```

would work?

Ge

**Comment by SimeonC** [comment]
That would work in theory. If there's a way of accessing the taBind's isolated scope? I can't think of one off the top of my head.

**Comment by episodeyang** [comment]
I was able to do that following your example code in one of the issues.

So in app.configure, I bind another directive to the ta-bind element. Then
I am able to isolate the scope.

Ge

**Comment by SimeonC** [comment]
Ok, I've added in an events object to the taBind scope. Its now `scope.events.keydown`. Will be in next patch, hopefully a full 1.3.0 so you may have to wait a day or two for the one outstanding issue to be confirmed resolved.

**Comment by episodeyang** [comment]
No worries! I have been pretty much working with my fork, so it will take
me a day or two to merge rebase with your master again.

Thanks for this great library! and sorry for not following up with my PR
with tests. It took some solid 4 weeks to get the code bullet-proof in
Chrome. Right now there are a few problems in safari and firefox.

I think actually if you have time (and I understand if you are busy), it
might be helpful if you can lend a hand.

Ge
