### ISSUE TITLE
Problem with Formation text from C&P

### ISSUE THREAD

**Issue by volkerpc** [fraywing/textAngular#494]
Hello together,

I have a problem:
My users often use c&p functionality with textAngular , and they like to format those texts afterwards.

At the moment we have problems with that.
Headlines are not possible, also list items are not working after c&p a text from the internet.

I have made a video to show this issue:
http://youtu.be/eMQelZrSOjo

Tested on firefox 35 browser on MAC/OS.

Thank you for your help !

Volker

**Comment by SimeonC** [comment]
This should be fixed in v1.3.0 which is nearly ready for full release.

**Comment by volkerpc** [comment]
Thank you !
