### ISSUE TITLE
Having a <br> inside the content breaks the editor

### ISSUE THREAD

**Issue by snekbaev** [fraywing/textAngular#497]
Hi,

if content has ```<br>``` apparently it is converted into ```<br></br>``` which is invalid and this breaks the editor. For now before binding I'm going over the model's properties and doing something like
```
item.text = item.text.replace(/<br>/g, '<br/>');
```
Thank you!

P.S.: using pre23 but different sanitizer, which you had in some version:
```
AngularJS v1.3.0-build.2711+sha.facd904
```
hopefully this is not an issue

**Comment by SimeonC** [comment]
That's just the sanitiser, it thinks that the `<br>` is just an unclosed tag and closes it.

If you grab the newer version of the sanitiser it should be fixed as with my current version it's taking in `<p>Test<br></p>` and converting it to `<p>Test<br/></p>`, though I do have to re-merge in the newest sanitiser version for angular.js as the current is based off 1.2.26...

**Comment by SimeonC** [comment]
I just re-checked, I think there's an issue with that version of the sanitiser, not sure why or how, but it was a pre-release and I reverted it later. Next version/pre-release will have the up to date versions of the textAngular-sanitize.js file.

**Comment by snekbaev** [comment]
I think the reason why I wasn't using the 1.2.26 one was because it was converting all foreign language characters, for example Finnish ä was becoming &auml etc. I will recheck this next week with the latest sanitizer taken from ng directly, unless you will have your own one by that time (more relaxed one?)

Thank you!
