### ISSUE TITLE
Issues copying images from LibreOffice

### ISSUE THREAD

**Issue by davidmartingonzalez** [fraywing/textAngular#501]
Hello,

I have noticed that there seem to be issues when copying images from LibreOffice to textAngular. When I have tried to copy a portion of a document consisting of both text and an image to textAngular 1.3.0, it seems to be copied flawlessly; however, if I select just an image, it is not really pasted, and only an empty paragraph is put in its place. I've tried testing the exact same behaviour on the Summernote demo and it seems to be working fine on both cases, both with Chrome 39 and Firefox 35.

The textAngular demo, which is running on version 1.2.2, seems to be behaving differently. On either browser, copying and pasting both text and an image actually pastes the text only, but not the image; meanwhile, single images are copied on Firefox but not on Chrome.

**Comment by SimeonC** [comment]
Hi, I haven't officially supported copy-paste from LibreOffice yet. v1.3.0 supports copy-paste with images and text for word and html. Pasting images is a bit of an issue and won't work as you expect at present as they need to be an image on a server (unless your image from LibreOffice pastes with a src to some web hosted image).

Pasting in 1.2.2 is text only.

**Comment by brackmayhall** [comment]
Is there any way we could detect that the image is a link(ie from word, libre,gmail, etc) and then request the image and base64 encode it?

Maybe this could be a flag that could be turned on if someone wants to use this type of funcationality. It seems that the encoding support is already there for drag and drop of images.

Thoughts?

**Comment by SimeonC** [comment]
@brackmayhall That's not something we'd do in textAngular itself, theres the ta-paste function available now that allows you to do this kind of conversion yourself.
