### ISSUE TITLE
[Fix Included] Unable to focus on inputs inside modals on touch devices 

### ISSUE THREAD

**Issue by numerized** [fraywing/textAngular#503]
From jdhiro commented on Apr 3, 2014
https://github.com/angular-ui/bootstrap/issues/2017

There is a related issue opened against angular, but I suspect this is an issue specifically with the modals. angular/angular.js#6432

Plnkr is here: http://embed.plnkr.co/gyNF9BhiaBuMtonPXYKS/preview

This repro requires:
1. Having an input inside of a UI Bootstrap modal box
2. Having angular-touch enabled (checked against 1.2 and 1.3)
3. Being on a touch device or using Chrome's touch emulation

Repro steps:
Click the button to open the modal, and then click on the text input field. On touch devices, the field will not handle tap to change the cursor position over the text and will lose its position when any option from TextAngular bar. With a normal mouse click, it's fine.

It looks like this probably is an angular-touch bug, so I'm going to close it out here. It's related to how the form has a parent element with ng-click (the background/fade), so this will fail in all circumstances were a form is inside of a modal if angular-touch is present.

I'm working around this in my own project by blocking touchend events from propagating past the modal form like this:

    <div class="modal-body" stop-event="touchend">

With a directive like this:

    .directive('stopEvent', function () {
        return {
          restrict: 'A',
          link: function (scope, element, attr) {
            element.on(attr.stopEvent, function (e) {
              e.stopPropagation();
            });
          }
        };
      });

**Comment by SimeonC** [comment]
Thanks for sharing, I agree that this looks like a not-textAngular issue so I'll close it off. Re-open if it is something we have to fix.

**Comment by numerized** [comment]
Thanks dude, it could help some ppl.

**Comment by webskin** [comment]
Thanks !!!

**Comment by hetAuxo** [comment]
great, thanks!!

**Comment by moorthi07** [comment]
Just tried on Android API 23, it works. but the catch is that it doesn't work with Single touch or Double touch. TA only gets focus with the** 'Touch and hold for 2 seconds ' **- which is the geture for the text selection in most mobile operating systems.

**Comment by phyopyae** [comment]
I faced the same problem that cannot select the input field and select box in modals dialog in mobile.

Clicking the button is okay.

But when I click the input field, it could not focus to the clicked input field.

And when I click select box, the select options could not display on the modal dialog.

I used AngularJS and Bootstrap.

This is the sample code which I copied from 
http://embed.plnkr.co/gyNF9BhiaBuMtonPXYKS/preview
and added select box in modal.

`<!DOCTYPE html>
<html>

<head>
  <link data-require="bootstrap-css@3.x" data-semver="3.1.1" rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
  <script data-require="angular.js@*" data-semver="1.2.15" src="http://code.angularjs.org/1.2.15/angular.js"></script>
  <script data-require="angular-touch@*" data-semver="1.2.13" src="http://code.angularjs.org/1.2.13/angular-touch.js"></script>
  <script data-require="ui-bootstrap@*" data-semver="0.10.0" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.10.0.js"></script>
</head>

<body ng-app="app">
  <div ng-controller="ModalDemoCtrl">
    <script type="text/ng-template" id="myModalContent.html">
      <div class="modal-body" stop-event="touchend">
        <input type="text" placeholder="Clicking here doesn't work =(" />
      <select>
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option>
      </select>

    </script>
    <input type="text" placeholder="Clicking here works" />
    <br />
    <button class="btn btn-default" ng-click="open()">Open me!</button>
  </div>
  
  <script>
    angular.module('app', ['ngTouch','ui.bootstrap'])

.controller('ModalDemoCtrl', function($scope, $modal, $log) {
  $scope.open = function () {
    var modalInstance = $modal.open({
      templateUrl: 'myModalContent.html',
      controller: 'ModalInstanceCtrl'
    });
  };
})

.controller('ModalInstanceCtrl', function($scope, $modalInstance) {})
  
.directive('stopEvent', function () {
    return {
      restrict: 'A',
      link: function (scope, element, attr) {
        element.on(attr.stopEvent, function (e) {
          e.stopPropagation();
        });
      }
    };
  });
  
  </script>
  
  
</body>

</html>
`

**Comment by cssckku** [comment]
Thanks!!
