### ISSUE TITLE
<input> field loses focus after leaving textAngular RTB and typing text

### ISSUE THREAD

**Issue by jpantall** [fraywing/textAngular#505]
Hello!
I'm having an issue with an input box losing focus after entering a character. This only happens when the text angular RTB is selected first and then the input box.

Here's a link to a plunker demonstrating the issue.
http://plnkr.co/edit/m5A6ReSXbpmEEeheXV3W?p=preview

Thank you in advance for your response,
Jonathan

**Comment by SimeonC** [comment]
Hi this was a bug in 1.2.2, 1.3.0 has this fixed and should be released any day now.

**Comment by SimeonC** [comment]
As it is, 1.3.0 is released now.
