### ISSUE TITLE
Bower package rangy not available

### ISSUE THREAD

**Issue by chanthus** [fraywing/textAngular#506]
Looks like 'rangy' is not available on bower repository and is instead called 'rangy-release'. And this is making bower install fail.

**Comment by SimeonC** [comment]
Bower install works for me in v1.3.1?

If you look here (https://github.com/timdown/rangy-release/commit/b0841582876035240fb98f70065c5fae124b97c2) `rangy-release` was actually `rangy-official` and is now `rangy`.

**Comment by chanthus** [comment]
Hmm in wonder why mine doesn't work. I cleared bower cache and ran bower install and he's the output i get.

```
bower textAngular#1.3.1     not-cached git://github.com/fraywing/textAngular.git#1.3.1
bower textAngular#1.3.1        resolve git://github.com/fraywing/textAngular.git#1.3.1
bower textAngular#1.3.1       download https://github.com/fraywing/textAngular/archive/v1.3.1.tar.gz
bower textAngular#1.3.1        extract archive.tar.gz
bower textAngular#1.3.1       resolved git://github.com/fraywing/textAngular.git#1.3.1
bower rangy#^1.3.0          not-cached git://github.com/Dakuan/Rangy-bower.git#^1.3.0
bower rangy#^1.3.0             resolve git://github.com/Dakuan/Rangy-bower.git#^1.3.0
bower rangy#^1.3.0        ENORESTARGET No tag found that was able to satisfy ^1.3.0

Additional error details:
Available versions: 1.2.3
```

**Comment by SimeonC** [comment]
That's very weird, it looks like bower hasn't updated yet - it was only yesterday when the change happened so I'm going to give it a little while longer to work itself out.

From what you posted it's going to the old rangy repo that was recently depreciated and the bower tag removed see #500.

**Comment by chanthus** [comment]
Yeah. I guess we can wait for a little while for bower to update itself

**Comment by SimeonC** [comment]
Ok, I checked again, it looks like rangy is up and running correctly now. Reverted back to the stable patch as he added it back in.

```
bower update rangy
bower rangy#^1.2.0              cached git://github.com/timdown/rangy-release.git#1.2.3
bower rangy#^1.2.0            validate 1.2.3 against git://github.com/timdown/rangy-release.git#^1.2.0
```

**Comment by chanthus** [comment]
Cool. Thanks!

**Comment by BattleBrisket** [comment]
Just FYI rangy still [does not appear in the Bower repo search](http://bower.io/search/?q=rangy), but installation works just fine.

**Comment by SimeonC** [comment]
It comes up under "Rangy-Release" for some reason, the actual bower.json definition is rangy. I dunno, I guess their process takes a while to update or struggles with package name changes.
