### ISSUE TITLE
Last <pre> tag in the textbox overwrites values of all previous <pre> tags.

### ISSUE THREAD

**Issue by jseminck** [fraywing/textAngular#508]
Hi,

I ran into a strange issue: it doesn't seem to be possible to have multiple "pre" tags in the textbox as the last one overwrites all the previous ones.

Have searched around a bit but couldn't find anyone with the same issue... which makes me think it may be due to my configurations somewhere?
EDIT: I only have this issue with 1.3.1 and 1.3.0. 1.2.0 works fine.

Here is a screenshot: http://i.imgur.com/KfXoMye.png - the second "pre" tag overwrites the contents of the first "pre" tag. I tried with three as well and the result is the same.

Any idea what may cause this?

Thanks

**Comment by SimeonC** [comment]
Hmmm, I know what will be causing this - it's the new processing I put in somewhere I've got a improperly scoped variable. Will fix up ASAP.
