### ISSUE TITLE
Pre tag in Chrome splits text per line

### ISSUE THREAD

**Issue by inormis** [fraywing/textAngular#511]
Reproduced 1.2.2 and 1.3.0 (http://textangular.com/) 

Steps to reproduce:
1. Select multiline text 
2. Click 'pre' button
3. Result - every line is wrapped in an individual pre tag

**Comment by SimeonC** [comment]
Thanks, looks like I need to look into this. Thanks.

**Comment by bhuvangu** [comment]
Any update/workaround for this

**Comment by JoelParke** [comment]
<p>I am taking a look at this.  It's interesting.  Under firefox it does the same thing.  <br/>And in either browser you can't select multiple Pre tag lines to undo, only one at a time.<br/>So this should not be too hard to correct... we will see.  Sorry this took so long to get to.</p>

**Comment by JoelParke** [comment]
<p>This is resolved the PR #1324 and will make it into the next release... probably late Monday.<br/>Now when you press the Shift key will clicking on the &lt;Pre&gt; button of the toolbar, if wraps the selection in &lt;pre&gt; just like &lt;blockquote&gt; does.</p><p><br/></p>

**Comment by JoelParke** [comment]
<p>But there is more work to do, since I discovered that this is new bug on Firefox.</p><p>For firefox, the multi selection without or with the Shift does the wrong thing.</p>

**Comment by JoelParke** [comment]
added a PR #1327 and a test that resolves this.
