### ISSUE TITLE
"Rangy-official" still appears in bower.json

### ISSUE THREAD

**Issue by eastenluis** [fraywing/textAngular#514]
Hi, in the bower.json file:
```JSON
{
  "name": "textAngular",
  "version": "1.3.3",
  "main": [
    "./src/textAngular.js",
    "./src/textAngular-sanitize.js",
    "./src/textAngularSetup.js",
    "./src/textAngular.css",
    "../rangy-official/rangy-selectionsaverestore.js"
  ] 
...
}
```
there is still a rangy-official directory in main. After I run bowerInstall, the "rangy-official" line is added to my index.html file, and reports that file is not found when I run my web app. I think since the latest has been changed to adapt he latest rangy, the line with "rangy-official" may not be needed anymore. Thanks.

**Comment by SimeonC** [comment]
Gah, I thought I'd caught and removed all of them :(

Sorry about that, I'll get it patched out soon.

Out of curiosity, as rangy is a requirement now, which of the rangy files gets put into your index.html?

**Comment by eastenluis** [comment]
```html
    <script src="bower_components/rangy/rangy-core.min.js"></script>
    <script src="bower_components/rangy/rangy-cssclassapplier.min.js"></script>
    <script src="bower_components/rangy/rangy-selectionsaverestore.min.js"></script>
    <script src="bower_components/rangy/rangy-serializer.min.js"></script>
    <script src="bower_components/textAngular/src/textAngular.js"></script>
    <script src="bower_components/textAngular/src/textAngular-sanitize.js"></script>
    <script src="bower_components/textAngular/src/textAngularSetup.js"></script>
    <script src="bower_components/rangy-official/rangy-selectionsaverestore.js"></script>
```
These are the lines appended after I run bowerInstall. So the first four are the rangy files. The last one is the duplicate but pointing to the old 'rangy-official' directory.

**Comment by SimeonC** [comment]
Cool, thanks. I'll just remove that extra line then.

**Comment by SimeonC** [comment]
Merged in, will be in next release.
