### ISSUE TITLE
jslint find that code is not clean regarding quotes

### ISSUE THREAD

**Issue by jcsena** [fraywing/textAngular#515]
Hi! 
as suggested in the syntax of the string double quotes are a warn for jslint

**Comment by SimeonC** [comment]
Hi, can you be a little more specific as to what the issue is and what it effects please?

**Comment by jcsena** [comment]
![screen shot 2015-01-27 at 10 04 51 pm](https://cloud.githubusercontent.com/assets/4293508/5931815/b3ce355a-a670-11e4-8139-aab8effd8be4.png)

really not a problem , but I see as a suggestion that the string varibles use single quotes , not double .
Adunte an image file textAngularSetup.js classes and observed that some variables have single and double quotes other this is a mistake when making a grunt task

Deputy grunt image also 
![screen shot 2015-01-27 at 10 11 25 pm](https://cloud.githubusercontent.com/assets/4293508/5931867/a34b8a38-a671-11e4-8bad-c26845c238b7.png)

**Comment by SimeonC** [comment]
OK, I'll think about it. Depends how much work it'll be to change this.

**Comment by SimeonC** [comment]
There's about 210 quote marks to change, some in regex and some not, so I won't be doing this.
If anyone fancy's grinding away at it and submit a PR, feel free.
