### ISSUE TITLE
With Bootstrap datepicker: when clicking on textAngular - calendar loose focus, but didn't close

### ISSUE THREAD

**Issue by kotmatpockuh** [fraywing/textAngular#516]
Maybe you have ideas: why and how to solve?

**Comment by SimeonC** [comment]
Sorry no, don't know anything off the top of my head.
Can you provide a plunkr or similar to replicate the issue please?

**Comment by JoelParke** [comment]
I haven't been able to reproduce this either.  Tested with 1.4.2-0.  Please retest and if still and issue, let us know.  I use the Bootstrap datepicker and all is well???
