### ISSUE TITLE
Pasting html toggle back to text view

### ISSUE THREAD

**Issue by realdigid** [fraywing/textAngular#517]
When I attempt to paste html, then toggle back to real text, none of my html is visible, however when I type it in, it is visible.

**Comment by SimeonC** [comment]
Hey, can you tell me which version of TA you are using please?

Also can you check that this isn't the same issue as in #512, which should be fixed in the latest patch.
If not either can you add the HTML you are trying to paste into the issue and some more specific steps to reproduce it please!

**Comment by realdigid** [comment]
textAngular
Author : Austin Anderson
License : 2013 MIT
Version 1.2.2

**Comment by realdigid** [comment]
I'll make sure I update it to the latest and see if the issue persist tomorrow. Thanks for the quick response.

**Comment by SimeonC** [comment]
Ah yes, in v1.2.2 we only supported plain pasting - all the HTML gets stripped out.
In 1.3.0+ we support paste from word and html, but do make sure you read the upgrading notes in the README before upgrading!

**Comment by realdigid** [comment]
Hrm, the issue seems to persist. Here is the html I'm pasting, perhaps you can reproduce the issue.

https://gist.github.com/realdigid/008670d594bd3e6683b8

**Comment by SimeonC** [comment]
Unfortunately pasting HTML is very unforgiving, on several lines you wrote `title=State Account Plan"` instead of `title="State Account Plan"`. This caused the sanitiser to reject the HTML.

Try using something like: http://www.htmlhelp.com/cgi-bin/validate.cgi to check your syntax over large HTML code before pasting it in.
