### ISSUE TITLE
Sanitizer getting rid of direction:rtl for Style

### ISSUE THREAD

**Issue by jchatel** [fraywing/textAngular#520]
I have customer complaining he can't write Hebrew properly with the editor.

I told him he could just add style="direction:rtl" to the paragraph for now and I wanted to add a button for it but this get stripped out by the editor.

RightToLeft is not the same as Right Align unfortunately.

So I'm not sure if doing a button would even help. How can I prevent this from being stripped out?

**Comment by SimeonC** [comment]
You'll need to add it to the sanitizer. Relevant lines are here: https://github.com/fraywing/textAngular/blob/master/src/textAngular-sanitize.js#L507-L533.

That code is the main reason we have our own fork of AngularJS' sanitise module. You should just need to add an extra boolean expression to the statement.

I think all you need to do is add `(key === 'direction' && value.match(/^ltr|rtl|initial|inherit$/)`

**Comment by jchatel** [comment]
Awesome Simeon. Seems like I'll need to upgrade. I don't have those lines in my version of the sanitizer. Appreciate the great support of this lib. God job!

**Comment by SimeonC** [comment]
Just to add a note, #80 is the issue to watch for the sanitiser whitelist.

**Comment by jchatel** [comment]
Works like a charm. Thanks Simeon!

**Comment by SimeonC** [comment]
Awesome!
