### ISSUE TITLE
Conflict when using multiple <pre> tags that have the same class.

### ISSUE THREAD

**Issue by gitChang** [fraywing/textAngular#524]
My changes are not being applied when my html data has `pre` tags with same class. I am using Prism for my demo code.

for example, I have:
`<pre><code class="language-bash">sudo foo</code></pre>`

and on the next paragraph, same code class will be used:
`<pre><code class="language-bash">sudo bar</code></pre>`

after updating, the contents of `pre` tags are the same.
`<pre><code class="language-bash">sudo bar</code></pre>`

At first, I thought it was a typo but I am sure now.

**Comment by SimeonC** [comment]
Can you check you're on the latest version please? I believe I fixed this recently in patch 1.3.2. [Changelog](https://github.com/fraywing/textAngular/blob/v1.3.3/changelog.md#132-2015-01-27)

**Comment by gitChang** [comment]
Thanks Man.  I was using 1.3.0 version. It's working fine now with version 1.3.3.
