### ISSUE TITLE
ordered list items are not text-align: center only the text is

### ISSUE THREAD

**Issue by bastienJS** [fraywing/textAngular#525]
I use textAngular 1.3.3 and angular 1.3.11.

![textangularerror](https://cloud.githubusercontent.com/assets/5945955/5991783/5833a916-aa06-11e4-88e0-dff9ec8e7664.PNG)

I would have expected that the numbers 1. 2. and 3. are also centered with the text else the whole formatting makes no sense.

**Comment by SimeonC** [comment]
This is just the way HTML lists work as far as I know. If you can show me this being done how you say in some other WYSIWYG HTML editor (or just on an HTML page) I'll be happy to try replicate it but I can't seem to find a solution for this anywhere.
