### ISSUE TITLE
Wrong rangy-official path in both ./bower.json files

### ISSUE THREAD

**Issue by bastienJS** [fraywing/textAngular#526]
PLEASE DELETE THIS DUPLICATE! ;-)

I use textAngular 1.3.3

When I build my application the index.html gets added with bower_component entries by grunt-wiredep I guess:

<script src="bower_components/rangy-official/rangy-selectionsaverestore.js"></script>

But this path does not exist at all in the rangy bower component!

The bug probably comes from your wrong bower.json:

{
  "name": "textAngular",
  "version": "1.3.3",
  "main": [
    "./src/textAngular.js",
    "./src/textAngular-sanitize.js",
    "./src/textAngularSetup.js",
    "./src/textAngular.css",
    "../rangy-official/rangy-selectionsaverestore.js"
  ],

The rangy bower package does not have  this path /rangy-official/

Thats the problem :-)

**Comment by SimeonC** [comment]
Closing duplicate #527
