### ISSUE TITLE
No more dependency in your bower.json to bootstrap

### ISSUE THREAD

**Issue by bastienJS** [fraywing/textAngular#527]
from your bower.json file:

  "dependencies": {
    "angular": "^1.2.x",
    "bootstrap": "^3.0.x",
    "font-awesome": "^4.0.x",
    "rangy": "^1.2.0"
  },

Why is the depency to the whole bootstrap package?

That does not make sense to me. As angularjs and angular ui bootstrap user I do not need the jquery bootstrap plugins.

But still with your dependency setting you force me to or my bower package manager to always install bootstrap although I am fine using bower bootstrap-css-only which has everything for an angularjs user except the jquery plugins and I do really not assume that your textAngular depend in any way on jquery plugins right?

So I really would prefer if the bootstrap is removed and instead write bootstrap-css-only in the dependency list.

**Comment by SimeonC** [comment]
I didn't know their was a bootstrap-css-only package, I've just always installed bootstrap and ignored the extra jQuery stuff.

I'll look into it.

**Comment by bastienJS** [comment]
WOW what a quick response and good decision, bravo Simeon :+1:
