### ISSUE TITLE
IE8 issue: Unable to get property 'appendChild' of undefined or null reference

### ISSUE THREAD

**Issue by silversonicaxel** [fraywing/textAngular#530]
Hi,
in use  AngularJS v1.2.16 / textAngularjs Version 1.3.4

I found out this issue for IE8, 
```
SCRIPT5007: Unable to get property 'appendChild' of undefined or null reference
```
reported inside textAngular.min.js and this is blocking because my app cannot be used at all - not totally loaded.
Thanks.

**Comment by SimeonC** [comment]
Could you run the non-minified version and let me know where the error occurs please?
It would be a great help as I don't have access to an IE8 box and my debugging skills on IE are awful!!

**Comment by SimeonC** [comment]
Though I will add, this is Open Source software, if you really need it done ASAP you could help out by creating a PR following the [guidelines](https://github.com/fraywing/textAngular/blob/master/CONTRIBUTING.md).

**Comment by silversonicaxel** [comment]
In the unminifed version I've of the Version 1.3.4 the error comes out at line 126

```
// Add the <style> element to the page, add as first so the styles can be overridden by custom stylesheets
document.head.appendChild(style);
```

![textangular](https://cloud.githubusercontent.com/assets/6851815/6017112/def0862e-ab8a-11e4-89e8-c2f1f84d1dea.jpg)

thanks for the support

**Comment by SimeonC** [comment]
Huh, reason for error is here: http://stackoverflow.com/a/17100272/1413689.
Easy fix - in next patch!
