### ISSUE TITLE
best practice for server side storing

### ISSUE THREAD

**Issue by ericq** [fraywing/textAngular#532]
This is an awesome component. I have a question about the server side handling -- I didn't see any discussion about it. 
I don't want to add a "save" button so what the user typed in will be stored on the server side automatically. But I don't want to overburden the traffic to the server neither. So what's the best practice here? Thanks in advance.

**Comment by episodeyang** [comment]
this question lays beyond the scope of this repo, but here are my 2cents.

I think if you just trigger saving on keyup, and have a rolling time out of two seconds it would work.

Something like:

'''JavaScript
var timeoutHandel;
function onKeyup(){
       If (timeoutHandle) { 
             $timeout.cancel(timeoutHandle);
             timeoutHandle = null;
       }
       timeoutHandle = $timeout(function(){
              //....   Do your stuff here like save
              //.... Profit!
        }

'''

**Comment by SimeonC** [comment]
@episodeyang Is right in that it's not really a textAngular question.
His solution is also good though you may as well just use a $watch on the var as that triggers on relevant keyups anyway. I'd say the best way to do this with minimum code is to send to server on $watch and use the ngModelOptions, specifically the debounce option. https://docs.angularjs.org/api/ng/directive/ngModelOptions
