### ISSUE TITLE
ngModel variable isn't watched properly

### ISSUE THREAD

**Issue by Kuzmin** [fraywing/textAngular#537]
When changing the ngModel property with focus inside the editor, the text inside the editor does not change. I have an example in this youtube-video: https://www.youtube.com/watch?v=NYjknZaUPWM 

The issue is caused by this code below, together with two buttons that modify slide.content on-click:

          <pre>{{slide.content}}</pre>
          <text-angular ng-model="slide.content"></text-angular>

Great library, has been a lot of help! Are you accepting any kind of donations?

**Comment by SimeonC** [comment]
See #38 for discussion. Next patch for the features.

Accepting donations is a little tricky as I do all the work, but the project is owned by someone else. On the other hand I can accept contracts to implement features or help implement TA into applications.
