### ISSUE TITLE
IE8: Invalid argument.

### ISSUE THREAD

**Issue by DumboJet** [fraywing/textAngular#538]
When I click inside the editor in IE8, I get this error in textangular-rangy.min.js :

Invalid argument.
The debugger is stopped at:

     f.insertBefore(n,n.previousSibling),e.moveToElementText(n);

Here is what each of the variables are:

[+]		f	{...}	DispHTMLAnchorElement
[+]		n	{...}	DispHTMLSpanElement
[+]		e	{...}	IHTMLTxtRange
		o	"StartToStart"	String
[+]		a	{...}	IHTMLTxtRange
[+]		n.previousSibling	{...}	DispHTMLSpanElement

**Comment by SimeonC** [comment]
Hey, which release of textAngular are you using? I can't replicate this on textangular.com which is the latest release. Can you create a plunkr if you are on the latest release or it still occurs when you upgrade to it?

**Comment by DumboJet** [comment]
I have got the latest files from here (I hope I didn't miss anything).
However, I use an old version of Angular (v1.2.18).
I don't know if this is the root cause of the problem.

**Comment by DumboJet** [comment]
OK. I have an update:

I have downloaded the latest un-minified rangy for production (v.1.3) from here:
https://github.com/timdown/rangy/releases

...and I see it works in IE8.
So, perhaps it only happens in 1.2.3 version and under my specific version of angular???

**Comment by SimeonC** [comment]
Interesting, thanks for letting us know, it may just be a rangy 1.2.3 bug in IE<=8.

I'm waiting on an official release of 1.3.0, though technically the core is stable in the alpha releases, someone is bound to complain I'm using an alpha build.

**Comment by DumboJet** [comment]
I guess the version I got is an alpha too, although it says nothing on the ZIP file nor in the link that I've used. Initially I hoped it wasn't an alpha, but it seems it is...

**Comment by SimeonC** [comment]
Yea, all the 1.3 versions are pre-release, he's changed naming conventions 2-3 times since putting releases on github.
