### ISSUE TITLE
Unoredered list only

### ISSUE THREAD

**Issue by LeleDev** [fraywing/textAngular#539]
I need to create a textarea in which the user can only add and remove elements:
```
<li></li>
```
to a unordered list:
```
<ul></ul>
```
Is it possibile to achieve this behaviour with your library?

Thank you in advance

**Comment by SimeonC** [comment]
Yes this is possible, Though I might caution that this probably isn't the best approach or the simplest as you would probably be required to modify our text a lot. (You may be able to get away with just setting `ta-default-wrap="li"` but no promises).

I think your best approach is to use an ng-repeat with multiple inputs (you could use textAngular here with `ta-default-wrap=""`), then just add the individual HTML strings together into a list format using a for loop when you save/display the content.

**Comment by LeleDev** [comment]
Mmh `ta-default-wrap="li"` works except for one thing: how to make the all the `li` elements wrapped by `ul`?

**Comment by SimeonC** [comment]
I'd say the best way is to write a directive that add's a formatter and parser to the ng-model to wrap and unwrap the content with an `<ul>`.

**Comment by LeleDev** [comment]
Ok, thank you!
