### ISSUE TITLE
Custom Images/Links

### ISSUE THREAD

**Issue by Anonyfox** [fraywing/textAngular#54]
I am building a small CMS with textAngular as the _awesome_ WYSIWYG Editor, but so far I didn't figure out how to build a custom image chooser. This is the functionality i want to achieve: 
1. OnClick at the image-button, i want to open a bootstrap modal window, which contains a selection of available images already uploaded before (as thumbnails), click on one of them, and have it's url used for the inserted image tag.
2. I must be able to set a custom alt and title attribute for the image. 
3. Bonus: It would be nice to edit the image src, title and alt attributes when i select the  image inside the editor, and click on "image" again. 
4. Drag'n'Drop an image from elsewhere of the page into the editor should append the image tag in the editor.
5. Links should be selectable form a predefined list, too.
6. Links also need a title attribute. 

---

Is it possible to achieve all of this with textAngular?

**Comment by jeserkin** [comment]
@SimeonC why `taPaste` doesn't recognize drag'n'drop of images? Is there some separate solution for listening to drag'n'drop event?

**Comment by Chhote** [comment]
Hi, I want to insert image too may computer how can do this in textangular. I am not like to give a link for inserting images

**Comment by pbassut** [comment]
You can create a button that asks for a file. Have you tried that? 

Enviado do meu iPhone
