### ISSUE TITLE
Disable keyboard shortcuts?

### ISSUE THREAD

**Issue by LeleDev** [fraywing/textAngular#544]
How to disable keyboard shortcuts (all or individually)?

For example, when I don't show the bold button into the buttons bar, I'd like also to prevent user to enable it with CTRL+B...

Thank you in advance

**Comment by SimeonC** [comment]
Most shortcuts can be disabled simply by not showing them, the problems arise with bold/italics etc which have a default handler in the contenteditable; http://stackoverflow.com/questions/7207291/is-it-possible-to-disable-or-control-commands-in-contenteditable-elements

I'll put it down as something we can try look into in future.

**Comment by LeleDev** [comment]
I've also tried forbidding key combinations with onKeyDown, but in this case the user could still paste text containing bold, italic etc. from the clipboard

**Comment by SimeonC** [comment]
There are a few other issues around to do with the formatting on paste issue, out of curiosity; if you aren't using the formatting features of textAngular what is your use case? I'm going out on a limb here but it sounds like textAngular might not be your best option here (I can be wrong, just asking).

**Comment by LeleDev** [comment]
I'm using textAngular to make a `<li></li>` only textarea

**Comment by LeleDev** [comment]
Maybe we could get some hints from this? https://stackoverflow.com/questions/6022551/pasting-into-contentedittable-results-in-random-tag-insertion

It seems that with an hack we could intercept and process the pasted content, but only if pasted from keyboard... right?

**Comment by SimeonC** [comment]
Welcome to our paste code: https://github.com/fraywing/textAngular/blob/master/lib/taBind.js#L258-L441

You can always intercept the pasted content via `ta-paste="interceptor($html)"` attribute.

**Comment by LeleDev** [comment]
That's wonderful, thank you!

I didnt't find it in the docs

**Comment by JoelParke** [comment]
see the taOptions.keyMappings[] and the docs for how to easily do this.
