### ISSUE TITLE
Toggling to 'HTML view' gets rid of text not in tags (1.3.0)

### ISSUE THREAD

**Issue by Reklino** [fraywing/textAngular#546]
When toggling to html view, if there is some text inside of tags, and some not in any tags, the text not in tags will be deleted.

Example:
```html
<h3>wooop</h3> this text will be deleted, but the h3 tags and content will not...
```
If you toggle back from html mode before making any changes, then the text will be intact.

This issue doesn't seem to exist in 1.2.

**Comment by SimeonC** [comment]
Thanks for pointing this out, can you confirm this happens with the latest patch, 1.3.7, please?

I thought I'd fixed this at one point but I may have only got one of several edge cases.

**Comment by Reklino** [comment]
I can't recreate the issue in 1.3.7. It seems to be fixed :)
