### ISSUE TITLE
Should allow for external changes to the binded model even when editor is focused

### ISSUE THREAD

**Issue by lostip** [fraywing/textAngular#547]
First I will explain the use case, then the problem.

## Use case:
Imagine we try to build a ToDo list like this one: http://todomvc.com/examples/angularjs/
But instead of a regular text input for typing the new items, we want that to be a textAngular editor.

So the behaviour we want is: you have the rich editor were you type/edit your html, then when you hit enter, that text is added as an item to the list, and the editor is cleared, so a new item can be typed.

## Problem:

The editor asumes that when the editor is focused, any changes to the model should be ignored:
```javascript
ngModel.$render = function(){
	// catch model being null or undefined
	var val = ngModel.$viewValue || '';
				
	// if the editor isn't focused it needs to be updated, otherwise it's receiving user input
```

## Demo:

http://plnkr.co/edit/8oW2xBoCtpnJu9ioZU5X?p=preview

## Workaround:

Whenever we need to update the model, instead of just assigning a value

```javascript
$scope.model = "this will not work";
```

we need to first loose focus:

```javascript
//var element is the contenteditable element
element[0].blur();
$timeout(function(){
  	$scope.model = "this will work";
  	element[0].focus();
 }, 1);
```

I understand this is not the most common scenario, but I think it is a valid use case, so it would be great if this behaviour could be at least configurable.

Thanks!

**Comment by SimeonC** [comment]
It does actually allow it, it's just that you weren't quite killing the keyup event before textAngular gets it, in that case we prevent the update.

I edited your plunkr so it works: http://plnkr.co/edit/tTygm1W53Mvki9QRR8ZQ?p=preview
Though you probably can get away without the additional directive with this approach.

**Comment by lostip** [comment]
Oh, my apologies, I forgot about textEditorSetup... I guess this allows my handler to be registered prior to textAngular handlers, which like you said effectively prevents the key event to reach textangular...
Thanks!

**Comment by lostip** [comment]
Hi again!

So, I just run into this again, and realised the main issue is still there. 
In your updated plunkr, although the external binded model is indeed updated, the text editor view model is not:

1. Type something, i.e. "Test"
2. Hit enter

Then you get:

![view](https://cloud.githubusercontent.com/assets/572961/6469522/03bf26da-c1bc-11e4-898a-a663545cb543.png)

**Comment by SimeonC** [comment]
Your right, it seems that sometimes it works and sometimes it doesn't. I'll look into it when I can.

**Comment by SimeonC** [comment]
OK, this should be fixed in master now. As an added bonus if you want buttons outside of textAngular's toolbar to update textAngular without loosing focus - add the ta-button directive attribute to the button.
