### ISSUE TITLE
New line character is ignored in the html editor

### ISSUE THREAD

**Issue by klaszlo** [fraywing/textAngular#550]
I have a html snippet defined as:
`var snippet = '<div >\n ' +`
`      '<ul >\n ' +`
`        '<li >Home</li>\n ' +`
`      '</ul>\n ' +`
`      '</div>';`

When I pass it to textangular, all the newline characters (\n) gots ignored, and the html source is one line.
It is really hard to edit this way. 
I initiate the editor like this:
`<div text-angular ng-model="snippet"></div>`

I'm using textangular 1.3.4.

Any idea how to prevent this?

**Comment by SimeonC** [comment]
I assume you're trying to edit this not using the html editor that's part of textAngular? Basically the sanitiser removes all of them.

If that's the case, change your textarea to have the `ta-bind` attribute. As of 1.3.0 textAngular will auto add in newlines and tabs to the HTML view of textAngular.

**Comment by klaszlo** [comment]
@SimeonC thank you very much for the quick reply.

I'm feeding textangular from a database (mongodb -> expressjs -> angularjs -> textangular) with html snippets. Some of the html snippets are complicated enough (has class attributes), that 
textangular wysiwyg editor not the best tool to edit it, so I switch to textangular builtin html source editor.

And I noticed, that the html source is a oneliner.
I'm editing for example a webpage menu (`<ul><li class="dropdown">...`), but if textangular converts the html source to a oneliner, it is next to impossible to edit it.

After I finished editing, it is saved back to the database.
Right now, it saves back without any newlines (\n), as textangular just strips the newline characters.

I believe textangular may have a builtin sanitizer which gets rid off all the non-wanted characters.
I read the source a little, but could not spot the right space yet. 
I'll dive a bit more tomorrow. 

Thank you for your attention.

**Comment by SimeonC** [comment]
That sounds very much like you're somehow using an old source version - 1.3.0-preX or before (somehow). If you have a look at http://textAngular.com the actual content is newline stripped but the html editor has tabs and newline characters put in.

Part of the problem is that when we use a fork of ngSanitize, which does remove all whitespace (/t, /n etc). But as I said this shouldn't be an issue anymore as I added in code to auto add in the newlines and tabs to make the html readable.

If possible could you run up a plnkr example (Fork this: http://plnkr.co/edit/8G84wkJVjabOvCl1DryF maybe) and I can see if I can spot the problem?

**Comment by klaszlo** [comment]
@SimeonC: After fixing your plunker demo 
(missing bootstrap.js, and no ng-controller in html, so the "content" variable was not assigned), 
here is a demo showing the problem:
http://plnkr.co/edit/065DxQQKRQU2p990HDsf

Just start the plunker, click inside the textarea, hit on the Toggle html button, and you see, that the source is a oneliner.
I hope it helps tracking this bug down.

Let me know, if I can assist to you anything more.

**Comment by SimeonC** [comment]
Ah, ok. Thanks that is a bug. I didn't account for nesting like that, it's more simplistic - if you remove the div wrapping it it works, sort of.

**Comment by JoelParke** [comment]
<p>I believe that this is now corrected with my PR #1356</p><p>Please test and re-open if this is still an issue. <br/>Thanks and sorry this took so long to fix!</p>
