### ISSUE TITLE
Site css applying to Wysiwyg

### ISSUE THREAD

**Issue by bnnadi** [fraywing/textAngular#551]
Not sure if this has been address, but I have noticed that when you apply class name to html tags if they are the same as your site/application style the Wysiwyg allows them to be applied, is there a way to stop this?

**Comment by SimeonC** [comment]
That's part of the way that textAngular works. What you are editing is html in a contenteditable so to prevent this you'll have to manually override the css. For example, if your `<p>` tags have blue color but in the editor you want it to be black, you'd do this:
```css
.ta-bind.ta-editor p {
    color: black;
}
```
