### ISSUE TITLE
Paste of text with more formatting/style than allowed in the toolbar

### ISSUE THREAD

**Issue by marcaurele** [fraywing/textAngular#552]
If I paste from Word a text containing some underlined words, and I didn't put the 'underline' button on the toolbar, the tags get pasted. Thus allowing people to paste formatted text with tags that I didn't allow. Would it be possible to strip tags not represented by the buttons on the toolbar? (It should work with custom buttons, for example to have a <strong> instead of <b>, or the red style documented in the wiki)

* angular 1.2.28
* textAngular 1.3.6

**Comment by SimeonC** [comment]
You could use the ta-paste (`ta-paste="modifyHtml($html)"` - result of expression is what the pasted content is) to try do this, but parsing out certain tags is a bit beyond our current capabilities, this could be possible in some form when we can dynamically modify the sanitizer list, but I'm not sure when that will happen.
