### ISSUE TITLE
textAngular creates divs instead of p tags after an ordered list

### ISSUE THREAD

**Issue by ee0pdt** [fraywing/textAngular#555]
Frustratingly I can't replicate this on the home page, but with version 1.3.6 on Chrome I get this issue:

**Steps to replicate:**

1. Type a sentence
2. Press return
3. Click ordered list button
4. Type a sentence
5. Press enter
6. Press return
7. Press return
8. Type a sentence

**Expected output:**
```
<p>Sentence One</p>
<ol><li>Sentence Two</li></ol>
<p>Sentence Three</p>
```

**Actual Output:**
```
<p>Sentence One</p>
<ol><li>Sentence Two</li></ol>
<div><span>Sentence Three<span></div>
```

**Comment by SimeonC** [comment]
That is odd, I can't replicate that on my end either. Maybe a side effect of the fix in 1.3.7 fixed this? (Also do update to 1.3.7, it fixes a rather large XSS hole in textAngular).

**Comment by ee0pdt** [comment]
I'll try that, thanks

**Comment by SimeonC** [comment]
Reopen if this is not fixed.
