### ISSUE TITLE
Undo/redo not working propperly

### ISSUE THREAD

**Issue by Hubrus** [fraywing/textAngular#558]
Undo and redo will work just fine as long as you don't click undo multiple times than actual modifications. If you make one modification, click undo twice and then redo, no modification will be  redone: http://screencast.com/t/TBwtLE0GG

**Comment by SimeonC** [comment]
Thanks for letting us know - that's an odd one.

**Comment by GIT090042178** [comment]
I have commented below lines and it is working. below function
                  var _inputTimeout;
                    element.on('input', function() {
                         .
                         .
                         .
                         .

                           **//var _savedSelection = rangy.saveSelection();** 
                           **//rangy.restoreSelection(_savedSelection);**
