### ISSUE TITLE
Centering a list item behaves different in Chrome & Firefox

### ISSUE THREAD

**Issue by Hubrus** [fraywing/textAngular#560]
In Chrome the li item is centered, but in Firefox, the entire ol element is wrapped in a div that is centered.

http://screencast.com/t/joFArrbpB

**Comment by SimeonC** [comment]
Thanks for reporting this, `execCommand` is just so flaky :(

**Comment by JoelParke** [comment]
<p>This is now more consistent, but there are still some strange artifacts.... to be improved...</p>

**Comment by JoelParke** [comment]
<p>Firefox and Chrome now behave the same --- so closing this issue.</p><p><br/></p>
