### ISSUE TITLE
Deffered button action is not performed when editor loses focus

### ISSUE THREAD

**Issue by shershen08** [fraywing/textAngular#561]
I did as it's stated in https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar 
Via deferred first param in **action** method:
```javascript
action: [function(deferred, restoreSelection)]
```
this is how my **taRegisterTool** looks like:
```javascript
//
 action: function(deffer){
                        $rootScope.$emit('openAdvancedImageDialog', deffer);
                       var thatLink = this;

                       deffer.promise.then(function(imageLink){
                            thatLink.$editor().wrapSelection('insertImage', imageLink, true);
                        });

                        return false;

                    },
//
```
then in controller I have, see comments

```javascript
$rootScope.$on('openAdvancedImageDialog', function(event, def){

            $rootScope.deferred = def;
            $scope.openImageDialog(def); 
//this shows image selection dialog, where you have to click on one of them
//as soon as you click, nothing is entered in textarea even when deferred is resolved
            
            $timeout(function() {
                $rootScope.deferred.resolve('this-is-fake-image-url');
            }, 5000);
//this is an example that works is you you don't click anywhere after opening dialog
//but fails if you click just anywhere on the page
           
        })
```

**Comment by SimeonC** [comment]
Basically the dialog will steal the focus and selection. Change your action to this:
```js
action: function(deffer, restoreSelection){
                        $rootScope.$emit('openAdvancedImageDialog', deffer);
                       var thatLink = this;

                       deffer.promise.then(function(imageLink){
                            restoreSelection();
                            thatLink.$editor().wrapSelection('insertImage', imageLink, true);
                        });

                        return false;

                    },
```

There seems to be a fair bit of confusion about this step so I may see if I can get this to be done automatically in future.

**Comment by shershen08** [comment]
Thank for the answer, I've tried this but that doesn't help
I have tried both following rangy files to load, with no result:

```html
<!-- standalone rangy-->
  <script src='js/rangy-core.js'></script>
  <script src='js/rangy-selectionsaverestore.js'></script>
<script src='js/textAngularSetup.js'></script> 
<script src='js/textAngular.js'></script>

<!-- or textAngular rangy-->
<script src='js/textAngular-rangy.min.js'></script>
<script src='js/textAngular-sanitize.min.js'></script>
<script src='js/textAngularSetup.js'></script> 
<script src='js/textAngular.js'></script>
```

**Comment by SimeonC** [comment]
I dunno, that's the way we've got it to work before hand, could you run up a plunkr demonstrating it?

**Comment by shershen08** [comment]
Here it is: http://plnkr.co/edit/31VqDL?p=preview
There's only one button in editor - that's insert image, that calls ngDialog with image selection.
There's also a timeout that will fire in 5 sec and insert 'fake-image-url.jpg' into editor ONLY if you don't click anywhere

**Comment by SimeonC** [comment]
Hmm, looks like plunkr isn't playing nice ATM, one possible solution may be to refocus the editor before restoring selection - but I can't confirm that will work atm.

**Comment by shershen08** [comment]
Yes, exactly, it worked if you put focus before resolving
```javascript
//put focus 
jQuery('div[contenteditable="true"]')[0].focus();
//resolve promise
my_defferedImageDialog_promise.resolve(my_data);
```

**Comment by SimeonC** [comment]
Thanks for confirming that this fixed it, TA should do this itself in the `restoreSelection()` so I'll mark it as a bug so it works as expected.

**Comment by figalex** [comment]
I was having the same issue. After digging a little bit I found out that the deferred object that it is passed on the ```action``` function has [this](https://github.com/fraywing/textAngular/blob/master/src/textAngular.js#L416) as the ```finally``` function of the promise and this is causing that the ```_savedSelection``` variable gets a ```false``` value and that's why ```restoreSelection()``` is not working when it's called  inside the promise resolve function.

**Comment by shershen08** [comment]
@figalex so is there a solution based on that notice?
because what i've mentioned that with putting focus artificially, https://github.com/fraywing/textAngular/issues/561#issuecomment-78021679
the text position - where *exactly* to put image is lost

**Comment by figalex** [comment]
Apparently it seems that angular promises execute ```.finally``` and ```.then``` callbacks in the order they are set, and because  ```.finally``` was set before any ```.then``` set inside the toolbar action callback the ```.finally``` callback was executed first and this removed the ```_savedSelection``` before the ```.then``` callback be called. I made a fix that is working for me and submitted it.

**Comment by SimeonC** [comment]
I've merged in the PR - @shershen08 can you confirm that that fix fixed your issue as well please? If it does close the issue.
