### ISSUE TITLE
contentEditable issue with IE9

### ISSUE THREAD

**Issue by godo13405** [fraywing/textAngular#563]
I'm using this plugin in a webapp that must work in IE9.

For some reason, I keep getting these drag handles around the <p> elements, and can't get rid of them.

Texting textangular.com, it doesn't happen on that page.

![capture](https://cloud.githubusercontent.com/assets/955048/6504910/3a9fe33c-c334-11e4-8859-138ec370060a.PNG)

can anyone please help me figure this out?

**Comment by magmel48** [comment]
@godo13405 Sometimes it happens if you have css rules, linked with content width and/or positioning content (paragraphs in example) inside contenteditable. Hope it helps.

**Comment by godo13405** [comment]
@magmel48 I don't have any rules dealing with sizing or positioning of the content there

**Comment by SimeonC** [comment]
I'm not familiar with the IE issues, but the source of textangular.com is available here: https://github.com/fraywing/textAngular/tree/gh-pages. Possibly you can figure out what's different from there.

**Comment by godo13405** [comment]
Turns out there was a min-height buried somewhere deep in the css that I couldn't see from IE9's dev tools.

Thanks anyway guys
