### ISSUE TITLE
Focusable elements inside a popover

### ISSUE THREAD

**Issue by rbistolfi** [fraywing/textAngular#564]
Our application requires that users can add entries to a dictionary from the editor. We implemented this with a new tool which interprets the selection as the term to be defined, and opens a popover with a textarea for the user to enter its definition. However, the textarea cant get focus on click. I think line 1838 in textArea.js currently prevents this textarea from grabing focus. We would also like to show the popover when the tool is activated, is it possible to do this in the context of the action function (because our popover is launched from onElementSelect, users are forced to click on the term to see the popover, and we would like it to show up after clicking in the button)?
Any suggestions are welcome. Thanks in advance.

**Comment by SimeonC** [comment]
We don't have a textArea.js? I'm not sure what you're referring to in regards to that - possibly this https://github.com/fraywing/textAngular/blob/master/lib/main.js#L178-L184. In that case see #297, which is the same issue.

You can trigger the popover by using `this.$editor.showPopover(_targetElement)` in the action function, using taSelection.getSelection() to get the current cursor position. Though make sure you rebuild the popover contents before hand.
