### ISSUE TITLE
Disabled some buttons

### ISSUE THREAD

**Issue by sardoj** [fraywing/textAngular#565]
Hi! Is it possible to disabled some buttons? 
For example, I don't want to display Hn buttons.
A solution?

**Comment by SimeonC** [comment]
See the wiki https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar#defining-the-toolbar Also can override this from textAngularSetup: https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L13-L17
