### ISSUE TITLE
Unable to edit html content without surrounding tags

### ISSUE THREAD

**Issue by slakin** [fraywing/textAngular#566]
In versions 1.3+ we don't able to edit html which doesn't have any surrounding tags. It was possible in version 1.2.2 (textAngular/demo/demo.html). It's big problem for me.

When we setup plain text as initial value for TA and press Toogle to HTML then textarea is empty.
We also have problem when initial text already has some html inside then in HTML mode shown only text surrounded by tag.

[Plunker with plain text](http://plnkr.co/edit/OinGMr7x4Cof9LsRRQTA?p=preview)
[Plunker with html inside plain text](http://plnkr.co/edit/LXZXBw4eX1eaiOBdnBht?p=preview)

**Comment by SimeonC** [comment]
I see, thanks for pointing this out. I'll add a check when I can.

**Comment by SimeonC** [comment]
Fixed in v1.3.9. Issue was that the HTML formatter was breaking - also this should have been auto wrapping into html so it does that now.

**Comment by kpomka** [comment]
Issue fixed partially. Following would fail

it('handles no tags (should wrap all content)', function(){
	$rootScope.html = '<b>Test</b> Line 1';
	$rootScope.$digest();
	expect(element.val()).toBe('<p><b>Test</b> Line 1</p>');
});
