### ISSUE TITLE
should not use ruleIndex

### ISSUE THREAD

**Issue by kaiqigong** [fraywing/textAngular#568]
If there are several textAngulars in one page, when destroying, it will say:  
```Error: Failed to execute 'removeRule' on 'CSSStyleSheet': The index provided (1) is larger than the maximum index```  
It happens because when we use ```sheet.removeRule(index)```, the rest indexes of sheet.cssRules change. We should use ```sheet.removeRule(rule)``` instead.  
I will send a pull request later.

**Comment by SimeonC** [comment]
Fixed in v1.3.10
