### ISSUE TITLE
How to set tool options?

### ISSUE THREAD

**Issue by geoidesic** [fraywing/textAngular#573]
I can't see this anywhere in the documentation. I found textAngularManager and I've injected it into my controller successfully... but I can't figure out what to do with it. What method should I call and what to pass to it?

The old version of textAngular you could just add a $rootScope.textAngularOpts object definition.

**Comment by geoidesic** [comment]
Figured it out. Instead of injecting textAngularManager, inject taOptions. Then set taOptions.toolbar to an array of arrays as per the old textAngularOpts.

**Comment by SimeonC** [comment]
Yup, you can also use the `ta-toolbar` attribute to change this instance by instance.

**Comment by SimeonC** [comment]
Yup, you can also use the `ta-toolbar` attribute to change this instance by instance.

**Comment by SimeonC** [comment]
Yup, you can also use the `ta-toolbar` attribute to change this instance by instance.

**Comment by SimeonC** [comment]
Sorry about the multi-post - something's not working on github for me this morning.
