### ISSUE TITLE
Bold not working

### ISSUE THREAD

**Issue by magdkudama** [fraywing/textAngular#581]
Hello,

I'm having a problem with textAngular. The editor gets displayed and everything seems ok. When I click the bold button, the text gets bold (obviously), but if I click it again, it just adds a new ```<b>``` tag.

That's not the behaviour with, for example, the italic...

I can see inside the button the "active" class is never shown, as opposed to when I click the italic:

```<button type="button" class="button-description ng-scope" name="bold" unselectable="on" ng-disabled="isDisabled()" tabindex="-1" ng-click="executeAction()" ng-class="displayActiveToolClass(active)" title="Bold"><i class="fa fa-bold"></i></button>```

This is the HTML I'm using:

```<text-angular ta-toolbar-button-class="button-description" ng-model="design.description" ta-toolbar='[["bold", "italics"], ["ul","ol"],["insertLink"], ["undo", "redo"], ["wordcount", "charcount"]]' id="description-box"></text-angular>```

Not sure what can be failing here. I'm using latest version of the plugin

**Comment by SimeonC** [comment]
Hi, I'm not sure what is going on there and I can't replicate it my end.

Can you provide a plunkr demonstrating the issue and which browser(s) your seeing this on please?

**Comment by magdkudama** [comment]
Hello,

On a fresh installation, it works also for me :cry:. But in my application it's just the bold that doesn't work...

Tried removing absolutely everything from the controller code and the view, just the TextAngular box there, and still failing, need to debug it and see what's going on...

I'm using browserify and angular-route, if that makes a difference. I don't think it does, as italic, underline... just work perfect :weary:.

I'll have a closer look.

**Comment by brianbroken** [comment]
I had the same issue with the bold button however this was because I was using custom css with no font weight for b tag, I only had <strong> tag specified. The following fixed it: 

b, strong {
    font-weight: 700;
}

**Comment by wlinkin** [comment]
@brianbroken I just had the same issue and solved the same way. Specifically, the font-weight must be greater or equal to a value of 600, "bold" or "bolder". In our case for our "b" and "strong" elements, we were using a bold version of web font with the font-weight set to normal.

I added this to the textAngular.css file to fix:

.ta-editor{
  b, strong{font-family: inherit; font-weight: bold}
}

**Comment by VaibhavP17** [comment]
Even I had the same problem but works fine with the above solutions.

**Comment by yayromina** [comment]
We are experiencing this issue with a fresh install of textAngular: attempting to unbold text creates multiple `<b>` tags instead of removing them. It's not a font weight issue because it appears as expected.. it's the creation of `<b>` elements rather than removing them that is our issue
