### ISSUE TITLE
ng-model-options debounce time double?

### ISSUE THREAD

**Issue by printztxikia** [fraywing/textAngular#582]
Hi there,
I think there is a bug when using textAngular in conjunction with ng-model-options directive (angularjs >=1.3.*).
It seems that the debounce time kind of doubles. I have modified your plunker to show it (note how it is set for 2 seconds, but when any data is entered, it isn't updated for 4 seconds).
http://plnkr.co/QkKYLlFuFtrvhjptuGA1

Let me know if my description of the problem isn't clear enough (or if I'm doing something silly ;)
Thanks!

**Comment by SimeonC** [comment]
It looks like something's broke in your plunkr as I can't open it up at all, can you check it's still working for you please?

**Comment by printztxikia** [comment]
Hi Simeon,

It seems there is a problem in Plunkr itself right now, as I can't even
access their main website. I'll try in the morning (in about 6h) and double
check that all still works. I'll send you an email when I've done it.

On Thu, Mar 19, 2015 at 12:21 AM, Simeon Cheeseman <notifications@github.com

**Comment by printztxikia** [comment]
Hey,
All seems ok for me now (in the morning I couldn't even login, it was
timing out for some reason). Could you try again?
http://embed.plnkr.co/QkKYLlFuFtrvhjptuGA1/preview

If it doesn't work, this is what I have:
<!DOCTYPE html>
<html>

  <head>
    <link data-require="bootstrap-css@3.1.1" data-semver="3.1.1"
rel="stylesheet" href="//
netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
    <link data-require="font-awesome@*" data-semver="4.3.0"
rel="stylesheet" href="//
maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
    <link data-require="bootstrap@*" data-semver="3.3.2" rel="stylesheet"
href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//
cdn.jsdelivr.net/angular.textangular/1.3.7/textAngular.css" />
    <script data-require="bootstrap@*" data-semver="3.3.2" src="//
maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script data-require="angular.js@1.3.*" data-semver="1.3.15" src="
https://code.angularjs.org/1.3.15/angular.js"></script>
    <script data-require="jquery@2.1.3" data-semver="2.1.3" src="
http://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="
http://cdn.jsdelivr.net/g/angular.textangular@1.3.7(textAngular-rangy.min.js+textAngular-sanitize.min.js+textAngular.min.js)
"></script>
    <script src="script.js"></script>
  </head>

  <body ng-app="testApp">
    <div text-angular="" ng-model="content" ng-model-options="{ updateOn:
'default blur', debounce: {'default': 2000, 'blur': 0} }"></div>

    {{content}}
  </body>

</html>

**Comment by SimeonC** [comment]
I can see that now, must have been a plunkr issue. That looks like it's going to be a real pain to debug...

**Comment by SimeonC** [comment]
In master we now make use of the ngModelOptions, though the debounce will now be only supporting a number and is the keyup debounce setting. It should work correctly now. Blur shouldn't have a debounce at all now. We may do full ngModelOptions in future but not at the present.
