### ISSUE TITLE
tool action function encounters an asynchronous call 

### ISSUE THREAD

**Issue by ericq** [fraywing/textAngular#583]
Hi, 
I tried to replace the insertImage tool button. The modalWindow I used will return a URL back. I found myself in a dead end because I'm invoking an asynchronous call (promise.then) from a synchronous method. 

I have my action function like the following: 

action: function(){

                    var imgLink = null;

                    // open the modal window here
                   
                    var modalInstance = $modal.open({
                        templateUrl: 'views/dts/insertImgModalElement.html',
                        controller: 'InsertImgModalCtrl',
                        size: 'lg',
                        resolve: {
                            items: function () {
                                return items;
                            }
                        }
                    });

                    modalInstance.result.then(function (selectedItem) {
                        $log.info('selectedItem: ' + selectedItem);

                        imgLink = selectedItem;

                    }, function () {
                        $log.info('Modal dismissed at: ' + new Date());

                        imgLink = 'N';

                    });

  // what do do here??? how to return the imgLink back? it's still empty at this time because it gets populated via the above asynchronies call

}

**Comment by SimeonC** [comment]
Try the docs or a search next time please. From our wiki [Here](https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar#creating-and-editing-tools).

**action:** `[function(deferred, restoreSelection)]` a function that is executed on clicking on the button - this will allways be executed using ng-click and will overwrite any ng-click value in the display attribute. The function is passed a deferred object (`$q.defer()`), **if this is wanted to be used `return false;` from the action and manually call `deferred.resolve();` elsewhere to notify the editor that the action has finished.** restoreSelection is only defined if the rangy library is included and it can be called as `restoreSelection()` to restore the users selection in the WYSIWYG editor.
