### ISSUE TITLE
Toggle html does not show all available html

### ISSUE THREAD

**Issue by kpomka** [fraywing/textAngular#584]
#566 has been fixed partially. Test-case:
```javascript
it('handles no tags (should wrap all content)', function(){
	$rootScope.html = '<b>Test</b> Line 1';
	$rootScope.$digest();
	expect(element.val()).toBe('<p><b>Test</b> Line 1</p>');
});
```

**Comment by SimeonC** [comment]
That's the correct functionality. From memory the reason is that the contenteditable does some really, really weird stuff/throws errors if you don't have some tag wrapping the content.

**Comment by kpomka** [comment]
What i mean if example provided when you toggle to html mode you will see only "<b>Test</b>" there. It will not show you the rest "Line 1"

**Comment by kpomka** [comment]
Any updates on this issue? It should be minor, just wrap content with default wrapper.

**Comment by SimeonC** [comment]
Thanks for the test, It should be fixed in Master now and will be in next release.

**Comment by kpomka** [comment]
Great job, thanks!
