### ISSUE TITLE
The line spacing is inconsistent 

### ISSUE THREAD

**Issue by chetandevradius** [fraywing/textAngular#586]
The html formatting gets messed up after doing some changes:
For example -
 1)Type a word for example "header", select it and and make it H1.
2)Press the return key to come to next line.
3)Now type a word for example "para".
4)Now take the cursor to the beginning of the second word "para" and press backspace/delete.
5)Now both the words are in same line ,now press enter/return , you will see that the word "para" comes to next line but with greater line spacing between the words and the cursor is still the size of H1 tag.

Is there something i am doing in a wrong way and is there a way to bypass this behaviour .
Thanks

**Comment by SimeonC** [comment]
I think this is on chrome correct? If that's the case it's cause chrome does some really stupid things - I'll see if I can loosen up the checker for detecting this king of stuffs.

**Comment by SimeonC** [comment]
On checking this through, I don't think there's anything I can immediately fix about this - If you look at/display what's in the model though you'll see that the header appears fine.

**Comment by JoelParke** [comment]
<p>I believe this is now fixed and closing this issue.  Please reopen if still an issue.</p>
