### ISSUE TITLE
How disable drop file event

### ISSUE THREAD

**Issue by tstodorov** [fraywing/textAngular#587]
How to override the default method defaultFileDropHandler() in order to disable dropping files onto the textangular's toolbar/textarea? Currently I'm trying doing that using the ta-file-drop plugin attribute.Thanks!

**Comment by SimeonC** [comment]
You should be able to do this by overriding the defaultTaFileDrop function or the ta-file-drop function as:

```js
function(file, insertAction){
	return true;
}
```

I think that should prevent any kind of drag/drop handling.

**Comment by sbedulin** [comment]
To disable globally:
```javascript
angular.module('app').config(function($provide) {
    $provide.decorator('taOptions', ['$delegate', function(taOptions) {
        taOptions.defaultFileDropHandler = function(file, insertAction) {};

        return taOptions;
    }]);
});
```

**Comment by gbittmann** [comment]
Is there a way to add your own file drop handler globally and still use the default as a fallback by returning false?
