### ISSUE TITLE
Text angular-editableFix input visible on IPad 2

### ISSUE THREAD

**Issue by Ardenexal** [fraywing/textAngular#588]
When we were testing our application we found a bug with the ipad 2 model MC773X/A running 8.1.3 for some reason the editable fix input that is attached to the body is visible and clickable. I have temporarily fixed it with display:none; but it would be nice to know what is causing the issue. I am using bootstrap 3 which it adding a display: inline-block so that might be the issue but its odd that its doing it on just this device and none of the others we tested

**Comment by SimeonC** [comment]
Interesting, normally in v1.3.x this is due to the stylesheet for textAngular not being loaded. But if it's only occurring on that one device then I have no idea what the reason could be. If you do figure it out let us know and we'll patch it.

**Comment by Ardenexal** [comment]
ah figured it out it was a caching issue. Apparently the app hadn't downloaded a new version of the css file and was still using an old one where text angular's css file wasn't included sorry about that
