### ISSUE TITLE
Doesn't work in any version of IE (including IE 10)

### ISSUE THREAD

**Issue by briangullo** [fraywing/textAngular#590]
Hello, I'm using the following mark up

&lt;div text-angular ng-model="[my scope property]"&gt;
                                        
&lt;/div&gt;

It allows me to type in some text, then select one option, such as bold, then every other button I press it errors with:

TypeError: Object doesn't support property or method 'saveSelection'
   {
      [functions]: ,
      description: "Object doesn't support property or method 'saveSelection'",
      message: "Object doesn't support property or method 'saveSelection'",
      name: "TypeError",
      number: -2146827850
   }

It works in FF and Chrome, but the results are the same in every version of IE i try it in.

Thanks,
Brian

**Comment by briangullo** [comment]
I did some more testing.

it turns out, if I only use keyboard shortcuts such as ctrl-b to bold (or any other keyboard short cut) it works fine.  It is when is use the mouse to select text, then click the "Bold" button that it gives the error as mentioned above.

**Comment by SimeonC** [comment]
That sounds odd, which version of textAngular are you using?

**Comment by briangullo** [comment]
This is what the source files say:
textAngular-rangy.min.js - v1.2.3
textAngular-sanitize.min.js - v1.3.1
textAngular.min.js - v1.3.8, v1.3.7 (textAngularSetup) 

Is the version I'm using.  I'm guessing it doesn't do the same for you?

Thanks!
Brian

**Comment by SimeonC** [comment]
Yea, I can't get it to occur in IE11 or IE10. Maybe try update to the v1.3.11 and try again? If that doesn't work I'll need to see it in a plunkr or something similar. I can't think of any reason why it only breaks in IE.

**Comment by briangullo** [comment]
Ok cool, I'll trying the most updated version as you recommended, I'll also try the unminified version as well, not that it should make any difference, but you never know.

I'll test and let you know what happened.  Thanks for responding!
B

**Comment by briangullo** [comment]
Ok, so this ended up being a mistake on my behalf.  

I was accidentally including the script twice, once statically on the page, and once being dynamically resolved.  

I suppose, Chrome and Firefox can handle the conflict of the same library being loaded twice, where IE would choke. 

Once i removed the erroneous second reference, it started working fine in all the browsers.

Thanks for being responsive.

B

**Comment by ahdorneles** [comment]
Brigangullo... I'm trying to solve an issue that is the same of yours, but I have never worked with text Angular, nor angular.

Can you tell me what is the files that you have edit (the static and dynamical script)?

Thanks you!

**Comment by briangullo** [comment]
@ahdorneles , can you tell me a bit more about your site.  In my situation I was using using a purchased templated site, a mix between asp.net mvc and angular js.
