### ISSUE TITLE
Image resize broken

### ISSUE THREAD

**Issue by chr22** [fraywing/textAngular#592]
You cant resize images in Chrome in the newest release (1.3.11). It works in version 1.3.10.

Here is a CodePen that shows the problem, if you inset an image and try to resize it.
http://codepen.io/chr22/pen/qEgqEE?editors=110

**Comment by SimeonC** [comment]
Ok, that should be relatively easy to fix, looks like a misnamed variable somewhere which is odd that the tests didn't pick that up.

**Comment by oosidat** [comment]
A possible fix might be to try and revert commit a84f6df4177b2315ebbc4f701e5b2bf8a1d8d873 - or improve upon it

https://docs.angularjs.org/api/ng/function/angular.element

> `css()` - Only retrieves inline-styles, does not call getComputedStyle(). As a setter, does not convert numbers to strings or append 'px'.

**Comment by pbassut** [comment]
@oosidat Thanks for pointing that out. @nickknissen is fixing ATM.
