### ISSUE TITLE
Popover image resize error

### ISSUE THREAD

**Issue by chr22** [fraywing/textAngular#593]
If you resize an image before using the popover buttons on an image, then the image is only resized in one direction and is therefore streched.

After using the popover buttons to resize, then the normal resize breakes.

Both bugs is in all the major browsers.

This is in version 1.3.10 because it isn't possible to resize in 1.3.11

Here is a CodePen that presents the bug (v. 1.3.10).
http://codepen.io/chr22/pen/wBNoGp

Here is a CodePen that presents the bug (v. 1.3.11, doesn't work in Chrome).
http://codepen.io/chr22/pen/qEgqEE

**Comment by chr22** [comment]
The reset zoom button can somehow reset the image back to an "unbroken state".

**Comment by JoelParke** [comment]
I believe this is corrected with PR's #1349 and #1350.  which handled the resize and scrolling issues.  Could you retest and re-open with details if still an issue?  Thanks!
