### ISSUE TITLE
ta-paste is not called in IE9 or IE10

### ISSUE THREAD

**Issue by carterpayne** [fraywing/textAngular#595]
ta-paste callback doesnt get called in IE9 or IE10. It works in chrome and other browsers. The pasted content is not sanitized at all either. 
For me:

``` javascript
    element.on('paste', scope.events.paste = function(e, eventData){

                        .........
                        } else {// Everything else - empty editdiv and allow browser to paste content into it, then cleanup
                            var _savedSelection = $window.rangy.saveSelection(),
                                _tempDiv = angular.element('<div class="ta-hidden-input" contenteditable="true"></div>');
                            $document.find('body').append(_tempDiv);
                            _tempDiv[0].focus();
                            $timeout(function(){
                                // restore selection
                                $window.rangy.restoreSelection(_savedSelection);
                                processpaste(_tempDiv[0].innerHTML);
                                element[0].focus();
                                _tempDiv.remove();
                            }, 0);
                        }
                    });
```

It seemed from stepping though the code that _tempDiv[0].innerHTML is an empty string. while at the same moment, element[0].innerHTML is the pasted material when processpaste is called

**Comment by tomchovanec** [comment]
I have the same issue:

HTML:
`<div ng-model="model.SomeText" text-angular ta-text-editor-class="border-around" ta-html-editor-class="border-around" ta-paste="stripFormat($html)"></div>`

Filter:
`app.filter('htmlToPlaintext', function () {
      return function (text) {
          return String(text).replace(/<[^>]+>/gm, '');
      };
  }
);`

Model:
    `$scope.stripFormat = function ($html) {
        return $filter('htmlToPlaintext')($html);
    };`

Works in Chrome, Firefox, doesn't work in IE9+.

**Comment by JoelParke** [comment]
<p>I this still an issue with the current release - 1.5.16?  Could you re-test.  Thanks!<br/>(I don't have a way to test earlier version of IE).</p>

**Comment by tomchovanec** [comment]
Unfortunately I can't. I have left the project more than a year ago (and I also changed employer, so I don't have access to source code anymore). Thank you for understanding.
