### ISSUE TITLE
Looking For Collaborators

### ISSUE THREAD

**Issue by SimeonC** [fraywing/textAngular#602]
Hi all. I know I've been a little slack at getting things fixed up recently - I'm currently in the process of changing jobs so I've had very little time to work on textAngular. As I'm moving from being a contractor to a full time employee I'm less likely to have large amounts of time to work on the project so I'm looking to see if anyone would be interested in becoming a collaborator and helping me out on getting bugs, features and PR's fixed.

If you are interested in helping out, post a comment below!

**Comment by rdeslonde** [comment]
I'm interested.

**Comment by SimeonC** [comment]
@rdeslonde Thanks for your interest, Email sent to you!

**Comment by zigrivers** [comment]
I'm using this plugin as well and would like to contribute/help in any way I can as well.

**Comment by asifshiraz** [comment]
Hi, 
I'm also willing to help out wherever, I can. Although I'll be available more after mid may.

**Comment by darlanalves** [comment]
+1 here. I'm a fulltime coder too, but I love how simple is the plugin. Top priority could be to nail down the open issues count and focus on nasty bugs. I'm using the plugin too :)

**Comment by pbassut** [comment]
Hey, I'm willing to help too. 
I love this plugin. And it solved a lot of my problems.

**Comment by JoelParke** [comment]
I too love this plugin... I have at the moment run into the issues with Rangy, but am in the midst of some other stuff...  Please let me know if you or someone else has started to work on this issue... Before I do something that doesn't need to be done?   Not sure at this point how best to fix this...  My first thought is to do something like using DOMParser -- but that would seem to by pass Rangy completely.  Do you know if Rangy is working on solving this issue more fully in the project???

Contact me.

**Comment by SimeonC** [comment]
Thank you all for your interest. I'll be doing my best to tidy up some loose ends and questions but I have no time any more to maintain this library any more. I've contacted @fraywing who's the owner to get a new maintainer(s) working on it using this thread as an expression of interest.

**Comment by SimeonC** [comment]
@JoelParke and @pbassut I don't have an email address to contact either of you, could you send me an email at simeon@lume.co.nz please?

**Comment by plumpNation** [comment]
@SimeonC Thanks to you for your efforts toward this project, it is much appreciated.

**Comment by nickknissen** [comment]
Are you still looking for collaborator? 
Because we use it extensively at educas.com and are willing to help out.
