### ISSUE TITLE
ctrl-a ctrl-x ctrl-v on firefox

### ISSUE THREAD

**Issue by grlks** [fraywing/textAngular#605]
If I type "ctrl-a ctrl-x ctrl-v" inside the textfield in textAngular I can no longer edit anymore.
Content of the textfield after typing: original
Html output (always):
```html
<br/>
```
Error message inside Firefox Console:
```
Exception { message: "", result: 2147500037, name: "NS_ERROR_FAILURE", filename: "http://textangular.com/dist/textAngular.min.js", lineNumber: 18, columnNumber: 0, inner: null, data: null } angular.min.js:92
e/<() angular.min.js:92
Rd/this.$get</<() angular.min.js:68
e/k<() angular.min.js:122
e() angular.min.js:38
te/k.defer/c<() angular.min.js:41
```
Firefox Version: 31.5.3 on Linux-x86

**Comment by Kayne** [comment]
It's still hapening in newest FF 40.0.

**Comment by pbassut** [comment]
Could you both check if this is present on 1.4.3?
We made a significant change on keybindings that might have solved the issue.
I couldn't reproduce on FF 39.0.

**Comment by Kayne** [comment]
I was looking on live demo here: http://textangular.com

**Comment by pbassut** [comment]
What's your OS?

**Comment by Kayne** [comment]
I'm using OS X but it was tested under Ubuntu as well with the same result.

**Comment by JoelParke** [comment]
<p>Can you check this error using version v1.4.6 as several things have been changed in the code and I cannot reproduce this bug...<br/></p>

**Comment by grlks** [comment]
Sorry JoelParke, I must open this again because the bug is still unsolved. I could not reproduce it on Linux but on Windows Firefox 41.0.
Textangular is version 1.4.6 as the live demo.

**Comment by grlks** [comment]
Anyway, I don't know how to re-open the bug. It would be great if anyone could be do this, please.

**Comment by pbassut** [comment]
I still can't reproduce this. So, the steps are:
* Open textangular.com
* Focus on the editor;
* Press Ctrl+a(or Cmd+a, tried both);
* Press Ctrl+x(or Cmd+x, tried both);
* Press Ctrl+v(or Cmd+v, tried both);
And then I shouldn't be able to type it, right?

**Comment by Kayne** [comment]
Exactly. Pasted content is displayed but text angular is now blocked. You can't focus it back. Also there is the exception in console. I'm on FF 40.0.3 and bug is still up. Just updated to 41.0 - bug is still up but no exception in console anymore.

If you do those steps and nothing happend - repeat them starting from step 3.

**Comment by pbassut** [comment]
I could reproduce it on FF40. I was on Chrome, it works just fine there.
This is a critical bug. 
Thanks for the report.

**Comment by pbassut** [comment]
If you type in while you hold your mouse's left button, it works again. 
Weird...

**Comment by mpapaleo** [comment]
I'm on Firefox 43 and the issue is still open.
I love the component and so I hope that the issue will be solved

**Comment by JoelParke** [comment]
I have tried this with the latest: v1.5.7 http://textangular.com/ and I cannot reproduce.  And I am almost certain that my work around 1.5.6 fixed this.  Please reopen if an issue!

**Comment by grlks** [comment]
Thank you! Now it seems to work just fine.
