### ISSUE TITLE
TextAngular catching Ctrl+Return

### ISSUE THREAD

**Issue by piggyslasher** [fraywing/textAngular#607]
We're using a global hotkey system so is there anyway to prevent textangular from catching this combination? we want to submit the form textangular is in.

**Comment by SimeonC** [comment]
Ahhh, though we aren't directly catching the combination, the we are catching !shift+return. Which will have to be expanded to !shift+!ctrl+!meta+!alt+return (Unmodified Return was what I intended).

**Comment by JoelParke** [comment]
<p>I create a PR #1316 to correct this.  Could you please check this and make sure that it solves the issue.  <br/>I will close this now. Please re-open if still an issue.</p>
