### ISSUE TITLE
Is there a way to manually remove focus (blur) from text box ?

### ISSUE THREAD

**Issue by figalex** [fraywing/textAngular#609]
I want to implement like a "save" toolbar button, when its clicked I want to remove focus from text box and just display the content user edited. I have not found a way to manually remove focus inside the "action" function.

**Comment by SimeonC** [comment]
Can you not just grab another element on the page and `.focus()` it to remove the focus?

**Comment by figalex** [comment]
Thanks, that worked. I was trying to trigger blur event on editor but just focusing another element did the job.
