### ISSUE TITLE
CSS Clearfix needed on taTextElement

### ISSUE THREAD

**Issue by JoaoMosmann** [fraywing/textAngular#611]
The image float problem bellow can be solved by applying a `::after` clearfix on the taTextElement

![image](https://cloud.githubusercontent.com/assets/5850824/6925295/d3317626-d7b4-11e4-93a2-c12f685a70f9.png)

**Comment by JoelParke** [comment]
<p>I am hesitant to add 'clearfix' to the taTextElement.  <br/>This would be trivially done to the code by modifying main.js and changing:</p><pre style="background-color: #ffffff;color: #000000;">scope.<span style="color: #660e7a;"><b>displayElements</b></span>.<span style="color: #660e7a;"><b>text</b></span>.<span style="color: #660e7a;"><b>attr</b></span>({<br/>   <span style="color: #008000;"><b>'id'</b></span>: <span style="color: #008000;"><b>'taTextElement' </b></span>+ <span style="color: #458383;">_serial</span>,<br/>   <span style="color: #008000;"><b>'contentEditable'</b></span>: <span style="color: #008000;"><b>'true'</b></span>,<br/>   <span style="color: #008000;"><b>'ta-bind'</b></span>: <span style="color: #008000;"><b>'ta-bind'</b></span>,<br/>   <span style="color: #008000;background-color: #e4e4ff;"><b>'ng-model'</b></span>: <span style="color: #008000;"><b>'html'</b></span>,<br/>   <span style="color: #008000;"><b>'ng-model-options'</b></span>: element.<span style="color: #660e7a;"><b>attr</b></span>(<span style="color: #008000;"><b>'ng-model-options'</b></span>)<span style="color: #008000;"><b><br/></b></span>});<br/></pre><p>to</p><pre style="background-color: #ffffff;color: #000000;">scope.<span style="color: #660e7a;"><b>displayElements</b></span>.<span style="color: #660e7a;"><b>text</b></span>.<span style="color: #660e7a;"><b>attr</b></span>({<br/>   <span style="color: #008000;"><b>'id'</b></span>: <span style="color: #008000;"><b>'taTextElement' </b></span>+ <span style="color: #458383;">_serial</span>,<br/>   <span style="color: #008000;"><b>'contentEditable'</b></span>: <span style="color: #008000;"><b>'true'</b></span>,<br/>   <span style="color: #008000;"><b>'ta-bind'</b></span>: <span style="color: #008000;"><b>'ta-bind'</b></span>,<br/>   <span style="color: #008000;background-color: #e4e4ff;"><b>'ng-model'</b></span>: <span style="color: #008000;"><b>'html'</b></span>,<br/>   <span style="color: #008000;"><b>'ng-model-options'</b></span>: element.<span style="color: #660e7a;"><b>attr</b></span>(<span style="color: #008000;"><b>'ng-model-options'</b></span>),<br/>   <span style="color: #008000;"><b>'class' </b></span>: <span style="color: #008000;"><b>'clearfix'<br/></b></span>});<br/></pre><p>but I worry that this will collide in applications where folks have already crafted their css, etc. to do what they need.<br/>What are your thoughts?</p><p>Thanks!</p>

**Comment by JoelParke** [comment]
After thinking about this some more.  I realized that there is already a 'ta-text-editor-class' attrib set to 'border-around' that I will add 'clearfix' to for the existing demo.
So I will close with an update the demo...
