### ISSUE TITLE
Set the model to null (from outside )doesn't work the first time, but the second time

### ISSUE THREAD

**Issue by foxx9** [fraywing/textAngular#614]
Hey !

If you check that plunker : 
http://plnkr.co/edit/0p3aW6G9CtqOc2rfB8Ck?p=preview

You can see that a button is setting the model used by textangular to null, but you have to click the button twice to make it actually null. 

Thanks for your help!

**Comment by SimeonC** [comment]
Upgrade to latest version v1.3.11. It's working with that one for me.

**Comment by foxx9** [comment]
Well I updated the plunker to 1.3.11 and I got the exact same thing
http://plnkr.co/edit/0p3aW6G9CtqOc2rfB8Ck?p=preview

( actually I noticed this bug in my app which had the latest version )
