### ISSUE TITLE
Bug: Duplicated Text after create of a Quote on Selection

### ISSUE THREAD

**Issue by avolution** [fraywing/textAngular#616]
Reproduction:

paste:
"TEST 1 2 <b>3</b> <i>4</i>"

in the editor on http://textangular.com/,

mark the Text

and press quote.

**Comment by JoelParke** [comment]
<p>I see this only on Firefox and it causes an error for version v1.5.9 -- so will be working on a fix.</p>

**Comment by JoelParke** [comment]
<p>This is fixed now... and will be out in the next release.  Please reopen if still an issue when release 1.6.0 and your should not see it already with release 1.5.9 -- in terms of duplicated text.</p>
