### ISSUE TITLE
Spaces are removed after pasting of formatted text

### ISSUE THREAD

**Issue by mnesov** [fraywing/textAngular#617]
**Browsers**: Chrome, FF
**Steps**:
1. Go http://textangular.com/
2. Clear editor from text
3. Switch to paragraph format (button P)
4. Enter few words, "one two three four"
5. Apply different formats (B, I, U) to each word, starting from second one ("two")
6. HTML output field should look like ```<p>one <b>two</b> <i>three</i> <b>four</b></p>```
7. Select all text, cut it, and paste back
**Expected result**: text have same spaces between words as on point 4. of steps
**Actual result**: text have no spaces between words, starting from second one.

**Comment by js-padavan** [comment]
same issue

**Comment by SimeonC** [comment]
I'm not able to replicate this particular one, it appears the demo is stripping out all text formatting but apart from that I get the correct text in Chrome on OS X.

@js-padavan That's a separate issue that's been cropping up recently see #598 and similar.

**Comment by mnesov** [comment]
Have updated steps. It seems to reproduce, first word should not have formatting applied.

**Comment by SimeonC** [comment]
Thanks for giving us better steps to reproduce, I can replicate the issue now.

**Comment by jeserkin** [comment]
Hmmm. Did try it in Chrome just now and it was pasted fine. Spaces present.

**Comment by mnesov** [comment]
@jeserkin
Ensure that you've done point 5 of steps correctly, 
the key sentence is "starting from second one ("two")".
Still reproducible in Chrome/MacOS

**Comment by jeserkin** [comment]
@mnesov https://www.screenr.com/znQN

**Comment by Xceno** [comment]
I can still reproduce this with 1.3.11 by pasting content from Word 2013

**Comment by riturajratan** [comment]
getting same issue when paste from doc to text-angular space are removed and words are join 

please anyone suggest me solution so i can proceed further.

Thanks

**Comment by marcaurele** [comment]
Turning off the sanitizer did fix the problem in my app. But it opens other security issues with XSS vulnerabilities.

**Comment by riturajratan** [comment]
@marcaurele  but not works for me :(

**Comment by jeserkin** [comment]
Is it possible somehow to make layer on top of layer with textAngular? Asking since pasting from Word works fine with ordinary textarea. I don't care much for loosing formatting. Or maybe it is possible to get raw paste input with `ta-paste`, paste it into textarea and then paste text into textAngular instance?

**Comment by JoelParke** [comment]
<p>I suspect that this may have been fixed with the most recent changes -- see aba826 or wait for the next release.</p>

**Comment by JoelParke** [comment]
I suspect that this may have been fixed with the most recent changes -- see aba8265 or wait for the next release.

**Comment by JoelParke** [comment]
<p>Nope -- I verified that this is still an issue even with the most recent changes.<br/>Stay tuned...</p>

**Comment by JoelParke** [comment]
<p>This is fixed with 2977bfca.  </p>

**Comment by askanhan** [comment]
i have the same issue.
What i do is just using some html messages as ng-model. Everything seems to work and i can add every character except space.

**Comment by RaviRanjan86** [comment]
Hi,

Can anyone please tell me how was it fixed
