### ISSUE TITLE
ta-max-text not seems to work

### ISSUE THREAD

**Issue by vapits** [fraywing/textAngular#619]
Hi there,

thanks for the amazing editor ;)

I'm having a strange issue. ta-max-text doesn't seems to work at all with not giving back any error.
I haven't edit at all your code and i'm just adding the editor like thes:
```html
<div text-angular ta-toolbar="[['h1','h2','h3'],['bold','italics','underline','strikeThrough'],['ul','ol'],['justifyLeft','justifyCenter','justifyRight'],['insertLink'],['undo','redo','clear']]" ng-model="form.content.description[activeLanguage]" ta-max-text="120"></div>
```

I'm not getting any error at all and i'm bit confused what else i have to do, could you please check it?
I'm using: "textAngular": "~1.3.11"

**Comment by vapits** [comment]
btw if you edit the demo plunker adn add this:

```html
<div text-angular="" ng-model="content" ta-max-text="20"></div>
```
still it does not work.
What am i missing?

**Comment by SimeonC** [comment]
Works for me? See http://plnkr.co/edit/cdllZdB3BJQ0dqSox7Uh?p=preview

**Comment by vapits** [comment]
My apologies. This is working for me also this way.
I thought that if user reach the max length then he could not add more text (As in simple text area maxlentgth).

**Comment by manuelmazzuola** [comment]
I have the same problem.
I'm using version 1.3.11

**Comment by SimeonC** [comment]
@manuelmazzuola ta-max-text is a validation only. We cannot prevent typing based on max length as we deal with HTML not plain text.

**Comment by inad9300** [comment]
With the very plnkr you show us, SimeonC, it's possible to reproduce the following issue (maybe already known): write some text (the counter works), switch to HTML mode and go back to the normal edition mode again, and write some more text (the counter doesn't work anymore).

**Comment by alexander-elgin** [comment]
@vapits and @manuelmazzuola I have created a directive (see https://github.com/alexander-elgin/ta-maxlength) with the functionality you required
