### ISSUE TITLE
Multiple clicks on an unordered list, breaks textAngular with Firefox

### ISSUE THREAD

**Issue by PhilFlash** [fraywing/textAngular#623]
Hi,
If you click several times of an unordered list, textAngular is broken with Firefox.
Plunker:
http://plnkr.co/edit/f9WqGgVcoiaLYmg9HT2r?p=preview

Steps to reproduce:

1. Goto at the end of "line 3" ("unordered list" button is selected)
2. Click on "unordered list" button
3. Check that the cursor is at the end of "line 3" and click on "unordered list" button
4. Check that the cursor is at the end of "line 3" and click on "unordered list" button

After this, lines 1, 2 ,4 and 5 are duplicated.

At the end of step2, the html code is: 
`line 2</li></ul>line 3<ul><li>line 4`

IMHO, the code should be :

>line 2&lt;/li&gt;&lt;/ul&gt;<strong>&lt;p&gt;</strong>line 3<strong>&lt;/p&gt;</strong>&lt;ul&gt;&lt;li&gt;line 4

With Internet Explorer 10, all is ok.
The html code (at the end of step2) is ok : `line 2</li></ul><p>line 3<p><ul><li>line 4`

With Chrome, all is ok. 
The html code is: `line 2</li></ul><span>line 3<span><br/><ul><li>line 4`

Is there a tip to have the same html code with different browsers?

Philippe

**Comment by SimeonC** [comment]
Hmmm, I think thats a bug, but will take some investigation to fix.

**Comment by JoelParke** [comment]
See PR #1347

**Comment by JoelParke** [comment]
See release 1.5.11
