### ISSUE TITLE
Unexpected hidden input presents in Chrome.

### ISSUE THREAD

**Issue by ozzimpact** [fraywing/textAngular#624]
![scr1](https://cloud.githubusercontent.com/assets/6742827/7006049/889e3ae6-dc86-11e4-8dea-63538b9f280c.png)
![scr2](https://cloud.githubusercontent.com/assets/6742827/7006048/889dc0fc-dc86-11e4-8f80-092016218aee.png)

**Comment by SimeonC** [comment]
Looks like your missing the `src/textangular.css` file.
