### ISSUE TITLE
How do I submit the text?

### ISSUE THREAD

**Issue by thegreatmichael** [fraywing/textAngular#626]
I was previously using a `textarea` with an `enter-submit` directive:

    .directive('enterSubmit', function () {
      return {
        restrict: 'A',
        link: function (scope, elem, attrs) {
         
          elem.bind('keydown', function(event) {
            var code = event.keyCode || event.which;
                    
            if (code === 13) {
              if (!event.shiftKey) {
                event.preventDefault();
                scope.$apply(attrs.enterSubmit);
              }
            }
          });
        }
      }
    });

but now (using textAngular, THANKS FOR THE HARD WORK ON IT!), it seems like perhaps the `scope.$apply` may be the wrong thing to do...? despite following https://github.com/fraywing/textAngular/wiki/Editor-Setup-Options#editor-setup-options and adding this directive via a setup function, I cannot get my enter-submit function to be called. Thanks in advance for any suggestions.

**Comment by SimeonC** [comment]
Ahhh, yea. Isolated scopes are the problem here - it'll probably work if you do something like `scope.$parent.$parent.$apply(...` (number of $parents unsure).

**Comment by JoelParke** [comment]
Closing this as it seems answered -- Please re-open if you have issues.
