### ISSUE TITLE
Styling the editor

### ISSUE THREAD

**Issue by Aizenko** [fraywing/textAngular#628]
Hi,

Something is escaping me, some style are applied 'inline" like height and min-height of the editor I don't know how to change these value and why they appear as inline.

Regards

**Comment by SimeonC** [comment]
They should only be being applied in the textAngular.css stylesheet - in 1.3.x versions at least. Which version are you using?

**Comment by Aizenko** [comment]
Hi,

I'm using the 1.2.0 because I started from the example (demo/textAngular.com.html).

Regards,

**Comment by SimeonC** [comment]
You should upgrade to 1.3 that's much more stable. Also it has the style sheet option. If you want a better example look at the gh-pages branch which is the source for textAngular.com

**Comment by Aizenko** [comment]
I just switched to the last version and there's no more inline style added.

Thanks.
