### ISSUE TITLE
Dragging textAngular element

### ISSUE THREAD

**Issue by azrielis** [fraywing/textAngular#630]
Hi,

I am trying to add the textAngular element inside of a parent div and make that div draggable.  I want to be able to double click to edit the text and then on blur be able to drag the parent div around.  I hope that makes sense.

**Comment by SimeonC** [comment]
That's not really related to textAngular. The best way would probably be using an invisible overlay that takes the drag events and when double-clicked it focusses the editor and hides itself - you can listen to the blur event on the editor to re-add in your overlay.
