### ISSUE TITLE
Uncaught rangy-selectionsaverestore.js is required for textAngular to work correctly

### ISSUE THREAD

**Issue by kiranwithgit** [fraywing/textAngular#632]
I get this error even I include all the required script files as per the instructions given.

<script src="files/textAngular.min.js" type="text/javascript"></script>
<script src="files/textAngular-rangy.min.js" type="text/javascript"></script>
<script src="files/textAngular-sanitize.min.js" type="text/javascript"></script>

when I create a sample app including all the script files, it works good and I can see the editor. But when I integrate it in my web based application, I get this error -
"Uncaught rangy-selectionsaverestore.js is required for textAngular to work correctl"

Request to assist here.

I am using Version 1.3.7 of textAngular
Angular JS - 1.3.11

**Comment by SimeonC** [comment]
Make sure that the rangy files are being loaded before the textAngular files - basically this is a check to ensure that you've correctly loaded up the rangy files.
