### ISSUE TITLE
form html tag is not working with ta-bind

### ISSUE THREAD

**Issue by klaszlo** [fraywing/textAngular#635]
The < form > html tag is not working inside ta-bind directive. 
Here is a simple demo:
```
$scope.probe = 
    '  <h4>Login</h4>\n' +
    '  <form id="login">\n' +
    '    <fieldset>\n' +
    '      <div class="form-group">\n' +
    '        <label for="login-name">Name</label>\n' +
    '        <input id="login-name" class="form-control" type="text">\n' +
    '      </div>\n' +
    '      <input id="login-submit" class="btn btn-primary" value="Register" type="submit">\n' +
    '    </fieldset>\n' +
    '  </form>\n';
```
and in html:
```
<div ta-bind="text" ng-model="probe" ta-readonly='disabled'></div>
```

It strips out all the input and form elements (also select, option html element)

**Comment by klaszlo** [comment]
I'm sorry it is offtopic. There is a sanitizer inside textAngular, and also a whitelist for tags.
But thinking through my original problem, I should not use textAngular with forms. 
I use ng-if, for displaying textAngular *while* editing the content. And ng-bind-html when not.

**Comment by SimeonC** [comment]
Yea, textAngular isn't really designed for form editing, you can just turn off the sanitiser if you're happy the content is safe via `ta-unsafe-sanitizer` attribute, but do be wary of this allowing in XSS vectors to your app.
