### ISSUE TITLE
Making certain parts of the content read-only

### ISSUE THREAD

**Issue by jamesmarnoch** [fraywing/textAngular#637]
Is it possible to make certain content elements read only / uneditable / undeletable whilst others are editable?

For example, if a piece of content contains images, and those images are not supposed to be edited or deleted.

Is this possible out of the box? Or?

Thanks

**Comment by jegjessing** [comment]
This was closed why? Did you find your answer your self?

**Comment by jamesmarnoch** [comment]
we used ckeditor instead (angular 1)

**Comment by pbassut** [comment]
This is not possible currently, no. You would have to implement it yourself. And to be honest, I don't see how this could come in handy being in the code library since it's a very specific situation

**Comment by jegjessing** [comment]
It would be very useful in our situation since we need some markers for data replacement...
And these markers may not be removed from the "document" since the data would not be inserted.
