### ISSUE TITLE
How to modify model

### ISSUE THREAD

**Issue by asifshiraz** [fraywing/textAngular#640]
Hi,
I forked the plunker example and tried to do a modification to replace text of one language with another. 
But it is not taking an ng-change based modification.

Can somebody please take a look and advise? I was expecting that if I type 'b', it should get replaced with another letter.

http://plnkr.co/edit/HSPxDBoPjzNNeaKoKEtY?p=preview

Thanks in advance
Asif

**Comment by asifshiraz** [comment]
Missed controller from the other one. This is the correct one.

http://plnkr.co/edit/IFZiwYxEr4eXzCvVL4QS?p=preview

Unlike regular behavior of ng-change, the replacement of the letter 'b' with a different character, only takes place when I loose focus to something else.

**Comment by SimeonC** [comment]
Yea, it broke. See #38, which has been re-opened.
