### ISSUE TITLE
No ng-model change after asynchronous "insertHTML" and "insertImage"

### ISSUE THREAD

**Issue by geralddzx** [fraywing/textAngular#643]
I tried to return false in the action and deferred.resolved() + restoreSelection(), but no matter what I do the model is not updating after I complete the async request. I have to type something else inside the editor to update the model.

Here is my code: 

```javascript
module.config(["$provide", function($provide){
		$provide.decorator('taOptions', ['taRegisterTool', '$delegate', '$http', function(taRegisterTool, taOptions, $http){
			taRegisterTool('uploadImage', {
				buttontext: 'Upload File',
				action: function(deferred, restoreSelection){
					var editor = this.$editor()
					filepicker.pick(
						{
	    					services: ['COMPUTER'],
						}, 
						function (blob){
							$http.post("api/media", {
								medium: {
									filename: blob.filename,
									url: blob.url,
									mimetype: blob.mimetype,
									size: blob.size,
								}
							})
							.success(function (data, status, headers, config){
		                        alert(data.message)
		                        if (new RegExp("image").test(blob.mimetype)){
		                        	editor.wrapSelection("insertImage", blob.url, true)
		                        } else {
		                        	var element = document.createElement("a")
		                        	element.innerHTML = blob.filename
		                        	element.href = blob.url
		                        	editor.wrapSelection("insertHTML", element.outerHTML, true)
		                        }
                                    deferred.resolve()
                                    restoreSelection()
		                    })
						},
						function(error){
							// console.log(error.toString())
						}
					)
                    return false
				}
			})
			taOptions.toolbar = [
            	['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'pre', 'quote'],
				['bold', 'italics', 'underline', 'strikeThrough', 'ul', 'ol', 'redo', 'undo', 'clear'],
				['justifyLeft', 'justifyCenter', 'justifyRight', 'indent', 'outdent'],
				['uploadImage', 'insertImage','insertLink', 'insertVideo', 'wordcount', 'charcount'],
        	]
			return taOptions
		}])
	}])
```

Also, how would I access the $scope within the action? I am trying to send a request based on the $scope my editor is in. Is there a way to do that?
Also, thanks for making such a simple and useful library! This is awesome!

**Comment by SimeonC** [comment]
Deferred.resolve() only works when you return false from the action. That should fix your model update. The scope should be accessible via this.$editor - I think that's the scope from memory.

**Comment by geralddzx** [comment]
Thanks for your help Simeon!

Please check my code again, I added return false but it still didn't work. It still won't update the model after uploading an image. Also, I'm getting another problem. When I am focused inside the editor, angular won't redirect properly. The url changes. But angular doesn't properly activate the template and controller.

**Comment by geralddzx** [comment]
Sorry I made a mistake somewhere else in my code. I don't have a problem redirecting now. Which function is called when I write something in the editor that updates the model? I need to force it to update some how.

**Comment by geralddzx** [comment]
Never mind, this issue came from file picker. In my filepicker.pick I had to add {container: window}
This caused a lot of problems sorry about that.
