### ISSUE TITLE
Line breaks not convert to <p> or <br> when pasted from plain text

### ISSUE THREAD

**Issue by markni** [fraywing/textAngular#644]
Here is some plain text that with line breaks.

![qq 20150419162226](https://cloud.githubusercontent.com/assets/1743179/7221827/895cf9b6-e6b0-11e4-959d-e3f50629f057.jpg)

When copy and paste into textAngular, we get:

![qq 20150419162550](https://cloud.githubusercontent.com/assets/1743179/7221835/c3d8320e-e6b0-11e4-859c-766995ed1784.jpg)

This seems to be very unfriendly, as user expected line breaks are keeped everywhere.

It looks like most editors out there can handle this:

![qq 20150419162909](https://cloud.githubusercontent.com/assets/1743179/7221840/3a72abd8-e6b1-11e4-949a-7f4597aaedf7.jpg)
![qq 20150419162900](https://cloud.githubusercontent.com/assets/1743179/7221841/3a8647e2-e6b1-11e4-87f8-8511ed9bbcac.jpg)
 
Would like know if there is a solution for this. Thanks!

**Comment by JoelParke** [comment]
I believe that this is fixed with the changes at f7d34a -- see the next release soon.  Thanks for reporting this.
