### ISSUE TITLE
activeState seemingly not firing after the first click after a highlight

### ISSUE THREAD

**Issue by eliothxchan** [fraywing/textAngular#655]
This is broken on the demo (http://plnkr.co/edit/tpl:RaBEszV5xrAZ0VRoZ7PM), and is an issue we've run into in my workplace. Repro steps:

1) Write "Hello World, everybody!"
2) Highlight just "World" and set it to bold - bold button should be set into the depressed state
3) Click at the end of the string
4) Highlight entire string
5) Click inside the word "World" - bold button should be set into depressed state, but it isn't
6) Click inside the word "World" again - bold button now is in the proper depressed state

**Comment by SimeonC** [comment]
Thanks for the bug report. A bit of an odd one there.

**Comment by JoelParke** [comment]
<p>PR #1322 corrects this issue and will be in the next release. Thanks again.</p>
