### ISSUE TITLE
ta-max-text and angular form validation

### ISSUE THREAD

**Issue by andrehagemeier** [fraywing/textAngular#656]
Tried a while to get it working but these two things just don't get along with each other.
When I specify ta-max-text, the form will be marked as invalid and corresponding styles apply. However, it will not be added to the angular form validation errors ($scope.formName.$error)
Therefore, I cannot provide user feedback based on these problems like I can do for the rest of my form. I tried to add them myself:

        if ('opportunity.create.form.summary' === value.$name) {
          console.log(value.$name);
          var noOfChars = $scope.data.summary && $scope.data.summary.replace(/(\r\n|\n|\r)/gm,"").replace(/^\s+/g,' ').replace(/\s+$/g, ' ').length || 0;

          if (noOfChars > 200) {
            $scope.createOpportunity.$error.exceed = [{$name:'opportunity.create.form.summary',$value:200}];
          }
        }

This way, I fake a new category of errors into the record and can react to it. But when I combine this with ta-max-text, the property will remove the whole text from the scope as soon as it exceeds the max value. So I cannot access them any more from the binding.
If I remove the ta-max-text, the value will be bound properly, and I can put them into the error record, but the css classes will be missing.

Any suggestions?

**Comment by SimeonC** [comment]
Write your own validator directive to put that code in (like the ta-max-text directive) - basically what angular does is set the model to undefined if the validation is invalid.
