### ISSUE TITLE
Why shouldn't the editor change on direct model change? How can I update it programmatically?

### ISSUE THREAD

**Issue by thegreatmichael** [fraywing/textAngular#660]
https://github.com/fraywing/textAngular/blob/0cd98dd3115f4e7d09263eeeb0136ec9d2ccaafa/test/textAngular.spec.js#L371 indicates that the editor should not be updated when the bound model is changed directly, why is that, or more important to me, how can I update it?

I'd like to clear the content.

**Comment by SimeonC** [comment]
Yea, this looks like it bugged it's way back in somewhere (#38), that test is probably wrong too.

**Comment by SimeonC** [comment]
Should be fixed in master now.
