### ISSUE TITLE
Is there a way to select text in the textAngular area

### ISSUE THREAD

**Issue by DonHaron** [fraywing/textAngular#666]
First of all, thank you for the awesome plugin! It solved a lot of my problems!

Now, I didn't find anything about this in the documentation, but is there some way to make text in the textAngular area selected? 

Other html elements use setSelectionRange or createTextRange for this, but they both do not work on a textAngular area. Did I miss this feature, or is this simply not possible right now?

Thank you!

**Comment by pbassut** [comment]
What you mean by "make text"?

**Comment by DonHaron** [comment]
No, sorry for any confusion.

I mean make the text "selected", like if you mark some text with your mouse, or via shift + arrow keys with the text cursor.

**Comment by DonHaron** [comment]
As an example, like this:

![selected-text](https://cloud.githubusercontent.com/assets/1902241/7407728/6adef0b2-ef15-11e4-913a-7c0cd056d45d.jpg)

Is there a way to do that in an angularText-box via code? Or is this a planned feature for a future version, maybe?

**Comment by pbassut** [comment]
It's not documented, I guess. But if you look at the source code you will see that taSelection has a method 'setSelectionBeforeElement', 'setSelectionToElementEnd' and 'setSelectionToElementStart'.

I haven't tested. But as how the method is named I think it does what you want.

**Comment by DonHaron** [comment]
Cool, I'll check those out, thank you very much!

**Comment by SimeonC** [comment]
Sorry to be a bit late on this, the setSelectionRange and createTextRange should have worked, we use them internally via the rangy library. Possibly the problem was that you have to make sure you trigger the focus handlers before you set the selection.

**Comment by DonHaron** [comment]
Hey SimeonC

Thank you for your reply!

I have been able to work it out now, once I correctly used the two methods. Works like a charm now!

Thank you & keep up the great work
