### ISSUE TITLE
Missing HTML5 required attribute

### ISSUE THREAD

**Issue by harshithkashyap** [fraywing/textAngular#671]
We use the HTML5 <b>required</b> attribute to avoid empty form submissions. The response is validated both on the client aswell as the server. But is there a way to specify the required attribute to the editor?

**Comment by gabrielperales** [comment]
You can't use it with the HTML5 validation, but you can use with the angular forms validation. If you check the [wiki](https://github.com/fraywing/textAngular/wiki/Directives) you will see you can use the **required** attribute.  If you use it, and if the form is empty, the form will get the **ng-invalid** and **ng-invalid-required** classes. You can do something like:

```html
<form name="YOUR_FORM_NAME" novalidate ng-submit="YOUR_FORM_NAME.$valid && YOUR_FORM_NAME.yourSubmitMethod()">
```

Using this, you will validate your form before submiting the form.

**Comment by harshithkashyap** [comment]
Thanks, this helps :+1:
