### ISSUE TITLE
Hitting "enter" should not propagate up to form

### ISSUE THREAD

**Issue by KatelynL** [fraywing/textAngular#677]
Hitting the enter key inside text angular should now propagate up to the form and submit the form.  Textareas do not allow 'enter' to propagate up to the form, my expectation is that a WYSIWYG editor would have the same functionality.

**Comment by SimeonC** [comment]
I can't seem to replicate this in the latest version of textAngular, can you provide a codepen/plnkr that demonstrates this please?

**Comment by pbassut** [comment]
I also can't reproduce this. I'm closing this very old issue.

**Comment by burakkilic** [comment]
+1 for this. I think some of included scripts cause that.
