### ISSUE TITLE
It does not seems working with AngularJS 1.3.14

### ISSUE THREAD

**Issue by webreinvent** [fraywing/textAngular#678]
http://codepen.io/paulbhartzog/pen/Hpsjg

If you replace angular js path to <strike>https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js</strike> https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js , editor stop working

**Comment by plumpNation** [comment]
You replaced angular with jquery and it stopped working. Is that a typo?

**Comment by pbassut** [comment]
Yeah, your issue statement doesn't make much sense. At least I hope not. Because if you do replace angular js path to a jquery path it will stop working. Cause it needs angular.js to work.

**Comment by webreinvent** [comment]
Apology for the typo. Below are the correct links:

Case 1) https://ajax.googleapis.com/ajax/libs/angularjs/1.2.4/angular.min.js  - Working
http://codepen.io/paulbhartzog/pen/Hpsjg

Case 2) https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js - Not working
http://codepen.io/anon/pen/ZGQbKE

The only change in code is the angularjs version. Give it a try.

**Comment by webreinvent** [comment]
Did you guys check that?

**Comment by pbassut** [comment]
Did you include rangy?

**Comment by webreinvent** [comment]
Hi @pbassut 

Here's pretty clean code http://codepen.io/anon/pen/ZGQbKE (ng 1.2.4 = working)  & http://codepen.io/anon/pen/yNeQmN (ng 1.3.14 = not working)

And why do I need Rangy, does textAngular has dependency on it?

**Comment by pbassut** [comment]
From the readme: 
https://github.com/fraywing/textAngular#requirements

**Comment by SimeonC** [comment]
Yea, textAngular requires rangy. Also definitely works on angular 1.3.x as current version of textAngular now requires it.
