### ISSUE TITLE
Alt Gr + z

### ISSUE THREAD

**Issue by baster33** [fraywing/textAngular#682]
In Polish language Alt Gr + z is used to write "ż" letter in textAngular it works as undo (Ctrl + "z").
I am using version 1.3.11 of textAngular.

I think to fix this You need to change line 1449 of textAngular.js and add "&& !event.altKey" in if statement.

**Comment by SimeonC** [comment]
Duplicate of #518, try the latest release of textAngular.

**Comment by baster33** [comment]
Thanks, I thought i use latest version of textAngular since i installed it via pip. I will change version than.
