### ISSUE TITLE
Confusion switching between multiple instances of the editor when content modified.

### ISSUE THREAD

**Issue by JoelParke** [fraywing/textAngular#683]
When I switch back and forth between difference instances of my UI - which lists items.  Each one is displayed in the same area which has a edit area with textAngular, which shows the text content.  All is fine, until I  modify the text content model (using textAngular) and then switch to a different item.  When the item switches, the textAngular portion does not update - it seems to get out of sync -- almost as if the editor makes a copy and then a portion is not changed, even though the model switched?  The other elements in the content area are rendered properly, but the textAngular piece does not update???  

Is it possible that when the model is switched, textAngular does not notice that the model has been completely changed?? Please let me know if you would like to see the behavior from the existing web app.  I suspect that playing with it briefly would make it clear what is going on under the covers on the textAngular side.  

Note I have added  textAngularManager.refreshEditor('task'), in addition to doing a $scope.$apply() in an attempt to understand more -- not believing this would make any difference, since I don't go outside of the angular world in this.  -- and it make no difference as expected.

I also upgraded to 1.3.11 and pulled in one small pull request for a missing var for a variable. but still no luck.  I will post back  when I learn more. -- and if no there is solution, I may attempt to craft a smaller model that illustrates the issue, but this will be a difficult.  

THANKS

**Comment by JoelParke** [comment]
As I have been looking at this in more detail.  I discovered that because I use ng-change on the model that textAngular is tied to, things were even more confusing.  So I pull that out of the html and NOW IT IS CLEAR that when the editor has focus, it stops seeing that the model has changed behind it's back. (by angular).  So I will take the focus away before the switch and see if the issue goes away.

**Comment by SimeonC** [comment]
Yup, that was a bug that I fixed last weekend - a rather nasty one to pin down as well. You shouldn't need to do that workaround in the 1.4+ versions. Note the breaking changes in 1.4.0 and 1.4.1 before upgrading.

**Comment by JoelParke** [comment]
Thanks so much for all your hard work.  YES - this one took a while to figure out what was going on!  I am glad it is fixed and will update to the new version tomorrow! Thanks again.
