### ISSUE TITLE
sanitizer wipes new lines before ta-paste making it impossible to replace them with BR tags

### ISSUE THREAD

**Issue by let4be** [fraywing/textAngular#686]
https://github.com/fraywing/textAngular/blob/7ee680ddc7d750641daa4f226b94bb73025749da/src/textAngular.js#L1420

sanitizer runs before paste, while should run after
Current behavior makes it totally impossible to replace new lines with BR tags to preserve text formatting when inserting text/plain into text angular

another approach would be to fix sanitizer(preserve space/newline) but this seems to be more complex

**Comment by let4be** [comment]
the fix is in(last published version):
https://github.com/lavab/textAngular/tree/textAngular/fix-ta-paste-sanitizing

**Comment by SimeonC** [comment]
OK, yea that makes sense. Not sure why I thought doing it that way was a good idea.

And yea, I think my poor choices of folder names are causing a bit too much confusion.
