### ISSUE TITLE
get non-html/plain-text version as output

### ISSUE THREAD

**Issue by codefullon** [fraywing/textAngular#688]
is there a feature within textAngular using which I can get the output in a non-html format? reason being that I want to do some text analysis only on the actual content inserted(minus the HTML syntax)

the current ng-model assignment only outputs HTML

thanks :-)

**Comment by noeliasfranco** [comment]
I need something similar, I'm trying to find the way that the user paste text but  remove all the images and HTML code

**Comment by SimeonC** [comment]
We use the following:
```js
element = angular.element(html);
plainText = element[0].innerText || element[0].textContent
```
It's a DOM method that returns just the text without the HTML, we use it for the char count and word counts as seen here: https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L687-L704
