### ISSUE TITLE
accessing character/word count 

### ISSUE THREAD

**Issue by codefullon** [fraywing/textAngular#689]
curious what's the model name to access the character and word count? looked at the DOM where the character count gets outputed in the editor although when i tried the '$scope.charcount', nothing shows up - but guessing that i'm not doing this properly

input on the above would really help

**Comment by SimeonC** [comment]
You'll need to get the editors scope via the textAngularManager. Something like this:
```js
textAngularManager. retrieveEditor('name-of-text-angular-element').scope.charcount;
```
