### ISSUE TITLE
Please add module exports for use with webpack 

### ISSUE THREAD

**Issue by kpgarrod** [fraywing/textAngular#691]
I am migrating an existing app to webpack and need to use this library. The code doesn't seem to include 'exports'. I tried to create a pull request but `grunt compile` failed. I have logged a separate issue for that.

**Comment by marduke182** [comment]
+1

**Comment by SimeonC** [comment]
Unfortunately I have no knowledge of web pack, and no time to learn it currently. If you can get a PR for this up I'll merge it in if it doesn't break anything but otherwise it's not something I'll be doing.

**Comment by kpgarrod** [comment]
@simeon I tried to make a pr but couldn't get the build to work. I raised
another issue on that.
