### ISSUE TITLE
certain tags are stripped when doing a POST

### ISSUE THREAD

**Issue by kyleiwaniec** [fraywing/textAngular#692]
I'm having trouble submitting the html from the editor via $http.post

When I log the scope variable to the console, everything looks good.

But when I look at the payload in my browser, certain tags are stripped out, like h1, h2.. u, but not all tags. ol, ul, li, b, are preserved.

Any idea why this might happen?

I am using the directive without any modification:
```<div text-angular ng-model="description" required></div>```

**Comment by SimeonC** [comment]
No Idea sorry, if it's correct in the scope variable then it's probably not something to do with textAngular.
