### ISSUE TITLE
Bold and Italics buttons can't be pressed one straight after the other

### ISSUE THREAD

**Issue by adrianb11** [fraywing/textAngular#693]
In the sample in http://textangular.com/, and also in the latest release. From an unselected state, the italics button can't be pressed immediately after a bold button press. It unselects the bold button press.

This functionality however works in Release 1.2.2 (the version used by demo.html in the demo directory from the latest release).

**Comment by SimeonC** [comment]
Thanks for the bug report. Unfortunately it looks like I broke this even more in the latest release - now it doesn't support bold/italics etc without a selection :(.

I'll look into it, probably the same underlying issue as #423

**Comment by alinnitan** [comment]
i am still having this problem with double selection. Any update on it, please?

**Comment by JoelParke** [comment]
This is mostly fixed with PR #1289 and actually a rangy bug.
