### ISSUE TITLE
How to make the toolbar fixed

### ISSUE THREAD

**Issue by zhaohaifeng** [fraywing/textAngular#697]
The toolbar will be unavailable when I scroll the page.
![image](https://cloud.githubusercontent.com/assets/3147637/7701389/32607604-fe59-11e4-997f-3d3aaa26bee1.png)

Is there any way to make the toolbar fixed when I scroll the content?

**Comment by SimeonC** [comment]
Hey, have a look at the demo/static-demo.html in the repo. It has an example of a static toolbar.
