### ISSUE TITLE
Anyone got this working with browserify?

### ISSUE THREAD

**Issue by Vvaltz** [fraywing/textAngular#698]
If I require: textAngular-rangy.min.js:  'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).

If I requrie: rangy-core.min.js and rangy-selectionsaverestore.min.js : Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded. 

Or this just won't work together?

**Comment by huuthonguyen76** [comment]
@Vvaltz have you fixed this? I have the same problem and don't know how to solve

**Comment by pbassut** [comment]
You're probably loading rangy stuff after textAngular. Those should be loaded BEFORE textAngular. So when textAngular loads it finds all the required dependencies(rangy-core, in that case)
