### ISSUE TITLE
No icons in toolbar buttons

### ISSUE THREAD

**Issue by OKNoah** [fraywing/textAngular#699]
This is what I'm seeing. No error about fonts or CSS not loading on console. Safari 8.

![screen shot 2015-05-21 at 10 29 49 pm](https://cloud.githubusercontent.com/assets/3739277/7764683/d087b804-0009-11e5-9171-41ca576a7ddd.png)

**Comment by SimeonC** [comment]
You are missing font-awesome as in the read me.

**Comment by OKNoah** [comment]
Oh, I thought I was but I guess not. Thanks.
