### ISSUE TITLE
inserting video from youtube image jump out of the editor when clicking on it version 1.3.11

### ISSUE THREAD

**Issue by Laazarus** [fraywing/textAngular#700]
Hello, 
First of all thanks for your great directive, it is really cool.

I am facing a problem that I cannot resolve. On the website of textangular everything is forking fine but when I install it on my project the version 1.3.11 behave in a strange way. the hight of the text area is vis very low and I have fixed it with a css rule. When I isert a youtube video the image does not have  the control to resize it and when I click on it the image jump out the window... I have tried older version and the problem is still there but in version 1.2.2 the image box get set perfectly but there is no image on it...

the html of the page is very simple 
<div class="container form-control">
<div text-angular="text-angular" name="htmlcontent" ng-model="review" ></div>
</div>

I do not know what I am doing wrong.. 

Thanks again for your directive.

**Comment by SimeonC** [comment]
Hi There. It sounds like this is something specific to your implementation, not our code. If you can provide a plnkr or similar that replicates the issue we can have a look but otherwise I can't really help you there.

**Comment by Laazarus** [comment]
Hello, Thanks for your response, I fixed the problem and you are right was my fault :( I am so sorry to have bothered you and then realise was my mistake. The problem was I could not load the css file of textangular but after fixing this the editor looks work properly, I had only one small problem but I want to test more before asking again.

I am so sorry for this and thanks again for your fast response and work.

Best Regards
