### ISSUE TITLE
[bug] Updating $viewValue incorrectly calls ngModel.$render function.

### ISSUE THREAD

**Issue by episodeyang** [fraywing/textAngular#705]
This is a fun one! Took me a good two-hour.
#### the symptom:

After typing the editor usually undoes the typing. The model is in fact updated, but the view appear to be the older version.
#### Require:

A custom ngModel.$render function that reads the ngModel.$modelValue to update the innerHTML.
#### Cause:

wrong side of the ngModel render/parse cycle.

**Comment by episodeyang** [comment]
Also some change in the 1.4.1 from 1.3.1 causes the editor to sometimes trigger an undo.

**Comment by episodeyang** [comment]
Okay, so the cause of the bug is the following:

I think the taBind `onKeyup` event was incorrectly calling the ngModel.$render() method.
In my custom $render function, I read the ngModel.$modelValue which hasn't changed since the `keyup`. Your code correctly updated the `ngModel.$viewValue`, but ngModel hasn't parsed the `$viewValue` into an updated version of `$modelValue` yet. Then when you call the `ngModel.$render` function, it pulls out the old `ngModel.$modelValue`, which make it appear that the change is undone.

the rendering cycle should *only* be triggered when the model is updated by means other than user input in the editing area.

**Comment by episodeyang** [comment]
I just tested it. removing this line fixes the problem:
https://github.com/fraywing/textAngular/blob/master/src/taBind.js#L226

**Comment by SimeonC** [comment]
Interesting, my intent was that the call to _setViewValue from the keyup should skip the render and just do the placeholder checking. There may be some fun race conditions going on there - I'll see if I can come up with a solution as there is good reason for the way it's written (I hope, it was past midnight when I coded that :worried: )

**Comment by episodeyang** [comment]
Haha it's 2AM in my time zone now :)

So my understanding is that this is *not* a race condition. My original post was incorrect and has since been changed to reflect the correct explanation.

During the `keyup` event, the view gets update first by the `keyup` handler. At this time, the ngModel value that we need to update is the $viewValue. using the ngModel.$setViewValue automatically sets the $viewValue, which then triggers the $parser to generate the new $ngModel.$modelValue. Since your _setViewValue is basically a wrapper for the ngModel.$setViewValue, it should be doing the parsing, instead of doing the rendering, which is on the other side of the ngModel cycle.

What was your intent? 

Here is a short version of the ngModel.$render() function I have:
```javascript

ngModel.$render = function (caretOffset, caretDelay, nextSiblingOffset) {
                                //console.log('rendering')
                                if (angular.element(iElement[0].parentNode.parentNode).hasClass('focussed')) {
                                    //console.log('saving caret position for textAngular editor');
                                    sel = getSel();
                                } else {
                                    sel = null;
                                }
                                /** For native rendering and compile the entire html,
                                 * use this  */
                                // _render.apply(ngModel);
                                /** or */
                                // iElement.html(ngModel.$modelValue);
                                /** and to compile embeded directives */
                                //$compile(iElement.contents())(scope);

                                iElement[0].innerHTML = ngModel.$modelValue;
                            };

```

**Comment by SimeonC** [comment]
Yea, looking through again I think I was having a dumb moment with being a little to enthusiastic about keeping things DRY...

You're right that setViewValue shouldn't be doing renders, I think I was being lazy around the placeholder show/hide logic. I'll fix it when I can.

**Comment by episodeyang** [comment]
Awesome! :)

**Comment by JoelParke** [comment]
episodeyang - is this still an issue?  Or did you fix this?  Of if not, how can I trigger it to fix it?
Your link: https://github.com/fraywing/textAngular/blob/master/src/taBind.js#L226 doesn't show any line to remove.. is it already gone????
I have been fixing bugs... so the current checked in code is the place to start.

**Comment by JoelParke** [comment]
<p>Do you still see this as a bug? I have been killing off bugs, but I would rather not go after this if has already been fixed???</p><p>I am going to close this.  Please re-open if still an issue.</p>
