### ISSUE TITLE
ng-model doesn't work well when applying text-align:center or right

### ISSUE THREAD

**Issue by kyleada** [fraywing/textAngular#707]
it works well to change the text-align according to the buttons.
but when I watch the htmlVariable binding to ng-model, htmlVariable doesn't contain attr text-align.
Is it a bug?

**Comment by SimeonC** [comment]
We actually use a style="text-align: right" attribute. Quite possibly your problem is to do with including ngSanitize instead of or as well as textAngular-sanitize?

**Comment by NewMediaRoc** [comment]
I had the same issue, and it was definitely that textAngular-sanitize needed to be included.
