### ISSUE TITLE
1.4.1 Version fails to load dependencies in webpack

### ISSUE THREAD

**Issue by bytasv** [fraywing/textAngular#708]
Hello,

trying to use textAngular in 1.4.1 with webpack loader, but failed to load rangy dependency:
```
ERROR in ./bower_components/textAngular/dist/textAngular-rangy.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./rangy-core in **/bower_components/textAngular/dist
 @ ./bower_components/textAngular/dist/textAngular-rangy.min.js 2:15430-15456
```

When I navigate to `textAngular.rangy.min.js` I can see that there is `./rangy-core` dependency defined, which means that loader should be looking for `rangy-core` file relatively to `textAngular.rangy.min.js`. And `rangy-core` file is located elsewhere (`rangy/rangy-core.js`).

Why is it trying to find file relative to `textAngular.rangy.min.js` while the file itself is located elsewhere? How could I fix that?

**Comment by SimeonC** [comment]
Hey, textAngular currently isn't compatible with webpack afaik - I believe there's a ticket open for that. Basically I've said I don't have resource to support it unless someone does a PR for it.

**Comment by bytasv** [comment]
@SimeonC how is supposed to be working with requirejs or any other loader then? It's trying to load file which is not located in that directory...

**Comment by SimeonC** [comment]
Dunno, I've only recently started getting issues about it and I haven't had a chance to work with any of the lazy loaders yet so I only know about their existence and general purpose.

**Comment by aaronroberson** [comment]
See #713.
