### ISSUE TITLE
Uncaught rangy-core.js and rangy-selectionsaverestore.js

### ISSUE THREAD

**Issue by kyleada** [fraywing/textAngular#709]
I run the demo, it works well, then I copy them into my project
src="../bower_components/angular/angular.js"
src="js/lib/textAngular-rangy.min.js"
src="js/lib/textAngular-sanitize.min.js"
src="js/lib/textAngularSetup.js"
src="js/lib/textAngular.js"

 but it said:
Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded. 
I really can't deal with it, why?

**Comment by kyleada** [comment]
Just now it works! I tried to move them before other dependences, then it work.
so I think maybe some other js conflict with it.

Thanks for your great job! @SimeonC

**Comment by manishrw** [comment]
I get the same error, @kyleada How did you resolve it ?

**Comment by dngad** [comment]
Same error all of a sudden, what was your solution?

**Comment by jacobscarter** [comment]
same error, any update on the solution?

**Comment by webmas216** [comment]
Hi kyleada

I hope your solution.

I have same issue as you had in the past 

"Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded."

I hope you will give me the solution.

Thank you

**Comment by kyleada** [comment]
@manishrw @jacobscarter @webmas216 @dngad 
Sorry to see late.
I put all the dependencies of textAngular before "requirejs", when I move them after require.js, it worked.

**Comment by aaronroberson** [comment]
See #713.
