### ISSUE TITLE
TextAngular+RequireJs

### ISSUE THREAD

**Issue by daniele-zurico** [fraywing/textAngular#712]
Hello;
I'm trying to use TextAngular but without fortune.
This's my configuration:

require.config
  paths:
  ...
  'rangy-core': '../bower_components/textAngular/dist/textAngular-rangy.min'
  'textAngular-sanitize':'../bower_components/textAngular/dist/textAngular-sanitize.min'
  'textAngular':'../bower_components/textAngular/dist/textAngular.min'

shim:
 'rangy-core':
      exports:'rangy-core'
      deps: [ "angular" ]

    'textAngular-sanitize':
      exports:'textAngular-sanitize'
      deps: ['angular', 'rangy-core']

    textAngular:
      exports:'textAngular'
      deps: ['angular','textAngular-sanitize']

This is the error that I receive:
✘ rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded.

thanks

**Comment by daniele-zurico** [comment]
1.3.1 works perfectly!

**Comment by aaronroberson** [comment]
See #713.
