### ISSUE TITLE
Problem to work with browserify.

### ISSUE THREAD

**Issue by huuthonguyen76** [fraywing/textAngular#713]
Hi guys. I have problem when using textangular with browserify:
Cannot find module 'rangy' from '/opt/lampp/htdocs/blog/bower_components/textAngular/dist'.
Can you show me how to fix this

**Comment by pbassut** [comment]
rangy is required for textAngular to work. Make sure you're loading rangy BEFORE textAngular.

**Comment by huuthonguyen76** [comment]
Hi @pbassut. I think your way not work in this situation. I use those code below:
```javascript
  require('../../bower_components/textAngular/dist/textAngular-rangy.min.js');  
  require('../../bower_components/textAngular/dist/textAngular-sanitize.min.js');
  require('../../bower_components/textAngular/dist/textAngular.min.js');
```
But it still show the same error: Cannot find module 'rangy' from '/opt/lampp/htdocs/blog/bower_components/textAngular/dist'

**Comment by pbassut** [comment]
Did you also load ```rangy-core.js``` and ```rangy-selectionsaverestore.js```? 
Not sure if ```rangy-selectionsaverestore.js``` is required. But ```rangy-core``` sure is.

**Comment by huuthonguyen76** [comment]
Hi @pbassut. I've included those script like you said but it seems not work.
```javascript
  require('../../bower_components/rangy/rangy-core.min.js');
  require('../../bower_components/rangy/rangy-selectionsaverestore.min.js');

  require('../../bower_components/textAngular/dist/textAngular-sanitize.min.js');
  require('../../bower_components/textAngular/dist/textAngular.min.js');
```
Still happen: Cannot find module 'rangy' from '/opt/lampp/htdocs/blog/bower_components/rangy'

**Comment by pbassut** [comment]
Could you double check if ```../../bower_components/rangy/rangy-core.min.js```and ```../../bower_components/rangy/rangy-selectionsaverestore.min.js``` exists?

**Comment by huuthonguyen76** [comment]
@pbassut  :D it exists buddy.

**Comment by eirikb** [comment]
This works for me:

    require('./bower_components/rangy/rangy-core.js');
    require('./bower_components/textAngular/dist/textAngular-rangy.min.js');
    require('./bower_components/textAngular/dist/textAngular-sanitize.min.js');
    require('./bower_components/textAngular/dist/textAngular.min.js');

But what I want to do is: `require('textAngular');`, which I can do with the rest of my modules via debowerify.

**Comment by aaronroberson** [comment]
@eirikb Thanks for the workaround by putting rangy and rangy.saveSelection on the global scope. Hope this gets fixed soon!

**Comment by hiteshjoshi** [comment]
Thanks @aaronroberson !! that worked.

**Comment by caok2709** [comment]
Why...make the loading process such complecated....

**Comment by jskrzypek** [comment]
I think this fix broke browserify and webpack. They can't seem to read the `"main": : [
    "./dist/textAngular.js",
    "./dist/textAngular.css"
  ],`

bit in the `package.json` or something.

@aaronroberson  where have you seen this pattern of `"main"` as an array...? It seems like a massive anti-pattern to me if it causes browserify to break like this...

**Comment by aaronroberson** [comment]
You can use arrays in bower main as well as node/npm. However you must be
on an older version of node/npm/browserify. The old, requirejs way of doing
it is to use shims.

**Comment by aaronroberson** [comment]
The following works for me:
```

window.rangy = require('rangy');
window.rangy.saveSelection = require('rangy/lib/rangy-selectionsaverestore');
require('textAngular');
angular.module('app', ['textAngular']);
```


Although I agree it is not ideal.

**Comment by jskrzypek** [comment]
I'm on the latest version of browserify. 11.1.0.
Webpack fails too.

If I'm fetching a package from npm, I shouldn't need to use shims...

Another question is why is the CSS file in the `main`? What benefit does this provide. This seems like a really weird pattern for not-only-bower packages.

**Comment by aaronroberson** [comment]
textAngular requires several resources, including the CSS. As long as you have the css-loader you won't have to explicitly import/require/shim the CSS separately. Here is my plugin configuration:

```
module: {
      preLoaders: [{test: /\.js$/, exclude: [/node_modules/, /bower_components/], loader: 'jshint'}],
      loaders: [
        {test: /\.js$/, exclude: [/node_modules/, /bower_components/], loader: 'babel'},
        {test: /\.css$/, loader: 'style!css!postcss'},
        {test: /\.json$/, exclude: [/node_modules/, /bower_components/], loader: 'json'}
      ]
    }
```
I'm also using [bower-webpack-plugin](https://github.com/lpiepiora/bower-webpack-plugin) in my project. Here is my entire webpack.config if it helps:
```
var webpack = require('webpack');
var autoprefixer = require('autoprefixer-core');
var BowerWebpackPlugin = require('bower-webpack-plugin');

module.exports = function(watch) {
  return {
    entry: {
      app: './src/app.js'
    },
    output: {
      filename: 'app.js'
    },
    watch: watch,
    devtool: (process.env.NODE_ENV === 'production') ? 'source-map' : 'inline-source-map',
    module: {
      preLoaders: [{test: /\.js$/, exclude: [/node_modules/, /bower_components/], loader: 'jshint'}],
      loaders: [
        {test: /\.js$/, exclude: [/node_modules/, /bower_components/], loader: 'babel'},
        {test: /\.css$/, loader: 'style!css!postcss'},
        {test: /\.json$/, exclude: [/node_modules/, /bower_components/], loader: 'json'}
      ]
    },
    postcss: [autoprefixer({ browsers: ['last 2 version'] })],
    plugins: [
      new BowerWebpackPlugin({
        exclude: [
          /angular/,
          /angular-cookies/,
          /angular-sanitize/,
          /angular-resource/,
          /angular-messages/,
          /angular-translate/,
          /angular-touch/,
          /angular-mocks/,
          /jquery/,
          /bootstrap-sass-official\/.*\.js/,
          /bootstrap\.css/,
          /awesome-bootstrap-checkbox/,
          /font-awesome/,
          /.*\.less/
        ],
        searchResolveModulesDirectories: false
      }),
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery',
        moment: 'moment'
      }),
      new webpack.DefinePlugin({
        ENV_TEST: (JSON.stringify(process.env.NODE_ENV) === 'test') ? true : false
      }),
      new webpack.DefinePlugin({
        APP_VERSION: JSON.stringify(require('./package.json').version)
      })
    ],
    resolve: {
      modulesDirectories: ['node_modules'],
      extensions: ['', '.js', '.json', '.css']
    }
  };
};
```

**Comment by pbassut** [comment]
The css loading is done by the browser. What impact would cause if that was removed from the ```main```?

**Comment by jskrzypek** [comment]
If you want the CSS included you can add a require to it from within `textAngular.js`. Better yet if you add an exported method that requires the CSS on demand. On our side we don't actually even use the whole CSS file, just the bits we need, and those live inside our styles.

Using `main` with this array will break browserify. That is bad for a third-party package to do, *particularly* in the commit that is trying to **add** support for CommonJS, *et al.* The best option, if you really really want to load the CSS as well as the JS with just a single `require` on your config, is to add a different key in the package than `main`, that webpack will automatically understand and be happy with, i.e. one of these: [`resolve.packageMain`](http://webpack.github.io/docs/configuration.html#resolve-packagemains). That way both systems can be happy, which seems optimal. 

YMMV, but in my mind the biggest issue is not that there is no warning that upgrading to 1.4.4 will break my build system and not even that upgrading will require adding difficult-to-test config code to set up shims or `browser` aliases or something that I will then have to maintain. My biggest concern is that the error you get from browserify when it fails gives you no indication of which package is causing the exception to be thrown by resolve. I discovered this problem when I cloned our project into a new folder to do some testing on my home machine and ran an `npm i` thinking, naively, that if our app runs with its deps on my co-worker's machine, it should on mine. Instead I got the error I described in #870 and I had research the error and add some `console.log()`s to a sub-sub-dependency in order to figure out that textAngular had a new release and that the error I was seeing was caused by it. I got lucky and figured this out and was able to downgrade to a safe release. I don't know that everyone will.

**Comment by aaronroberson** [comment]
@jskrzypek I don't believe my original PR (https://github.com/fraywing/textAngular/pull/760) was merged in because another individual reported that it didn't work with Browserify and because there wasn't 100% testing coverage. However, something did get merged in on account of high demand.

Unfortunately, I have been swamped with a complete re-write of our application which as due to launch September 10th and I was unable to follow up and help.

Can you please look over the comments in my PR, create your own fork and apply your suggested fixes for Browserify and to ensure that all systems can live happily together? I believe your subsequent PR would be gladly received.

Thanks!

**Comment by pbassut** [comment]
@aaronroberson as a temporary fix, I removed the .css from the fix. And if @jskrzypek could provide this that would be really good.

**Comment by jskrzypek** [comment]
We're also busy with a big refactor and I have a lot on my plate in my off
time as well, but I will take a look tomorrow some time at your PR. I'll
try to find time to do as you ask in the next week or two.

**Comment by YangZhouChaoFan** [comment]
我也遇到同样问题，我的插件版本为
Angular 1.4.8
textAngular 1.4.6
rangy 1.3
requirejs 2.1.22

下面是我的解决方法：
1) 首先配置requirejs的配置文件
```
require.config({
    paths: {
        'angular': 'bower_components/angular/angular',
        'rangy-core': 'bower_components/rangy/rangy-core.min',
        'rangy-selectionsave': 'bower_components/rangy/rangy-selectionsaverestore.min',
        'textAngular-sanitize': 'bower_components/textAngular/dist/textAngular-sanitize.min',
        'textAngularSetup': 'bower_components/textAngular/dist/textAngularSetup',
        'textAngular': 'bower_components/textAngular/dist/textAngular'
    },
    shim: {
        'angular': {
            exports: 'angular'
        },
        'rangy-selectionsave': ['rangy-core'],
        'textAngular-sanitize': ['angular'],
        'textAngularSetup': ['angular'],
        'textAngular': ['angular', 'textAngular-sanitize', 'textAngularSetup']
    }
});

require(['rangy-core', 'rangy-selectionsave'], function(rangyCore){
    window.rangy = rangyCore;
});
```
2) 删除textAngular中run方法。

that's OK!

**Comment by drm-code** [comment]
@aaronroberson Thanks a lot bro, it worked like a charm

**Comment by aaronroberson** [comment]
Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy16yTYuBAdvhHKKSXGCRd7LUIpkPPAJnNDWPgYxIxCNgs5RnH1kxyReYX7QN99b4WJrhA-2FwCqIqPrt4jbVTAzyIr-2F7rLN-2FC35ee3tW-2F8YcyN4E5PnqXz6U2T87mOqzyjWzpWV6K8gTuBFXscypbtlolTwfVeAQabf0QRm7I1aHRFMoyrr0dbLvW9D7ouCRmNTKYqmkiWg51xnL9L-2FFNDZnC8i8pP-2Bx7MkwfhoFhdPTSsFm68K4y2k1IUTNp8vvnWooBOu5oe0X5mu2GyY0gXpT8O15n6D-2F3-2FOa5d2bSAwjJwQ-3D-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsY7cXUBwf9vcBN4RD1N0zjupvWyMPe0GyHp6qI14d-2FXzZdM2k-2FCrCqJkSpxhCdIrbyLid7O99ESMfJzN4EqsqFuWyQZHdZtZ61-2BIrjNwFzC52yEIx3U3np4vKM7cSBQzXw0zOybfAPqNZPFdRAHM82HQ-3D-3D )

Aaron sent you a $55 gift for Handy

With Handy, a spotless home is only a few clicks away. Just pick a service and choose a time—an experienced, background checked professional will take care of the rest. Click below to claim your $55 credit or use code AARON9231 at checkout.

Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy16yTYuBAdvhHKKSXGCRd7LUIpkPPAJnNDWPgYxIxCNgs5RnH1kxyReYX7QN99b4WJrhA-2FwCqIqPrt4jbVTAzyIr-2F7rLN-2FC35ee3tW-2F8YcyN4E5PnqXz6U2T87mOqzyjWzpWV6K8gTuBFXscypbtlolTwfVeAQabf0QRm7I1aHRFMoyrr0dbLvW9D7ouCRmNTKYqmkiWg51xnL9L-2FFNDZnC8i8pP-2Bx7MkwfhoFhdPTSsFm68K4y2k1IUTNp8vvnWooBOu5oe0X5mu2GyY0gXpT8O15n6D-2F3-2FOa5d2bSAwjJwQ-3D-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYFFM6NR2Y85oZgrth6c-2Bpzqz55VsdIoLuAuWuzHiikzyBQD2VpcyUL10CVZpIxBnGjmbHG8pp1qR1zmecZf-2BMkXCs7WLsiOp7K2lNE4BDp6h9wkSa-2FO30ZMQEo2m5qAmnooSWovMS-2B4ofs0dRBTBTLQ-3D-3D )
Use your $55 gift on any of Handy's services
(use code AARON9231 at checkout):

View all of Handy's Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MWDFialnox81TfwNCxNUNxhHKA-2BdMfFIp0irzQtrT5-2FC7EBZRmlTEE9RzPGGsa0-2BNerKUsc6-2FzrAdWKAQw-2BXzyldlAEwTjpfQF339Id5VSeQ2WO-2FQ9tSpKWE-2F-2BDilm3RY-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsY6YGxJByJgD33li717Z5luezdcHiOlfWetuaMBWW04qobdfmd-2BkKrpQkRK-2Fu3QnKZ4iK7o37YXolFT-2BJFI4llBQg3V71y4L-2BxyQX-2BMMY7RQp1dusJlORkJf8zhDZEccydLsy6S2d-2FldyRneE7tmtHCw-3D-3D )

Handy Twitter ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKaX-2FU2oXhnvLnp3gZfkeb2AF7vRpkoN40hgM4hNyDSth_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsY9jstXmPiUEjayxLOajJ3Ds82rKcxtj9VqvhLUWzIb7qDTQoEcP3SmfOxK4GZ8Iyuu-2FQPuRHviITOgAJ-2BncbVkyczGUHuEq37gPTxM07Fw0IlVM-2BVrsp9XDnKHebmezKjkLlJ5LzPemJkRhhdz8qkpg-3D-3D )
Handy Facebook ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfa9DXUWP0mdASikrPI0DmDoKViAyBoQIsV4x7PT02KC_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYVvEafxZxZIVYbQedH0kc82a6jvR1BFD8cSABmj6x1XYuzyRC1Vaqw3NQv27lKcVF-2FQF-2FjdjVQu19iBcRQFWIAL5KI-2BLBi10Wrw6SLL-2Bhv8XcwqitWjwnMsSGq826wbhXVuYI4QH0tVpA2S-2Fs5LXklA-3D-3D )
Handy Instagram ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfeBoaKL8Ev6spOpwM7gM6S-2F8a-2BuAMyY5qXEGPy9TRAc_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYMMsV82l9ab6x29anjQvxI0nAFKf0Cf6SVBrHoSCgEsEhdLZtk-2B-2B48YkmjSf9m3EMSYNs3UbKFc6GTbl40lcT6Bfiq30l5OZo2qu0naM-2F1dWLgsfAulFdriaqL4aZJhQ-2Fkf-2BrAB6gVk33qJTpPlDCow-3D-3D )

Our Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MQJ44OHPcJikSh-2BVUrFwzQO4xaArAScjwh7B1X-2Bws5DZzdjanMyViAICvTlcFLTkw-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYydQsmBDBl7cFcHkPQZryMSXVUyr2FdmOT3aAlT-2FhS46oSFYCzkWJp5k-2FPZOzlJUKnVGesew2dQmQDEeNZ5mF7O28eomHgmC5cAi0Ji11NKVahMQVC3Y41OxKECLYE8pDdpLm7FqVNqmv8Lz-2FAG4n9A-3D-3D )
helpcenter ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcse4Lp6fgbkd2iUk5hd2lBMUpBCYqNi1V7ydYheQ49Mw4W-2FJwIs-2FOCxm2wmUesDoFsLAcQPHKGpgX9GOqDdMK5RE-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYzo74tkuu7GK1S0emTGz8Tc7x7VPG65SwCSJzrDTJPvCKSKh3QYAe0gfI745S5IUnzOLgzaL6H0Y0rrkGzJ8hHdLjhBwgEYegbeegH9-2BnW0tph2F9RwJrDb9WgDy8r-2F1wXfYzdGsmvgi-2B1PXe-2Bvvv5w-3D-3D )
Download Handy iOS app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKe-2B4bz-2FAZDzUh1KL03FtyJ2uqoInuMQFjnKVNRO5FQSo-2FpakL1Y4hX85UGZ2zp5KD-2BI8hjWgTPijyltMY2jEortmwgrC-2F2r8jq6s0-2Bya9iXK_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYGeOqJymJrYVobnSTATviczSETmwoDHyFJh-2BAEvmKd8X71SrDrrYw5FgN1fRmXCEgFxyPLsvocBIV115YJl1atbPCdDBvY1NEQ192Tam1VLWGu7pfijC35wo0HaQjpMxRIfJqc2zQMJYAMdpz1dLuew-3D-3D )
Download Handy Android app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKeJcuYvtamgIYRZeccCPxkcFs2tKreRwShvBbhgLgpeznxEEVKVOltp8oC6Ig4DUHnf-2ByPOZsMz-2F8ivVr-2FUyO-2Fo-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYo8a7wKR-2B0b0ZoUF-2ByzmYuKV3WoBgHhPkOP2tHnVkR8fSzozJwavJNz9GXuK-2FH2I9-2FBSpNaEdYaaHjbURnDOs-2BZEDX8oGq6Uj7Css12vdVe53SazM694lO45DQ2P-2BR-2FSXKCCEx2bQKHg9GoKAUQYnbg-3D-3D )

Refer a Friend, Earn $50! ( xhttps://sgemail.handy.com/wf/click?upn=YsKWC7yTmiePOc2Pn-2Fa7R9V1Z-2FmspGRWKf5-2BNbJAcZuLZGz8MM1bTALYgBeeFogRy7AGwMT0R9RgzqFAR0taDV2mxNZC183vLo10oJ4jrl62VC5ZEK8f9-2FimJ4ErLRJFtBaPdxxGW4y5Kg4isuxRoVO-2BwMhi5auKgqzPwOAwtaY-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYSR9b6AmVwlzNntmc9u7Tij05RuG42N4vF9nW7NeTuqqA-2BRxtQiWZeSHLDLi5KYJeimvj8KSaJNu-2BQh1SF2olT5Cm5-2BG1J2DRoH0f1cUOJS-2F8LHxkx1WEU7aVdDJWFiO1gLAjfxfSUQ97Ttq-2BEYEKCQ-3D-3D )|Privacy Policy ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKXE0Lx8wVhm5qiHGXjJOgd7oLwhjwvzCLbE0HeWhRyGB_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYjNzfr4W8-2FB1i-2FNQ8jcEoHF9GHoavC0I6R-2F-2BcmP-2FNTKOBtwvWz-2FR8bCshfFJpokr8jsnIDJq5IQhU3jE4khBdx7HPohwfO4Tn35hEHYyHZics6IMolO45Wer09aMDy9uSIAthmznVFWv24lmcvLSXtA-3D-3D )|Unsubscribe ( https://sgemail.handy.com/wf/click?upn=wz-2FQ7Wmj26-2Boily69xWn-2FdB3gxvuT-2Fcn2o1CsCXSMqzTVlu8lrEjD2X6MEa5PfWykQXw3furN5FmkHriE7aMHmKwbCW-2FS1-2BiQ1UH29V4cSc-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYzexd91F7UvtCwgT1iYB4QccAI5GCBVXmMaDXjV-2BWNoS7Lir374UEClVaMEYd-2BWhR4WXt-2Fes4YviYKeRfsegAlxrxPj3sE1-2B0ZHCy0EJlxRJG20B2kaMdoqW7FGv954RQxvXnVRepHynCS020Xzhaig-3D-3D )

*By clicking this email, this allows us to send you the occasional marketing email, with goodies like special offers and limited-time services.
**Valid for new customers only. New customers receive $55 off their first booking. Must click through the 'Claim' url or use provided referral code, AARON9231, at checkout. Not combinable with other offers. Handy reserves the right to alter or end this promotion at any time, including but not limited to any noted discount amounts.

Handy, through the Handy platform, offers information & a method to obtain the above services, but does not itself provide these services. The provision of these services is up to the independent professionals, scheduled through the Handy Platform.
handy.com ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcseJZkXaGdRcWLa8SGTMwMTwgoOqsD8c4LW4PJHfa5XvNhV91IOu7BoVwnt-2FvzqlT3hviWxTDZJDtK9iqkY6Hnhk-3D_s5UH8bhnBaopYjthcNSRcXSFq0cZSGkPztcv6Ng3jT3Biz7jj9PCRxA1iMYx0rqd84fUwonG23koub-2FAEGQSK28MINDYmmU3ZMsHpB85DnCu7ot8dT1kZmxBKLk5DfW4xSWZ-2FMBTI8fEgQhdYtXD2BJRzMw0lMyZPfzGjGj1uHG67DY7omaGuwPi4mV48mOmDuiJuaurh6sYDg5hd0Oh-2BZNxTpGbRDd8AU1lmXrm0EIrAiCaV-2B5UrmnZJl66uKsYPIew8Mj6Lv4tKOa1bMKnjeixMhz3OwT8VnHm1VK8xUZ-2BFJUbSSzORI-2FziYZ-2B5t2zWoDFmz67SuKqATggDLoZjLm5uqqTL3t3sdZyv69IGGROHdvA394PlslTl8vt5sUebaBs-2FEpFvO0gSZaOiiYhug-3D-3D )
