### ISSUE TITLE
Changing default formatting button

### ISSUE THREAD

**Issue by ballanstewart** [fraywing/textAngular#714]
Maybe I am missing something but I'm attempting to set a specific instance of textAngular to start out using a 'ul' instead of a 'p'. I only want the user to make a list. But, I can't seem to figure out how to activate the 'ul' button by default.

**Comment by jshado1** [comment]
I'm not sure how to programmatically trigger those buttons, but [the setup wiki says](https://github.com/fraywing/textAngular/wiki/Editor-Setup-Options#data-attributes) if your model is empty and the innerHTML of the text-angular element is not empty, it will be instantiated with it, so you can use it as a template:
`<text-angular ng-model="your.model"><ul><li></li></ul></text-angular>`

If you want to have only the ul button in the toolbar (remove all the others), see [Defining the toolbar](https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar#defining-the-toolbar)

```html
<text-angular
  ng-model="your.model"
  ta-toolbar="[['ul']]"
  >
    <ul><li></li></ul>
</text-angular>
```

**Comment by jshado1** [comment]
Ah, so there is a directive for this: [`taTargetToolbars`](https://github.com/fraywing/textAngular/wiki/Directives)

> Evaluates to an array of toolbar names, all of these will be activated when the editor is focussed and will act on the editor.

**Comment by ballanstewart** [comment]
I remember trying `taTargetToolbars` but it never seemed to work like it seemed like it should. And, I mostly only made the toolbars crap out.

But, for whatever reason, it didn't cross my mind to instantiate with an empty list - lightbulb moment. It worked great. I appreciate it.
