### ISSUE TITLE
I am using text angular i want to bind my length of text area on key up is it possible

### ISSUE THREAD

**Issue by aggarwal12** [fraywing/textAngular#715]

**Comment by jshado1** [comment]
If you're referring to the content within the textarea, you can probably do with the value from ngModel:

```html
<text-angular
    ng-model="yourContent"
    ng-model-options="{updateOn: 'keyup'}"
    >
</text-angular>

<div>Length of content: {{yourContent.length}}</div>
```

**Comment by aggarwal12** [comment]
Hi, if i am calculating the length so i am getting the length with the html tag , means for example:-if my code is <p>gaurav</p>it is calculating the length 8 as it is taking both tag <p>and</p> i have used ta-bind but it is not working.Can anybody please help

**Comment by aggarwal12** [comment]
hi, if i am calculating the length of the content  i am getting the length more than the typed length because it is taking the length of the html tags .For ex <p> something </p> it is also calculating the length of p tag. I have also used ta-bind but it is not working can you pls tell.

**Comment by aggarwal12** [comment]
<div id="txtDescription" style="resize: none; margin-top: 10px; margin-bottom: 10px;"
						text-angular  ng-model="testComment.description"  on-keyup-fn="textlimitcheck"ta-bind="testComment.description">
						</div>
I am using like this

**Comment by pbassut** [comment]
You should strip the html tags first then. With something like $sce.trustAsHtml(html_string).

**Comment by nickknissen** [comment]
You can already do this by using the toolbar button `charcount` https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L699
