### ISSUE TITLE
Module 'rangy' not found in textAngular-rangy.min.js - textAngular 1.4.1

### ISSUE THREAD

**Issue by manishrw** [fraywing/textAngular#716]
When i tried in a standalone project (demo), it works fine. But when i tried to integrate it with my project, it says:
Module 'rangy' not found in textAngular-rangy.min.js

Below is the code, I use to include textAngular:
require('./bower_components/textAngular/dist/textAngular-rangy.min');
require('./bower_components/textAngular/dist/textAngular-sanitize.min');
require('./bower_components/textAngular/dist/textAngular.min');

P.S.  I've added textAngular as a dependency in my main app.
Thanks to help.

**Comment by dngad** [comment]
+1 same issue started very recently.

**Comment by jacobscarter** [comment]
Same issue, using 1.3.11 until a solution is created.

**Comment by manishrw** [comment]
Same here, using 1.3.11 till they solve it.

**Comment by aaronroberson** [comment]
+1

I also tried to `npm install rangy` and then require rangy (before textAngular like so:

```
require('rangy');
require('rangy/lib/rangy-selectionsaverestore');
```

Unfortunately, this results in the following exception:

`Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded.`

I'm using Webpack and I installed textAngular via npm.
