### ISSUE TITLE
Sometimes throw Type Error: "Cannot read property 'tagName' of undefined" once i click 'Clear Formatting' 

### ISSUE THREAD

**Issue by emmansun** [fraywing/textAngular#717]
When i clicked 'Clear Formatting' button, sometimes i will get below error:

loggerName: "Angular"
message: "Cannot read property 'tagName' of undefined"
stack: "TypeError: Cannot read property 'tagName' of undefined↵    at angular.module.factory.service._document (http://localhost:3000/client_modules/textAngular/dist/textAngular.js:563:28)↵    at n.textAngular.directive.link.angular.extend.wrapSelection (http://localhost:3000/client_modules/textAngular/dist/textAngular.js:1935:8)↵    at n.taRegisterTool.action (http://localhost:3000/client_modules/textAngular/dist/textAngularSetup.js:434:69)↵    at n.executeAction (http://localhost:3000/client_modules/textAngular/dist/textAngular.js:421:18)↵    at ib.functionCall (http://localhost:3000/client_modules/angular/angular.min.js:199:303)↵    at Ec.(anonymous function).compile.d.on.f (http://localhost:3000/client_modules/angular/angular.min.js:216:74)↵    at n.$get.n.$eval (http://localhost:3000/client_modules/angular/angular.min.js:126:15)↵    at n.$get.n.$apply (http://localhost:3000/client_modules/angular/angular.min.js:126:241)↵    at HTMLButtonElement.<anonymous> (http://localhost:3000/client_modules/angular/angular.min.js:216:126)↵    at HTMLButtonElement.c (http://localhost:3000/client_modules/angular/angular.min.js:32:389)"

<b>Angular Version:</b> 1.3.15
<b>textAngular:</b> 1.4.1
<b>Browser:</b>  Google Chrome 42.0.2311.135
<b>Operation System:</b>  Windows 7 Professional

**Comment by DoobleD** [comment]
Same issue for me. Also the CSS of my page breaks;

**Comment by stevokk** [comment]
Please provide a plunkr if you require assistance with this, the original report was submitted over a year ago.

**Comment by DoobleD** [comment]
@stevokk Thank you for answering. I updated my version of textAngular (I was using 1.5.0) and the bug doesn't seem to occur anymore.
