### ISSUE TITLE
DOMException: INDEX_SIZE_ERR thrown when interacting with html-view in IE

### ISSUE THREAD

**Issue by kaizerroll** [fraywing/textAngular#721]
### Bug + Repro Steps

**Issue**: This issue primarily boils down to standard usage of textAngular in Internet Explorer, where an exception is being thrown that ideally should not, though it is unclear if there is any truly negative, unintended effect, or if the exception is just thrown where it should be caught and handled.

**Repro**: Can actually be reproduced using the standard plunker example [here](http://plnkr.co/edit/tpl:RaBEszV5xrAZ0VRoZ7PM?p=preview)

*Repro steps are:*
1. Focus textEditor window
2. Toggle the rich-text/html-view button on (i.e. into html-view mode)
3. Unfocus the textEditor window
4. Refocus the textEditor window

At this point the error 'DOMException: INDEX_SIZE_ERR' should be thrown.

These steps are repeatable, where the exception is rethrown every time the textEditor in html-view is refocused.

**Fix**: I'm almost positive this is coming from textAngular-rangy.js and the issue is that the html-view doesn't have the rangy object connecting to it properly, so some index value is coming back -1

**Work Around?** While the bug stands, any means of catching the exception myself would also be useful.

### Environment Info

* **Angular Version**: 1.3.11
* **TextAngular Version**: 1.4.1, using textAngular-rangy + textAngular-sanitize
* **Browser**: This issue only seems to effect me in Internet Explorer (latest). Confirmed no error with Chrome (latest).
* **Related**: Very similar - https://github.com/fraywing/textAngular/issues/360

**Comment by mak962753** [comment]
It seems rangy does not work on textareas/and inputs at all. but in case when IE is used rangy throws an exception (it happens in rangy-core.getSelection function). so probably it would be possible to somehow remove rangy usage when the textAngular is in html view mode.

**Comment by pbassut** [comment]
@bac1087 Didn't the solutions on the provided related issue work for you? At the end it wasn't TA's fault with the two people in there.

**Comment by bac1087** [comment]
I think it is correct that the issue is happening with Rangy, though after some various attempts I was unable to correct the issue, likely because I'm not that familiar with how Rangy works, and couldn't seem to disable it in such a way that the underlying TextAngular calls wouldn't still throw the  INDEX_SIZE_ERR exception. 

My current solution is to simply catch that exception in the root of my project and suppress it, though I don't think that's really a 'fix' by any means.

**Comment by JoelParke** [comment]
<p>I am not able to reproduce this error with TA v1.5.11 and iExplorer 11.0.35<br/>Please reopen if still an issue.</p>
