### ISSUE TITLE
Not showing any options

### ISSUE THREAD

**Issue by miqdadalik** [fraywing/textAngular#729]
Why its showing like this?

Getting console error while clicking buttons

TypeError: Cannot read property 'getSelection' of undefined

TypeError: Cannot read property 'saveSelection' of undefined

Angular version: 1.3.15
textAngular version: 1.4.1
font-awesome-4.3.0
bootstrap 3.3.4

![error](https://cloud.githubusercontent.com/assets/8424930/8145476/c3a3bb40-1226-11e5-81d6-c08bb40cfafa.png)

**Comment by plumpNation** [comment]
Is it replicable in a fiddle or a plunkr? Always helps to isolate the problem :)

**Comment by episodeyang** [comment]
I think some library code was not included properly for this issue. If you still have the issue, comment below.

**Comment by abhishekBansal** [comment]
I am also facing this issue. I am working on angularjs and rails project with bower to manage front end dependancies. font-awesome is there as bower installed it with textangular but i can't seem to make it work. I have imported font-awesome in my `application.scss` still it doesn't seem to find required fonts.

**Comment by pbassut** [comment]
@abhishekBansal Could you set up a plunkr to replicate the issue?
If you can't replicate on a plunkr it means you're doing something wrong.
I suggest removing the library and adding it from the start.

**Comment by abhishekBansal** [comment]
@pbassut I removed font awesome downloaded by bower during text-angular install and used `font-awesome-saas` rails gem instead, which solved the issue for me. The actual issue was app was able to find font-awesome lib but not fonts. Thanks !

**Comment by pbassut** [comment]
@abhishekBansal Awesome, then!
