### ISSUE TITLE
Activating Bold and then Italic puts both in activated state 

### ISSUE THREAD

**Issue by RanjeetR** [fraywing/textAngular#732]
If the user writes text in bold, italic, or underlined, adds a space, deselects the style and then attempts to select another style, both the newly selected style and the original style buttons become selected. 

For example : -  if the user writes some text in bold, presses space, deselects bold and selects italic, both bold and italic will be selected. When the user then attempts to deselect bold, both buttons will become deselected. These buttons should function separately. This issue was only seen to occur if the user puts a space after the word with a style still selected.

Tested on IOS 7.1 , IOS 8.0 , IOS 8.3

**Comment by RanjeetR** [comment]
This issue is not present in older version like i have checked in v1.2.2 its working fine but in newer version this issue is present .

http://plnkr.co/edit/Wu1mc0v5bbuoLkvvDb9V?p=preview

**Comment by amitdoshi** [comment]
Hi,

Can you please update on this issue. I am also facing this issue.

Thanks!

**Comment by pbassut** [comment]
This bug proceeds. I'll look into it.

**Comment by amitdoshi** [comment]
Thanks. Please look into this and let me know whenever it get resolved.

**Comment by radiart** [comment]
This bug is serious, I need to switch to another text editor because of that.

**Comment by amitdoshi** [comment]
True , I am also awaiting for this bug to get resolved. Any update?

**Comment by pbassut** [comment]
I'm looking into it. I'll finish it today. And should be available in the next release.

**Comment by amitdoshi** [comment]
Great.. ! Thank you so much :)

**Comment by pbassut** [comment]
Sorry I was unavailable for a couple of days. I'm solving this at the very moment.

Problem is, when you add a space queryCommandState still returns true because technically you're still on bold mode(because you didn't insert any non-bold text).

I'm not sure what I should do about this.

**Comment by pbassut** [comment]
UPDATE:
Actually, this happens because the editor gets focus again and queryCommandState is trigger and falls in the process I describer previously.

Meaning if you use the key bindings(Command+B and Command+I), it works as expected.

**Comment by RanjeetR** [comment]
@pbassut Thanks for update , we will try to trick this with the help of information you have provided .

**Comment by JoelParke** [comment]
This is mostly fixed with PR #1289
