### ISSUE TITLE
Tab and Shift-Tab for Indent and decrease-indent

### ISSUE THREAD

**Issue by JoelParke** [fraywing/textAngular#734]
I am very used to using Tab and Shift-Tab to increase and decrease my indent of items from using MS word in the long past.  

So, should there be commandKeyCode's added to 

    taRegisterTool('indent'....) and 	
    taRegisterTool('outdent'...), 

or do others end up needing the tab and shift-tab when editing?  

Without those, tab and shift-tab causing my focus to jump to other content in the browser which is VERY annoying -- since my muscle memory causes me to use tab and shift-tab :-).  And when the editor is active, I am not sure this is a good thing.  Any opinion on this??? 
Perhaps having an option??? to enable or disable this?

**Comment by JoelParke** [comment]
So I wanted to try this -- so I did a few small hacks...
Until the issue with Rangy #733 is fixed, this too has the same issues.
 
To handle the Tab and Shift-Tab I modified _keydown slightly to detect the shift key and tell textAngular that this was from a metaKey and if the shiftKey was pressed, to set the event.which to 999999:

    // start updating on keydown
    _keydown = function(event){
      if (event.ctrlKey===false && event.metaKey===false && event.keyCode==9) {
        event.preventDefault();
        //console.log(event);
        if (event.shiftKey) {
          event.which=999999;
        }
        event.metaKey = true;
        _keypress(event);
      }
      /* istanbul ignore next: ie catch */
      if(!scope.focussed){
        scope._bUpdateSelectedStyles = false;
        return;
      }
      /* istanbul ignore else: don't run if already running */
      if(!scope._bUpdateSelectedStyles){
        scope._bUpdateSelectedStyles = true;
        scope.$apply(function(){
          scope.updateSelectedStyles();
        });
      }
    };

Then in textAngularSetup - I added commandKeyCode's to 'indent' and 'outdent'

    taRegisterTool('indent', {
      iconclass: 'fa fa-indent',
      tooltiptext: taTranslations.indent.tooltip,
      action: function(){
        return this.$editor().wrapSelection("indent", null);
      },
      activeState: function(){
        return this.$editor().queryFormatBlockState('blockquote');
      },
      commandKeyCode: 9
    });
    taRegisterTool('outdent', {
      iconclass: 'fa fa-outdent',
      tooltiptext: taTranslations.outdent.tooltip,
      action: function(){
        return this.$editor().wrapSelection("outdent", null);
      },
      activeState: function(){
        return false;
      },
      commandKeyCode: 999999
    });

**Comment by pbassut** [comment]
I'm also used to that feature. I think it's annoying when the focus changes to another element in a textarea for example. I'll test your code and I think if you make a PR @SimeonC might accept it. That's a pretty standard feature.

**Comment by episodeyang** [comment]
I have working code, there was a PR a long time ago. But I wasn't able to write the full test so it was never merged.

When you do this, the proper way is to traverse the DOM and look up the closes block/list element. It is not simple to get right.

**Comment by JoelParke** [comment]
The question seems to be: do we build on top of rangy -- since rangy's mission is somewhat this same problem.  OR is it worth re-inventing the problem/solution since textAngular content is a bit more specific.

**Comment by JoelParke** [comment]
I have submitted a pull request... Of course this does not address the Rangy issues.

**Comment by episodeyang** [comment]
@JoelParke , the code is bit too hacky.

First of all: I think everyone would need tab and shift-tab to behave the way you specified. I think it is worth a PR
second, the right way is to have the `keyup` handler call the `indent` and `outdent` execCommand. This in turn requires implementing those two execCommand functions properly. 

Currently the browser implementations for 'indent` and `outdent` are all wrong. This is why couple of hundred lines of code is needed for that. 

Mutating the event is a very clever way to achieve what you want in the short term. It shouldn't be part of the library code. The right way is outlined above.

**Comment by JoelParke** [comment]
I attempted to confine my changes to only enable the execution of the existing toolbar item.  In that way it is very clean.  

Since the indent and outdent is incorrect (as we have all noticed), it's clear that the way that Rangy has been used isn't the whole solution.  So I agree that save/restore should be fixed.  

Having thought more about how to connect to tab and shift-tab, I don't feel like what I did actually hacky, except that the tab and shift-tab keys don't generate keypress events.  So perhaps you are suggesting that we generate keypress events on tab and shift-tab -- but since this goes against what jquery did, I don't think that is a good idea and feel like what I did is perhaps the best compromise.

Ultimately I very much like the way textAngularSetup only uses commandKeyCode to connect to short-cut keys. In this way, it is very clear to anyone in the future adding their own tool, how to connect to a shortcut key.    

Do you have an existing replacement for Rangy -- i.e. one that is fool-proof?

**Comment by JoelParke** [comment]
Updated the code to support this.
