### ISSUE TITLE
textAngular-rangy.min.js requires require

### ISSUE THREAD

**Issue by shusain** [fraywing/textAngular#737]
Having a problem when I bumped versions of textAngular it seems the 1.4 version has a dependency on RequireJS via the textAngular-rangy.min.js  I keep getting errors to the effect of:

ReferenceError: require is not defined

when I try running my tests.  Strange thing is this doesn't seem to show it's face anywhere when I'm just actually running my site in a browser.

Just figured out if I use rangy directly instead of using the minified file it works used this in my files array in karma.conf.js
```
      'app/bower_components/rangy/rangy-core.js',
      'app/bower_components/rangy/rangy-selectionsaverestore.js',
```

Anyhow would be good to have a solution that doesn't require me to add rangy separately ideally, but this works for now.  Thanks for the well done RTE in angular.

**Comment by illumimari** [comment]
+1

I am having the same issue

**Comment by sercangurbuz** [comment]
+1

**Comment by aaronroberson** [comment]
+1

When using with Webpack I get the following error:

```
ERROR in ./~/textangular/dist/textAngular-rangy.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./rangy-core in /node_modules/textangular/dist
 @ ./~/textangular/dist/textAngular-rangy.min.js 2:15430-15456
```

**Comment by princejwesley** [comment]
+1
