### ISSUE TITLE
Programmatically set focus to textangular

### ISSUE THREAD

**Issue by worldspawn** [fraywing/textAngular#74]
Hi, I am trying to set focs to the textangular box so the user should be able to type immediately after.

Skimming the code it looks like

```
element.triggerHandler('focusin')
```

Should do it but it doesn't. This is running from a separate directive applied to the same element as the textAngular directive. Any ideas on how to do this? Also tried

`element[0].focus()`
`element.triggerHandler('focus')`

**Comment by rogercampos** [comment]
I think it's worth mentioning in this issue, for future reference, that the caret will be positioned at the beginning of the contenteditable by default when doing `editorScope.displayElements.text[0].focus();`. 

To restore it to the previous position you need to manually save it and restore it, like it's done here https://github.com/fraywing/textAngular/blob/3269705824087e5773272aea9fa4831537913e07/src/main.js#L391. 

```
// your custom action begins, save current position
_savedSelection = $window.rangy.saveSelection()

// ... now your custom action ends and needs to introduce content in the editor
editorScope.displayElements.text[0].focus();
$window.rangy.restoreSelection(_savedSelection);
```
