### ISSUE TITLE
[bug] taSelection.insertHtml can not insert '\n'

### ISSUE THREAD

**Issue by episodeyang** [fraywing/textAngular#754]
other non-empty text are fine.

**Comment by pbassut** [comment]
Wouldn't it be '<br>' to break a line?

**Comment by episodeyang** [comment]
It is inside a pre block in fact. So I did try br, but it didn't work.

**Comment by episodeyang** [comment]
I am looking into the code. If I submit a PR soon, can you guys merge it?

**Comment by episodeyang** [comment]
This one should be reletively simple, or I hope.

**Comment by pbassut** [comment]
@episodeyang Any progress on this?

**Comment by ivschukin** [comment]
guys fix please

**Comment by JoelParke** [comment]
<p>This is now corrected with PR #1356 and will be part of the next release. Sorry this took so long!!!</p>
