### ISSUE TITLE
Bold/italics/underline don't change their state to active

### ISSUE THREAD

**Issue by ByteMug** [fraywing/textAngular#757]
When I click on each of them, they don't become active, so I can't write i.e. bold text.
When I select a portion of text and click on one of them, they work fine, but I can't turn them off
![image](https://cloud.githubusercontent.com/assets/4204494/8305336/50f3ff4e-19ae-11e5-80e8-97f819cfc357.png)
v1.4.1
Thanks

**Comment by kaloyan-chernev** [comment]
I am having the same issue. Hope there will be a fix soon.

**Comment by pbassut** [comment]
Guys, look at this [plunker](http://plnkr.co/edit/tpl:RaBEszV5xrAZ0VRoZ7PM?p=preview). It works just fine for me.

**Comment by nickknissen** [comment]
If this is i fixed, it should be marked as resolved
