### ISSUE TITLE
DOMException: INDEX_SIZE_ERR in Safari when clicking on textarea

### ISSUE THREAD

**Issue by peterjkirby** [fraywing/textAngular#762]
When using textAngular in a Safari browser on Mac, attempting to click on any portion of the textarea of the editor results in a DOMException: INDEX_SIZE_ERR exception being thrown. The editor is in an unfocused state prior to interaction with it.

The steps to reproduce are identical to those described in this closed issue: https://github.com/fraywing/textAngular/issues/360

Browser: Safari 8.0.6
OS: OS X Yosemite 10.10.3

Additional potentially relevant information:
- The editor is embedded in an angular bootstrap ui modal window
- The editor is embedded within a directive

The stack trace printed in the Safari console displays:
getRangeAt - textAngular-rangy
getSelection - textAngular
mouseup - textAngular
dispatch - jquery
handle - jquery

The getSelection function looks as follows:

```
var api = {
    ...
    getSelection: function(){
        var range = rangy.getSelection().getRangeAt(0);
        var container = range.commonAncestorContainer;
        var selection = {
            start: brException(range.startContainer, range.startOffset),
            end: brException(range.endContainer, range.endOffset),
            collapsed: range.collapsed
        };
    
        // Check if the container is a text node and return its parent if so
        container = container.nodeType === 3 ? container.parentNode : container;
        if (container.parentNode === selection.start.element ||
            container.parentNode === selection.end.element) {
            selection.container = container.parentNode;
        } else {
            selection.container = container;
        }
        return selection;
    }
    ...
```

I played around with the getSelection function a bit and found that on browsers where no exception is thrown, rangy.getSelection().rangeCount has a value greater than 0. In Safari, however, the rangeCount is equal to 0.

I am not familiar with the rangy library, so I'm not sure if the above observation is helpful or obvious. 

If you need any additional information, let me know and I'll post it ASAP.

**UPDATE AND SOLUTION**
The issue was the result of the following CSS rule:

    body {
        -webkit-user-select: none;
        -moz-user-select: -moz-none;
        -ms-user-select: none;
        user-select: none;
    }

Removing these rules fixed the issue described above.

For those interested about why user-select CSS rules effect contenteditable in Safari browsers, please read [this question on StackOverflow](http://stackoverflow.com/questions/20823468/user-selectnone-breaking-safari-contenteditable)

**Comment by nickknissen** [comment]
If your solution fixed the problem i'm going to close this issue

**Comment by amolc** [comment]
Hello guys, thanks for this awesome library. I am facing the same issue as above like @peterjkirby. As he mentioned that removing the above css fixed the issue. But I don't have the above css anywhere so can you guys help me with this?

**Comment by krishcdbry** [comment]
I am facing the same issue even after removing those CSS lines. I actually have two contenteditable div's in which one is working after removing the 
`user-select` stuff but the textAngular is still giving the error **DOMException: INDEX_SIZE_ERR**

Any help would be appreciated. Thanks !
