### ISSUE TITLE
Regression with using multiple instances of textAngular on the same page

### ISSUE THREAD

**Issue by Omer** [fraywing/textAngular#763]
The recent version of textAngular (since Rangy became a hard dependency) appeared to introduce a regression when using multiple instances of textAngular on the same page.

**Plnkr examples:**
* [textAngular v1.2.2](http://plnkr.co/edit/N5ZhBPNXE9WVfb58YG7S?p=preview)
* [textAngular v1.3.7](http://plnkr.co/edit/5SKbenboNQCEsTv91xSu?p=preview)

**Steps to reproduce:**
* Add 2 instances of textAngular to a single page.
* Set the focus on the first directive.
* Set the focus on the second directive.
* Set the focus back to the first directive.
* Write something.
* Click on any of the buttons in the toolbar.
* *Note how the focus is lost (and the changes are discarded) in the recent version of textAngular.*

**Comment by hukkelaas** [comment]
This also happens when using textAngular and an input text field.

**Comment by pbassut** [comment]
So the bug is only on the second plnkr. I don't see any changes being discard. But I see the focus being lost, though. 

What browser are you using?

**Comment by Omer** [comment]
Sorry for being vague in my original bug report. When referring to "the changes being discarded" I should have probably said not being applied before the loss of focus. As for the browser, I am using Chrome / latest / Mac, but also tested on Firefox / latest / Windows  and Chrome / latest / Windows.

Finally, I have noticed a much a larger regression since my original bug report which can be easily reproduced using the steps below.

**Steps to reproduce:**

* Add 2 instances of textAngular to a single page.
* Set the focus on the first directive.
* Write something.
* Set the focus on the second directive.
* Write something.
* Click on "clear formatting"
* See the page falling apart, and the following error message in the console:

```
TypeError: Cannot read property 'tagName' of undefined
    at http://cdn.jsdelivr.net/g/angular.textangular@1.3.7(textAngular-rangy.min.js+textAngular-sanitize.min.js+textAngular.min.js):51:8944
    at k.angular.extend.wrapSelection (http://cdn.jsdelivr.net/g/angular.textangular@1.3.7(textAngular-rangy.min.js+textAngular-sanitize.min.js+textAngular.min.js):51:31411)
    at k.a.action (http://cdn.jsdelivr.net/g/angular.textangular@1.3.7(textAngular-rangy.min.js+textAngular-sanitize.min.js+textAngular.min.js):43:8223)
    at k.executeAction (http://cdn.jsdelivr.net/g/angular.textangular@1.3.7(textAngular-rangy.min.js+textAngular-sanitize.min.js+textAngular.min.js):51:6085)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:176:141
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:193:165
    at k.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:112:319)
    at k.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:113:48)
    at HTMLButtonElement.<anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:193:147)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:31:225(anonymous function) @ angular.js:9959
```

**Comment by pbassut** [comment]
This is a serious bug. Thanks for reporting. 

I'm working on something else now so I won't be to pick this issue. But as soon as I finish I'll investigate this.

**Comment by BannedForLife** [comment]
+1

**Comment by bZichett** [comment]
Any word on this issue?  I'm surprised many others aren't chiming in (perhaps they don't check the bug reports.)  Anyway, this is hurting me real bad.  Specifically editors lose focus on first attempt to press a button, and clear formatting completely annihilates the page depending on the tags occurring in the html 

I've also noticed that if two editors are instantiated, the former one has issues with bringing the focus to before the first element.  I'm pretty sure it's related.  If someone can point out where/how this might be happening I'd be more than happy to help with a fix.

**Comment by bZichett** [comment]
Any word on this issue? I'm surprised many others aren't chiming in especially since I'm using the most recent version 1.4.6 on Chrome (perhaps they don't check the bug reports.) 

Anyway, this is hurting me real bad. Specifically editors lose focus on first attempt to press a button, and clear formatting completely annihilates the page depending on the tags occurring in the html

I've also noticed that if two editors are instantiated, the former one has issues with bringing the focus to before the first element. I'm pretty sure it's related. If someone can point out where/how this might be happening I'd be more than happy to help with a fix.
