### ISSUE TITLE
Header buttons different style to all the others

### ISSUE THREAD

**Issue by dreadeddev** [fraywing/textAngular#764]
I realise that headers are structural and not formatting but to the average user there is no different, can we make all buttons look the same somehow as the current implementation does look a bit odd if you only have one header style allowed.... see pasted image
![image](https://cloud.githubusercontent.com/assets/9987089/8374260/d459a2d2-1beb-11e5-9a83-39704b06612f.png)

**Comment by pbassut** [comment]
This looks like it's material design. Although I'm not sure. But someone at #625 converted everything to angular material. So, yeah, it's possible and fairly heavy work depending on what level you want to customize it.
