### ISSUE TITLE
Proper way to use taExecCommand

### ISSUE THREAD

**Issue by mattjameswdd** [fraywing/textAngular#771]
I'm trying to write my own toolbar button to allow the user to upload an image before insert it into the editor, and everything is fine in Firefox.  But, when I jump to IE, nothing happens.

Here's my base code as it stands:
```
$provide.decorator('taOptions', ['taRegisterTool', '$delegate', '$modal', function (taRegisterTool, $delegate, $modal) { // $delegate is the taOptions we are decorating
	taRegisterTool('localImage', {
		iconclass: "fa fa-picture-o",
		action: function () {
			var editor = this.$editor();

			var modalInstance = $modal.open({
				templateUrl: '/Main/ImportImage',
				controller: 'ImportImageController'
			});

			modalInstance.result.then(function (imageName) {
				editor.wrapSelection('insertImage', imageName);
			}, function () {
			});
					
			return;
		}
	});

	$delegate.toolbar = [
			['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'quote'],
			['bold', 'italics', 'underline', 'strikeThrough', 'ul', 'ol'],
			['justifyLeft', 'justifyCenter', 'justifyRight', 'indent', 'outdent'],
			['localImage', 'insertLink']
       	];

	return $delegate;
}]);
```

I tried changing the editor.wrapSelection call to be 
```
taExecCommand('insertImage', false, imageName)
```
but then nothing happened in either browser.  I added the injection to call so that I avoid the missing object errors, but still get nothing.

Is taExecCommand documented any where that I'm not seeing?  What is the proper usage for my scenario?

**Comment by JoelParke** [comment]
Matt, what version of IE is not working? And does Chrome, etc. work?

**Comment by nickknissen** [comment]
I did something similar but had a problem with modal switching selection. Try
```javascript
taRegisterTool('localImage', {
        iconclass: "fa fa-picture-o",
        action: function (deferred, restoreSelection) {
            var editor = this.$editor();

            var modalInstance = $modal.open({
                templateUrl: '/Main/ImportImage',
                controller: 'ImportImageController'
            });

            modalInstance.result.then(function (imageName) {
                restoreSelection();
                editor.wrapSelection('insertImage', imageName);
                deferred.resolve()
            }, function () {
            });

            return false;
        }
    });
```
See #54 and #146

**Comment by mattjameswdd** [comment]
@nickknissen - that did what I needed!  Thanks for the help!

**Comment by pbassut** [comment]
@mattjameswdd Could you still say what version of IE was it? Just in case @JoelParke wants to take a quick look at it and remain the issue opened.

**Comment by mattjameswdd** [comment]
Under Windows 8.1, I tried IE11 (failed), Chrome 43 (failed) and Firefox 38 (worked).  Once I made the changes Nick recommended, all of these browsers worked as expected.

**Comment by JoelParke** [comment]
Okay -- I am closing this issue -- please reopen if needed.
