### ISSUE TITLE
Paragraph tag on every keystroke

### ISSUE THREAD

**Issue by randallto** [fraywing/textAngular#772]
Working in latest chome, the editor, upon any keystroke, inserts a paragraph tag at the top, making the editor unusable. Using angular 1.3.15

**Comment by pbassut** [comment]
Could you set up a plnkr reproducing this issue?

**Comment by JoelParke** [comment]
I've never seen this sort of behavior.  Has it persisted? and is this Windows? Ubuntu?

**Comment by randallto** [comment]
It was a plain angular site. I could not figure it out. We scrapped the rich text editor.

**Comment by JoelParke** [comment]
Closing this for now, and it is not reproachable... and seems that randallto has moved on. Please re-open if this reoccurs.  Or in there is more information to add.
