### ISSUE TITLE
Alignment behaviour broken in Firefox, inconsistent between browsers

### ISSUE THREAD

**Issue by mathrick** [fraywing/textAngular#776]
Tested in FF 38 and 39:
### Steps
- Go to http://textangular.com/
- Click somewhere on one of the list items (any will do)
- Click the "align: centre" button
  - Observe the alignment toolbar buttons
- Afterwards, try selecting the whole list, then centring it
### Results
- The list item number will stay on the left, and the left alignment button will remain selected and unclickable. Works fine in Chrome (but see below)
- When the whole list is centred, the item from first step will have its number stay on the left, whilst all the others get centred. Works fine in Chrome (but see below)
- Additionally, in Chrome the numbers always stay left-aligned (which itself looks like a bug), whilst in Firefox they're centred, so it's inconsistent

**Comment by pbassut** [comment]
Unfortunately, this error proceeds. It might be only a css-related issue. I'll look into it in a while.

**Comment by JoelParke** [comment]
I will take a look at in a while.  But I can already tell some of this is Firefox stuff and probably can't be fixed.

**Comment by JoelParke** [comment]
<p>This is now corrected.  So closing this issue 1.5.13</p>
