### ISSUE TITLE
Cursor position after clicking on custom button

### ISSUE THREAD

**Issue by Awelemdy** [fraywing/textAngular#781]
I have set up a bunch of custom buttons using the taRegisterTool like this:
```
taRegisterTool('somebutton', {
            buttontext: "Some button text",
            action: function(){
                this.$editor().wrapSelection('inserthtml', 'buttontext');
            }
});

```
This works very well. The problem is that after the text is inserted, the cursor is behind the inserted text. For instance:
` some text I am working it xxxbuttontext`. 
The cursor was originally at position xxx and after inserting the custom buttons, it is still at xxx. Any idea what could be causing this? I have been googling for this issue.

**Comment by pbassut** [comment]
So, you're saying you have a button that inserts some text into TA but when the text is inserted, the cursor should change it's position too. But it doesn't, right?

**Comment by Awelemdy** [comment]
Yup, that's the issue

**Comment by pbassut** [comment]
Well, it works fine for me using 1.4.1 with angular 1.2.19.
Could you set up a plunkr?

**Comment by episodeyang** [comment]
Hi @Awelemdy If possible, you can use this plunkr as a template to reproduce your bug.
http://plnkr.co/QkKYLlFuFtrvhjptuGA1

Let us know if the bug still exist with 1.2.19

**Comment by Awelemdy** [comment]
Thanks for the template. I am using text angular 1.4.1, angular 1.4.0. Here is a link to my plunkr: http://plnkr.co/edit/HYpQQi5chADQf0NXlaMQ?p=preview

If I switch to an earlier version of text angular like 1.3.7, it works.

**Comment by nickknissen** [comment]
I wouldn't call this a bug. But expected behavior in 1.4.1  
After `action` is called `endAction` is triggered which does `$window.rangy.restoreSelection(_savedSelection)` for textAngular v1.4.1.
This is fixed in master branch and you will have to wait for the next release.

For a temporary fix you can call `restoreSelection()` before inserting html.  
 See my plunker: http://plnkr.co/edit/wh2boedblcKehC5A2Jda?p=preview

**Comment by Awelemdy** [comment]
Thanks, will use the temporary fix till the next release.
