### ISSUE TITLE
Collaborator and git messages

### ISSUE THREAD

**Issue by nickknissen** [fraywing/textAngular#783]
Now that @SimeonC is not the only one committing to this repository it is important to follow [guidelines for contributing](https://github.com/fraywing/textAngular/blob/master/CONTRIBUTING.md) and be strict about it. 
A small problem not following the guideline has caused the changelog not being able to auto generate when using `grunt release`

**Comment by JoelParke** [comment]
Thanks nick... One slight issue is that github -- when you merge a pull request, and you add the right sort of comment, it just puts 'Merged with...' ahead of your added comment.  So for now, I will just edit the changelog.md as I follow the release process.  
Do you know if there is a better grunt-changelog plugin that can search the 'git log' for the standard changelog messages?  and it if worth updating that? -- If I did this enough times I would probably just write something to pull those out with a bit more flexibility.

**Comment by SimeonC** [comment]
Joel - if you merge on GitHub you can edit the message, same as if you merge via cmd line. I think webstorm is the only one you can't (webstorm's VCS is utter trash sadly).

**Comment by JoelParke** [comment]
Thanks... things will get better :-)

**Comment by nickknissen** [comment]
Things are better now :+1:
