### ISSUE TITLE
Paste Rich Text does not work (from Word, Outlook)

### ISSUE THREAD

**Issue by agilepro** [fraywing/textAngular#786]
As far as I can tell, copying text from MS Word, or MS Outlook, does not preserve any formatting at all, and you get just a single big paragraph will all the un-styled text within it.  Am I doing something wrong?
Previously I have been using TinyMCE as the editor, and I switched to textAngular to get all the cool Angular features, however not being able to paste from a Word copy is becoming a real limitation.  I see others discussing the capability as if it existed, so I am wondering whether I am doing something wrong.
I did a test with the demo at http://textangular.com/ and found the exact same behavior.   
Here is text in Word:
![wordcut1](https://cloud.githubusercontent.com/assets/5544889/8583974/baf3ef92-2586-11e5-8068-dfae5a89e6f2.PNG)
When that is selected and pasted into the sample at textangular.com it looks like this:
![wordcut2](https://cloud.githubusercontent.com/assets/5544889/8583980/d69806a2-2586-11e5-8e00-74800857b742.PNG)
Am I doing anything wrong????

**Comment by agilepro** [comment]
I am using the latest Firefox.

**Comment by pbassut** [comment]
What version of textAngular you're using? Pasting from MSWord should do completely fine.

The version on the demo is 1.2.2 which is outdated(there's an issue to update this in the next release, don't worry).

I just tested here and it works fine. I can plunkr a test if you want too.

**Comment by pbassut** [comment]
I tested from Word for Mac. Are you using windows?

**Comment by agilepro** [comment]
Yes, on windows 7.  I am using a version of textAngular that I downloaded about four weeks ago labeled Version 1.4.1.   I tried again just now from a different computer (Windows 7 again) and in Firefox.  In this computer I don't have MS Word, and instead selected text from Open Office Writer and got the same result -- all the formatting is removed.

If I use Chrome, it works much better (essentially perfect -- just a few strange glitches)  And Internet explorer worked OK as well.   But Firefox appears to be a problem.  I seem to be using version 39 which appears to be the latest version on Mozilla site.

**Comment by agilepro** [comment]
Sometimes I use Chrome to copy text from Word.  But Chrome has an even stranger behavior when pasting text from Excel -- it seems to appear, but it is not really there.  Switching to HTML code mode and back shows that nothing has really been pasted.  That is the behavior on Chrome.   On firefox I just get one big paragraph.   This is a big limitation to the editor.  Is there any work around?

**Comment by ingojauch** [comment]
I have a similar issue, when i paste text from word/openoffice into textAngular it kills off random? white spaces.
e.g. pasting this text from word/openoffice:
"Testing is done differently in different contexts. For example, safety-critical software is tested differently from an e-commerce site."
results in:
"Testingis done differently in different contexts. For example,safety-critical software is tested differently from an e-commercesite."

**Comment by agilepro** [comment]
Yes, I have seen that as well.  When I use Chrome, and paste from Word, I get something that looks just about right, but certain spaces are missing -- maybe every 10th word or so.

**Comment by agilepro** [comment]
I have confirmed that if you create a HTML file, which has words, and for which some words run to the end of a line, and the next starts at the beginning of the line -- that is, the only white space between the words is a line feed -- then those white spaces will be stripped out, and the two words will be joined.

It appears that during PASTE, textangular is NOT considering newline characters to be white space.  It is simply stripping them out and ignoring the fact that there used to be whitespace there.  

I just wasted an hour trying to get a block of text into a a textangular editor.  I have converted to formats, stripped tags, but in the end, I have no confidence that the entire text is there.  Not only are spaced missing, but sometimes complete sections of the document go missing.  This is really a problem.

**Comment by EspenHolmen** [comment]
I am seeing paste problems that seem related when it comes to pasting from Microsoft Word 2010. 

In Firefox I always get the text pasted as plain text with the newlines stripped out.

In Chrome I get the same content as in Firefox when I paste as plain text. When I paste without specifying plain text I lose the content that's been marked up as headings. Looking at the clipboard, I can see that the html version contains text tagged with h1 and h2 tags.

    <body lang=EN-US style='tab-interval:.5in'>
    
    <h1>Heading 1<o:p></o:p></h1>
    <h2>Heading 2<o:p></o:p></h2>
    <p class=MsoNormal><o:p>&nbsp;</o:p></p>
    
    </body>

When I copy and paste content from a webpage I get the formatting correctly. 

I am using version 1.4.1 of textangular.

**Comment by episodeyang** [comment]
To fix this, we need to remove the pre-filters that gets executed before the paste-handle is called. It might be better to make the filter selections customizable or make it barebone so that people can just write their own.

**Comment by agilepro** [comment]
Strongly second that suggestion to use a proper parser and not regex.

**Comment by micaelmbagira** [comment]
Do you have the same problem when copying from Gmail or any other email client ?

**Comment by EspenHolmen** [comment]
I can paste formatted text from any web page. The H1 though H6 tags are all kept intact.

From Office 2010 I get plain text.

**Comment by yaldak** [comment]
This might be fixed as part of fix #644, I just do not have Office to test it

**Comment by Benew** [comment]
@EspenHolmen I have the same problem with headers pasted from word.

This line of code seems to be the problem : 
```
if(!dom[0].childNodes[i] || dom[0].childNodes[i].nodeName === "#text" || dom[0].childNodes[i].tagName.toLowerCase() !== "p") {
```
for h1 and other headings, `dom[0].childNodes[i].tagName.toLowerCase() !== "p"` is true and the script ignores the tag!

This is a huge problem...

**Comment by Benew** [comment]
I'd love to fix it btw.

**Comment by Benew** [comment]
PR #967 should fix the headings problem

**Comment by Benew** [comment]
Please merge it ;)

**Comment by haseenaa** [comment]
unable to copy & paste from outlook, word into tinymce and  it adds more tags while pasting.

Spaces are truncating when User copy text from tinymceI and paste it into  Note Pad

Paste from Outlook to Chrome and Firefox 'eats' blanks in tinymce

Please help me to resolve the issues as our businness is not satisified with the tinymce copy , paste functionality .

**Comment by gbittmann** [comment]
I think you took a wrong turn somewhere haseenaa. This is textAngular.

TinyMCE is here.

[https://github.com/tinymce/tinymce](https://github.com/tinymce/tinymce)

**Comment by agilepro** [comment]
This was a critical problem.  Finally pulled the textAngular out, and switched to Tiny MCE.  That is not perfect either, but at least the users can paste rich text -- which seems something that every user ran into.

**Comment by LANole** [comment]
Word 2010... same issues as above. Extra breaks, missing paragraphs, formatting shot to all hell... simple 5 bullet points are so far off, misaligned text and more that it makes you want to put 5 bullets in your head trying to get it formatted correctly. Hyperlinks... its just easier to paste as plain text and go back and redo the links. Easy set-up and loved it until I actually tried to cut and paste from my Word.  Will try another program for sanity sake but copying and pasting from Word 2010 is awful. textAngular1.5, Windows 10.

UPDATE: tried Google Doc's and this is def better. Formatting there for the most part. Bullet points were there but had to do some backspacing and bolding BUT nothing like copying and pasting Word 10. Sanity saved... for now.... on to the next group of issues with the next project on the list.
