### ISSUE TITLE
Editor styles should default to browser defaults

### ISSUE THREAD

**Issue by KasraKhosravi** [fraywing/textAngular#788]
I'm using `textAngular` in my project's admin panel. The problem is I have a `reset.css` from bootstrap loaded in my panel, so all default styles of famous tags (e.g. `H1`, `B`, etc) are gone.

Is there a way to reset back (!) all styles of the editor area to browser defaults?

**Comment by nickknissen** [comment]
Don't include `reset.css` or remove the styles from `reset.css` you would like to keep.  
TextAngular relies upon browser styling `h1`, `b`, etc

**Comment by KasraKhosravi** [comment]
Thanks @nickknissen. I actually got to the same result and used `Normalize.css` instead of `reset.css`. That actually solved my problem. Thanks :)
