### ISSUE TITLE
ta-min-text behaviour doesn't conform 

### ISSUE THREAD

**Issue by jc74** [fraywing/textAngular#794]
I think the ta-min-text behaviour is slightly incorrect.  

It's current behaviour:-
- stops data-binding until the min length has been reached
- doesn't evaluate until text has been entered, ie length exists (probably because of behaviour above)

This is a little too opinionated and restricts functionality.  Instead, to conform with typical input behaviour, it should:-
- always data-bind
- always evaluate the min-text

This would immediately invalidate the element but this is normal behaviour and allows the user to decide how to proceed (with touched etc.).

**Comment by nickknissen** [comment]
What version of textAngular are you using? Because has been updated in in 1.4

**Comment by jc74** [comment]
1.4.2

Shall I provide an example?

**Comment by nickknissen** [comment]
Please do :+1:

**Comment by pbassut** [comment]
@jc74 Could you help us reproduce this issue so we can close it or mark it as a bug?

**Comment by pbassut** [comment]
I'm closing this since we got no reproduction example.
