### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by Stegoo** [fraywing/textAngular#796]
Hello,
I'm trying to use your editor. It works fine, except that I have this error showing up in my console when I type in the input.
It even does it on the demo page : http://textangular.com/.
I'm using ff, it seems to be fine on chrome.

Thank you

**Comment by JoelParke** [comment]
Stegoo,  Can you copy the exact error? - Thanks

**Comment by pbassut** [comment]
Maybe some FF plugin or something is messing with the document?

**Comment by Stegoo** [comment]
I have tried with a pluginless version of FF (39.0 and 36.0)
The lib is minified so it's not easy to get the error :
```
ReferenceError: event is not defined
http://textangular.com/dist/textAngular.min.js
Line 18
```

**Comment by JoelParke** [comment]
Have you tried this with the non-minified lib? -- that at least would highlight where the event is not defined.

**Comment by Stegoo** [comment]
Here is the error with the non-minified 1.4.2 lib :
```
ReferenceError: event is not defined
Line 2411: event.ctrlKey===false && event.metaKey===false && event.keyCode===9) 
```

**Comment by agairing** [comment]
I can confirm the error. It happens on my system with firefox, too.

**Comment by episodeyang** [comment]
Hey guys, here is the source of the error. We will fix it asap.

<img width="938" alt="screenshot 2015-07-14 19 41 16" src="https://cloud.githubusercontent.com/assets/630490/8688334/6c59fb54-2a60-11e5-907b-8b9a67dabbc8.png">

**Comment by JoelParke** [comment]
Stay tuned... for the AM

**Comment by JoelParke** [comment]
I pushed a new release out that fixed this... see final v1.4.2
