### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by tasca05** [fraywing/textAngular#798]
Please, anyone know to put a button to print?
I put a but prints the page , not any text.

grazie mile...

**Comment by pbassut** [comment]
You want to print the text inside textAngular?
If so, you could open a new tab with that tab's innerHTML attribute set to the html in TextAngular. Then just call print();

**Comment by tasca05** [comment]
I'm getting, can anyone help?

taRegisterTool('printAsta', {
		iconclass: 'fa fa-print',
		tooltiptext: taTranslations.print.tooltip,
		action: function(){
			return this.$editor().wrapSelection("print", null);
		},
		activeState: function(){ 
			//var iframePrint = angular.element('<iframe id="printFrame">' + this.$editor().html + '</iframe>');
			//document.getElementById('printFrame').print();
			//console.log(this.$editor().html);
			return this.$editor().queryCommandState('print'); 
		}
	});

**Comment by pbassut** [comment]
You can't call print on a tag AFAIK. You should create a new tab and set the document to be what you want to print.
That would be something like:
```javascript
var win = window.open(url, '_blank');
win.document.innerHTML = document.getElementById('theTagIdYouWantToPrint').innerHTML;
win.focus();
```

**Comment by tasca05** [comment]
Thanks, I am grateful.
