### ISSUE TITLE
Turkish character problem when sending data to server

### ISSUE THREAD

**Issue by cimey** [fraywing/textAngular#801]
Hi,

Turkish characters like ş,ı,ö,ü is fine in html editor but when sending the content of html editor,  ş turn to '  &#351'.

How can i send only character's itself?

**Comment by nickknissen** [comment]
You shold decode the HTML you recieve on the server.  
If you use PHP you could use `html_entity_decode` or `HttpServerUtility.HtmlDecode` for a .NET application.

**Comment by cimey** [comment]
Hi,
it worked, thanks for reply.
