### ISSUE TITLE
Upload image to S3 before inserting into the doc 

### ISSUE THREAD

**Issue by oharlem** [fraywing/textAngular#802]
Hi guys,

Please advise, how I can intercept image insertion, to do some my work first.
Workflow:
1. User clicks my custom "insert image" btn

2. This button opens an upload model.
I'm already working with ng+Material modals no prob, just need to figure out how to tie with textAngular.

3. Modal uploads to S3 and returns the URL. 
No prob here, just showing a step.

4. textAngular inserts image url returned from my script
Script output is an an image URL and would just insert an S3 URL into textAngular.

I did scan similar issues and saw several threads on this, however for some reason these solutions did not work - new image insert button appeared but was not producing any effect.
I'm using 1.3.17 + material design 0.10.0

I would really really appreciate your guide from A to Z!

Thank you,
D.

**Comment by pbassut** [comment]
Did you check #139 ?

**Comment by dopgm** [comment]
@pbassut 
Hi, yes, however i'm stuck at the first step: I'm adding a config with $provider.decorator, I see a button appearing on the toolbar, however the button is empty (w/o the icon) and does not react on clicks, also console.log from the provider does not return any result ( and no errors in the logs =/ ). 
I'm inserting this config right on the top of my controller file as simple as 

(function () {
    'use strict';
    angular
        .module('app')
        .config(function ($provide) {
            $provide.decorator('taOptions', ['taRegisterTool .....

Thoughts?

Thanks!
D.

**Comment by pbassut** [comment]
The way you describe it looks like it's not a textAngular issue. But something must be wrong with your angular logic. I suggest you double check if you're putting things where they should be.

**Comment by dopgm** [comment]
@pbassut 

Hi, I thought you might be right and I decided to check the basics first and followed the instructions from https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar

My provider (identical to the one from the docs, just set module):

    angular
        .module('app')
        .config(function($provide){
            $provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions){
                // $delegate is the taOptions we are decorating
                // register the tool with textAngular
                taRegisterTool('colourRed', {
                    iconclass: "fa fa-square red",
                    action: function(){
                        this.$editor().wrapSelection('forecolor', 'red');
                    }
                });
                // add the button to the default toolbar definition
                taOptions.toolbar[1].push('colourRed');
                return taOptions;
            }]);
        });

My textAngular obj:

<div text-angular ta-toolbar="[
                            ['h1','h2','p'],
                            ['bold','italics','underline','quote'],
                            ['justifyLeft', 'justifyCenter'],
                            ['ul', 'ol'],
                            ['insertImage','insertLink','insertVideo'],
                            ['undo', 'clear','colourRed']
                        ]" ng-model="vm.blogPost.body" class="btn-groups"></div>

+ I have the "red" css class.

When clicking the new button I see this error:

        TypeError: this.action is not a function
    at Scope.executeAction (textAngular.min.js:17)
    at $parseFunctionCall (angular.js:12456)
    at angular-touch.js:481
    at Scope.$get.Scope.$eval (angular.js:14555)
    at Scope.$get.Scope.$apply (angular.js:14654)
    at HTMLButtonElement.<anonymous> (angular-touch.js:480)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.js:4435)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (jquery.js:4121)

I would appreciate your insights into this :/
Thank you,
D

**Comment by dopgm** [comment]
@pbassut 
You are right, decorator was called too late :/ Thank you for your help!!

**Comment by dopgm** [comment]
P.S.

Everything's working for me now: pop + uploading + inserting S3 image, etc. Thanks!

However, here's an issue:
document.execCommand('insertImage', true, result); from example in #139 returns only an <img> tag and when I click on the image, Chrome throws "textAngular-rangy.min.js:2 Uncaught DOMException: INDEX_SIZE_ERR"

What is the correct way to insert an image wrapped into with the code to show the image editor (scaling, alignment, etc.)?

Thanks!
D.

**Comment by pbassut** [comment]
This is an open issue #721. And the workaround as of now is to catch the exception and suppress it. While that's not a solution because it might break something else, we're working on it and we'll fix it asap.

**Comment by dopgm** [comment]
@pbassut 
Thank you!

**Comment by dopgm** [comment]
@pbassut 
Still a question, when I suppress the exception, what is the approach to insert images with the image editor "attached" to them?

Thank you!

**Comment by pbassut** [comment]
The exception occurs because the image can't be found in the index specified(thus raising INDEX_SIZE_ERR). You will have to wait until #721 is fixed. Sorry

**Comment by dopgm** [comment]
Got it! Thanks again.
