### ISSUE TITLE
Word count position

### ISSUE THREAD

**Issue by 0Neji** [fraywing/textAngular#806]
Is there anyway to move the word count to the bottom of the text editor? I've had a look at the options in the Wiki but failed to find what I'm after. Not sure if I've just missed it or not but any help would be great.

**Comment by mangrovestudios** [comment]
Just curious: did you check the multiple toolbar option (https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar#multiple-toolbars)? A second toolbar with `wordcount` after the HTML container?

**Comment by pbassut** [comment]
Take a look [here](http://plnkr.co/edit/PynJgXigwUbWXT6bg93H?p=preview). this is a plnkr from another issue.

**Comment by 0Neji** [comment]
It didn't hit me to use multiple toolbars - great that this is possible! Thanks for the help!
