### ISSUE TITLE
Limit buttons in multiple toolbars

### ISSUE THREAD

**Issue by KirillFedorov** [fraywing/textAngular#808]
How can i customize buttons on my external toolbars?

editor
`<text-angular name="body" ng-model="text" ta-toolbar="[['h1','h2','h3'],['bold','italics']]" ta-target-toolbars='toolbar' ta-text-editor-class="input" placeholder="type please"></text-angular> `

toolbar
`<text-angular-toolbar name="toolbar"></text-angular-toolbar>`

not work, toolbar have default case of buttons

**Comment by pbassut** [comment]
I don't understand what you're trying to achieve here. The title says to limit the buttons on toolbars. But the code says something completely different. 
Could you make clearer what you're trying to do or set up a plunkr with the intended behaviour and describe the expected behaviour, please?

**Comment by KirillFedorov** [comment]
Oh, sorry. I find solve my problem. Need just move `ta-toolbar="[['h1','h2','h3'],['bold','italics']]"` to `<text-angular-toolbar>`. 

finaly:
`<text-angular-toolbar ta-toolbar="[['h1','h2','h3'],['bold','italics']]" name="toolbar"></text-angular-toolbar>`
