### ISSUE TITLE
Question: Clarification on how to bind to focus() unfocus() events

### ISSUE THREAD

**Issue by zorba-the-geek** [fraywing/textAngular#811]
Hi,

I am wondering how I am supposed to override the Editor focus() and unfocus() events.

Once I grab the editor with retriveEditor, how do set the focus and unfocus settings?

<code>
var edit = textAngularManager.retrieveEditor('editor');
        edit.unfocus = function () {
            console.log('unfocus');
        };
        edit.focus = function () {
           console.log('focus');
        };
</code>

**Comment by pbassut** [comment]
We don't have a feature for this yet. 
But it's a content editable, so this should work:
```
$timeout(function() {
    angular.element('text-angular[name=some-id]').find('*[id*=taText]').focus();
});
```

**Comment by nemes1s** [comment]
@pbassut this fires up an error for me:

rangy-core.js:3289 The given range isn't in document.
