### ISSUE TITLE
Specifying toolbar elements

### ISSUE THREAD

**Issue by Awelemdy** [fraywing/textAngular#812]
I understand that the ta-toolbar can be an array of elements or use a javascript variable which has an array of elements. However, when I try the later, the toolbar doesn't compile. Here is a plunkr I created: http://plnkr.co/edit/ltx95gNYfRzCmTNXAjDU?p=preview

**Comment by pbassut** [comment]
I think you forgot to add ng-controller to the second toolbar? Thus it's not finding the scope.
I'm on my phone, can't help you much more than this right now.

**Comment by pbassut** [comment]
Also, you're declaring it as a string. It should be an array of arrays.

**Comment by Awelemdy** [comment]
I think it can find the scope since the variable content in the controller is attached to the textarea and when you type, it is actually shown.

**Comment by pbassut** [comment]
Take a look: http://plnkr.co/edit/KCsBF2uexK4XgrdOT580?p=preview

**Comment by Awelemdy** [comment]
I see my mistake now. The docs need to be edited, would help alleviate some of the misunderstandings. 

Also, I am trying to render the content from the editor which most likely will contain youtube videos. I have been trying to include the `<div ta-bind="text" ng-model="htmlcontent"></div>`  but it seems to only work when the editor's ng-model is set to htmlcontent as well. 

I can't just have a string like:
`var htmlcontent = "<p><img class=\"ta-insert-video\" src=\"https://img.youtube.com/vi/hRVOOwFNp5U/hqdefault.jpg\" ta-insert-video=\"https://www.youtube.com/embed/hRVOOwFNp5U\" contenteditable=\"false\" allowfullscreen=\"true\" frameborder=\"0\" height=\"247\" width=\"335\"/><br/></p>"; `
and have the directive render the string.

**Comment by Awelemdy** [comment]
I see my mistake now, thanks for answering my question. This plugin is awesome!
