### ISSUE TITLE
Override bold button

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [fraywing/textAngular#816]
I think doing so will give us more control over toolbar's appearance.

**Comment by pbassut** [comment]
You mean you would like to remove the current bold button and add your own?

**Comment by Nick-The-Uncharted** [comment]
@pbassut yes,that's exactly what I mean . Thank you for reply.

**Comment by nickknissen** [comment]
You can just create your own toolbar items.
```javascript
	taRegisterTool('myCustomBoldButton', {
		iconclass: 'your-custom-bold-style',
		tooltiptext: taTranslations.bold.tooltip,
		action: function(){
			return this.$editor().wrapSelection("bold", null);
		},
		activeState: function(){
			return this.$editor().queryCommandState('bold');
		},
		commandKeyCode: 98
	});
```

**Comment by pbassut** [comment]
As @nickknissen stated, you need to create a whole new toolbar if you want to override just one button. That's annoying IMO.
I'm not sure if we should label that as an enhancement or as a wontfix

**Comment by Nick-The-Uncharted** [comment]
@nickknissen But it seems impossible to control things like gap width between button.And  if there is an existing toolbar , I have to move all item to textAngular's toolbar.

**Comment by Nick-The-Uncharted** [comment]
I find a solution:
In html:

    <text-angular id="editor" name="editor" ng-model="data.htmlcontent" ta-target-toolbars='[]' data-tap- disabled="true"></text-angular>
    <button ng-click="setTobold()">test</button>

In controller:

     $scope.setTobold = function () {
          editor = textAngularManager.retrieveEditor('editor').scope;
          editor.wrapSelection('bold',false, null);
     }
