### ISSUE TITLE
Inserting text dynamically at the cursor position

### ISSUE THREAD

**Issue by Prashanth-Nelli** [fraywing/textAngular#817]
Hi Guys, is there any way to insert text at the cursor position dynamically,
could you please provide any sample code.

**Comment by 0AlexScott** [comment]
@Prashanth-Nelli  I inserted a couple of symbols a while ago [this](https://stackoverflow.com/questions/26145428/how-to-insert-text-symbols-from-a-custom-button-on-textangular-toolbar/26252128#26252128) might help
