### ISSUE TITLE
Translate the toolbar tooltips according to browser settings

### ISSUE THREAD

**Issue by m-hauptma** [fraywing/textAngular#821]
Is it possible to translate the tooltips for the toolbar buttons easily or are there any plans for future releases to support internationalization?

**Comment by pbassut** [comment]
Just override [this](https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L116-L210) and you should be good to do.

**Comment by m-hauptma** [comment]
True, but is it somehow possible to use a translate service (angular-translate) in combination with textAngular to translate on the fly and not hard-coded in the textAngular setup?

**Comment by nickknissen** [comment]
You just need to configuring the `taTranslations` value with help of `$provide.decorator`
```javascript
app.config ($provide) ->
	$provide.decorator 'taTranslations', ($delegate) ->
    $delegate.html.tooltip = 'Toggle html / Rich Text'
    $delegate.justifyLeft.tooltip = 'Venstrejustér'
    $delegate.justifyCenter.tooltip = 'Centrér'
    $delegate.justifyRight.tooltip = 'Højrejustér'
    $delegate.bold.tooltip = 'Fed skrift'
    $delegate.italic.tooltip = 'Kursiv'
    $delegate.underline.tooltip = 'Understreg'
    $delegate.insertLink.tooltip = 'Indsæt/redigér link'
    $delegate.insertLink.dialogPrompt = "Skriv link URL"
    $delegate.editLink.targetToggle.buttontext = "Åbn i nyt vindue"
    $delegate.editLink.reLinkButton.tooltip = "Rediger link"
    $delegate.editLink.unLinkButton.tooltip = "Fjern link"
    $delegate.insertVideo.tooltip = 'Indsæt video'
    $delegate.insertVideo.dialogPrompt =
      'Skriv Youtube video URL, der skal indsættes'
    $delegate.clear.tooltip = 'Ryd formattering'

    return $delegate
```

**Comment by m-hauptma** [comment]
Okay, but I guess here is the problem. Is it possible to use angular-translate to do something like: 
$delegate.html.tooltip = $translate('togglehtml_tooltip'); 
As far as I know is it not possible to use a service within the config block and during the run block I can't inject the provider.

**Comment by nickknissen** [comment]
Can't you do something like this:
```
app.config(function($provide) {
  $provide.decorator('taTranslations', function($delegate, $translate) {
    $delegate.html.tooltip = $translate('togglehtml_tooltip');
    return $delegate;
  });
});
```

**Comment by m-hauptma** [comment]
Well translate returns an object with a promise so I would need to do something like:
app.config(function($provide) {
  $provide.decorator('taTranslations', function($delegate, $translate) {
    $translate('togglehtml_tooltip').then(function(title){
        $delegate.html.tooltip = title;
    };
    return $delegate;
  });
});

But that won't work because I guess the config already returns when the callback is still waiting.

**Comment by kamilbrk** [comment]
+1
At the moment, there is no way to fetch translations asynchronously.

**Comment by delwiv** [comment]
Hi, I found a turnaround of this problem.

As we know, at the .config() moment you don't have any async data such as user's lang or translations files, but check this : 
```javascript
    $delegate.insertVideo.tooltip = "{{'common.yes' | i18n}}";

```
So doing this way, using a filter, when the data will be displayed, your async translations will have been fetched.

**Comment by rnagy90** [comment]
**Angular version: 1.5.8
Angular translate version: 2.11.1
Text angular version: 1.5.16**

Also works with angular-translate.

```
function taTranslations($delegate) {
   $delegate.bold.tooltip = "{{'TOOLTIP.ADD' | translate}}";
   return $delegate;
}
```

I think the tooltip context is also compiled by the angular.
