### ISSUE TITLE
Cannot remove empty bullet point (empty li)

### ISSUE THREAD

**Issue by kitze** [fraywing/textAngular#828]
No matter how i try to manipulate the text it just doesn't work, i cannot select it or delete it in any. Is this fixable in any way or should i modify the content in the database to remove the empty li element?

Screencast of the issue here:
http://screencast.com/t/ppBxIyGBhm

**Comment by pbassut** [comment]
To remove this bullet point you must put the cursor in front of it and press backspace. That's how every editor works AFAIK.

**Comment by kitze** [comment]
@pbassut you cannot put the cursor anywhere near the bullet, i know how to delete bullets :) I solved the issue by directly editing the html and removing the empty <li> but that's not a solution...

**Comment by pbassut** [comment]
It's not. I just deleted the bullet at (textAngular.com)[textAngular.com], though. 
I can't assume you know how to delete bullets, sorry. It see that happening sometimes.

Could you provide more info, then? I'm using chrome 44.

**Comment by pbassut** [comment]
I didn't see you trying to scroll or click after the bullet point. Maybe you did and I couldn't notice. That's why I said you must put the cursor in front of it.
