### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by Jakobovski** [fraywing/textAngular#837]
http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.4.0/textAngular-sanitize.min.js

is not working

**Comment by pbassut** [comment]
I think you got the wrong link. http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.4.0/dist/textAngular-sanitize.min.js

**Comment by Jakobovski** [comment]
Sorry I pasted the wrong link.

The links in the README are broken, for example:
http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.3.0/textAngular-sanitize.min.js

**Comment by pbassut** [comment]
Still: http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.3.0/dist/textAngular-sanitize.min.js

**Comment by pbassut** [comment]
Oh yeah. The links in the README. Right.

I'll fix them ASAP.
