### ISSUE TITLE
textAngular Toolbar always in disabled state

### ISSUE THREAD

**Issue by maramkiran** [fraywing/textAngular#839]
In one of my project am using textAngular. I included textAngular in a View, that view am loading using ng-include. If the View is directly called textAngular is working but If I used with ng-include always the toolbar is in disable state.

**Comment by pbassut** [comment]
Can you setup a plunkr so we can see what's going on?

**Comment by maramkiran** [comment]
Actually its not an issue with ng-include, I think its an issue with modal popup. We are opening the modal window with some kind of flip animation. I need to figure out the actual issue, weather its an issue with Modal window or flip animation script. Thanks

**Comment by pbassut** [comment]
Okay, I'm closing this for now.
