### ISSUE TITLE
Place text-angular-toolbar somewhere else on the page

### ISSUE THREAD

**Issue by jbonigomes** [fraywing/textAngular#840]
Hi there,

I was wondering if there is a way to place the text-angular-toolbar somewhere else on the page, or to the very least, right below the textarea, but ideally, having a way to specify a custom template.

**Comment by nickknissen** [comment]
You can use the `text-angular-toolbar` directive.  
You can do something like this:
```html
<text-angular-toolbar name="myToolbar"></text-angular-toolbar>
<text-angular ng-model="data.htmlcontent" ta-target-toolbars='myToolbar'></text-angular>
```

**Comment by jbonigomes** [comment]
Thanks @nickknissen works perfectly
