### ISSUE TITLE
Setting <li> to use a font size causes text angular to output random divs when closing a list

### ISSUE THREAD

**Issue by Quirksmode** [fraywing/textAngular#843]
I thought I was going mad, but really bizarrely if you have your <li> font size defined the lists do not close properly, they output divs instead of switching back to <p> Have created a plunkr to show the issue:

http://plnkr.co/edit/tEAIPEHMLQuVH08WMXy0?p=preview

**Comment by pbassut** [comment]
"Before switching back to..."?

**Comment by Quirksmode** [comment]
The steps to recreate is click ordered list (for example), create a few list items, then press return twice to leave list mode. The next time you type it will create a div and inside that will be a span with the font styles inlined.

**Comment by pbassut** [comment]
Thanks for your time!
Help me out to reproduce this issue, please. 
Does that occur on Chrome using the TA instance hosted at [textangular.com](textangular.com)?

**Comment by Quirksmode** [comment]
No probs at all, thanks for such an awesome plugin, fingers crossed this is a simple fix, it's certainly a strange one. The TA instance on chrome works great for me so I have matched up my plunkr so all the files are basically the same e.g. the Angular versions are matching now. 

I can add/remove any of the files and nothing fixes the issue except for removing the following css:

```
li {
  font-size: 18px;
}
```

It's so strange that CSS can have such a drastic effect on the JS, but those 3 lines seem key to the whole issue. 

Here is the simplified plunkr that shows the problem. 
http://plnkr.co/edit/2AVVw2wsbONgNRKwGiL6?p=preview

**Comment by pbassut** [comment]
Do you think this is a bug? 
I'm sure there's some browser rendering issue that made a developer include a span there. At least that's what I want hope for.

**Comment by Quirksmode** [comment]
Almost definitely, unless you know a workaround/fix to get that plunkr working? I am pretty screwed on this project I am working on so praying for a fix

**Comment by pbassut** [comment]
well, it should create a p. You're right.
I'm marking it as a bug.

**Comment by Quirksmode** [comment]
Thanks, fingers crossed it's something simple :-)

**Comment by Quirksmode** [comment]
Hey, any idea of an eta for a fix for this bug, it's a fairly major one for the project I am working on with the deadline closing in. I have done some investigating and have found a couple of things that may help:

- It only affects webkit browsers
- It only happens when a style (any style) is applied to an <li>
- It basically takes all the attached styles and writes them inline inside a div (e.g. <div><font color="#000000" face="Lora, sans-serif">sdf</font></div>)
- I can prevent the issue from occurring by resetting the styles by using inherit e.g. line-height: inherit, color: inherit
- I believe it is to do with either the factory taFixChrome or the function transformLegacyStyles(html) found within textAngular.js

**Comment by Quirksmode** [comment]
Really desperate for a fix for this now, there is a definite problem when styles are applied. The issue occurs when I copy and paste text as well. Any idea of when this will get looked at, is there any advice you can offer me for trying to fix it myself?

**Comment by Quirksmode** [comment]
At the very least is there a way to switch off Text Angular from copying inline styles when you copy and paste?

**Comment by JoelParke** [comment]
<p>I have reproduced this issue with v1.4.6 and looking into why!! Stay tuned.</p>

**Comment by JoelParke** [comment]
There is a fix:  https://github.com/fraywing/textAngular/commit/a0b79276d351d9223e6d3892daf2093f27588e58 This will be included in the next release.

**Comment by Quirksmode** [comment]
This is amazing, thank you so much!!

**Comment by gomezfx** [comment]
Any idea when the next release is coming out? Don't think the current one has this fix.
