### ISSUE TITLE
Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded.

### ISSUE THREAD

**Issue by radiart** [fraywing/textAngular#844]
I'm using **textAngular 1.4.3** with **AngularJS 1.4.4** and **requireJs 2.1.20**, I declared paths like this:

```
 require.config({
    paths: {
       'rangy-core': '../lib/rangy/rangy-core.min',
        'rangy-selectionsaverestore': '../lib/rangy/rangy-selectionsaverestore.min',
        'textAngular-rangy': '../lib/textAngular/dist/textAngular-rangy.min',
        'textAngular-sanitize': '../lib/textAngular/dist/textAngular-sanitize',
        'textAngularSetup': '../lib/textAngular/dist/textAngularSetup',
        'textAngular': '../lib/textAngular/dist/textAngular',
},   
 shim: {
        'textAngular-rangy': ['rangy-core', 'rangy-selectionsaverestore'],
        'textAngular-sanitize': ['angularSanitize'],
        'textAngularSetup' : ['angular'],
        'textAngular' : ['angular','textAngularSetup', 'textAngular-sanitize','textAngular-rangy']
    },
 });
```

When  I'm traying to use 'textAngular' all the time I have the same error:

"**Uncaught rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded.**" 

I checked Sources and files **rangy-core.js** and **rangy-selectionsaverestore.js are loaded**...

Use this library is very complicated...

**Comment by pbassut** [comment]
We currently don't support requireJS.
There's an issue open that addresses this issue and a PR has already been created.
This is becoming a high priority issue now.
We'll see what we can do ASAP.

**Comment by StErMi** [comment]
@pbassut I'm using bower and I also get this error.

how can I hotfix this?

**Comment by pbassut** [comment]
Take a look [here](https://github.com/fraywing/textAngular/pull/760)

**Comment by linlak** [comment]
I think the error arises from the attempt to require modules with predefined urls. I am loading the modules from a cdn but, in the console the error shows that rangy is being loaded from my server and 404 not found  error.
