### ISSUE TITLE
comments getting converted to <p> tags

### ISSUE THREAD

**Issue by beyondcreed** [fraywing/textAngular#846]
Hello,

We just noticed on your demo page at: http://textangular.com/ if we add following at top (toggle to source)

```
<!-- hello world -->
```
It converts to: 

```
<p> hello world </p><h2>Try me!</h2><p>textAngular is a super cool  ...
```

is this normal behaviour?

**Comment by pbassut** [comment]
You mean if we're on source mode and add this it converts to a paragraph?
Well, that didn't happen here.
It's a comment it should be rendered but it does appear on view mode.

Just so I can get this straight, what you think should be the normal behaviour?

**Comment by beyondcreed** [comment]
Correct. If you are on source mode and you add the comment at top then flip back to HTML it shows as para. I attached screenshot, look into HTML Output.

![snapshot-ta](https://cloud.githubusercontent.com/assets/928851/9316698/80f23d88-44eb-11e5-9521-6af81d608df3.png)

**Comment by beyondcreed** [comment]
I am just curious is this is what's expected, or should the comment be hidden when flipped back to HTML mode, because its comment.

**Comment by pbassut** [comment]
I think the comment should be hidden, for sure. I don't know why this is not being parsed correctly.
I'll mark it as a bug, though I think is a low priority one.

Thanks for

**Comment by beyondcreed** [comment]
yes, right now we are stripping comments out as it messes up the html rendering, due to them being converted to paragraphs.

**Comment by JoelParke** [comment]
That's a bit weird!  When I try it, the comments vanish. if the doc is empty.  BUT if you add the comment ahead of something like:

<p>ss</p>
It shows up just as you report!:
a simple comment

ss
VERY strange.

**Comment by beyondcreed** [comment]
it would be good to get this and #847 fixed. it was not an issue in earlier versions.

**Comment by JoelParke** [comment]
a test comment

**Comment by JoelParke** [comment]
<p>This is a <b style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);"><b></b><b><b>test</b></b></b> comment!<br/></p>

**Comment by JoelParke** [comment]
<p>This is a <b style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);"><b></b><b><b>test</b></b></b> comment!<br/></p>

**Comment by JoelParke** [comment]
<p>This is a <b>test</b> comment!</p>

**Comment by JoelParke** [comment]
<p>test comment</p>

**Comment by JoelParke** [comment]
<p>test comment</p>

**Comment by JoelParke** [comment]
<p>this is a test comment - please ignore. I am testing github integration. This is go away momentarily. </p>

**Comment by JoelParke** [comment]
<p>Interesting, I know why this is happening in the current version.  What version have you seen it work correctly, and I bet the comment is being removed from the model.  Can you verify?</p>

**Comment by JoelParke** [comment]
<p>This bug is tightly related to #846 -- and when that is fixed, this one will go with it... </p>

**Comment by JoelParke** [comment]
See textAngular aba8265 -- this is fixed and will be out in the next release....
