### ISSUE TITLE
It's possible to select 3 formats at once? For example: Bold, Italic and Underline?

### ISSUE THREAD

**Issue by radiart** [fraywing/textAngular#848]
It's possible to select 3 formats at once? For example: Bold, Italic and Underline?

Now when I'm selecting 3 formats is adding only last choosen style... Underline...

For example in CK Editor http://ckeditor.com/demo you can select few styles at once, it also possible in Text Angular? If yes how to achieve this?

**Comment by pbassut** [comment]
It is!
We're currently with a bug that prevents this in some cases #732. But this happens in very rare cases where I believe you won't encounter.
So yeah, we do
