### ISSUE TITLE
g.rangy.saveSelection is not a function

### ISSUE THREAD

**Issue by JECR9421** [fraywing/textAngular#853]
This problem appear when any of the buttons are been pushed.

![captura](https://cloud.githubusercontent.com/assets/11413523/9452189/259a7a60-4a70-11e5-88d1-976ed86ce4f1.PNG)

**Comment by pbassut** [comment]
Does it happen on [textAngular.com](textAngular.com)?

**Comment by anavagomez** [comment]
I am getting the same error when clicking on any of the buttons. I am implementing textAngular with requireJS. I am using version 1.4.3

**Comment by pbassut** [comment]
requireJS is not supported ATM. We have a PR open for that. So it should be available in a while. Maybe in the next release.

**Comment by anavagomez** [comment]
I opened rangy-core, and rangy-selectionsaverestore files and in there it seems to have some AMD support. Also, I ran into this other post: https://github.com/fraywing/textAngular/issues/713
Are they using requireJS and textAngular? Thank you much for your help.

**Comment by pbassut** [comment]
We're about to merge this PR: https://github.com/fraywing/textAngular/pull/760.
That solves the issue.

**Comment by pbassut** [comment]
@JECR9421 are you using requiresJS too?

**Comment by JECR9421** [comment]
Yes I am using them.

**Comment by pbassut** [comment]
Just made a PR that solves this.
Should be ready in our very next release

**Comment by rbnvrw** [comment]
I still have this issue when using browserify. Opened this stackoverflow question: http://stackoverflow.com/questions/34104643/typeerror-g-rangy-saveselection-is-not-a-function-using-textangular-rangy-b

**Comment by hxgqh** [comment]
I succeeded doing below:

versions:

    1. textAngular 1.5.0
    2. rangy 1.3.0
    3. requirejs 2.1.22
Just add a line below to app.js(in config() not run()):
    
    window.rangy = require('rangy-core');

That's all to fix this issue for me.

**Comment by cluis13915** [comment]
I was struggling with the same error. I followed this [tutorial](https://medium.com/@dcardosods/migrating-an-angularjs-apps-dependencies-from-bower-to-npm-ed474f44bd2) to migrate from bower to npm. After that, **textAngular** stopped working. After checking the [doc](https://github.com/textAngular/textAngular) I noticed that `rangy-selectionsaverestore` is a must dependency, so I followed the instructions from my tutorial to override the main files for "rangy" in my `package.json`.
```
  "overrides": {
    "rangy": {
      "main": [
        "lib/rangy-core.js",
        "lib/rangy-selectionsaverestore.js"
      ]
    }
  }
```
After that little tweak, the error disappeared. :pizza: :relaxed:

**Comment by Pyot** [comment]
in my case I had to import rangy in that way 

```
 import rangy from 'rangy/lib/rangy-core.js';
 import 'rangy/lib/rangy-highlighter';
 import 'rangy/lib/rangy-classapplier';
 import 'rangy/lib/rangy-textrange';
 import 'rangy/lib/rangy-serializer';
 import 'rangy/lib/rangy-selectionsaverestore';
```
