### ISSUE TITLE
textAngular's internal model ignores style attr

### ISSUE THREAD

**Issue by jshado1** [fraywing/textAngular#854]
When `styleWithCSS` is enabled, the browser inserts `<span>` tags instead of old-school tags like `<b>`. The span tags contain a style attribute like `<span style="font-weight: bold;">foo</span>`. However, that is registered as `<span>foo</span>` in textAngular's model.

**Comment by pbassut** [comment]
What's the intended behaviour?

**Comment by jshado1** [comment]
The intended behaviour is that the model correctly reflects the DOM: It should be recorded with the `style` attribute (and any other attributes that the element has).

**Comment by pbassut** [comment]
Oh right! You were very restrictive in your example. Although could you please setup a plunkr so I can investigate the issue a bit more?

**Comment by jshado1** [comment]
Incoming

**Comment by JoelParke** [comment]
<p>test Comment</p>

**Comment by jshado1** [comment]
http://plnkr.co/edit/zXicBR?p=preview

**Comment by jshado1** [comment]
bump

**Comment by pbassut** [comment]
Sadly, looks like a bug. You're right, it should remains with the style attrs intact.
Thanks for the report

**Comment by jshado1** [comment]
@pbassut curiously, it does not strip the style attr with:

```js
var elem = [
    '<q ', // an anchor tag also works
        'class="',
            CONF.classNames.spoiler,
        '" ',
        CONF.directiveNames.spoiler,
    '>',
    selectedText,
    '</q>'
].join('');

this.$editor().wrapSelection('insertHTML', elem); // works even in IE10
```

It DOES however strip off the directiveName attr. The stripping of the directive attr is the real problem (I was trying to work around this by attaching the directive based on classname).

Also, I realise that the `styleWithCSS` causes all sorts of problems with textAngular—mostly because you very strictly validate which elements and attributes are "acceptable" (basically html v1). The above sample is without styleWithCSS.

**Comment by sharmashobhit** [comment]
@pbassut I faced the same problem(i had't enforced styleWithCSS so I faced it with Strikethrough and underline) . The problem is with the textAngular-sanitize.js
I added following line after line number 535.

```javascript
key === 'text-decoration' && (value === 'underline'|| value === 'strikethrough')||
```

**Comment by JoelParke** [comment]
<p>pull request <span style="color: rgb(118, 118, 118);text-align: left;float: none;background-color: rgb(245, 245, 245);">#937<span class="Apple-converted-space">  fixes this...</span></span></p>

**Comment by rdkleine** [comment]
Could Italic also be included in the validStyles function?

**Comment by jshado1** [comment]
Better yet, make that extensible.

On Nov 11, 2015, at 04:41, Ralf de Kleine <notifications@github.com> wrote:

Could Italic also be included in the validStyles function?

―

**Comment by rdkleine** [comment]
pull request https://github.com/fraywing/textAngular/pull/964 fixes italic and font-size.
