### ISSUE TITLE
How to implement textAngular into AngularJS

### ISSUE THREAD

**Issue by anavagomez** [fraywing/textAngular#856]
I would like  to learn how to use textAngular with my AngularJS application. How can I inject the dependencies before manually bootstrapping the app.

**Comment by JoelParke** [comment]
<p>Not sure what you want to do.<br/>Normally, you just do:<br/>bower install textAngular<br/>Then in the app.js<br/></p><pre>angular.module('....myapp...', [ ...., 'textAngular', .....])<br style="color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);"/>.config(....)</pre><p>If this is unclear, when I wanted to learn I started with 'yo angular-fullstack' to generate the base app.<br/>A <a href="http://acuriousanimal.com/blog/2014/10/18/7-reasons-to-use-yeomans-angular-fullstack-generator/" target="">good article</a> gives some information. <br/>I hope this helps.</p>

**Comment by JoelParke** [comment]
Closing this question as I am hopeful that this has been answered.
