### ISSUE TITLE
insertImage with base64 has no effect in firefox

### ISSUE THREAD

**Issue by vincentcialdella** [fraywing/textAngular#860]
Hi,

I would like to insert an image containing a base64 source.
I have a bootstrap modal that still returns me this base64. This action is working in IE and chrome but fails in firefox (no content is added). The problem does not seem to come from the base64 Since this same base64 when hardcoded works for all other browsers.

I provide my code:  

    $provide.decorator('taOptions', ['$modal', 'taRegisterTool', '$delegate', function ($modal,    taRegisterTool, taOptions) {    
          taRegisterTool('insertFromClipboard', {
                iconclass: "fa fa-files-o",
                tooltiptext: 'copy from clipboard',
                action: function (deferred, restoreSelection) {
                    var editor = this.$editor;

                    var modalInstance = $modal.open({
                        templateUrl: 'app/views/assessmentcreator/pasteFromClipboard.html',
                        controller: 'CtrlPasteFromClipboard',
                        backdrop: 'static',
                        keyboard: false
                    });

                    modalInstance.result.then(function (base64) {
                        restoreSelection();
                        editor().wrapSelection('insertImage', base64, true);
                        deferred.resolve();
                    });
                    return false;
                }
            });

            taOptions.toolbar[2].push('insertFromClipboard');

      return taOptions;
    }]);

What is strange is that the same code for another button / action returning me a base64 is working (registered in another taRegisterTool function)(only name and icon differ).

**Comment by pbassut** [comment]
What that base64 actually is?
Is it like this ```<img alt="Embedded Image" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..." />```

**Comment by vincentcialdella** [comment]
Yes it starts like this:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAN4AAAF8CAIAAAAv...`

**Comment by pbassut** [comment]
Could you set up a plunkr so I can see what you might be doing wrong? This should work fine

**Comment by vincentcialdella** [comment]
What I have seen is that the base64 returned by my modal is ok.
I have found a proccess that inserts the image: I can achieve inserting image if I type a text and put the cursor before the text entered.
If the editor is empty or if there is nothing after the cursor, the image is never inserted.
I hop this can help you to help me :-)

**Comment by pbassut** [comment]
I really wanted a plunkr to investigate your issue a bit more

**Comment by pbassut** [comment]
Sorry, I'm closing this since I got no response.
