### ISSUE TITLE
Editor placeholder text not translating on refresh

### ISSUE THREAD

**Issue by nachoargentina** [fraywing/textAngular#863]
Hello everybody!

I'm opening this issue because I think it's something that anyone making an application that supports internationalization might stumble upon.

I'm developing an app that currently supports multiple languages. Selecting a different language translate the whole app, including placeholders.
How do I translate placeholders? Using an angular filter. So, for example, translating an input placeholder would be something like
```html
<input placeholder="{{'textToTranslate' | translate}}">
```
This works perfectly fine on all html elements, so I thought "this has to work fine as textangular placeholder attribute".
So, I tried it out, and it actually works when you navigate to a screen where textangular is used. The text get's translated accordingly and everyone is happy.

BUT...the problem comes when, once in a page where textangular is present, I hit F5 to refresh the page. When I do that, eveything loads up again and ALL placeholders are translated correctly again, but textangular placeholder is not translated for some reason!

I suspect it might be something related with the digest cycle or something that is preventing the filter to be applied when the application loads up. Can anyone point me in the right direction on how I should fix this?

Thanks in advace for your time!

**Comment by pbassut** [comment]
I would suggest you check your filter to see if it's loading fine BEFORE textAngular.
When you navigate to a screen where there's a textAngular instance you already loaded your filter, so it should work fine.
You might say that this works with input placeholders even when you refresh the page. But textAngular is a library that takes up time to load. So there might be a concurrency issue there. Check it out.

**Comment by pbassut** [comment]
Did you get a chance to try this out?

**Comment by nachoargentina** [comment]
Guys, fist of all, thanks for taking the time to check this out.
Second, I apologize for the delay in the response. I was out of town for a couple days.
I totally understand what you say and also think it might have something to do with concurrency.

I'm currently using angular-translate to translate everything in my app. One of the ways in which you can do that, is by applying a "translate" filter on whatever element contains the translate key, and it should do the job.
So, currently I have something like:
```html
<div text-angular ta-toolbar="[['bold','italics','underline'],['undo', 'redo'],['insertLink'],['wordcount','charcount']]"                                    
                  data-ng-model="vm.model"                                   
                  placeholder="{{'data.about.name.etymologyPlaceholder' | translate}}">
</div>
```
After I log into my app and navigate to this screen, everything works perfectly fine. The issue comes when I'm at this screen and press F5 to reload the whole thing. That's where I suspect a concurrency issue is messing this up.
I checked on my index.html and I'm importing angular-translate first, before importing text-angular.
Is there anything you can think of to resolve this issue? any suggestion would be greatly appreciated!

**Comment by nachoargentina** [comment]
Btw, all native angular filters, like uppercase for example, works just fine
