### ISSUE TITLE
Making edits in source view, loses events applied to editor content elements

### ISSUE THREAD

**Issue by TheFoot** [fraywing/textAngular#864]
I am attaching events to various elements within the editor (specifically for custom tags, used with a custom tool).

When switching to source view to make some edits, and then back to the WYSIWYG editor, the events are lost. I understand why.. my question is how can I best detect this change? Should I $watch the model property the editor is bound to, or is there an event I can handle?

Example: http://codepen.io/TheFoot/pen/JYdMdo

Thanks!

**Comment by pbassut** [comment]
Currently I think the best solution is to watch the model, yeah. But we're discussing about textAngular sending events so the user can handle it properly. And one of those would be switching views.

**Comment by TheFoot** [comment]
Cool thanks! How can I get notified when the events make it into the core build?

**Comment by pbassut** [comment]
I'll try to get this ready for 1.4.4. But watch our repository for changes. Get into the discussion here: https://github.com/fraywing/textAngular/issues/730. And hopefully help us build it :)

**Comment by TheFoot** [comment]
Awesome stuff.. I am hoping to start contributing.. am currently working with a fork as I had to implement some custom `wrapSelection()` functionality, but I couldn't get the test suite to run locally and ran out of time, so I couldn't make a PR. Its probably way out of date now, so not sure what to do. Hopefully I will get some time to start getting involved though - this is a really useful project!

**Comment by pbassut** [comment]
Awesome! We're all busy doing stuff to help out people more and more. Glad you like it so far!
Thanks for the report!
