### ISSUE TITLE
set initial activated buttons

### ISSUE THREAD

**Issue by markus138** [fraywing/textAngular#869]
in my project at the beginning Paragraph and Bold are always selected. Paragraph is of course find, but I dont want to have bold to be the standard. Is there a way to define what is activated at the start and what not?

**Comment by pbassut** [comment]
How so? That shouldn't happen. No button should be selected when the editor starts up. Could you make a plunkr to clarify?

**Comment by markus138** [comment]
I'll post a plunkr later, but is there any way to set the selected option from javascript?

**Comment by markus138** [comment]
Bug was on my end and had nothing to do with textAngular, sorry for the confusion 
(i set my p.font-weight: bold)

**Comment by adamjudson** [comment]
I just saw the same issue.  

Again, it was because of page styling:

body {
    font-weight: 700;
}

But why should this affect the html generated by typing in the editor?

This feels like a bug to me.  Regardless of the style of the page I embed the editor into, I would expect the buttons to be unaffected.
