### ISSUE TITLE
Release 1.4.4 breaks bundling with browserify and webpack

### ISSUE THREAD

**Issue by jskrzypek** [fraywing/textAngular#870]
I get this error: 
```
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at /Users/jskrzypek/dev/*******/node_modules/browserify/node_modules/resolve/lib/async.js:150:37
    at fs.js:334:14
    at /Users/jskrzypek/dev/*******/node_modules/karma/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:42:10
    at /Users/jskrzypek/dev/*******/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/jskrzypek/dev/*******/node_modules/gulp-electron/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
    at /Users/jskrzypek/dev/*******/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I figured out that textangular was the culprit by following the suggestion in this comment: https://github.com/substack/node-browserify/issues/1029#issuecomment-96666983

It's probably because of the array provided as `main` in the `package.json`

When I try it with webpack, it can't resolve the module at all. 

These issues disappear when I  downgrade to textangular 1.4.3.

**Comment by pbassut** [comment]
So, if you change the package.json manually it works?

**Comment by jskrzypek** [comment]
Yup. If I downgrade or just change the `main` back to `'./dist/rectangular.min.js'` it works.

**Comment by jskrzypek** [comment]
*textAngular

**Comment by pbassut** [comment]
As you pointed out on the other issue it doesn't make much sense to have the main application file as two files. So I'm removing the .css file since it won't break anything.

**Comment by jskrzypek** [comment]
Awesome! Thanks @pbassut
