### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by ghost** [fraywing/textAngular#88]
Is there a way to have formatting triggered on keyboard press? 
For instance `cmd+b` or `ctrl+b` will make the highlighted text bold etc..

**Comment by LeleDev** [comment]
How to disable keyboard shortcuts (all or individually)?

For example, if I don't put the bold button into the buttons bar, I'd like also to prevent user to enable it with ctrl+b

**Comment by bansalnitish** [comment]
@LeleDev did you found a way to disable that? thanks
