### ISSUE TITLE
Wrapselection formatBlock ignores selection and formats full line

### ISSUE THREAD

**Issue by 0AlexScott** [fraywing/textAngular#881]
For commands like PRE, P, and BLOCKQUOTE the selection isn't taken into account when applying the formatting, and it will format either the full line or multiple lines.
Which means I can't add custom buttons for subscript and superscript.

The action in textangularsetup is ' this.$editor().wrapSelection("formatBlock", "<'P'>");'

Can anybody help?

**Comment by koo4** [comment]
I think you should use

`this.$editor().wrapSelection("superscript", null); `
`this.$editor().wrapSelection("subscript", null); `
