### ISSUE TITLE
Displaying error of the element "taTextElement" after updating from 1.4.3 to 1.4.4

### ISSUE THREAD

**Issue by fims** [fraywing/textAngular#882]
I get an error in displaying the content of the ta-editor after updating from 1.4.3 to 1.4.4.

1) The "taTextElement" div takes the size of the text and is surrounded with a border. I have also to click exactly on this div and can't just click on the ta-editor to change the text. The code view gets shown correctly as before. 

2) If I click on an image the taTextElement gets moved down and on the top of the ta-editor the dimension of the image is shown. There appears a div element with the class="ta-resizer-handle-overlay"

This problem is also visible on the plunker demo.

**Comment by pbassut** [comment]
Would you update to 1.5.4. There was a bug with the css and it was solved. And that might solve your problem.

**Comment by fims** [comment]
Yes, this solved my problem. 

Thanks
