### ISSUE TITLE
Is there a way to define taPaste globally?

### ISSUE THREAD

**Issue by nachoargentina** [fraywing/textAngular#883]
Hi again guys.
I'm using this module in my app and the idea is not to allow the pasting of image or any HTML tags.
Is there a way to define taPaste globally so that I don't have to apply it as an attribute on every single instance?

**Comment by pbassut** [comment]
You could use ta-paste="globalFunction()" and then define this function on $rootScope. This takes a bit of the pain away. Or you could create a directive that has a template which generates textAngular and pass attrs to the textAngular markup.

**Comment by nachoargentina** [comment]
Thank you for your answer irmão! I like the idea of a directive that has a common textAngular template. That would take much of the code repetition away.
Btw, can you look at https://github.com/fraywing/textAngular/issues/863 when you have a chance? 
I know you closed it because it took me long to answer, so whenever you have some time I would really appretiate your point of view on that.
Thanks again!

**Comment by pbassut** [comment]
Sure!

**Comment by ajayreddy56** [comment]
I am facing the same issue Bro @pbassut @nachoargentina  if it is solved please drop the answer.Thanks in advance
