### ISSUE TITLE
textAngular.css is broken and contains JavaScript

### ISSUE THREAD

**Issue by chaddjohnson** [fraywing/textAngular#884]
When I build my app using textAngular version 1.4.4, my build breaks because textAngular.css contains JavaScript. Here is a screenshot:

![screen shot 2015-09-14 at 10 00 22 pm](https://cloud.githubusercontent.com/assets/676134/9866771/4e87e4ae-5b2c-11e5-889b-f31ccb8bfaac.png)

Thank you for open sourcing this great library!

**Comment by pbassut** [comment]
It has been fixed already. I'm waiting so @JoelParke  can do a new release of this and get this fix out there.
Thanks for the report, thought.

**Comment by chaddjohnson** [comment]
Super -- thank you @pbassut and @JoelParke!
