### ISSUE TITLE
insertLink on FireFox - Adding link causes that any writing text after the link is still a  link

### ISSUE THREAD

**Issue by meireliezer** [fraywing/textAngular#890]
Prerequisite:
only FireFox 
Scenario:
1. Add Link to the textAngular (insert url, press ok)
2. write any text after that link
Expected:
The additional text will not be link able
Actually:
Any text that you write is having the link style (with the url previously added)

**Comment by malde** [comment]
I can confirm this.

**Comment by jmkenz** [comment]
I've experienced this as well in Firefox only.

**Comment by hao** [comment]
This appears to be an issue with how Firefox handles `contenteditable`. Even if `textAngular` were to guess where the link should end, it would still be a guess…

**Comment by MateuszAxence** [comment]
I also want to confirm that. Is it possible to fix that?

**Comment by JoelParke** [comment]
This was fixed v1.5.6 Aug 18 https://github.com/fraywing/textAngular/commit/0fb9083ce8e3afd8cf1b42c1fa0784aab8ff8fb7
