### ISSUE TITLE
Module breaks if rangy is not defined in requirejs

### ISSUE THREAD

**Issue by afreeland** [fraywing/textAngular#892]
Was previously using 1.2.2 of textAngular and decided to upgrade to a more stable version, 1.4.5.  Loaded in each necessary file `textAngular.css`, `textAngular-sanitize.min.js`, `textAngular-rangy.min.js`, and `textAngular.js`....which caused all some grief for over an hour.

Decided to take a deep dive through textAngular and came across what I believe is the issue:
```
textAngular.run([function(){
	/* istanbul ignore next: not sure how to test this */
	// Require Rangy and rangy savedSelection module.
	if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(function(require) {
			window.rangy = require('rangy');
			window.rangy.saveSelection = require('rangy/lib/rangy-selectionsaverestore');
		});
	} else if (typeof require ==='function' && typeof module !== 'undefined' && typeof exports === 'object') {
		// Node/CommonJS style
		window.rangy = require('rangy');
		window.rangy.saveSelection = require('rangy/lib/rangy-selectionsaverestore');
	} else {
		// Ensure that rangy and rangy.saveSelection exists on the window (global scope).
		// TODO: Refactor so that the global scope is no longer used.
		if(!window.rangy){
			throw("rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded.");
		}else{
			window.rangy.init();
			if(!window.rangy.saveSelection){
				throw("rangy-selectionsaverestore.js is required for textAngular to work correctly.");
			}
		}
	}
}]);
```

This method assumes that if `require` is available that `rangy` can be **required**...however, we have not implemented all files through require, rangy is among those not implemented. The really crummy part is that even though require fails to load, no errors are thrown and the app appears to just break.

Changing the above code to the below solved this for us.  I may try to fork later and put in a pull request with a proper fix...but wanted to list this as a concern to others that may run across this issue.

```
textAngular.run([function(){
	// Ensure that rangy and rangy.saveSelection exists on the window (global scope).
	// TODO: Refactor so that the global scope is no longer used.
	if(!window.rangy){
		throw("rangy-core.js and rangy-selectionsaverestore.js are required for textAngular to work correctly, rangy-core is not yet loaded.");
	}else{
		window.rangy.init();
		if(!window.rangy.saveSelection){
			throw("rangy-selectionsaverestore.js is required for textAngular to work correctly.");
		}
	}

}]);
```

**Comment by pbassut** [comment]
Thanks for reporting this!
But looks like the way you fixed it, we're just rolling back to 1.4.2 (which was where requireJS was not supported). 

I agree with you that the current code is taking in account that require WILL be there. Which isn't the case.

I think the right fixed would be: try to require rangy, if that doesn't work, looks for rangy in the global scope. Or the opposite direction.

**Comment by afreeland** [comment]
Yeah, I agree entirely!  I just put the `fix` in there to help illustrate what we did to get past the issue for now.  If I was to do a pull request I was going to actually fix it instead of the just stripping out code that we didn't need.

Glad to see this repo is so active =)

**Comment by pbassut** [comment]
We try our best :)
Thanks again for the report.

**Comment by kelkes** [comment]
But rangy-selectionsaverestore ist not at rangy/lib/rangy-selectionsaverestore. with the latest bower package of rangy.

**Comment by pbassut** [comment]
@kelkes Sorry, but what's your point?

**Comment by kelkes** [comment]
I've been using textAngular (and its dependencies) thru bower an browserify.

require('rangy/lib/....') breaks because in the latest version of rangys bower package the files are not in a lib directory anymore.

So i am not able to build my app with the current textAngular version.

Thats my point :)

**Comment by pbassut** [comment]
hmmm, that's a bummer. I can't change the path due to backwards compatibility stuff though. I'll need to check both and the first one that works out I'll use it.

**Comment by kikhtenko** [comment]
+1. have the same issue with the latest version

**Comment by smashew** [comment]
+1 I am having the same issue...

**Comment by pbassut** [comment]
So, I need a sample project to investigate this. I'll fix it today.

Could someone provide one? If so, leave a message here before you create one so other people won't do it and waste time.

Thanks.

**Comment by pbassut** [comment]
@kelkes sorry, but they're still there: https://github.com/timdown/rangy
I don't think that's the cause.

**Comment by kelkes** [comment]
Have you tried bower install rangy 1.3?

**Comment by pbassut** [comment]
You mean after building it. Yeah, it's there. I only looked at the source code through github.

**Comment by kelkes** [comment]
The file is there but in the root dir after installing rangy via Bower.

I will setup a small demo project as a showcase after lunch. (CEST, vienna)

**Comment by pbassut** [comment]
@kelkes Thanks, I appreciate it!

**Comment by kelkes** [comment]
checkout https://github.com/kelkes/textAngular-browserify-demo
run
npm install
bower install
npm run gulp

you should see 
Error: Cannot find module 'rangy/lib/rangy-selectionsaverestore' from '/Users/kelkes/devel/textAngular-browserify-demo/client/components/textAngular/dist'

have a look into ./client/components/rangy

i've added my workaround to the gulpfile

**Comment by pbassut** [comment]
Alright, so if we're so strict about what version of rangy to use, I'll just look for rangy on ```rangy/rangy-selectionsaverestore```. I guess that makes sense.

**Comment by pbassut** [comment]
@kelkes Is your issue related to the OP? I mean, you do have require, he doesn't. I just wanna make sure I fix in a way that makes everyone happy here.

**Comment by kelkes** [comment]
If do not have enough information about the OPs setup to have a clear answer here.

I am fine using my workaround. Its more on the rangy side to expose all of its addons as modules also.

**Comment by JoelParke** [comment]
I just started looking at this.... And I have never used browserify for anything I have done.  In  looking at you branch and seeing that rangy-selectionsaverestore is not found AND your workaround.  Is this primarily an issue with rangy??? or should I day to fully understand browserify and then change something we are doing????
Sorry for the dumb questions --- but I would like to understand the scope of the work before I dive in...
Thanks!

**Comment by pbassut** [comment]
@JoelParke I don't think it's an issue with rangy. It's textAngular that's looking for the module in the wrong place when using require. 

@kelkes If you change the textAngular.js to use the right path to rangy, would that work? I tried here and it didn't. I haven't used browserify myself either.

**Comment by kelkes** [comment]
No it didn't work, you are right.

It only work using the manually resolve.

**Comment by JoelParke** [comment]
@keikes Should we just doccument your work around?  Is this an issue with browserify that it can't access the rangy-selectionsaverestore without extra work?  Please advise us, as we are grouping in the DARK :-) but we would like to make this easier for others that come across this issue in the future.  Also full understanding is powerful.

**Comment by kelkes** [comment]
I will try to figure out why its not working when the path is correct (without the lib part)... hope i can find a good answer :)

**Comment by pbassut** [comment]
@kelkes Do you think there's still the need the remove the lib part? I mean, bower package has no ```lib/```, but npm does. What should we do in that case?

**Comment by kelkes** [comment]
I think they should be the same but thats a issue with the rangy packages.

**Comment by SoftCreatR** [comment]
The issue still exists. Currently experiencing it:

```
Error: Cannot find module 'rangy' from '/theme/app/bower_components/rangy'
Error: Cannot find module 'rangy' from '/theme/app/bower_components/textAngular/dist'
Error: Cannot find module 'rangy' from '/theme/app/bower_components/textAngular/dist'
Error: Cannot find module 'rangy/lib/rangy-selectionsaverestore' from '/theme/app/bower_components/textAngular/dist'
```

**Comment by dreadjr** [comment]
Have you tried something like this, not ideal but...

```js
window.rangy = require('rangy');
window.rangy.saveSelection = require('rangy-selectionsaverestore');

require('text-angular-sanitize');
//require('text-angular-rangy');
require('text-angular');
```

**Comment by SoftCreatR** [comment]
This is what it looks like atm:

```
require('../../theme/app/bower_components/rangy/rangy-core.min');
require('../../theme/app/bower_components/rangy/rangy-selectionsaverestore.min');
require('../../theme/app/bower_components/textAngular/dist/textAngular-rangy.min');
require('../../theme/app/bower_components/textAngular/dist/textAngular-sanitize.min');
```

However, the `window....` thing didn't fix that. Commenting out `text-angular-rangy` didn't either.

**Comment by jpepper07** [comment]
Fix this please.... +1

**Comment by kelkes** [comment]
I will try to fix this as i need to update. Will provide the fix if had success.

**Comment by warent** [comment]
+1 this issue just started showing up on a production scale application
