### ISSUE TITLE
suggestion:Will you add some callbacks in some events?

### ISSUE THREAD

**Issue by natee** [fraywing/textAngular#893]
Thanks for the nice plugin , it helps me a lot!

When I use it,I have to change the source code to achieve my features. For example, when the textEditor was focussed or blurred I need to do some callbacks,or when I select some text I need to do that also.

So do you have a whitelist to add some callbacks in `focus` `blur` `mouseup`..?

**Comment by pbassut** [comment]
We do look forward to implementing this. Take a look and hopefully hop in the discussion about it
https://github.com/fraywing/textAngular/issues/730

**Comment by pbassut** [comment]
I'm closing this since there's already an open discussion and if a PR is provided that issue can be referenced instead since it's older.
