### ISSUE TITLE
Loading Rangy through require doesn't work

### ISSUE THREAD

**Issue by FilipZawada** [fraywing/textAngular#905]
if you load Rangy through `require()` text-angular starts throwing:
`Uncaught TypeError: Cannot read property 'getSelection' of undefined` when editing text.

The reason it's thrown is because:
1. [Here](https://github.com/fraywing/textAngular/blob/c3ba4ff523a4c3b893f9c25a052308d5f8f370f9/dist/textAngular.js#L670) `$window.rangy` is undefined, because rangy is loaded through `require()` (not as a global var).
2. Then it calls these [lines](https://github.com/fraywing/textAngular/blob/c3ba4ff523a4c3b893f9c25a052308d5f8f370f9/dist/textAngular.js#L2033-L2034). They assign `window.rangy = rangy`, but it's too late at this point. If point 2. was executed first, all would work properly.

A simple fix would be to reference `$window.rangy` in every usage in taDirective (rather than caching it in `rangy` var). But I believe a proper solution would be to keep rangy in an angular constant available for all services/directives:
```
// pseudo-algorithm:
var rangy = getRangy();
function() { 
  if(window.rangy) {
    return rangy
  } else {
    return require('rangy')
  }
}
```

Also, assigning rangy to a `window.rangy` sounds like a bug (it pollutes global workspace without a need for that).

P.S. Anyway, big thanks for all the huge work you've done so far!

**Comment by pbassut** [comment]
It originally looks in the global scope because when rangy is loaded without require it sets itself to window, maybe? 
Also, I tried to tackle this but looks like I'll have to include the rangy constant everywhere $window.rangy is used. Or I could just at module startup set the $window.rangy before anything happens. I'm trying a few things here.

**Comment by pbassut** [comment]
Weird. This shouldn't happen. ```.run()```runs before any provider is set up.
Take a look http://jsfiddle.net/ysq3m/

**Comment by SonofNun15** [comment]
Reverting to 1.3.x because 1.4 is broken when bundling with webpack via npm.

**Comment by MikaAK** [comment]
+1 I cannot use 1.4.5 with webpack, had to role back to 1.4.3. Seemed to be an issue with the require of `rangy`

**Comment by pbassut** [comment]
Could someone setup a plunkr so I can investigate the issue and fix it?
I don't use webpack myself so I can't test it.
