### ISSUE TITLE
Option for reseting a view value

### ISSUE THREAD

**Issue by kuceram** [fraywing/textAngular#908]
Having a reset button for text angular form, I want to reset user's changes. Giving `ng-model-options="{ updateOn: 'submit' }"` to text angular updates the model only on submit action. However, `editForm.richText.$rollbackViewValue();` doesn't propagate to text angular.

Code snippet:
```html
...
<div text-angular
         name="richText"
         ng-model="myObject.richText"
         ng-model-options="{ updateOn: 'submit' }">
</div>
...
<button type="button" ng-click="cancel(editForm)">
      Cancel
</button>
```
```javascript
$scope.cancel = function (editForm) {
      editForm.richText.$rollbackViewValue();
};
```

Angular: 1.4.4

**Comment by pbassut** [comment]
Could you provide a plunkr and let us know how to reproduce this issue?
