### ISSUE TITLE
Removing an Editor?

### ISSUE THREAD

**Issue by michaelpelletier** [fraywing/textAngular#91]
Hey, apologies if this has already been asked, I've been poking through the source (1.2) and wiki this morning and haven't seen anything on it.

As part of a web application I have, I'm allowing the user to add a series of textAngular inputs, which are all named based on {$index}. textAngular works great with adding new ones, but if I remove one and then try to add it back, textAngular throws an error about that index already being used.

Any tips on how I could unbind the editor before deleting it to prevent this issue?

**Comment by zacol** [comment]
Hi! What is the status for this issue? I need destroy method but I can't find any information about it in documentation.

**Comment by JoelParke** [comment]
This was closed 2 years ago.  When the editor is deleted, it looks like it is automatically removed through js garbage collection.
