### ISSUE TITLE
Custom toolbar not deactivating

### ISSUE THREAD

**Issue by luispg1987** [fraywing/textAngular#910]
I have a custom tool that executes a superscript. However, I am not able to stop the effect by clicking my custom button again. How do I stop the effect? I am including an example of my code

.config(function($provide) {
		$provide.decorator('taOptions', [
			'taRegisterTool', '$delegate', function(taRegisterTool, taOptions) {
				// $delegate is the taOptions we are decorating
				// register the tool with textAngular
				taRegisterTool('superscript', {
					iconclass: "fa fa-superscript",
					action: function () {
						return this.$editor().wrapSelection("superscript", null);
					},
					activeState: function () {
						return this.$editor().queryCommandState('superscript');
					}
				});
				// add the button to the default toolbar definition
				taOptions.toolbar[2].push('superscript');
				return taOptions;
			}
		]);

**Comment by pbassut** [comment]
What you mean by "stop the effect"?

**Comment by xEugenex** [comment]
Same issue.
At Firefox working OK, but not at Chrome.
When I press Superscript button and input first character in superscript, then button became unpushed, but text still typing in superscript. If I press Superscript button again, then text became second superscript level. And again button state became unpushed after first character I've input.
![superscript](https://cloud.githubusercontent.com/assets/11294357/10158500/23fe243a-669b-11e5-84cf-a96fa29cc259.png)

**Comment by xEugenex** [comment]
I've googled a little bit.
And added this strings to CSS, now superscript working OK...

sup {
    vertical-align: super;
}
sub {
    vertical-align: sub
}

**Comment by luispg1987** [comment]
thank you

**Comment by Jebedo** [comment]
Hi, I have same problem and need help. 
How do I stop effect?

```javascript

          taRegisterTool('insertEKS',{
					iconclass : 'fa fa-eur',
					tooltiptext : "Insert EKS",
					action : function btnClick($deferred,restoreSelection) {
						this.$editor().wrapSelection('insertHTML','<h7>EKS</h7>',true);                                                                                                                     
                                                    },
                    activestate : function (){
                                     return this.$editor().queryCommandState('insertEKS');
                                   }
                      });

```

![image](https://cloud.githubusercontent.com/assets/6505882/10188532/4e709a5c-6760-11e5-8e6b-e9c9bf028cb6.png)
