### ISSUE TITLE
Codemirror instead of textarea to edit in HTML mode

### ISSUE THREAD

**Issue by millerbarros** [fraywing/textAngular#912]
How i can use codemirror instead of textarea to edit in HTML mode?

I'm already including all dependences and setted the 'ui-codemirror' attribute as in the example below:

```
taOptions.setup.htmlEditorSetup = function($element){
    $element.attr( 'ui-codemirror': '');
}
```
The codemirror editor instance of is successfully created after the **textarea** element, the textarea is forced to hide and de codemirror editor always is showed (but should not), even if  **showHtml = false**. If **showHtml = true**, the **wysywig editor is hidden** but even when the **codemirror editor have focus**, the 'Toggle HTML / Rich Text' button **is disabled**.

Someone can help me to do that?

**Comment by pbassut** [comment]
```$element.attr( 'ui-codemirror': '');```
Is that syntactically valid?

Can I get a plunkr setup to investigate it a bit more?

**Comment by millerbarros** [comment]
Desculpe, foi um erro na ora de adaptar o código que estou usando para o comentário. Coloquei um o meu problema no [Plunkr](http://plnkr.co/edit/WyWeReF1cvT2XMSRH5YN?p=preview). O que eu quero é que o **codemirror** funcione como se fosse a textarea do editor **html**.

Eu já tentei de diversas formas mas nada funciona, o editor **codemirror** continua não recebendo o valor do ng-model quando é alterado pelo editor de **texto**. Eu até já tentei criar uma diretiva a parte para transformar o textarea em <ui-codemirror> e mesmo assim não funcionou.

O fato do editor **codemirror** ficar sempre visível obviamente está ligado ao ng-show do textarea, mas o problema maior é o fato de desabilitar a **toolbar** quando o editor **codemirror** tem o foco.

Seria ótimo que o textAngular já tivesse um suporte nativo para o **codemirror** ou **ace** para melhorar essa integração.

**Comment by pbassut** [comment]
Sorry but we don't support codemirror and have no plans at the momento to support it in the future. :(
