### ISSUE TITLE
Pasting From Word Losing Styling

### ISSUE THREAD

**Issue by brenthaertlein** [fraywing/textAngular#913]
I know that there have been many updates to support pasting from Word and other Rich Text editors, including in the latest revision in 1.4.6.

However, in the latest version it appears that all font styling and text alignment is lost when pasting content from Word. There was improved functionality (in 1.4.3 we were losing certain content, namely text after bullet points) but at the same time losing the style is a pain.

I'll post some screenshots later.

**Comment by brenthaertlein** [comment]
Additionally, when pasting Rich Text content on Mac OS X, the standard Cmd-V or Edit / Ctrl-click > Paste commands do not work (they seem to insert a line break <br /> which then disappears, according to the html output on the demo @ textangular.com).

To circumvent this, you can paste with Ctrl-click > Paste and Match Style, but this obviously isn't ideal behavior.

**Comment by pbassut** [comment]
Thanks. I could reproduce this using OSX. 
This bug is starting to get annoying. ;p

**Comment by brenthaertlein** [comment]
I noticed that the standard paste issue on Mac may be linked to having any non-left-aligned elements in the original Rich Text. I had a document that wouldn't paste, and when I left-aligned everything it pasted fine with Cmd-V.

However, there were still various formatting errors and certain pastes lose content, especially in bullet points.

Hope this is helpful.

**Comment by AlexAmyago** [comment]
Hello everyone

I have the same problem. 
https://github.com/fraywing/textAngular/issues/907

Thanks, 
Alex

**Comment by abhisb** [comment]
I too have the same issue with 1.4.6 version.

In Chrome, content copied from Outlook/Word is neither pasted in the text area using `Ctrl +V/right click ->Paste` rather able to Paste using `right click->Paste as Plain Text` only, so no styling will be applied in that case. It was working fine in 1.4.3v.

For IE, we are able to paste the content copied from Outlook/Word, but it's adding extra 3 blank lines between two lines in 1.4.6v. For Eg: 

Normal Content: 
```
Good Morning,
Please find the attached document.

Have a good day!
```

Pasted Content:
```
Good Morning,

 

Please find the attached document.




Have a good day!
```

The above issue doesn't exists in 1.4.3v for IE, but found another issue while copy pasting a long text or paragraph, space between some words found missing. I don't know why it keeps removing space between words.

**Comment by pbassut** [comment]
Could you set ```ta-unsafe-sanitizer="true"``` and see if it works?

**Comment by JoelParke** [comment]
I believe that this is now fixed.  Please re-open if still an issue with next release 1.5.12 (soon).
