### ISSUE TITLE
textAngular Hijacks Backspace Key Down strangely

### ISSUE THREAD

**Issue by brenthaertlein** [fraywing/textAngular#914]
So this is a pretty niche issue that is going to be hard to recreate, and I'll have to put together a plunkr or something later to see if I can replicate it outside of our app.

In textAngular 1.4.3 and beyond, I've run into a circumstance where moving from an <input> to textangular causes the Backspace key down event to apply directly to the document (basically trying to send the page "Back"). The behavior is present in a .jsp loaded with Angular 1.4.3 and textAngular 1.4.3+.

This is obviously a really rare bug, and it's not specifically throwing a console error, but it doesn't seem to effect any other part of the page or application. To test it I've removed nearly all functionality from our page, so that the only javascript running is to load data from REST calls (to populate various ng-models).

The strange workaround I noticed was this:

One of our inputs has a conditional ng-if on the div wrapping it. For some reason, that input did not cause textAngular to have poor relations with my Backspace key. I tried testing many different situations, including:

Removing all attributes from the input element(s) (including: id, ng-model, name, type, etc.)
Removing all attributes from the text-angular element (as above)
Removing all custom JavaScript.
Creating a new input in a completely separate part of of the page.

Under all of those circumstances, the behavior still occurred. If at any point any input element became focused, thereafter pressing backspace in the textarea of the textAngular editor would try to navigate Back instead of erasing a character. This occurs until the page is reloaded.

So, back to ng-if. Strangely, I decided to try putting a ng-if on the divs wrapping the other inputs. I set it to something that would always evaluate true on page load, because these inputs were not conditional. This solved the problem, although it is obviously a complete hack and not the desired solution.

Anyway, I hope that this leads somewhere as I probably spent 4 hours yesterday trying to fix this. I'm actually doing a lot of work in Angular, both here at work and on two personal projects in my spare time. I'll see if I can do any work on my end to help you guys out, and maybe end up contributing to actual projects in the Angular community like yours. 

Thanks for all your hard work, look forward to hearing back from you.

**Comment by pbassut** [comment]
Sorry for the late response on this.
This is really weird. I guess I don't send backspace commands anywhere in the code and I don't see how that would make sense. 

But I'd love to reproduce this issue and if you could provide a setup with the code needed to reproduce the bug, that would be great.

Thanks !

**Comment by brenthaertlein** [comment]
Yeah, I know it's possibly our problem or just the most extreme fringe bug.

I don't think it's the backspace command being sent via textAngular, but more when textAngular becomes focused after this specific situation, the backspace is being applied to the page itself instead of the textarea. If that makes sense.

We've had a really busy week and in the middle of a frustratingly buggy deployment right now, but I'll see what I can put together to show you sometime this week.

**Comment by pbassut** [comment]
Alright, looking forward to reproduce this weirdly magic bug! ;p

**Comment by brenthaertlein** [comment]
Fixed. There was an issue with our code with an old alert when backspace was pressed in a form and no input was focused. Since textAngular isn't an input, it fired inside textAngular.
