### ISSUE TITLE
Unable to have buttons not set to disable by default

### ISSUE THREAD

**Issue by CharlesVoita** [fraywing/textAngular#915]
I want to be able to set all the buttons to not be disabled by default. I have found that I can update `taRegister(foo, bar.disabled)` to false which will keep it enabled at all times, except that we will get an error if it is a boolean. On line 2924 of textAngular.js `isDisabled` states that "to set your own disabled logic set a function or boolean on the tool called 'disabled'". You cannot pass a boolean without an errror occurring. Also no way that I can see to update all buttons to enabled by default.

**Comment by pbassut** [comment]
Could you provide a plunkr so we can investigate the issue a bit more?

**Comment by pbassut** [comment]
And what do you mean "disabled by default"? They aren't disabled by default. They are if the editor has no focus yet. When the editor gets focus, they all get enabled. Is that you're referring to?
