### ISSUE TITLE
Bizarre Behavior within Ionic App

### ISSUE THREAD

**Issue by queejie** [fraywing/textAngular#917]
I've installed it successfully and get no error message, but every button seems either to toggle the text to and from an h1 element, or do nothing at all.  So if I press bold or numbered list it toggles the text to and from h1.

Any ideas on what might be interfering with it?

Thank you in advance.

**Comment by pbassut** [comment]
We didn't tried to support ionic apps. So, if you could provide a plunkr so we can check what's going on, that would be awesome and easier to tackle.
