### ISSUE TITLE
undefined getSelection  

### ISSUE THREAD

**Issue by rdvs** [fraywing/textAngular#918]
When i am clicking text area then i got "Uncaught TypeError: Cannot read property 'getSelection' of undefined" and while typing "TypeError: Cannot read property 'getSelection' of undefined".

I am using requirejs with angular. 
My config given below:
paths: {
		jquery     : '../lib/bower_components/jquery/dist/jquery.min',
		angular    : '../lib/bower_components/angular/angular.min',
		ngCookies  : '../lib/bower_components/angular-cookies/angular-cookies.min',
		ngResource : '../lib/bower_components/angular-resource/angular-resource.min',
		ngRoute    : '../lib/bower_components/angular-route/angular-route.min',
		ngSanitize : '../lib/bower_components/textAngular/dist/textAngular-sanitize.min',
		textRangy : '../lib/bower_components/textAngular/dist/textAngular-rangy.min',
		textAngular : '../lib/bower_components/textAngular/dist/textAngular.min',
		textAngularSetup : '../lib/bower_components/textAngular/dist/textAngularSetup',
}

and dependencies

textAngular: { deps: ['angular', 'textRangy']}
		
For more please look the attached file.

<img width="1277" alt="screen shot 2015-10-02 at 8 05 17 pm" src="https://cloud.githubusercontent.com/assets/1086000/10249064/f4a392d0-6940-11e5-935b-a0dd4b5a3301.png">

**Comment by paulstefanday** [comment]
I am getting the same issue using gulp/browserify

**Comment by pbassut** [comment]
@rdvs Did #713 solved your problem too?

**Comment by YangZhouChaoFan** [comment]
我也遇到同样问题，我的插件版本为
Angular 1.4.8
textAngular 1.4.6
rangy 1.3
requirejs 2.1.22

下面是我的解决方法：
1) 首先配置requirejs的配置文件
```
require.config({
    paths: {
        'angular': 'bower_components/angular/angular',
        'rangy-core': 'bower_components/rangy/rangy-core.min',
        'rangy-selectionsave': 'bower_components/rangy/rangy-selectionsaverestore.min',
        'textAngular-sanitize': 'bower_components/textAngular/dist/textAngular-sanitize.min',
        'textAngularSetup': 'bower_components/textAngular/dist/textAngularSetup',
        'textAngular': 'bower_components/textAngular/dist/textAngular'
    },
    shim: {
        'angular': {
            exports: 'angular'
        },
        'rangy-selectionsave': ['rangy-core'],
        'textAngular-sanitize': ['angular'],
        'textAngularSetup': ['angular'],
        'textAngular': ['angular', 'textAngular-sanitize', 'textAngularSetup']
    }
});

require(['rangy-core', 'rangy-selectionsave'], function(rangyCore){
    window.rangy = rangyCore;
});

```
2) 删除textAngular中run方法。

that's OK!
