### ISSUE TITLE
Dropup/Dropdown buttons?

### ISSUE THREAD

**Issue by Ericmcer** [fraywing/textAngular#924]
Is there anyway you can think of to configure the button toolbar to use bootstrap dropdowns or dropups?
I have done a few customizations through the standard routes to the buttons, but I cannot think of a way to do this without modifying the textAngular code itself. Boss wants me to do like [headers] button that displays  h1,h2,h3,h4,h5,h6 on click and similar for other tools.

**Comment by pbassut** [comment]
Take a look [here](https://github.com/fraywing/textAngular/issues/397).
