### ISSUE TITLE
Tab keydown 1.4.2 vs 1.4.6

### ISSUE THREAD

**Issue by Ericmcer** [fraywing/textAngular#925]
Hey spent awhile figuring this out today. I had an older app using a directive I built which used textangular. I used the same directive in a new app and the tab button would focus on the last textangular element on the page, regardless of which one you tabbed on. Textangular version 1.4.2 did not have this issue. Somehow or other event.preventDefault() was not getting triggered in the 1.4.6 version.

**Comment by pbassut** [comment]
Somethings regarding key bindings was introduced on 1.4.3.

**Comment by pbassut** [comment]
I'm closing the issue since I got no response.
