### ISSUE TITLE
Variables / Placeholders

### ISSUE THREAD

**Issue by fynnfeldpausch** [fraywing/textAngular#926]
I am not sure if this has already been implemented or whether this is possible. Here is what I am trying to achieve:

I want to define a list of variables that can be passed into the editor. These are string / string pairs (so basically a flat JS object). The user should be able to reference these variables via placeholders in the editor. These variables are then replaced by the values that have been passed in. Once the editor retrieves focus, the variables should become visible again.

As an example, the editor should contain the following text (on focus): ```Hello {name}, {text}```

The editor should then render the output as "Hello John, how are you?" if the following variables have been bound: ```{ name: 'John', text: 'how are you?' }```

I think you get the idea. Is this possible or how can I write a plugin for it? Any hints in the right direction are appreciated...!

**Comment by pbassut** [comment]
We don't have that implemented. And I don't think we will. 
I tried to create a similar behaviour once. Every time there was text like #{myobject.myattr.anotherone} it would translate to the value of that. I used it mainly for urls images binding.

If we had events you could bind to a onFocus event and onFocusOut and then handle those translations from there. But for the actual replacing, you must do a regex of something to get it working.

Now, with the current implementation you could make use of ng-focusand ng-blur to do the text processing stuff. And then maintain a context object in your controller to keep track of stuff, maybe?

**Comment by fynnfeldpausch** [comment]
Many thanks for your suggestions. I will close this ticket and try my best to come up with my own solution then. When / if I find one, I will place it in the comments under this ticket...

**Comment by fynnfeldpausch** [comment]
I ended up implementing the same approach you proposed (using ng-focus and ng-blur). Here is the key part in case someone is interested:


		$scope.htmlVariable = "";
		var vars = {
			'one': '1',
			'two': '2'
		};
		$scope.focus = function() {
			var regex = new RegExp('<span data-key="([^"]*)">([^<>]*)</span>', 'g');
			$scope.htmlVariable = $scope.htmlVariable.replace(regex, function(html, key) {
				return '{' + key + '}';
			});
		};
		$scope.blur = function() {
			var regex = new RegExp('{([^}<>]*)}', 'g');
			$scope.htmlVariable = $scope.htmlVariable.replace(regex, function(pattern, key) {
				var text = vars[key];
				return text ? '<span data-key="' + key + '">' + text + '</span>' : pattern;
			});
		};

**Comment by pbassut** [comment]
Sweet! 
Thanks for the script, btw!
