### ISSUE TITLE
fix(initialization): fix initialization value for model

### ISSUE THREAD

**Issue by mateusleon** [fraywing/textAngular#927]
Hello there!

Thanks for your amazing plugin!

I've noticed one little issue with the initialization of TA. I declare the value of the model, on my controller, with an `undefined` value. That's because when any element is cleared, the model turns `undefined`, and TA is included.

But, when it's initialized with a model, which is an object property that has an `undefined` value, it triggers the invalid state of TA, even without any interaction with the field.

I've found this while I was developing one functionality on my app based on the edition state of the form, keeping an original copy of the data and comparing it with the modified one (like an `isEdited` state verification). With this, I can warn the user if he's leaving something without save, or let the save button disabled if the values remain exactly the same.

But, with this differences on the initialization of TA, and the value when it's cleared, I'm not able to keep track of the form.

**Comment by pbassut** [comment]
I think I understand what you're saying but could you provide a plunkr with this behavior so I can see what's going on and help you out ?

**Comment by mateusleon** [comment]
Here is the plunker (http://plnkr.co/edit/gOeATz?p=preview). Sorry for the styling, I'm in a rush here.

**Comment by pbassut** [comment]
So, there's the undo stack. You could try to match the last modification of the undo stack(the last change the user made) with the first one(the original state of the text) or with your model itself. Then, if they are different you prompt the user.

**Comment by mateusleon** [comment]
But the model will be different anyway... the point is that, if the user input a phrase, and then, erase it, the model need to be in its initial state.

The prompt here, if is or not edited, its up to the comparison watcher, which isn't able to give the truthy of falsy positive, you know?

**Comment by pbassut** [comment]
I don't see how that invalidates my approach.
This would go like this:
```javascript
text = 'My text'
undoStack = ['My text'];
// user inputs ', not my text'
text = 'My text, not my text'
undoStack = ['My text', 'My text, not my text']
// user erases ', not my text'
text = 'My text
undoStack = ['My text', 'My text, not my text', 'My text']
// Comparing first position of the stack with the last one
if(undoStack[0] == undoStack[len(undoStack) - 1]){
    // Disable save button and there's no need to prompt the user since not modifications were made
}else{
    // Enables the save button and prompts the user in case he leaves without saving his modifications
}
```

If that's not what you want I think I misunderstand your issue/

**Comment by mateusleon** [comment]
The approach is the one presented below:

```js
$rootScope.$watch(function () {
    return angular.equals(model, modelBackup);
}, function (newVal, oldVal) {
    if (newVal !== oldVal) {
        scope.isEdited = !newVal;
    }
});
```

Because the form doesn't have only one TA, but many other fields. To evaluate TA, exclusively, with the undo stack, it's an unnapropriate way, and then add to the verification, well, I guess now you see my point.

The main issue is: TA doesn't return the model value properly, if the content of it is erased. On one normal input, with an object model that isn't declared, it begins undefined and, if filled and then erased, it returns to undefined. With TA this is not occuring.

My point, while declaring this issue, was not surrounding one way to verify a UX flux with you guys and found one way to do it. Was to point out one lack on the element behavior.

**Comment by pbassut** [comment]
Sorry but check this using angular. If you have an ngModel on a input and you type some text in it and then erases it, it goes to an empty string, not undefined.
