### ISSUE TITLE
I can't able to see the CURSOR when I click first time to the textangular editor

### ISSUE THREAD

**Issue by Sureshdjea** [fraywing/textAngular#929]
![10 13 2015-09 03](https://cloud.githubusercontent.com/assets/13254231/10452766/bc0950ae-71c4-11e5-89b4-f50bd71eef95.png)

**Comment by pbassut** [comment]
Mind telling me what OS you're using? Browser? Version of TA? Angular Version?
I can't reproduce this on textangular.com

**Comment by Sureshdjea** [comment]
Hi pbassut, I am using Ubunut OS, Chrome Browser, Version 1.4.6, AngularJS v1.3.14

**Comment by pbassut** [comment]
Could you text and see if it happens on textangular.com?

**Comment by Sureshdjea** [comment]
Ya I could see, but in my local is not visible at first time

**Comment by pbassut** [comment]
Sorry, so that must be an issue with your local code base that I'm afraid I can't help much with.
