### ISSUE TITLE
Add class/style in img attribute while capturing file drop

### ISSUE THREAD

**Issue by thedarklord1** [fraywing/textAngular#930]
I have implemented the global file drop handler using the below config.

<pre><code>
config(['$provide', function($provide) {
        $provide.decorator('taOptions', ['$delegate','dataService', function(taOptions, dataService) {
            taOptions.defaultFileDropHandler = function(file, insertAction) {
                if(file.type.substring(0, 5) !== 'image'){
                    alert('The image type is not supported. Please use a jpeg, png, gif, or bmp.');
                    return true;
                }
                dataService.uploadDropFile(file).success(function(response){
                    document.execCommand('insertImage', false, response.name);
                }).error(function(error){
                    console.log(" uploadDiscussionFile error", error);
                });
                return true;
            };
            return taOptions;
        }]);
    }])
</code></pre>

The problem is, the image does not has any styling class (E.g: <code>style="width: 100%;"</code>) in it, and it just mess up the whole editor block. I want to introduce a style attribute in the generated img tag. I have searched for it, and I have got the suggestion to use <code>insertHTML</code> instead of <code>insertimage</code> but the <code>execCommand</code> documentation says that insertHTML is not supported by IE. Could you please give me any pointers so that I can move forward with this. 
TIA.

**Comment by pbassut** [comment]
First we should investigate why the inserted image(with no styles) messes up the editor. Then we can move forward to adding styles to it. 
Now, could you paste the html you start with, add an image, and paste the html after that? Also a screenshot of the view would be great.

**Comment by Sureshdjea** [comment]
<text-angular ng-class="replyTimelineClass" ng-model="reply['+ comments[k].nodeId + ']"></text-angular><div class="error-div reply-error" style="display:none;">* Reply required</div><button type="submit" class="brand-button-submit" ng-click="createReply($event)" data-id="' + k + '">Submit</button>

**Comment by thedarklord1** [comment]
The screenshot of the editor - 
![screen shot 2015-10-14 at 11 52 10 am](https://cloud.githubusercontent.com/assets/8191081/10476367/b9882cdc-726a-11e5-8213-acf3cc333f74.png)

First image is resized one, after I clicked 100% on the image editor. The HTML code generated for the above is,


    <p><img src="https://meta.greymeter.com/apis/media/uploaded_files/LOGOTagline-Challenge.jpg" style="width: 100%;"><br></p>
    <p><br></p>
    <p><img src="https://meta.greymeter.com/apis/media/uploaded_files/LOGOTagline-Challenge_FX6UPkS.jpg"><br></p>
    <p><br></p>

I am using TextAngular version 1.4.6, on chrome browser, on MacOS.

**Comment by pbassut** [comment]
I don't see how it messes up the editor. Could you explain what you mean by that?

**Comment by thedarklord1** [comment]
If the image is too large, it takes a large portion of the editor. I could just insert some style attribute if the image size is too large to fit the editor. 
Please forgive me if I am sounding too naive. I am not very good with CSS.

**Comment by thedarklord1** [comment]
By the way, after doing a bit of searching, I looked at this [SO Post](http://stackoverflow.com/questions/4394309/how-do-i-fit-an-image-img-inside-a-div-and-keep-the-aspect-ratio/4395459#4395459) and have put in global CSS settings in my img attribute. It seems to solve my problem. 
Thanks a lot for your help and patience. :)

**Comment by pbassut** [comment]
Sure :)
