### ISSUE TITLE
Just one toolbar for all editable zone ?

### ISSUE THREAD

**Issue by narigua** [fraywing/textAngular#935]
Hi,

First of all, good job for your work, one of must have module for angular's apps.

Is it possible to instantiate just one fixed toolbar for multi editable texts ?

Thank you.

**Comment by pbassut** [comment]
Short answer: no.
Long answer: You could create use the same toolbar on each instance you have and assign a class with a 'display: none' to hide the ones you're not interested in showing. This way, you would have one type of toolbar across many TA instances.

**Comment by narigua** [comment]
Ok, thank you.
