### ISSUE TITLE
Placeholder in orightml posssible?

### ISSUE THREAD

**Issue by oktay89** [fraywing/textAngular#936]
I have some select and input fields in my form. I want to use angular's two-way data-binding to put some placeholders to the model of textAngular and then change it if something is written in the input. Here is a plunker with placeholder and input:

http://plnkr.co/edit/dfL0lyxNmQMcbefCc6ls?p=preview

It works only if i have a 'change' button and click on it and manually override the model of textAngular.

**Comment by pbassut** [comment]
I think you're missing the way data-binding works. The way you're doing, you're actually using the value that's inside placeholderText and that's it. You're not binding to anything.
