### ISSUE TITLE
When ngModel is null it is initialized to '\n    ' by textAngular

### ISSUE THREAD

**Issue by kuceram** [fraywing/textAngular#938]
When the user clicks to textAngular input field, it sets the ngModel to empty string. I would expect to have the ngModel null at least not to be initialized to some weird sequence.

**Comment by pbassut** [comment]
This is not a TA issue, it happens using angular alone. Once you set a model that reflects a text, there's no point of setting it to undefined or null because is not undefined and is empty. And empty is a value too.
Checkout this plunkr: http://plnkr.co/edit/VPrMLyYgVMMcdC0WwJzB?p=preview
