### ISSUE TITLE
Pasting within text creates new lines in Chrome Windows (textAngular v.1.4.6)

### ISSUE THREAD

**Issue by asylejmani** [fraywing/textAngular#944]
Hi,

I just updated to v.1.4.6 and I noticed an issue in Chrome Windows. The bug is basically paste creating new lines. For example:

try typing 1234567890 and then copy/paste number 5 in the same place (without moving cursor) instead of pasting it in the same place (making it 12345567890) it adds 5 in a new line.

This issue is not happening in v.1.4.2 (the one I tested). Here's the plunker with v.1.4.2 where sample code where this issue doesn't happen: http://plnkr.co/edit/cSer49hDICx1XkoS9XnT?p=preview

and here's the one where it happens (v.1.4.6): http://plnkr.co/edit/ehDyqi1gKS9DIwuAGPXy?p=preview

P.S. I also noticed on Chrome Windows (I only tested it there), pasting content always wraps is with a span tag and lots of inline styles, whereas on Chrome Mac it just pastes an plain string (as it should). - both versions

**Comment by JoelParke** [comment]
<p>I just tested this with Chrome Version 46.0.2490.80 (64-bit) on Ubuntu 15.10 and I cannot reproduce.  Also, I tried the plnkr as well. <br/>Does this only happen on windows....???<br/>Also what is being held in the paste buffer?</p>

**Comment by asylejmani** [comment]
Yes, it is only happening in Chrome Windows. I didn't check paste buffer (sorry) and I don't have access to a windows machine at the moment :(

**Comment by JoelParke** [comment]
<p>I just verified that it IS happening on Windows7, but strangely this seems to be related to what's in the paste buffer... Since if I do the copy from the 1.4.2 version and the paste into the 1.4.6 version, it does not happen.... So that's a bit surprising...</p>

**Comment by asylejmani** [comment]
That makes both of us :-)

**Comment by JoelParke** [comment]
<p>I just verified the v1.4.3 does not have this problem.<br/>BUT v1.4.4 does! -- so I am getting closer...</p>

**Comment by JoelParke** [comment]
It turns out that the fix for #644 broke this...
I have a fix and will submit a pull request to solve this.
I will also email yaldak who submitted the original fix and have him check this... to see if my change breaks his fix.

**Comment by JoelParke** [comment]
<p>The pr #945 is out there...</p>
