### ISSUE TITLE
Uncaught DOMException: INDEX_SIZE_ERR

### ISSUE THREAD

**Issue by sgentile** [fraywing/textAngular#949]
The only thing maybe unique is the editor is in a ng-repeat and inside a collapsable panel ?

**Comment by Jebedo** [comment]
This error?
https://github.com/fraywing/textAngular/issues/921

**Comment by sgentile** [comment]
Yes (but not just IE11 - I get it in Chrome as well)

Thanks!!!

**Comment by mpmlj** [comment]
+1
To reproduce: insert an image into a text body and then click on it.

**Comment by i-kaplin** [comment]
+1

**Comment by ezk84** [comment]
+1

**Comment by marius-c** [comment]
+1 

IE 11.0.9600.18.161

Click on "Toggle Html / Rich Text" then click the editor. each time generates this error.

**Comment by JoelParke** [comment]
I cannot reproduce this with v1.5.7 - please reopen if still an issue.
