### ISSUE TITLE
Placeholder text? 

### ISSUE THREAD

**Issue by ztbrown** [fraywing/textAngular#95]
Am I crazy, or does textangular not support placeholder text?

**Comment by arindambarman1** [comment]
Hi placeholder is not working on chrome. Am I using it wrong?
![image](https://cloud.githubusercontent.com/assets/8678513/5695547/68bc15a8-99cf-11e4-97ca-92c949dac440.png)

**Comment by johannesjo** [comment]
It seems to be there is an issue with the timing somehow. If you wrap the assignment of the model variable in your controller into a timeout, the placeholder is displayed, otherwise it is not.

**Comment by arindambarman1** [comment]
@johannesjo Can you please put up a code snippet of how to do it?

**Comment by johannesjo** [comment]
```html
<text-angular ng-model="myText" placeholder-text="Teeeext real text">
```
```JavaScript
myMod.controller(function($scope, $timeout){
  $timeout(function(){
    $scope.myText = 'Some Text';
  });
});
```

**Comment by arindambarman1** [comment]
@johannesjo Thanks a lot

**Comment by SimeonC** [comment]
Weird, I'm not noticing a need for a timeout. What version of angular, textAngular and browser are you on?

**Comment by arindambarman1** [comment]
@SimeonC 
Actually the timeout is still not solving my problem. I am using chrome 40. Angular 1.3

**Comment by SimeonC** [comment]
Ok, can you run up a codepen/plunkr that has the issue in it please? I should be doing some more work TA tomorrow so if you can get a working example/reproduction steps (preferably both) up I should be able to find the cause and get back to you about what I thinks wrong.

**Comment by ajayreddy56** [comment]
@johannesjo I am facing issue Bro.without declaring it's value in js ,It should display the value whatever user assigned. (I Mean,placeholder="text")

**Comment by kadamska** [comment]
When I add the placeholder text, there is an extra `<br>` inserted in the `<p>` element, producing an extra line. How do I get rid of it? It's visible if you set the height to a single line.

**Comment by DumboJet** [comment]
On IE11, sometimes the empty editor makes the model value a:
```
<p>
<br/>
</p>
<br/>
```

This hides the placeholder. :(
The last `<br/>` causes the problem. Without it all seem OK. When it is there, there is no placeholder.
I am trying to hack-fix it now...

**Comment by DumboJet** [comment]
This was my fix:

                    var bindingElem = elem.find('[ta-bind]'),
                        whiteSpaceRegex = /(\s|\<br\/?\>|\<\/?p\>|\<\/?div\>)/gi;
                    scope.$watch(function() {
                        return bindingElem.html();
                    }, function (html) {
                        if (html.replace(whiteSpaceRegex, '') === '') {
                            bindingElem.empty();
                        }
                    });
