### ISSUE TITLE
Image preview for Google Drive Photo ?

### ISSUE THREAD

**Issue by axacheng** [fraywing/textAngular#950]
Hi, 
Does textAngular has options that can change image url before it gets rendered ?

My photos are stored on google drive and make it public. Here is an example : https://drive.google.com/file/d/0B30LhVSDLYo9MVpGZVRSRG5tQm8/view

When i was trying to use this google drive link as image URL to insert, it didn't show up image preview in the editor content box ~ 

I think this is because google drive share link is not the same as image actual link is it.
https://productforums.google.com/forum/#!topic/drive/yU_yF9SI_z0/discussion

Thanks in advance.

**Comment by axacheng** [comment]
just deeply look at the code and found an useful factory - taToolFunctions on textAngularSetup.js.
I added one more method to fix for Google Drive link.

```javascript
		fixGoogleDriveLink: function(url) {
			var internalGoogleDriveLink = 'https://drive.google.com/a/google.com/file/d/'
			var externalGoogleDriveLink = 'https://drive.google.com/file/d/'

			if (url.indexOf(internalGoogleDriveLink) === 0){
				console.log('internal google drive link')
				alert('internal google drive link')
				var re = /https:\/\/drive.google.com\/a\/google.com\/file\/d\/(.*)\//i;
			}
			else if (url.indexOf(externalGoogleDriveLink) === 0){
				console.log('external google drive link')
				alert('This is external google drive link, Dont be evil...')
				var re = /https:\/\/drive.google.com\/file\/d\/(.*)\//i;
			}
			var match = url.match(re)
			console.log(match)
			return (match && match[1]) || null;
		},
```

**Comment by jackRoadOnTop** [comment]
So do I. IOS not insert image url,such as 


    taRegisterTool('selectImage', {
      iconclass: 'fa fa-picture-o',
      action: function() {
        var imageLink = "https://vis-workworld-image.oss-cn-qingdao.aliyuncs.com/undefined/undefined_1482139607387.jpg";
        var thisd = this;
        if (window.cordova) {
          addOnlinePhotoService.show(onSuccessCall);

          function onSuccessCall(result) {
            console.log(result);
            if (result.responseCode == 200) {
              if (device.platform.toLowerCase() === 'android') {
                //json返回格式问题，故用eval
                var retObj = eval('(' + result.response + ')');
                console.log(retObj);
                var embed = '<img src="' + retObj.retmsg + '"><br/>';
                console.log(embed);
                thisd.$editor().wrapSelection('insertHTML', embed, true);
              } else if (device.platform.toLowerCase() === 'ios') {
                var retObj = eval('(' + result.response + ')');
                console.log(retObj);
                var embed = '<img src="' + retObj.retmsg + '"><br/>';
                console.log(embed);
                thisd.$editor().wrapSelection('insertImage', embed, true);
              }
            }
          }
        } else {
          var embed = '<img src="' + imageLink + '"><br/>';
          thisd.$editor().wrapSelection('insertHTML', embed, true);
        }
      }
    }
