### ISSUE TITLE
tabIndex not focusing next target

### ISSUE THREAD

**Issue by tholene** [fraywing/textAngular#970]
Plunker demo here: http://plnkr.co/edit/gOSW2VLJH0gy9XLaUMXb?p=preview

I'm using  v1.4.5 in my project and I guess it's the same version here.

In a previous project of mine I was using v1.4.3 and tabbing worked fine with a custom directive that removed the attribute from the root element and added it to the ````<div id="taTextElem...">````, but I did not know about the optional <b>tabIndex</b> directive included in text-angular by then.

**Comment by yleichanok** [comment]
Subscribing. It worked perfectly in 1.4.1 but was broken since then.
