### ISSUE TITLE
textAngularManager.addTool not working?

### ISSUE THREAD

**Issue by xyuanX** [fraywing/textAngular#972]
what I am doing here is try to add toolbar dynamically, so I read the codes and google a lot.
this looks fine at the first place : http://stackoverflow.com/questions/26671289/angular-config-with-dynamic-data.

but somehow it is not working with my App, I am using textAngular 1.2.2
here is a plunker to show your the issue, http://plnkr.co/edit/jKoGJMwC1Efvz3UgjhlV?p=preview 

any idea? did I do it wrong?

**Comment by iggyZiggy** [comment]
+1

**Comment by pbassut** [comment]
Looks like @SimeonC answered this question on Stackoverflow. And the OP says it works.  
I'm closing this then.
