### ISSUE TITLE
Cannot insert image into text editor with custom toolbar

### ISSUE THREAD

**Issue by 0xMatt** [fraywing/textAngular#997]
Hello, I'm trying to use my s3 uploader to place images within the text editor. Everything is working up until the point of inserting the actual link within the editor. Here's my current implementation:

    $provide.decorator('taOptions', ['taRegisterTool', '$delegate', '$modal', function (taRegisterTool, taOptions, $modal) {
        taRegisterTool('uploadImage', {
            buttontext: 'Upload Image',
            iconclass: "fa fa-image",
            action: function (deferred, restoreSelection) {

                var modal = $modal({
                    controller: function ($scope) {

                        $scope.upload = function () {
                            var file = $scope.file;
                            restoreSelection();
                            console.log(file);
                            document.execCommand('insertImage', true, file);
                            deferred.resolve();
                            $scope.hide();
                        };

                        $scope.hide = function () {
                            modal.$promise.then(modal.hide);
                        };

                        $scope.cancel = function () {
                            $scope.hide();
                        };
                    },
                    templateUrl: 'app/sections/ContentManagement/articles/editor/upload.toolbar.html',
                    show: false
                });

                modal.$promise.then(modal.show);
            }
        });
        taOptions.toolbar[1].push('uploadImage');
        return taOptions;
    }]);

'file' does indeed contain the expected url from S3, however nothing is getting sent to the textarea. Any feedback would be greatly appreciated, thanks!

**Comment by MrJaeger** [comment]
Might want to follow the example of using `wrapSelection` as seen in https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js#L734.

In your configuration you will need to bind `this.$editor()` at the beginning of your action function. I would do `$editor = this.$editor()` at the beginning of the action function. Then instead of `document.execCommand('insertImage', true, file);` I would do `$editor.wrapSelection('insertImage', imageLink, true);`. I don't have a good way to set up your config but I would try that to start and if not we can debug more from there.

**Comment by 0xMatt** [comment]
Thanks for taking the time to help @MrJaeger . However, your recommendation only yielded similar results. Also, please note, the value I'm passing is simply a url to the image in 'file'. 

With this update, my textarea was not being focused after $scope.upload(), now it is, but the text still isn't appearing.

**Comment by MrJaeger** [comment]
No problem, looking back on how I did this for a tool I built internally I ignored `execCommand` completely and went with something along the lines of:

```
restoreSelection();
selection = $window.getSelection()
if (selection.getRangeAt and selection.rangeCount) {
    range = selection.getRangeAt(0);
    range.deleteContents();
    el = range.createContextualFragment('<img src="' + src + '"/>');
    range.insertNode(el);
}
```

Hopefully something along those lines will work for you!

**Comment by 0xMatt** [comment]
No cigar with that method, thanks again for the help though. Maybe @fraywing can provide some extra insight

**Comment by 0xMatt** [comment]
Used solution from #261
